### ISSUE TITLE
圣遗物强化希望支持16:10

### ISSUE THREAD

**Issue by 1235789gzy1** [babalae/better-genshin-impact#10]
希望圣遗物强化能支持2560x1600（16:10）的分辨率

**Comment by huiyadanli** [comment]
未来会把各类功能的分辨率相关性参数暴露至配置文件，有特殊需求自行配置

**Comment by huiyadanli** [comment]
此功能可能会在 原神 4.3 后废弃，官方支持一键强化且不会再弹出提示
