### ISSUE TITLE
自动剧情中“自动选择选项”有时会失效

### ISSUE THREAD

**Issue by xlhd19980327** [babalae/better-genshin-impact#100]
剧情中遇到主角需要选择对话/操作的时候（也即触发“自动选择选项”），有时候程序并不会自动选择。
这个时候是程序未识别到对话框选项呢？还是程序识别到了，但是判定已经点击过了（但实际并没有点上）所以卡住了？

1.  如果是第一个问题，是不是一个bug呢？

2.  如果是第二个问题，是不是可以将点击需要自动选择的选项框的触发器变成多次，也就是说多点几次那个选项框来修复呢？

**Comment by FangDingli** [comment]
在 v0.14 的时候经常遇到这个问题，是此时左上角的自动剧情变灰色了导致软件没识别成功以为没在剧情，但最新版 v0.15 我发现这种情况好了很多，可能部分情况下还是会出现

**Comment by huiyadanli** [comment]
是一个已知的暂时无法解决的问题
文档内也有说明 https://bgi.huiyadan.com/doc.html#%E8%87%AA%E5%8A%A8%E5%89%A7%E6%83%85
>左上角“自动”按钮识别不到的时候就不会自动剧情了，这种情况下可以调整视角使其能够被识别，或者先手动过剧情。（锁定视角的情况下无法调整，只能先手动点击）

最新版本有针对这个优化过，添加了播放中的文字识别，但是效果不佳。

**Comment by FangDingli** [comment]
> > 是一个已知的暂时无法解决的问题 文档内也有说明 https://bgi.huiyadan.com/doc.html#%E8%87%AA%E5%8A%A8%E5%89%A7%E6%83%85
> > > 左上角“自动”按钮识别不到的时候就不会自动剧情了，这种情况下可以调整视角使其能够被识别，或者先手动过剧情。（锁定视角的情况下无法调整，只能先手动点击）
> > 
> > 
> > 最新版本有针对这个优化过，添加了播放中的文字识别，但是效果不佳。
> 
> 实际上我这边的问题主要是程序对于对话选项程序做不到自动识别，但是自动剧情（程序模拟点击空格）可以。但是根据兄弟你说的，如果没识别到自动播放，自动剧情和自动选项不应该都不行吗？这点我没太懂，如果是我理解错了也烦请赐教啦

他是持续识别的，你可以看到左上角自动剧情的地方有红框，但是有时候需要点选项的时候这个播放按钮会变淡导致识别失败，表现为红框消失。 所以不会自动点选项的绝大多数情况都是左上角看不到那个红框
