### ISSUE TITLE
建议：自动拾取的黑白名单支持正则表达式

### ISSUE THREAD

**Issue by batvbs** [babalae/better-genshin-impact#103]
不太懂C#，不过有三个思路

1. 单独列个名单，匹配 正则表达式
2. 单独列个名单，匹配 通配符?*
3. 单独列个名单，判断是否包含文本
```
var str = "abcdefg"; //一个示例
 
str.Contains("BCD")；//返回false
str.Contains("bcd")；//返回true
 
str.IndexOf("bc")；//返回true，不区分大小写
str.IndexOf("BC")；//返回true，不区分大小写
 ```

有些按钮的内容是不固定的，比如
![image](https://github.com/babalae/better-genshin-impact/assets/60730393/00816931-7a86-469f-b5b3-441c2dd915a7)

![image](https://github.com/babalae/better-genshin-impact/assets/60730393/6ddc0bea-4b6e-4896-abe5-0c58bd562dc6)

**Comment by huiyadanli** [comment]
这个场景比较单一，感觉没必要。种地的时候关闭自动拾取即可

可以加一个包含则生效的黑白名单。正则模式太慢了。

**Comment by batvbs** [comment]
> 这个场景比较单一，感觉没必要。种地的时候关闭自动拾取即可
> 
> 可以加一个包含则生效的黑白名单。正则模式太慢了。

不太懂C#，搜了下判断是否包含，供参考
```
var str = "abcdefg"; //一个示例
 
str.Contains("BCD")；//返回false
str.Contains("bcd")；//返回true
 
str.IndexOf("bc")；//返回true，不区分大小写
str.IndexOf("BC")；//返回true，不区分大小写
 ```

**Comment by huiyadanli** [comment]
已经加上写死了的判断了，下版本发布。

**Comment by huiyadanli** [comment]
[0.17.0](https://github.com/babalae/better-genshin-impact/releases/tag/0.17.0) 已经针对这种情况做了特殊处理
