### ISSUE TITLE
最新版本启动后报错程序异常

### ISSUE THREAD

**Issue by 1742035356** [babalae/better-genshin-impact#110]
下载的最新版本，启动后报程序异常然后就退出了
![Snipaste_2023-11-30_11-37-37](https://github.com/babalae/better-genshin-impact/assets/99705099/28e60487-c593-4bce-b847-d14b809781f5)

**Comment by 1742035356** [comment]
电脑是win11系统的

**Comment by 1742035356** [comment]
> 最新版本是0.16.1，已经解决这个问题了
我看好像是网路报错，把vpn关了启动了就没报这个错。后续启动也没报错了

**Comment by huiyadanli** [comment]
是从阿里云获取最新版本信息失败了，最新版本已经把弹窗去掉了

**Comment by huiyadanli** [comment]
[0.17.0](https://github.com/babalae/better-genshin-impact/releases/tag/0.17.0) 已经去除弹窗
