### ISSUE TITLE
请问可否同时也匹配中英文客户端的任务功能呢？

### ISSUE THREAD

**Issue by wizardt** [babalae/better-genshin-impact#111]
请问这里怎样才能实现可同时匹配中英文客户端呢？

**Comment by huiyadanli** [comment]
支持多语很难，当前都是中文模型

**Comment by wizardt** [comment]
> 支持多语很难，工作量极大，当前都是中文模型

感谢回复。那能否仅增加支持英文客户端的自动剧情点击？

**Comment by huiyadanli** [comment]
你好歹测试下吧，自动剧情点击大部分都不涉及文字相关内容的识别
