### ISSUE TITLE
自动选择使用体力、自动跳过动画 & 自动领取纪行任务

### ISSUE THREAD

**Issue by Koitoyuuu** [babalae/better-genshin-impact#112]
刷圣遗物时自动选择使用体力、自动跳过动画
自动领取纪行任务奖励

**Comment by huiyadanli** [comment]
优先选择浓缩树脂

![image](https://github.com/babalae/better-genshin-impact/assets/15783049/01e34770-01ac-4dbc-91bc-3e909d3603c9)

**Comment by huiyadanli** [comment]
1. 自动秘境已经可用
2. #222
