### ISSUE TITLE
希望加入自动购买 自动做饭，快捷键可以绑定 任意按键 

### ISSUE THREAD

**Issue by batvbs** [babalae/better-genshin-impact#115]
#### 功能
1. NPC商店界面一键购买(如尘歌壶 锻造)，点 购买>数量拉满>确定，类似一键强化圣遗物
2. 一键做饭，点 手动做饭>识别进度条>完美点确定，熟练度满之后结束

#### 建议
1.快捷键可以绑定 任意按键 或 任意多按键组合，这方面可以参考[ahk](https://www.autohotkey.com/) 和 [MyKeymap](https://github.com/xianyukang/MyKeymap)

**Comment by TheTychoStar** [comment]
附议一个自动烹饪功能，自动识别满熟练度倒不是必须，像伐木一样能设置烹饪次数就行了，实现起来应该更简单。

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.24.0  快捷已经优化
