### ISSUE TITLE
自动剧情跳过时间自定义

### ISSUE THREAD

**Issue by linglongyoudoufu** [babalae/better-genshin-impact#117]
不想手点跳过，自动播放的时间油太慢，又想看剧情。而目前自动跳过时间太快，想要自动剧情跳过时间自定义的功能

**Comment by huiyadanli** [comment]
这个时间加上可能会比游戏自动播放更慢，无法判断3D动画是否播放完毕的。

后续可能回家点击选项的延时。

**Comment by huiyadanli** [comment]
[0.17.0](https://github.com/babalae/better-genshin-impact/releases/tag/0.17.0) 添加了点击选项的延时

自动播放的延时暂时做不到，无法判断当前文字播放了多久
