### ISSUE TITLE
`如果启动 BetterGI 时原神没有启动，则自动启动原神`功能未生效

### ISSUE THREAD

**Issue by forchannot** [babalae/better-genshin-impact#121]
`Release`中的描述`（功能测试存在一定问题，延期上线）`是否针对的整个启动，还是仅仅是针对的`启动原神后自动进入游戏按钮呢`，如果是整个启动都未上线当我没说（

版本`0.17.1`，在软件ui设置界面中并未查找到原神游戏路径的配置项，在config配置文件中发现了`installPath`配置选项，但是更改后仍未生效，在原神未启动的情况下启动本软件仍会提示未找到原神窗口，查看`历史commit`记录发现有默认从注册表读取，但是实际上未生效。

**Comment by huiyadanli** [comment]
整个启动都未上线，问题有点多先关掉了。预计下个版本会上的
