### ISSUE TITLE
希望自动剧情点击能支持后台原神窗口

### ISSUE THREAD

**Issue by abgnwl** [babalae/better-genshin-impact#122]
原神窗口位于后台时，看起来无法自动点击过剧情，左上角的“自动”检测红框也消失了。请问技术上能否实现后台窗口检测+点击

**Comment by Duck-Deng** [comment]
> 非最小化情况下截图还能正常运行，但是失去焦点后所有键鼠操作都无效了
> 
> 两种方案：
> 
> 1. windows开启远程桌面多用户，自己连接自己。https://asu.stysqy.top/guide/bs.html
> 2. 注入游戏进程，hook dx进行模拟操作（未验证可行性，⚠有风险）

这个链接失效了，能否提供其他网站的转载，或给出简要的操作步骤？

**Comment by huiyadanli** [comment]
https://github.com/Night-stars-1/Auto_Simulated_Universe_Docs/blob/docs/docs/guide/bs.md
