### ISSUE TITLE
关于配置文件和自定义快捷键

### ISSUE THREAD

**Issue by AirHolic** [babalae/better-genshin-impact#123]
建议添加一个配置文件导出和导入的功能，便于用户更新。
关于快捷键，鼠标侧键目前无法自定义加入，希望加入鼠标侧键（方便龙王转圈圈

**Comment by Aniverse** [comment]
配置文件你复制粘贴 User 目录下的应该就可以了

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.24.0  快捷键已优化
