### ISSUE TITLE
自动伐木在国际服情况下会少侦测一次

### ISSUE THREAD

**Issue by MuwuIqwqNawaT** [babalae/better-genshin-impact#125]
![image](https://github.com/babalae/better-genshin-impact/assets/97110737/06d41a44-af5c-463e-a191-4615cdf30ca0)
遇上的状况是触发完树王瑞佑 离开登入之后 
按一次进入游戏后
停留在这个窗口
![image](https://github.com/babalae/better-genshin-impact/assets/97110737/06e88040-f9bf-40ba-8f92-d4fb87098a78)
要手动点击才会继续作动

**Comment by emako** [comment]
@MuwuIqwqNawaT 提供`GenshinImpact.exe`同目录下的`config.ini`文件，比如我的路径是`D:\Program Files\Genshin Impact\Genshin Impact Game\config.ini`

```ini
[General]
channel=1
cps=
game_version=4.2.0
sdk_version=
sub_channel=1
plugin_5_version=2.6.0
plugin_7_version=1.0.0
```

**Comment by MuwuIqwqNawaT** [comment]
[General]
channel=1
cps=mihoyo
game_version=4.2.0
sub_channel=0
plugin_7_version=1.0.0

**Comment by MuwuIqwqNawaT** [comment]
[General]
channel=1
cps=mihoyo
game_version=4.2.0
sub_channel=0
plugin_7_version=1.0.0

**Comment by MuwuIqwqNawaT** [comment]
![Genshin Impact Screenshot 2023 12 04 - 18 16 08 34](https://github.com/babalae/better-genshin-impact/assets/97110737/e1987660-8305-4ca1-ac36-699e2091fa40)
![Genshin Impact Screenshot 2023 12 04 - 18 15 55 03](https://github.com/babalae/better-genshin-impact/assets/97110737/a2c1030b-1efb-4508-bbea-dcd831cbd5b2)

**Comment by MuwuIqwqNawaT** [comment]
![Genshin Impact Screenshot 2023 12 04 - 18 16 08 34](https://github.com/babalae/better-genshin-impact/assets/97110737/29ea0793-9f42-4203-a228-a7c8dad4fdc6)
![Genshin Impact Screenshot 2023 12 04 - 18 26 38 47](https://github.com/babalae/better-genshin-impact/assets/97110737/7c920960-c674-40da-aed7-4f3d776f34ca)

**Comment by EH1919** [comment]
啊哈，国际服会比国服多一个 选择服务器 的选项，这也就是为什么他会停留在大门前了

**Comment by huiyadanli** [comment]
已支持
https://github.com/babalae/better-genshin-impact/releases/tag/0.18.0
