### ISSUE TITLE
[feat request]关于快速传送的半智能化开关

### ISSUE THREAD

**Issue by emako** [babalae/better-genshin-impact#127]
快速传送过于灵敏导致问题：
必须调整正确地图缩放=>精准点击
这系列操作必须完全操作正确，否则面临反复传送的时间浪费，用户心智负担过重

期望方案：
提供半智能化开关，在地图页时：

1. 有传送菜单选项
按1次`空格`或`Tab`，自动选传送菜单，再次1次`空格`或`Tab`，自动点传送按钮

2. 无传送菜单
按1次`空格`或`Tab`，自动点传送按钮

**Comment by huiyadanli** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/15783049/393d9c25-07ce-499f-8b5c-550342a75c1e)

添加了选项

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.24.0  已优化
