### ISSUE TITLE
使用Better GI时出现异常内存占用

### ISSUE THREAD

**Issue by EH1919** [babalae/better-genshin-impact#131]
作者你好，我在使用软件时出现了两次内存异常占用。
第一次是昨天使用0.16.1的时候，因为突然游戏非常卡我就调出了任务管理器，然后我发现我的内存已经被占满了，在关闭软件之后就恢复了正常。
<img width="390" alt="屏幕截图 2023-12-03 233635" src="https://github.com/babalae/better-genshin-impact/assets/152836596/715da546-57e3-4daa-8da3-8a36f0578124">
今天更新了0.17.1版本之后我特地打开了任务管理器查看内存占用，发现在活动时是有内存回收的，但是我一旦开始挂机内存占用就开始暴涨。之后我动了一下鼠标它又开始自动回收。
<img width="570" alt="屏幕截图 2023-12-03 233547" src="https://github.com/babalae/better-genshin-impact/assets/152836596/d6267f06-91a5-447e-8cb8-f609f5739fa7">
<img width="401" alt="屏幕截图 2023-12-03 011041" src="https://github.com/babalae/better-genshin-impact/assets/152836596/500c922d-5d4c-45e5-92d4-35dbf3517633">
我电脑的配置是7600x+32GB内存。

**Comment by EH1919** [comment]
我

**Comment by EH1919** [comment]
我貌似发现了内存溢出的原因。。。
在长时间软件无交互或拾取时，内存回收会失效，然后内存占用会稳步爬升。然后一旦出现交互或拾取物品，就会自动触发内存回收导致占用下降。
为了验证这个猜想我尝试了两次，两次都出现了同样的状况和同样的结果。
<img width="926" alt="屏幕截图 2023-12-04 000619" src="https://github.com/babalae/better-genshin-impact/assets/152836596/aa6c6d88-f98f-4a7c-9771-44c60ee5269c">
<img width="1025" alt="屏幕截图 2023-12-04 000856" src="https://github.com/babalae/better-genshin-impact/assets/152836596/c34a457b-38cd-449c-aaa6-a043fc9f30e6">

**Comment by EH1919** [comment]
以下是我BetterGI里的设置
<img width="451" alt="屏幕截图 2023-12-04 003627" src="https://github.com/babalae/better-genshin-impact/assets/152836596/c5cf71b5-9cde-49a6-b5fb-ee6f08496f21">
<img width="451" alt="屏幕截图 2023-12-04 003632" src="https://github.com/babalae/better-genshin-impact/assets/152836596/18c422d7-8c60-4b4e-b251-4eba5482cba2">
<img width="448" alt="屏幕截图 2023-12-04 003639" src="https://github.com/babalae/better-genshin-impact/assets/152836596/a8761be0-be5b-4ccb-94ce-66b1dc0e5748">
<img width="448" alt="屏幕截图 2023-12-04 003642" src="https://github.com/babalae/better-genshin-impact/assets/152836596/ca2245b9-6985-43de-ad29-a245f31c7865">

**Comment by SoYeonQwQ** [comment]
<img width="559" alt="56db2be1d381863fad075165dadb95cd" src="https://github.com/babalae/better-genshin-impact/assets/30514102/339b49ab-840d-4592-bbb2-4b1df1f9f7bd">
倒是没测试过，确实有异常，停止后就恢复正常了

**Comment by goldenapple1** [comment]
好好好，终于有人找到原因了，之前就反馈过一次内存管理问题但是没找到具体原因

**Comment by EH1919** [comment]
今天似乎没有出现这种状况，我也有点懵了。。。
今天我开任务管理器监视内存占用发现，像昨天那样挂机它内存占用到快满了的时候无论有没有互动和拾取它又自动触发回收然后占用暴降。

**Comment by EH1919** [comment]
不过如果出现互动和拾取或者玩家靠近NPC出现对话选项之后必定触发内存回收。

**Comment by EH1919** [comment]
> 交互选项我的观察比较少，我是在钓鱼的时候发现内存问题的，我提的issue：#52

它软件只要开启了之后游戏里面不活动（指没有交互或者正在进行中的活动）就会开始逐步占用系统剩下的内存，当内存被占满之后游戏就开始掉帧卡顿了。你在钓鱼的时候可以开个任务管理器看一下你的内存占用。

**Comment by EH1919** [comment]
> 交互选项我的观察比较少，我是在钓鱼的时候发现内存问题的，我提的issue：#52

还有就是你在里面提到了貌似跟帧率有关，我晚点试试不解锁帧率看看内存占用上升会不会慢点，我解锁了帧率到144现在大概两分钟左右没有活动就被占满。

**Comment by huiyadanli** [comment]
我16G内存测试正常，会在1G左右的时候自动回收。测试了两种截图方式。

**Comment by goldenapple1** [comment]
内存大于16G触发貌似是成立的， #52 的另一位反馈者推测也是32G内存。但我目前还有一个怀疑点，这个内存回收会不会跟屏幕分辨率更有关系？就我观察，作者应该是1080P笔记本的屏幕？我是1440p屏幕全屏+32G内存下运行出现过类似的内存使用异常， #52 里另一个有截图的反馈屏幕分辨率也大于1080p，该问题下另一位反馈者的屏幕推测为2160p，也是大于1080p。

~~要不资助作者一个2k显示屏测试吧（逃~~

**Comment by EH1919** [comment]
> 内存大于16G触发貌似是成立的， #52 的另一位反馈者推测也是32G内存。但我目前还有一个怀疑点，这个内存回收会不会跟屏幕分辨率更有关系？就我观察，作者应该是1080P笔记本的屏幕？我是1440p屏幕全屏+32G内存下运行出现过类似的内存使用异常， #52 里另一个有截图的反馈屏幕分辨率也大于1080p，该问题下另一位反馈者的屏幕推测为2160p，也是大于1080p。
> 
> ~要不资助作者一个2k显示屏测试吧（逃~

（草

我稍后更改帧率和分辨率再进行尝试，看看分辨率和帧率是否会对这个造成影响。

**Comment by EH1919** [comment]
> 我16G内存测试正常，会在1G左右的时候自动回收。测试了两种截图方式。

今天我在重新启动之后它也是会在剩余1G左右的内存就开始回收，但是之前前两次都是直接占满导致电脑卡顿游戏掉帧。看来是有某种原因造成了内存回收失效。

**Comment by huiyadanli** [comment]
我一直是窗口化测试的，我也试试2K屏。。。

**Comment by goldenapple1** [comment]
我刚刚进行了几次测试，分别以分辨率、帧率和触发器间隔作为变量，得到的结果是内存清理周期和这些变量都没有明显正相关，几乎都会在一分十五秒左右清理一次内存，但是分辨率越高内存申请速度越快，2k分辨率下触发清理之前可以达到98%的内存占用，但1080p下会在八十多占用左右清理。

我是找到了一个可以稳定触发这个内存异常的条件，就是先在一个钓鱼点钓一次鱼，然后等到窗口上跳出识别张力条的框，这时候内存就会开始稳定增长，这个框就是下图的样子
![2023-12-05_014516](https://github.com/babalae/better-genshin-impact/assets/56142186/3f66c8da-ab91-49b0-98bd-664ccd9c4b73)
有时候会在2000-5000MB左右突然触发一次清理，但是大多数情况下都会到一万多MB的时候才会开始清理

那现在我就有个问题了，作者说1G左右自动回收，那么这个时候内存占用是到98%了吗，如果没有那我觉得可以考虑环境问题，看起来不一样的好像也只有环境了，自动GC有没有可能调用了什么目前没有包含的库？

**Comment by EH1919** [comment]
> 我刚刚进行了几次测试，分别以分辨率、帧率和触发器间隔作为变量，得到的结果是内存清理周期和这些变量都没有明显正相关，几乎都会在一分十五秒左右清理一次内存，但是分辨率越高内存申请速度越快，2k分辨率下触发清理之前可以达到98%的内存占用，但1080p下会在八十多占用左右清理。
> 
> 我是找到了一个可以稳定触发这个内存异常的条件，就是先在一个钓鱼点钓一次鱼，然后等到窗口上跳出识别张力条的框，这时候内存就会开始稳定增长，这个框就是下图的样子 ![2023-12-05_014516](https://private-user-images.githubusercontent.com/56142186/287959641-3f66c8da-ab91-49b0-98bd-664ccd9c4b73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MjE3NjcsIm5iZiI6MTcwMTgyMTQ2NywicGF0aCI6Ii81NjE0MjE4Ni8yODc5NTk2NDEtM2Y2NmM4ZGEtYWI5MS00OWIwLTk4YmQtNjY0Y2NkOWM0YjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDAwMTEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNzIyN2IwNDVlNWZlOTI0ODNiNThmMTE2N2M5YTgwMzllOGNjZDAwYzM2OGQ2MTBiNzIzNWNmZWNiZTdiNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NlTFQOxpP1qNZVgOw-qsBgAA9Qluvyfc88G1YkoE_iw) 有时候会在2000-5000MB左右突然触发一次清理，但是大多数情况下都会到一万多MB的时候才会开始清理
> 
> 那现在我就有个问题了，作者说1G左右自动回收，那么这个时候内存占用是到98%了吗，如果没有那我觉得可以考虑环境问题，看起来不一样的好像也只有环境了，自动GC有没有可能调用了什么目前没有包含的库？

我前两次没有触发自动回收的时候内存占用的可用内存已经剩下500m左右，而且一直都没有触发回收，你可以看我发的第一张图，上满占用率在我关闭软件之前还持平了一段时间，而且在这段时间里也没有触发内存回收。
而昨天在触发自动回收时内存占用是97%，剩余可用内存是800MB

**Comment by huiyadanli** [comment]
https://f.ws59.cn/f/cubsyz447vc 密码:2152 

可以试试这个2s一次GC的测试版本

**Comment by EH1919** [comment]
> https://f.ws59.cn/f/cubsyz447vc 密码:2152
> 
> 可以试试这个2s一次GC的测试版本，我这边测试内存占用会一直保持在400M下。

<img width="347" alt="屏幕截图 2023-12-06 173009" src="https://github.com/babalae/better-genshin-impact/assets/152836596/82ae0caf-2686-4213-b651-ceae46ddf288">
打开的时候出现了这个

**Comment by EH1919** [comment]
<img width="346" alt="屏幕截图 2023-12-06 173348" src="https://github.com/babalae/better-genshin-impact/assets/152836596/5b4d2ddb-5606-43ef-921f-f45105944a64">
<img width="349" alt="屏幕截图 2023-12-06 173351" src="https://github.com/babalae/better-genshin-impact/assets/152836596/e063528c-f30b-4933-af06-d0ac3f85b88e">

**Comment by goldenapple1** [comment]
> https://f.ws59.cn/f/cubsyz447vc 密码:2152
> 
> 可以试试这个2s一次GC的测试版本，我这边测试内存占用会一直保持在400M下。

我这边的运行结果是修复了内存占用问题，现在内存占用稳定在800MB以下，但是出现了概率识别不了“上钩了”文本和概率识别不了钓鱼拉条。

我不清楚C#是什么样子，但是如果有可能的话，我建议实现纯手动析构，管好内存也算是程序员的一个必修课吧。我目前怀疑是不是自动回收把你需要的东西也一起回收了，因为之前在我给了软件管理员权限的情况下是没有出现这种问题的。

至于楼上碰到的程序异常可以试试更新一下.NET环境，看看能不能修复这个错误。

**Comment by goldenapple1** [comment]
> > https://f.ws59.cn/f/cubsyz447vc 密码:2152
> > 可以试试这个2s一次GC的测试版本，我这边测试内存占用会一直保持在400M下。
> 
> <img alt="屏幕截图 2023-12-06 173009" width="347" src="https://private-user-images.githubusercontent.com/152836596/288565989-82ae0caf-2686-4213-b651-ceae46ddf288.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MDc3NzYsIm5iZiI6MTcwMTkwNzQ3NiwicGF0aCI6Ii8xNTI4MzY1OTYvMjg4NTY1OTg5LTgyYWUwY2FmLTI2ODYtNDIxMy1iNjUxLWNlYWU0NmRkZjI4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwN1QwMDA0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2YxOTVhYTZhZTY4MTMyMWEzZWY4MWY1OWU3N2NmY2M1NDA4MDk3NjYyNTQwMGFmYWQ1NzZmMGYxYjk4MGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y_66Ww8SMaO6jm9yMlHFAonkvkeWDhIZ5y4nz0pdWGQ"> 打开的时候出现了这个 <img alt="屏幕截图 2023-12-06 173302" width="347" src="https://private-user-images.githubusercontent.com/152836596/288566454-96620751-22ee-490e-ba3b-193f6fef9de8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MDc3NzYsIm5iZiI6MTcwMTkwNzQ3NiwicGF0aCI6Ii8xNTI4MzY1OTYvMjg4NTY2NDU0LTk2NjIwNzUxLTIyZWUtNDkwZS1iYTNiLTE5M2Y2ZmVmOWRlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwN1QwMDA0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTZkOWNlN2FiYjJiZDJkYTYzY2QzOWE3Njk4NDk0N2QyNjNmZDk4YzU0ZjE3Zjg3MTI5Njc0YzRiMzMyOWY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xXI1IlGpJMqYJDEo_uy6JZOuo6OeWXSkIX20AZbJVY0"> 然后启动失败了

你这个跟 #132 很像，试试132下面的解决方案

**Comment by huiyadanli** [comment]
@EH1919 不要解压到桌面运行

**Comment by EH1919** [comment]
> @EH1919 不要解压到桌面运行

没有啊，我解压到我F盘里的

**Comment by huiyadanli** [comment]
@goldenapple1 钓鱼无变更，我得试试。正常来说是没有影响的。

当前就是已经有在手动释放对象了（也有可能有哪边漏了），还有些调用c++的非托管内存不太好处理。

**Comment by huiyadanli** [comment]
> > @EH1919 不要解压到桌面运行
> 
> 没有啊，我解压到我F盘里的

奇怪了，老版本能运行，我新发的版本反倒无法运行吗 :joy:

**Comment by EH1919** [comment]
> > > @EH1919 不要解压到桌面运行
> > 
> > 
> > 没有啊，我解压到我F盘里的
> 
> 奇怪了，老版本能运行，我新发的版本反倒无法运行吗 😂

对的，都在同一个文件夹里

**Comment by huiyadanli** [comment]
你找一处新地方解压运行试试？

**Comment by EH1919** [comment]
> 你找一处新地方解压运行试试？

我把路径里面的中文都删了，现在好了。
不过我也安装了那个 #132 的那个东西。
所以不知道是哪个起作用了

**Comment by EH1919** [comment]
> https://f.ws59.cn/f/cubsyz447vc 密码:2152
> 
> 可以试试这个2s一次GC的测试版本，我这边测试内存占用会一直保持在400M下。

<img width="465" alt="屏幕截图 2023-12-06 215000" src="https://github.com/babalae/better-genshin-impact/assets/152836596/e5dcdb21-653e-45c9-9e88-63748e82f642">
<img width="465" alt="屏幕截图 2023-12-06 221109" src="https://github.com/babalae/better-genshin-impact/assets/152836596/3388a16f-29d7-4913-b14d-e4a898f8c6fc">
新版本好用，内存占用基本上没有什么太大的波动。

**Comment by huiyadanli** [comment]
会于下版本上线，不知道还有没有其他内存泄露的点。但是对于用户而言基本解决了问题。

对于一个C#程序而言实际是一个不太优雅的方案。

**Comment by goldenapple1** [comment]
OK，那如果我找到了钓鱼不触发的条件我开新issue吧

**Comment by EH1919** [comment]
> 会于下版本上线，不知道还有没有其他内存泄露的点。但是对于用户而言基本解决了问题。
> 
> 对于一个C#程序而言实际是一个不太优雅的方案。
能正常运行就行

**Comment by huiyadanli** [comment]
已经发布新版本
https://github.com/babalae/better-genshin-impact/releases/tag/0.18.0

如果后续还有明显的内存泄露问题，可以继续开新issues，感谢各位的反馈和测试。
