### ISSUE TITLE
[bug]当收到进入世界确认时自动提竿失效

### ISSUE THREAD

**Issue by goldenapple1** [babalae/better-genshin-impact#137]
![image](https://github.com/babalae/better-genshin-impact/assets/56142186/a05ac44d-6ecc-48fe-9ab6-231b2bc008dc)
这个是在1080p窗口化下得到的一个结果，更高分辨率下可能无法复现，我观察到的行为是只要申请进来它就找不到张力点在哪里

其实我觉得可以把这个截图的地方裁的更精确点，可能就没有这个bug了

**Comment by huiyadanli** [comment]
奇妙的问题，看上去是黄色条干扰的钓鱼判断。

不过这个问题太过于罕见了，不会修复。当前的剪裁判断位置已经非常小了，再小可能会影响正常识别。

**Comment by goldenapple1** [comment]
啊这😂
