### ISSUE TITLE
可以添加一个在商店买东西自动买最大值的功能吗

### ISSUE THREAD

**Issue by zmy1828** [babalae/better-genshin-impact#138]
原食玩家，每天四处进货最难受的就是拖动选择数量太费劲(；´д｀)ゞ

**Comment by Scighost** [comment]
补充一些细节，商店物品可购买的最大值不会使材料溢出，达到容量上限的材料会出现在商店列表的最底部。摩拉不足的场景无法测试。

<img width="1280" alt="Snipaste_20231207_120658" src="https://github.com/babalae/better-genshin-impact/assets/61003590/e1cba7ac-904d-46aa-8aee-1562d5390514">

<img width="1280" alt="Snipaste_20231207_120903" src="https://github.com/babalae/better-genshin-impact/assets/61003590/77aa09a7-0008-4a76-bdf3-8d6172e1ad77">

**Comment by goldenapple1** [comment]
> 补充一些细节，商店物品可购买的最大值不会使材料溢出，达到容量上限的材料会出现在商店列表的最底部。摩拉不足的场景无法测试。
> 
> <img alt="Snipaste_20231207_120658" width="1280" src="https://private-user-images.githubusercontent.com/61003590/288627126-e1cba7ac-904d-46aa-8aee-1562d5390514.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwODk3MzQsIm5iZiI6MTcwMjA4OTQzNCwicGF0aCI6Ii82MTAwMzU5MC8yODg2MjcxMjYtZTFjYmE3YWMtOTA0ZC00NmFhLThhZWUtMTU2MmQ1MzkwNTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDAyMzcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYzdjYmM5Y2FlNzk4ZGI5NzdjZmFhYTQ0YmYxZjNjMDRkNTcxYzBhNjNjNWM3NzYyNjU5OTgxZTA2YTc5OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c3KB47oWXzwOr-B8b9qJ7_pWBNE5bmRvw94FFAqHcDw"> <img alt="Snipaste_20231207_120903" width="1280" src="https://private-user-images.githubusercontent.com/61003590/288627318-77aa09a7-0008-4a76-bdf3-8d6172e1ad77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwODk3MzQsIm5iZiI6MTcwMjA4OTQzNCwicGF0aCI6Ii82MTAwMzU5MC8yODg2MjczMTgtNzdhYTA5YTctMDAwOC00YTc2LWJkZjMtOGQ2MTcyZTFhZDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDAyMzcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNDc4NTdjNzRjMjFlMGVkYjlhYmZkODA1MDljNjExN2IwZjJhMjA4YmUwY2E3MWFhMTE5OWMxOGZlOTNjZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P78FmU-3HsS_RSlGtorDLv5pNIUMijZJspgN7yEqNnE">

捉大佬，starward作者（手动狗头

**Comment by huiyadanli** [comment]
在物品购买/兑换页按下，使用快捷键调用，想要买几次物品，就点按几次。

长按可能会炸，可以通过切换出游戏界面解决。

**Comment by batvbs** [comment]
> 在物品购买/兑换页按下，使用快捷键调用，想要买几次物品，就点按几次。
> 
> 长按可能会炸，可以通过切换出游戏界面解决。

目前的版本，好像没有这个功能与快捷键

**Comment by huiyadanli** [comment]
@batvbs 下版本实装

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.18.0
