### ISSUE TITLE
七圣召唤问题修复

### ISSUE THREAD

**Issue by huiyadanli** [babalae/better-genshin-impact#14]
- [x]  1. 出战角色识别率优化
![2)Q){HFF)L $SMH2JO~%SR7_tmb](https://github.com/babalae/better-genshin-impact/assets/15783049/49330316-108d-4710-b7c8-3a1834955e0e)

- [x]  2. 最后一张牌烧牌失败
- [x]  3. 场地骰子不正确

**Comment by TheTychoStar** [comment]
大佬，正说好像七圣有点问题，就看到这里了。

**Comment by huiyadanli** [comment]
1、3 的OCR解决方案识别效果也不佳

**Comment by huiyadanli** [comment]
修复版本：
https://github.com/babalae/better-genshin-impact/releases/tag/0.14.0
