### ISSUE TITLE
原神窗体最小化并还原的时候，频繁出现窗口大小变化的警告

### ISSUE THREAD

**Issue by goldenapple1** [babalae/better-genshin-impact#145]
https://www.bilibili.com/video/BV1Sj411W7Ar

详情请看视频简介（没有找到这个bug的触发原因，有点玄学）

补充一下，发现“游戏窗口大小发生变化”错误可以在窗口焦点发生变化后切回原神的时候稳定触发，但我认为这个应该不是预期的行为，因为窗口只是最小化了，并没有更改分辨率。

**Comment by goldenapple1** [comment]
加个焦点检查就行，原神只要你切窗口焦点不在游戏这儿了就会自动最小化，除非你改注册表，但这样的话它就不会最小化也不会出问题了。

**Comment by huiyadanli** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/15783049/14a79a9d-26ef-41f7-bec1-367de62bf2de)

打印了日志才发现这么好改

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.25.0 已修复
