### ISSUE TITLE
[bug]游戏注册表信息读取失败

### ISSUE THREAD

**Issue by uprprc777** [babalae/better-genshin-impact#147]
![IMG_0062](https://github.com/babalae/better-genshin-impact/assets/77074728/557080cf-2fba-4fd1-b826-4de80c3aab7e)

I sincerely apologize for taking a photo instead of making a clean screenshot. I can't transfer any data from the PC I play Genshin to the Mac I use to submit this GitHub issue. Also, I am not able to log in GitHub account on that PC.

Every time I hit "启动", this error message pops up. It says, "游戏注册表信息读取失败" and some debug info.
Although I can ignore this window and most functions of BetterGI seem to work properly.

FYI, I am using Windows 10 IoT Enterprise LTSC, 19044.1288.

**Comment by uprprc777** [comment]
I noticed that it says, "cannot open log for source '.NET Runtime'". But I am sure that I have .NET Desktop Runtime 7.0.14, x86 and x64, installed.
Also, the error message gives a strange path "D:\HuiPrograming\...\TaskTriggerDispatcher.cs" while I only have one drive/partition C: in my Windows.

**Comment by goldenapple1** [comment]
#139 

According to author of BetterGI, "bug, please use v0.16"
According to 139, you have 2 possible solutions: 1. move Genshin Impact back to its original path; 2. modify registry of genshin, the path of genshin registry should look like "计算机\HKEY_CURRENT_USER\SOFTWARE\miHoYo\原神", which 计算机 means "computer" and 原神 means "Genshin Impact"; 3. try 0.17.2, which is a preview test version: https://drive.google.com/file/d/1-vOW06M9zij2k2cXQLjVoUFtdR4b_iR0/view?usp=sharing All I know is that this version fixes the memory management problem, but I'm not sure if it removes the registry read failure prompt.

**Comment by Mcayear** [comment]
Are you using Cloud Genshin Impact?
![image](https://github.com/babalae/better-genshin-impact/assets/48203962/17c63e9a-7d4a-46cb-a45a-e986bd306ae3)

**Comment by huiyadanli** [comment]
try "Run as administrator"? The folder where the BetterGI is located may not have permission to write.

**Comment by uprprc777** [comment]
> Are you using Cloud Genshin Impact?

No. It's local GI, international though.

> try "Run as administrator"? The folder where the BetterGI is located may not have permission to write.

This might be not the case.

Each time BetterGI launches, it asks for administrator privilege. So BetterGI has always been running with administrator privilege.
I tried explicitly using the "Run as administrator" option to launch BetterGI. Unfortunately, this issue persists.
Also, I can confirm that it doesn't require administrator privilege to write to BetterGI's directory.

**Comment by goldenapple1** [comment]
I think there is a possiblility that the package from international server has a different registry path and we didn't consider that.

**Comment by goldenapple1** [comment]
If your GI package is international version, I assume the registry path below should be exist: Computer\HKEY_CURRENT_USER\SOFTWARE\miHoYo\Genshin Impact

It is possible that typos exists in above path, but I think it is something like that. I guess the code want to read "GENERAL_DATA", if this data does not exist, this error will show up.

Another possibility is, you change your GI to Simplified Chinese, then restart BetterGI, and you find the error disappears...

**Comment by uprprc777** [comment]
> If your GI package is international version, I assume the registry path below should be exist: Computer\HKEY_CURRENT_USER\SOFTWARE\miHoYo\Genshin Impact
> 
> It is possible that typos exists in above path, but I think it is something like that. I guess the code want to read "GENERAL_DATA", if this data does not exist, this error will show up.
> 
> Another possibility is, you change your GI to Simplified Chinese, then restart BetterGI, and you find the error disappears...

I have set GI to Simplified Chinese before the first time I use BetterGI. This doesn't resolve the issue.

The registry key `Computer\HKEY_CURRENT_USER\SOFTWARE\miHoYo\Genshin Impact` exists in my Windows, and there are some DWORD and BIN values under it.
There is a BIN value named `GENERAL_DATA_<***a_string_possibly_random>`.

**Comment by goldenapple1** [comment]
Does this issue persists in 0.18.0？

**Comment by huiyadanli** [comment]
@goldenapple1 Nothing to do with the registry, it's a log output problem

**Comment by uprprc777** [comment]
> Does this issue persists in 0.18.0？

It's gone but 0.18.0 is completely broken for me.

**Comment by uprprc777** [comment]
> Is there an error prompt or log printing in version 0.18.0?

No more `游戏注册表信息读取失败`, but [150](https://github.com/babalae/better-genshin-impact/issues/150).
