### ISSUE TITLE
细化自动剧情的选项

### ISSUE THREAD

**Issue by sblzdddd** [babalae/better-genshin-impact#149]
能否加一个筛选对话对象的功能（如对话黑名单）
每次供奉神瞳的时候都会被自动拾取+自动剧情打断（
另外一个小问题就是枫丹部分剧情会有中断类的选项，选了就算暂停，能否出一个匹配选项关键词的？

### 粗略的实现方法
使用屏幕绝对位置 （+文字颜色，如果是识别对话对象）识别文字位置（抄一下[PickTextInference.cs](https://github.com/babalae/better-genshin-impact/blob/main/BetterGenshinImpact/Core/Recognition/ONNX/SVTR/PickTextInference.cs)？），然后在黑名单里不点击

### 可能的问题？
高占用，我猜

#16 写完了才发现...

**Comment by huiyadanli** [comment]
文字识别会使用 [PaddleOcrService.cs](https://github.com/babalae/better-genshin-impact/blob/main/BetterGenshinImpact/Core/Recognition/OCR/PaddleOcrService.cs)

大概率是通过图标 + 橙色文字来实现细化。

直接使用文字识别也是一种很好的思路（速度慢点，但是开发效率更高）

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.24.0  已优化
