### ISSUE TITLE
有没有可能支持Mac云原神

### ISSUE THREAD

**Issue by linyu003** [babalae/better-genshin-impact#15]
如果要支持Mac云原神，有哪些技术问题需要解决呢？ 
我想搞一搞，想听听作者的想法

**Comment by huiyadanli** [comment]
虽然 C# 有一定的跨平台能力。

但是当前的界面UI库和底层模拟操作都是基于win32的，基本需要替换掉。

不过实际识别的原理和识别所用的依赖库都是有对应的跨平台实现，可以直接参考并迁移。比如 OpenCV 、 ONNX 等。
