### ISSUE TITLE
[feature request] BetterGI自身是否有启动参数？

### ISSUE THREAD

**Issue by goldenapple1** [babalae/better-genshin-impact#152]
核心需求是想让starward和BetterGI联动启动原神，但是看起来BetterGI好像没有类似可以通过参数直接启动自己、启动视觉识别并且启动原神的功能

starward项目地址：https://github.com/Scighost/Starward
我在starward那边也开了一个issue：https://github.com/Scighost/Starward/issues/537

我怀疑starward作者本人也在用BetterGI（逃

**Comment by emako** [comment]
目前仅实现了url协议启动：`BetterGI://`
未支持更多的启动参数。

**Comment by goldenapple1** [comment]
可以从哪里知道目前有什么参数？
顺便我感觉betterGI目前好像没有什么开发文档，比如API什么的，就算我想贡献代码也不知道从哪里入手

**Comment by huiyadanli** [comment]
url协议已经支持 `bettergi://start` 
命令行支持 `BetterGI.exe start`

加上这个参数软件启动后会立即触发内部的“更好原神启动”。

**Comment by emako** [comment]
> url协议已经支持 `bettergi://start` 命令行支持 `BetterGI.exe start`
> 
> 加上这个参数软件启动后会立即触发内部的“更好原神启动”。

感觉得引入ASP的解析组件了

**Comment by huiyadanli** [comment]
只要不大，引，都可以引
