### ISSUE TITLE
[bug] 在游戏分辨率大于800x600的情况下仍然报错窗口分辨率不得小于800x600

### ISSUE THREAD

**Issue by goldenapple1** [babalae/better-genshin-impact#153]
![image](https://github.com/babalae/better-genshin-impact/assets/56142186/d4924762-8ac7-40fb-a4ac-e5c5eeca465e)
![image](https://github.com/babalae/better-genshin-impact/assets/56142186/a8792d62-88ce-4a33-a53a-e918257b3243)
（我甚至能找到分辨率的注册表

我是从betterGI直接启动原神的，直接启动原神然后再启动betterGI好像就没有这个问题

**Comment by goldenapple1** [comment]
好像是个偶发bug，没找到触发条件，怀疑是因为Windows的最大化动画导致的

**Comment by huiyadanli** [comment]
是直接通过窗体句柄获取的窗口大小。在实际计算捕获区域的时候，获取原神的配置无意义。

疑似和这个问题是相同的原因造成的 https://github.com/babalae/better-genshin-impact/issues/135

0.18出现，0.17应该是没问题的

**Comment by goldenapple1** [comment]
> 是直接通过窗体句柄获取的窗口大小。在实际计算捕获区域的时候，获取原神的配置无意义。
> 
> 疑似和这个问题是相同的原因造成的 #155
> 
> 0.18出现，0.17应该是没问题的

我提这个注册表是因为我觉得很奇怪，按理说原神的窗口变化是不会有最小化最大化的动画的，如果我没记错的话就算你把原神本体改成窗口模式它的最大化最小化按钮也是灰色的。如果你直接切窗口应该也不会有动画，就只是瞬间变小瞬间变大。。Windows真神奇

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.19.0
