### ISSUE TITLE
H.InputSimulator无法支持模拟NumEnter按键

### ISSUE THREAD

**Issue by emako** [babalae/better-genshin-impact#154]
```xml
<PackageReference Include="H.InputSimulator" Version="1.4.1" />
```
H.InputSimulator无法支持模拟NumEnter按键，现在用魔改版的`Fischless.WindowsInput.csproj`替代实现。
目前已经将BetterGenshinImpact.Core.Simulator.Simulation.SendInput标记为Obsolete。

**Comment by huiyadanli** [comment]
这个代码可以无缝替换吗？

**Comment by emako** [comment]
就是vanara版本的H.InputSimulator，换了能通过测试就OK

**Comment by emako** [comment]
进度：目前已基本检查键盘模拟代码一致性

**Comment by huiyadanli** [comment]
`IMouseSimulator` 缺失了一个中键点击的功能。刚好在自动秘境中用到了

**Comment by emako** [comment]
> `IMouseSimulator` 缺失了一个中键点击的功能。刚好在自动秘境中用到了

得空了瞅瞅，键盘那部分代码还没review

**Comment by emako** [comment]
@huiyadanli 好像是说能用了？

**Comment by huiyadanli** [comment]
NumEnter 我没测试过hhh
