### ISSUE TITLE
全屏游戏被识别成游戏窗口最小化的问题

### ISSUE THREAD

**Issue by huiyadanli** [babalae/better-genshin-impact#155]
![~%IWOQEX~U59JKD1B{_LV90_tmb](https://github.com/babalae/better-genshin-impact/assets/15783049/b5dd5c27-21e7-411b-ba8e-d648eced14a5)

疑似是这个bugfix造成的
https://github.com/babalae/better-genshin-impact/issues/135

**Comment by goldenapple1** [comment]
意外发现了全屏无边框可以避免这个bug，而且应该也可以避免 #153 #145 

办法是，修改注册表的Screenmanager Is Fullscreen mode为0并且使用-popupwindow参数启动原神，这样可以让游戏窗口行为变成全屏无边框，彻底消除了最大化最小化动画过程中游戏分辨率改变的问题

但如果考虑到还有很多人有独占全屏的需求，可能后续还是得把这个报错的触发改改吧，只当是提供了一种实现全屏无边框的思路了

**Comment by huiyadanli** [comment]
fixed，但是忘记关issue了
