### ISSUE TITLE
左上角小地图显示东西南北文字

### ISSUE THREAD

**Issue by huiyadanli** [babalae/better-genshin-impact#156]
@Lightczx

**Comment by goldenapple1** [comment]
我倒是觉得可以考虑出一个小地图放大工具，最好适配一下地图锁定玩家视角的情况

**Comment by emako** [comment]
这加的字体感觉有点大

**Comment by Lightczx** [comment]
我认为20-24是比较合适的尺寸 @huiyadanli

**Comment by huiyadanli** [comment]
> 我认为20-24是比较合适的尺寸 @huiyadanli

按你喜好来

**Comment by Lightczx** [comment]
配置感觉可以简化一下，存个地图中心和半径就行，四个字的坐标反正本来就是算出来的

**Comment by Lightczx** [comment]
> 配置感觉可以简化一下，存个地图中心和半径就行，四个字的坐标反正本来就是算出来的

这样改配置也比较轻松

**Comment by emako** [comment]
NSWE呢

**Comment by Lightczx** [comment]
> NSWE呢

我觉得不好，跟视频的时候脑子没这么灵活，尽量不要转换

**Comment by startui** [comment]
> 近期会添加界面实时识别，可以让东西南北文字跟随小地图展示

好的，感谢
