### ISSUE TITLE
客户端组件运行异常,请重新启动客户端

### ISSUE THREAD

**Issue by huiyadanli** [babalae/better-genshin-impact#157]
![image](https://github.com/babalae/better-genshin-impact/assets/15783049/5ab70106-a577-4cc2-9856-6d8af5fb013a)

![Cache_-7531ceca3c023854](https://github.com/babalae/better-genshin-impact/assets/15783049/5f331166-6da7-44c9-a137-7363191bc931)

原因未定位，0.18部分人出现，0.17没问题

猜测原因如下：
1. 从BetterGI启动原神的原因
2. 修改了原神窗体句柄的获取方式的原因（较大概率）
3. <del>某个操作出现了高频点击（大概率不是这个原因，这个报错是10259-4001）</del>

**Comment by goldenapple1** [comment]
应该不是操作速度过快，我今天开着的时候触发了几次，都是在没有触发软件点击条件的情况下遇到了这个报错，具体原因我再测试一下

**Comment by goldenapple1** [comment]
很可能甚至不是betterGI触发了这个问题

![image](https://github.com/babalae/better-genshin-impact/assets/56142186/3e767fd2-c2b4-48c4-bbc0-9b901b60edc4)

**Comment by huiyadanli** [comment]
尝试用官方启动器启动游戏

**Comment by goldenapple1** [comment]
问个问题，你在遇到这个错误的时候有没有修改原神窗口相关的，比如把原神变成全屏无边框模式

**Comment by huiyadanli** [comment]
我没有遇到这个问题，但是其他人有反馈这个问题。大概猜测原因已经更新至1L

**Comment by goldenapple1** [comment]
高频点击应该可以删掉了，错误码不一样，高频点击是10259-4001，咱这个是10258，我从GitHub和b站看到的高频点击导致的组件运行异常都是9结尾报错

**Comment by goldenapple1** [comment]
我目前认为这个问题和0.18版本相关，确实在开0.17、0.16的时候并没有问题。

不清楚你那边是什么情况，但是我这边是，只要0.18和原神一起开个两分钟左右原神就会开始报这个错

**Comment by whomtao** [comment]
我认为这个问题和BetterGI没有关系。目前遇到了四次，第一次我以为是快速拾取导致的，我关了以后又出现了（但是程序还在运行）。之后我关了程序，几分钟以后又报错了。之后我关了游戏，用unlockfps_clr运行约一（二）分钟后还是报错了，期间报错好像不止10258，我还遇到了10259

**Comment by goldenapple1** [comment]
> 我认为这个问题和BetterGI没有关系。目前遇到了四次，第一次我以为是快速拾取导致的，我关了以后又出现了（但是程序还在运行）。之后我关了程序，几分钟以后又报错了。之后我关了游戏，用unlockfps_clr运行约一（二）分钟后还是报错了，期间报错好像不止10258，我还遇到了10259

10259是快速点击和帧率解锁会触发的，10258我目前没有在其他地方查到过，应该不是专门针对BetterGI的，但我目前猜测也确实是BetterGI新版的某个改动导致了这个问题

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.19.0

**Comment by L2020817SX** [comment]
0.15版本也遇到了，我都没有运行，就只是打开betterui然后就有了

**Comment by goldenapple1** [comment]
> 0.15版本也遇到了，我都没有运行，就只是打开betterui然后就有了

0.19修了，如果继续出现再到这里反馈

**Comment by Tudorose** [comment]
有没有人知道102564001是什么意思？
