### ISSUE TITLE
能否在启动游戏时支持解锁帧数？

### ISSUE THREAD

**Issue by Duck-Deng** [babalae/better-genshin-impact#158]
从battleGI 启动游戏是无法直接解锁帧数的，设置自定义启动程序也无法选择Yuanshen.exe以外的程序。能否添加启动时解锁fps功能？

**Comment by huiyadanli** [comment]
下个版本将不再限制选择的启动程序。

解锁帧率短时间不会添加。有太多程序已经有这个功能了

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.19.0
