### ISSUE TITLE
[bug] 多显示器下BetterGI任务栏图标行为异常

### ISSUE THREAD

**Issue by goldenapple1** [babalae/better-genshin-impact#161]
betterGI启动的时候会出现在显示器1，但是如果我把它的窗口挪到显示器2，那么这时候betterGI的任务栏图标会同时在显示器1和2显示，挪回屏幕1又会变成只有一个图标，单例模式倒是没有出错。

看起来可能是一开始就有这个问题，我目前只测试了0.17、0.18、0.16三个版本，均存在上述问题。

你问我为什么现在才发现？因为我开了自动隐藏任务栏。。

**Comment by goldenapple1** [comment]
淦，原神自己的官方启动器也有这b问题

**Comment by emako** [comment]
猜测是W11玩家，W11任务栏一直很多BUG

**Comment by goldenapple1** [comment]
> 猜测是W11玩家，W11任务栏一直很多BUG

win10 22H2 内部版本19045.3758，一会儿我重启下试试，如果是概率bug我就关问题

**Comment by huiyadanli** [comment]
我Win11双显示器未复现以上问题，倒是会出现图标莫名缩小偏移的问题

**Comment by goldenapple1** [comment]
测试了一下发现和betterGI无关，应该是Windows的bug
