### ISSUE TITLE
伐木一段时间后黑屏

### ISSUE THREAD

**Issue by 11389698** [babalae/better-genshin-impact#162]
![image](https://github.com/babalae/better-genshin-impact/assets/79733561/c505865f-42f4-4b34-9074-76ba43dc6487)
伐木大约50轮，然后电脑黑屏，想qq截图没有反应，然后qq闪退

**Comment by huiyadanli** [comment]
使用BitBlt的截图方式

**Comment by 11389698** [comment]
> 使用BitBlt的截图方式

我用的就是BitBlt

**Comment by emako** [comment]
复现一次：
步骤：
1. 启动总开关，启动伐木开关
2. 伐木大概50轮内
3. 关启动总开关，不关伐木开关
4. 发现有这个弹窗

**Comment by huiyadanli** [comment]
一般不会去关总开关的吧，关了肯定寄

**Comment by emako** [comment]
总开关都关了，子开关理应自动关吧

**Comment by huiyadanli** [comment]
> 总开关都关了，子开关理应自动关吧

也是，倒时候联动改造下

**Comment by huiyadanli** [comment]
增加了重试次数，增长了时间间隔，不知道有没有效果

**Comment by huiyadanli** [comment]
**电脑熄屏后，截图功能无法正常工作，会导致自动伐木失败。所以长时间挂机时，请调整“电源策略”，让电脑屏幕不自动关闭屏幕。**
