### ISSUE TITLE
能否添加弓箭速射

### ISSUE THREAD

**Issue by nomoneynolife** [babalae/better-genshin-impact#164]
看演示好像是说，不停点击取消普通攻击和瞄准

**Comment by goldenapple1** [comment]
这个东西容易触发原神的10259-4001客户端组件报错，你想用目前也有其他软件可以达成的手段，个人认为这个功能可能优先级比较低

**Comment by TheTychoStar** [comment]
这个风险太大了，容易引起数据异常，想用可以自己去搜鼠标宏，风险自担。

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.27.0 已支持
