### ISSUE TITLE
0.19.0 自动钓鱼无效

### ISSUE THREAD

**Issue by Horane** [babalae/better-genshin-impact#166]
三种图像捕获方式都看了，视觉上正常的
日志也能看到开启了自动钓鱼，但是咬钩之后无任何反应
“鱼儿上钩啦”几个字也不出现红框
但是在我手动开始拉线后，能偶尔感觉到有非手部操作的干预
如果不手动开始拉线，脱钩提示“鱼儿脱钩啦”这五个字偶尔会出现红框，且log里有自动提竿提示（只有两行）

自动拾取正常
触发器间隔-默认50ms
自动抛竿-关
![image](https://github.com/babalae/better-genshin-impact/assets/4545313/f4058ff4-5196-4303-ac89-d3fb22c5c9fb)

**Comment by huiyadanli** [comment]
屏幕分辨率使用1920x1080，截图方式使用BitBlt重试下

**Comment by Horane** [comment]
> 屏幕分辨率使用1920x1080，截图方式使用BitBlt重试下

嗯 试过了 1920x1080是可以的 可能是分辨率异常了 我是ALT+ENTER切过窗口/全屏，我在全屏（2560*1440）状态下进入设置时，显示的是1920*1080窗口 改过之后就可以了

**Comment by Horane** [comment]
出现了另一个问题~全屏状态下，ALT+TAB切换后，有概率遮罩窗口不自动置顶了，只能F11关开或反复切窗口才又能显示遮罩

**Comment by huiyadanli** [comment]
> 出现了另一个问题~全屏状态下，ALT+TAB切换后，有概率遮罩窗口不自动置顶了，只能F11关开或反复切窗口才又能显示遮罩

这个问题暂时无解，独占全屏的情况下，窗口置顶有些时候能生效有些时候生效不了。也许延迟下窗口的置顶设置能解决，也只是猜测，独占全屏在每个人的系统上的表现结果不一定相同

**Comment by goldenapple1** [comment]
看起来和我之前测试遇到的情况很像，但是我当时遇到的是概率触发的，你这边遇到的情况能稳定复现吗？

**Comment by uprprc777** [comment]
> 三种图像捕获方式都看了，视觉上正常的 日志也能看到开启了自动钓鱼，但是咬钩之后无任何反应 “鱼儿上钩啦”几个字也不出现红框 但是在我手动开始拉线后，能偶尔感觉到有非手部操作的干预 如果不手动开始拉线，脱钩提示“鱼儿脱钩啦”这五个字偶尔会出现红框，且log里有自动提竿提示（只有两行）
> 
> 自动拾取正常 触发器间隔-默认50ms 自动抛竿-关 ![image](https://private-user-images.githubusercontent.com/4545313/290453122-f4058ff4-5196-4303-ac89-d3fb22c5c9fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzcyOTMsIm5iZiI6MTcwMjYzNjk5MywicGF0aCI6Ii80NTQ1MzEzLzI5MDQ1MzEyMi1mNDA1OGZmNC01MTk2LTQzMDMtYWM4OS1kM2ZiMjJjNWM5ZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMTA0MzEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDdkMDkwNTNjOTNjNzg2MmU5MzQ1ZTg1MjhkOTBhNGE5MGI3MzFmNDlkYWQzYjE3YjE3NmYxYmI0Y2U4OWNkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1QdV14fk6X5IJNUUEQ2xYLR8TaKPAIX-WubJl5oQeeQ)

Same issues here for 0.17.x and 0.18.0. Even the game is in 1920x1080 window.

Auto fishing is enabled, and there is correct log printing.

Auto fishing fails randomly occasionally, about once for tens of successful fishing.

When the fish is on the hook, the "鱼儿上钩啦" message appears. But no red rectangle surrounds the message, and BetterGI doesn't raise the hook.
Then, the fish will run away eventually, and everything will repeat.

If I manually raise the hook, the auto fishing will recover and begins struggling. And it will remain functional for the next tens of fishing.

**Comment by huiyadanli** [comment]
> > 三种图像捕获方式都看了，视觉上正常的 日志也能看到开启了自动钓鱼，但是咬钩之后无任何反应 “鱼儿上钩啦”几个字也不出现红框 但是在我手动开始拉线后，能偶尔感觉到有非手部操作的干预 如果不手动开始拉线，脱钩提示“鱼儿脱钩啦”这五个字偶尔会出现红框，且log里有自动提竿提示（只有两行）
> > 自动拾取正常 触发器间隔-默认50ms 自动抛竿-关 ![image](https://private-user-images.githubusercontent.com/4545313/290453122-f4058ff4-5196-4303-ac89-d3fb22c5c9fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzcyOTMsIm5iZiI6MTcwMjYzNjk5MywicGF0aCI6Ii80NTQ1MzEzLzI5MDQ1MzEyMi1mNDA1OGZmNC01MTk2LTQzMDMtYWM4OS1kM2ZiMjJjNWM5ZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMTA0MzEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDdkMDkwNTNjOTNjNzg2MmU5MzQ1ZTg1MjhkOTBhNGE5MGI3MzFmNDlkYWQzYjE3YjE3NmYxYmI0Y2U4OWNkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1QdV14fk6X5IJNUUEQ2xYLR8TaKPAIX-WubJl5oQeeQ)
> 
> Same issues here for 0.17.x and 0.18.0. Even the game is in 1920x1080 window. Haven't tried 0.19.
> 
> Auto fishing is enabled, and there is correct log printing.
> 
> Auto fishing fails randomly and occasionally, about once for tens of successful fishing.
> 
> When the fish is on the hook, the "鱼儿上钩啦" message appears. But no red rectangle surrounds the message, and BetterGI doesn't raise the hook. Then, the fish will run away eventually, and everything will repeat.
> 
> If I manually raise the hook, the auto fishing will recover and begins struggling. And it will remain functional for the next tens of fishing.

Try using BitBl. 

There is a delay in WindowsGraphicsCapture.

![image](https://github.com/babalae/better-genshin-impact/assets/15783049/ef1f4b2f-5a8d-4b9f-9ca0-4035956c992f)
