### ISSUE TITLE
数据异常，请重新登录游戏 10051-4001

### ISSUE THREAD

**Issue by huiyadanli** [babalae/better-genshin-impact#169]
![1OMCBXBEUG`TDO RHU86 3](https://github.com/babalae/better-genshin-impact/assets/15783049/26d38388-c456-496e-82f9-585ccb632823)
![FD6@JVCYME(WS0WJJTAG})V_tmb](https://github.com/babalae/better-genshin-impact/assets/15783049/bbe94faf-2840-46b6-a1dd-8b12cb16d155)

自动伐木

**Comment by goldenapple1** [comment]
。。咱还真就跟错误码杠上了

**Comment by goldenapple1** [comment]
我开自动伐木开了两百多次，在0.19.0下没有复现这个错误，有可能跟BetterGI无关。

这个错误码也很奇怪，谷歌、b站、GitHub都没有关于这个错误码的结果。

我只找到了部分关于“数据异常，请重新登录游戏”这个提示出现的讨论：https://notabug.org/Krock/dawn/issues/401
这个讨论看起来相关度不高。

**Comment by TheTychoStar** [comment]
我已经自动伐木上千次了，没有出现过这个问题，应该和本项目无关。

**Comment by huiyadanli** [comment]
这个issue感觉也是个例，毫无头绪，仅作记录。先close了
