### ISSUE TITLE
[feat request] 快速拒绝：拒绝进入世界申请

### ISSUE THREAD

**Issue by emako** [babalae/better-genshin-impact#170]
应用场景：
正常按Y可以打开申请对话框，再按一次Y可以直接拒绝。

**Comment by goldenapple1** [comment]
好feature，社恐人快乐

**Comment by emako** [comment]
考虑到类似的对话框还有挺多的，最好确实是做成可配置不同快捷键为Y or N来触发确定or取消

**Comment by gongfuture** [comment]
可是如果全部拒绝的话，那为啥不直接设置成禁止加入呢？

**Comment by emako** [comment]
> 可是如果全部拒绝的话，那为啥不直接设置成禁止加入呢？

没说过要全部拒绝

**Comment by goldenapple1** [comment]
我倒是觉得可以加个，ID和好友一样的不拒绝

**Comment by huiyadanli** [comment]
按下快捷键 直接寻找对应按钮点击。确认取消按钮整个原神就4个款式

**Comment by huiyadanli** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/15783049/7cb74df9-94b8-4b79-8927-094e0ace1221)

**Comment by huiyadanli** [comment]
完成了个寂寞，发现不是一个素材图:joy:

**Comment by gongfuture** [comment]
> 完成了个寂寞，发现不是一个素材图 :joy:

啊这

**Comment by umieqb** [comment]
大佬大佬    能识别一下有对话框的时候自动禁用嘛，有时候打字的时候按到设置的键位会自动切断输入法    或者允许设置，。、这些比较冷门的键位也可以哇orz  φ(゜▽゜*)♪
