### ISSUE TITLE
发现了一个收益更高的伐木点位

### ISSUE THREAD

**Issue by goldenapple1** [babalae/better-genshin-impact#172]
![image](https://github.com/babalae/better-genshin-impact/assets/56142186/a84fc05a-527e-4afe-83ca-f7cb1e572355)
![image](https://github.com/babalae/better-genshin-impact/assets/56142186/c0880366-0a53-4ad3-a566-a0bb8523aeb6)

收益是悬铃木x9+椴木x9，翻了一下目前文档里的图似乎没有这个

**Comment by emako** [comment]
+

**Comment by huiyadanli** [comment]
![](https://img.alicdn.com/imgextra/i1/2042484851/O1CN01MVT1fI1lhoDyGoMGi_!!2042484851.jpg)

已经添加并更新 https://bgi.huiyadan.com/doc.html#%E6%8E%A8%E8%8D%90%E4%BC%90%E6%9C%A8%E7%82%B9
