### ISSUE TITLE
快速传送误触的问题

### ISSUE THREAD

**Issue by clcm8629** [babalae/better-genshin-impact#173]
快速传送在讨罚悬赏定位目标的时候，会误触导致传送到错误的地方
再有复数传送点位的时候（例：风龙、雷神周本、一些密集点位）會因為自动点击传送到错误的地方
希望能进行优化，像是如有复数点位时，让玩家自己选择点位之类的

**Comment by huiyadanli** [comment]
观察发现，鼠标点选的传送目标是排序在第一位的。

遇到复数传送点时，选择第一个传送点

**Comment by clcm8629** [comment]
用遊戲裡自帶的定位，如：懸賞.每日任務等
還是會出現錯誤傳送的問題

**Comment by huiyadanli** [comment]
每日任务，需要你点击正确的传送点，程序又没法区分点击后列表中存在多个传送点情况下，离每日最近或者正确的传送点。

如果我理解的不对，请结合实际截图说明

**Comment by clcm8629** [comment]
![螢幕擷取畫面 2024-01-24 012741](https://github.com/babalae/better-genshin-impact/assets/69196409/09030f5f-e175-4d91-98a8-514cfa70dd37)
每日任务定位时会开启大地图，此时BetterGI会识别错误导致点击，可能会出现错误传送的问题
![螢幕擷取畫面 2024-01-24 012819](https://github.com/babalae/better-genshin-impact/assets/69196409/42622c68-fda1-4433-b022-d361ac99cbbd)
悬赏也是同理（我这周已经过了，撷取不到定位页面）
悬赏接取后也会出现定位按钮，按下后会开启大地图

**Comment by huiyadanli** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/15783049/aedf7522-82ce-4142-a2ba-a8506a3d50c1)

测试每日，无反应


![image](https://github.com/babalae/better-genshin-impact/assets/15783049/c4f8384d-f9e4-4799-97fc-e9be1da87019)

测试讨伐，无反应

看上去是你使用的分辨率是2K，这种情况下的识别可能会有一定误差

**Comment by clcm8629** [comment]
我的分辨率是1920*1080，缩放1.25

讨伐测试不是每个点位都会发生，如本周讨伐三个里面只有一个觸發

![image](https://github.com/babalae/better-genshin-impact/assets/69196409/2559b1a9-6e13-49c1-ba16-86a8ad264e62)
![image](https://github.com/babalae/better-genshin-impact/assets/69196409/58bb1b48-2b0d-4e28-8aee-7bf440860da0)

如图，日志里BetterGI识别成“要知道”导致错误传送

另经测试传送点位如果包含秘境，BetterGI会优先选择传送点而不是秘境

分别有：蒙德雪山冰水套、风龙周本、璃月绝云间天赋、稻妻防御治疗套、雷神周本、枫丹秋分山东侧治疗结晶套、还有些一次性秘境同理

另外传送点如果包含地上与地（水）下，则BetterGI会优先选择地上

**Comment by clcm8629** [comment]
我的分辨率是1920*1080，缩放1.25

讨伐测试不是每个点位都会发生，如本周讨伐三个里面只有一个觸發

![image](https://github.com/babalae/better-genshin-impact/assets/69196409/cf4fb10a-4407-4cee-9875-dfa42564c430)
![image](https://github.com/babalae/better-genshin-impact/assets/69196409/f36ccdca-f8ae-4cc0-b9a2-a1e1986f4d61)
![image](https://github.com/babalae/better-genshin-impact/assets/69196409/ce1f2937-f078-4883-b5d3-c5fc6f2368da)
![image](https://github.com/babalae/better-genshin-impact/assets/69196409/71b31481-2a30-4992-a8df-465ac198fe61)


如图，日志里BetterGI识别成“要知道”导致错误传送

另经测试传送点位如果包含秘境，BetterGI会优先选择传送点而不是秘境

分别有：蒙德雪山冰水套、风龙周本、璃月绝云间天赋、稻妻防御治疗套、雷神周本、枫丹秋分山东侧治疗结晶套、还有些一次性秘境同理

另外传送点如果包含地上与地（水）下，则BetterGI会优先选择地上

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.24.0  已优化
