### ISSUE TITLE
【征集意见】伐木文档推荐点位展示

### ISSUE THREAD

**Issue by emako** [babalae/better-genshin-impact#174]
目前是有点乱，挂贴征集意见

**Comment by emako** [comment]
目前思路是按国区分类

**Comment by goldenapple1** [comment]
我的建议是内嵌大图减少网站的访问量，并且提供根据木材名称搜索的搜索框，因为我自己很多时候其实都是要找某种特定的木材。在用户没有搜索的时候可以以列表形式浏览所有的木材点位。

我觉得按照国家区分也是很不错的设计，找起来也比较方便。

**Comment by emako** [comment]
已更新按国区分类
