### ISSUE TITLE
枫丹每日任务“总得喝一杯”需加入自动拾取黑名单

### ISSUE THREAD

**Issue by antecanis8** [babalae/better-genshin-impact#175]
因为需要玩家**按照自己的任务进度选择对话中NPC给出的相应原料**来调配咖啡，所以这些原料的按钮都需要加进pick_black_lists.json
按钮标签如下：
加入咖啡
加入水
加入牛奶
加入奶油
加入奶泡
任务中还有个“放置咖啡”的按钮，应该也需要加入

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.24.0  已经添加，但是效果未测试
