### ISSUE TITLE
希望自动拾取能更改快捷键

### ISSUE THREAD

**Issue by HUA179** [babalae/better-genshin-impact#177]
罗技GHUB似乎绑定不上游戏软件，原神开启后无法识别到我在罗技中设置好的侧键F拾取只会用我的全局设置的侧键enter，所以在游戏中我就把拾取的F改成了ENTER来方便平时游戏时的侧键操作。
但betterGI仅支持F自动拾取，无法支持改绑按键后的自动拾取，希望能支持修改自动拾取按键的功能。

**Comment by huiyadanli** [comment]
侧键? 在游戏内拾取显示的是什么，提供一个拾取截图看看

**Comment by emako** [comment]
鸭蛋图像识别的F？

**Comment by huiyadanli** [comment]
> 鸭蛋图像识别的F？

是的

**Comment by emako** [comment]
ElementIdentifierIdConverter.ToName可以得到对应OCR目标文字，不过Right Shift要改成右Shift

**Comment by revy-git** [comment]
只是提一下，但我认为新的自动秘境（自动战斗）功能应该也支持按键重新绑定，对于 AZERTY、DVORAK 和其他键盘布局用户，我个人使用 colemak-dh
![image](https://github.com/babalae/better-genshin-impact/assets/111768965/f07065b8-1edf-41d8-b8ca-1e1af8f07f40)

我用机器翻译写了这篇文章，所以请原谅任何错误。

**Comment by wwpruilin** [comment]
> 只是提一下，但我认为新的自动秘境（自动战斗）功能应该也支持按键重新绑定，对于 AZERTY、DVORAK 和其他键盘布局用户，我个人使用 colemak-dh ![图像](https://private-user-images.githubusercontent.com/111768965/295780423-f07065b8-1edf-41d8-b8ca-1e1af8f07f40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDQxMTksIm5iZiI6MTcwNjAwMzgxOSwicGF0aCI6Ii8xMTE3Njg5NjUvMjk1NzgwNDIzLWYwNzA2NWI4LTFlZGYtNDFkOC1iOGNhLTFlMWFmOGYwN2Y0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QwOTU2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMThjZmUwN2FmY2U5OWI5ODI0NWY2NjdlZGU3NDAxY2IyOWJjYzc5ODljMjI0MWU4OTU1NTdlNzAyYWU4ODJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3GYmqk8R5m0DVr9Iv4D8Sq01LAPsEhwZjCuJ_yJX3WE)
> 
> 我用机器翻译写了这篇文章，所以请原谅任何错误。
这个按键设置感觉有点离谱

**Comment by revy-git** [comment]
> > Just a mention, but I think the new auto-chat (auto-battle) feature should also support key rebinding, for AZERTY, DVORAK and other keyboard layout users, I personally use colemak-dh ![image](https://private-user-images.githubusercontent.com/111768965/295780423-f07065b8-1edf-41d8-b8ca-1e1af8f07f40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDQxMTksIm5iZiI6MTcwNjAwMzgxOSwicGF0aCI6Ii8xMTE3Njg5NjUvMjk1NzgwNDIzLWYwNzA2NWI4LTFlZGYtNDFkOC1iOGNhLTFlMWFmOGYwN2Y0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QwOTU2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMThjZmUwN2FmY2U5OWI5ODI0NWY2NjdlZGU3NDAxY2IyOWJjYzc5ODljMjI0MWU4OTU1NTdlNzAyYWU4ODJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3GYmqk8R5m0DVr9Iv4D8Sq01LAPsEhwZjCuJ_yJX3WE)
> > I wrote this article using machine translation, so please forgive any errors. 
> > This button setting feels a bit outrageous

也许这提供了更多背景信息

https://zh.wikipedia.org/wiki/%E9%98%94%E7%A0%81%E9%94%AE%E7%9B%98

![image](https://github.com/babalae/better-genshin-impact/assets/111768965/897b9dc4-5b0f-4c22-b015-b10f8b3616ba)
![8df3489a805cc7983b0642a9791597da_97eacdf5-02db-4af3-9fe5-7ec404190e16-3416347234](https://github.com/babalae/better-genshin-impact/assets/111768965/0f31bf9d-60af-4301-80c7-0239a06621ae)

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.31.0
