### ISSUE TITLE
bitblt圖像捕獲間歇性罷工

### ISSUE THREAD

**Issue by blackwelt4270** [babalae/better-genshin-impact#179]
目前還未找到原因
已測試的捕獲條件：480P to 4K，窗口化與全屏，默認30fps to 240fps，進程語言簡繁英
/*
Edition	Windows 11 Pro for Workstations
Version	23H2
OS build	22631.2861
Experience	Windows Feature Experience Pack 1000.22681.1000.0
*/
該bug似乎是隨機觸發
![Screenshot 2023-12-21 034143](https://github.com/babalae/better-genshin-impact/assets/140785556/63a970bb-7673-47e6-801b-64bc681d63b4)

**Comment by huiyadanli** [comment]
可以参考：https://github.com/babalae/better-genshin-impact/issues/92

或者使用其他截图方式

**Comment by huiyadanli** [comment]
长时间无回复，关闭此issue
