### ISSUE TITLE
大佬不要删圣遗物强化呀😭😭

### ISSUE THREAD

**Issue by Yotor1** [babalae/better-genshin-impact#184]
新版虽然自带了一键强化，但是批量融五星的时候还是会有警告弹框要手点，大佬可以把原有的强化功能改成自动点掉警告框嘛😭😭

**Comment by emako** [comment]
你5星不合成？

**Comment by Yotor1** [comment]
> 你5星不合成？

你四星狗粮够用？

**Comment by huiyadanli** [comment]
啊，还有警告框？感觉已经意义不大了，现在一次点击都能拉这么多级了。

5星本来就有选的步骤，程序没法去执行这个操作。一但出错就是一键毁号

**Comment by Aniverse** [comment]
1-4 星狗粮不够用就去捡狗粮，嫌捡狗粮麻烦就去找个自动捡狗粮的脚本，五星还是拿去合成吧

**Comment by Yotor1** [comment]
> 1-4 星狗粮不够用就去捡狗粮，嫌捡狗粮麻烦就去找个自动捡狗粮的脚本，五星还是拿去合成吧

打个游戏还跟上班一样累不累啊

**Comment by Aniverse** [comment]
> > 1-4 星狗粮不够用就去捡狗粮，嫌捡狗粮麻烦就去找个自动捡狗粮的脚本，五星还是拿去合成吧
> 
> 打个游戏还跟上班一样累不累啊

原神本就如此，做每日、刷本又何尝不是上班？捡狗粮还有自动化手段。我是觉得五星拿去当狗粮喂有些亏，所以提个建议，怎么做是你的事了

**Comment by huiyadanli** [comment]
原有强化功能测试还能用，已经还原，下版本上线。

5星强化提示框本人保留上述意见。

**Comment by Yotor1** [comment]
> 原有强化功能测试还能用，已经还原，下版本上线。
> 
> 5星强化提示框本人保留上述意见。

谢谢大佬  爱你🥰🥰
