### ISSUE TITLE
启动时程序异常

### ISSUE THREAD

**Issue by 42057048** [babalae/better-genshin-impact#185]
![1703585990575](https://github.com/babalae/better-genshin-impact/assets/154884368/20ed18fb-b430-4091-9e0b-854a9f947b7c)

**Comment by huiyadanli** [comment]
是否影响程序正常使用？


可以参考”[提示“PaddleOcr预热失败”应该如何解决？](https://bgi.huiyadan.com/faq.html#%E2%9D%93%E6%8F%90%E7%A4%BA-paddleocr%E9%A2%84%E7%83%AD%E5%A4%B1%E8%B4%A5-%E5%BA%94%E8%AF%A5%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3)“ 的方法尝试解决

**Comment by 42057048** [comment]
出现这个之后无法使用任何功能

**Comment by 42057048** [comment]
点击启动后就会弹出这
![image](https://github.com/babalae/better-genshin-impact/assets/154884368/ae1b6b2a-2dd0-4a91-bcea-2ff26e8e662f)

**Comment by huiyadanli** [comment]
问题是否已经解决？

**Comment by 42057048** [comment]
未解决

**Comment by huiyadanli** [comment]
”[提示“PaddleOcr预热失败”应该如何解决？](https://bgi.huiyadan.com/faq.html#%E2%9D%93%E6%8F%90%E7%A4%BA-paddleocr%E9%A2%84%E7%83%AD%E5%A4%B1%E8%B4%A5-%E5%BA%94%E8%AF%A5%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3)“ 的方法都试过了吗？

**Comment by 42057048** [comment]
试过了还是不行

**Comment by huiyadanli** [comment]
寄，无法解决

**Comment by 42057048** [comment]
我哭死
