### ISSUE TITLE
能否支持自动选择“开始吧”，“准备好了”之类的选项？

### ISSUE THREAD

**Issue by willowsheng** [babalae/better-genshin-impact#186]
每次参加活动或者是剧情自动脚本都会默认点最下面的选项，还要手动关了，重新选“开始吧”，体验不是很好。

**Comment by huiyadanli** [comment]
以后也许可以添加一个可自定义的白名单，选项包含白名单内容时，自动选择

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.24.0  已优化
