### ISSUE TITLE
希望重新加入uid遮罩

### ISSUE THREAD

**Issue by wgll000** [babalae/better-genshin-impact#19]
最新版本去除了uid遮罩，希望重新加入uid遮罩

**Comment by Lightczx** [comment]
@huiyadanli 加个开关吧

**Comment by wgll000** [comment]
每日委托与每日奖励与自动跳过剧情分离
自动跳过剧情会导致一些npc意外退出，如钓鱼人

**Comment by Lightczx** [comment]
> 每日委托与每日奖励与自动跳过剧情分离 自动跳过剧情会导致一些npc意外退出，如钓鱼人

优先点击黄色文本即可

**Comment by huiyadanli** [comment]
@wgll000  @Lightczx  设置菜单内有选项可以开启UID遮罩

**Comment by huiyadanli** [comment]
> 每日委托与每日奖励与自动跳过剧情分离 自动跳过剧情会导致一些npc意外退出，如钓鱼人

# 16 

可能会有一定的性能损失，但是会考虑对更多对话 icon 进行识别。

过多的情况下可能会考虑使用分类算法提升性能（或者使用反向模板匹配方式）

**Comment by wgll000** [comment]
现在是默认必须要管理员权限打开了吗？刚刚试了下用普通用户打开未弹出窗口，但能在任务管理器内查看到进程

**Comment by huiyadanli** [comment]
> 现在是默认必须要管理员权限打开了吗？刚刚试了下用普通用户打开未弹出窗口，但能在任务管理器内查看到进程

必须要管理员权限，普通用户会弹出提升权限提示。现在没弹出权限应该是有BUG。

**Comment by wgll000** [comment]
开启自动识别后有较明显的卡顿感，且在尘歌壶种菜时疯狂误触

**Comment by huiyadanli** [comment]
> 开启自动拾取后有较明显的卡顿感，且在尘歌壶种菜时疯狂误触

1. 实时任务对电脑性能有一定要求
2. 尘歌壶种菜的情况暂未处理，因为当前拾取本来是最大化求快，对多个 F 目标的处理还有一定问题

**Comment by huiyadanli** [comment]
> > 现在是默认必须要管理员权限打开了吗？刚刚试了下用普通用户打开未弹出窗口，但能在任务管理器内查看到进程
> 
> 必须要管理员权限，普通用户会弹出提升权限提示。现在没弹出权限应该是有BUG。

0.13.1 已经修复

**Comment by huiyadanli** [comment]
遗留问题已补充到其他相关 issues

有新的独立问题，建议开多个 issues

此 issue 关闭
