### ISSUE TITLE
我觉得可以加个统计信息，就是累计采集率多少次东西

### ISSUE THREAD

**Issue by 810517583** [babalae/better-genshin-impact#194]
我觉得可以加个统计信息，就是累计采集率多少次东西，
本次采集了多少物品，
本日采集了多少物品，
本月采集了多少物品，
总的采集了多少物品，

**Comment by emako** [comment]
感觉有点难，OCR本来就不精准

**Comment by huiyadanli** [comment]
可以记录，但是不准。。。

等以后看能不能对接空荧酒馆吧

**Comment by 810517583** [comment]
左下角不是有输出日志吗，在日志里面提取就好了吧？

> 感觉有点难，OCR本来就不精准

**Comment by huiyadanli** [comment]
> [810517583](/810517583)

你仔细看看那个日志，文字识别有错的，个数也是对应不上的

**Comment by 810517583** [comment]
那这样，希望可以在右下角可以添加一个凭照可以遮蔽ID，这样在网吧玩开辅助的时候会安全一点

**Comment by huiyadanli** [comment]
这个功能已经有了，设置选项卡里有
