### ISSUE TITLE
关于砍树

### ISSUE THREAD

**Issue by nyano** [babalae/better-genshin-impact#195]
刷树是不是有上限？
4.2的时候我就测试了，后面刷好像不给木头了
今天来测了一下，好像是2000个/天？
单个树类型，换其他树似乎又可以了

9小时2000多次？ 每次15个，约每小时250次（具体次数没算）
2000个=134次  约半小时。
那么意思就是 得半小时换一个树

就我一个人有这问题还是？

**Comment by huiyadanli** [comment]
是的，一天最多2000个。

但是一个种类最多2000个我也是第一次知道。。。

**Comment by nyano** [comment]
oh 天呐 浪费了一天啊哈哈哈哈 不过也就1天变5天而已
