### ISSUE TITLE
修改拾取黑名单后报错

### ISSUE THREAD

**Issue by ddkj541** [babalae/better-genshin-impact#196]
![QQ截图20240104011929](https://github.com/babalae/better-genshin-impact/assets/109357245/a735a661-520b-474c-a321-16a4d798ca66)

**Comment by ddkj541** [comment]
把添加的删掉之后又能正常启动了，是格式有问题吗
![QQ截图20240104012029](https://github.com/babalae/better-genshin-impact/assets/109357245/c714cacc-ac64-4777-b0e3-65026b0a3479)

**Comment by huiyadanli** [comment]
行尾没加逗号
