### ISSUE TITLE
关于编程的问题

### ISSUE THREAD

**Issue by hsh778205** [babalae/better-genshin-impact#197]
感谢作者写出了这么有用又美观的工具！

我是c#小白，想知道这种美观的UI窗口（还是圆角的，很符合win11的感觉）（配色也很好看！）是用什么方法写出来的？

具体需要我知道哪些知识点？

c#与AI方面的功能结合是否方便？图像处理方面，cnn和人脸识别之类的。

我也想动手学习如何做出这样的软件。谢谢！

**Comment by huiyadanli** [comment]
窗体UI直接用的库：https://github.com/lepoco/wpfui

AI方面选择合适的平台即可，我是把所有模型转换成了onnx格式，通过 ONNX Runtime 驱动： https://onnxruntime.ai/

**Comment by hsh778205** [comment]
我去了解一下，谢谢！
