### ISSUE TITLE
关于自动战斗/刷本的建议

### ISSUE THREAD

**Issue by Normal-pcer** [babalae/better-genshin-impact#200]
1. 可以设置E,Q等技能的后摇
2. 添加检测大招充能的方案，大招和E技能CD的方案，并可以脚本中选择跳过技能或等待CD
   例如：添加`qOrSkip`, `eOrSkip`, `eOrWait`方法
3. 添加连续普攻方法
4. 添加开书(开地图)吃球方法
5. 可以通过手动指定的方式带主角

**Comment by huiyadanli** [comment]
1. e 技能后摇请通过 `wait` 控制。 q技能后摇会自动判断。e、q连续的情况下，q会在e后摇结束的时候释放（有超时判断时间）
2. 检测cd的方案并不靠谱，目前只能明确检测Q是否就绪以及Q是否释放成功（未实装）。在错过的情况下会自动跳过执行。这些方法的添加是无意义的，现在就能够实现对应的效果。
3. `attack(时间)` 就是连续普攻
4. 意义不大，可以添加
5. 下版本添加，只能通过“强制指定配队”功能使用。

综上：4、5会进入排期修改

**Comment by huiyadanli** [comment]
4. 使用0.22新增的脚本语法解决，按下 F1 吃球后 ESC 退出： `keypress(F1),wait(1),keypress(ESCAPE)`
5. 0.22 已经支持通过“强制指定配队”功能带上主角
