### ISSUE TITLE
希望可以增加尘歌壶商店的物品搜索并自动定位功能

### ISSUE THREAD

**Issue by qq617753694** [babalae/better-genshin-impact#201]
您好，我是一个尘歌壶玩家
尘歌壶商店的物品非常多，而且没有搜索功能，每次想要在商店买自己想要的东西，都需要翻好几遍，眼睛都看花了
所以我希望BetterGI团队可以增加一个功能

**在软件里输入我想要的物品名称，在游戏中打开尘歌壶商店，运行功能，软件就会自动开始翻找
一旦识别到与我输入的对应文字，就会停止**

这个功能会大大提高尘歌壶玩家的游戏体验，希望BetterGI团队的大佬们能够给予通过！
我只是个小白，能想到的办法只有这样，如果大佬们可以针对这个问题给出更好的解决办法，我觉得是很好的！

**Comment by emako** [comment]
genshin data 应该有标记壶子的 release date，道具栏大概就是按照这个排序的，还能查出漏了哪个奇馈宝箱

**Comment by qq617753694** [comment]
> genshin data 应该有标记壶子的 release date，道具栏大概就是按照这个排序的，还能查出漏了哪个奇馈宝箱

我可以理解成，或许不需要文字识别，通过 release date的排序，直接定位物品位置吗
如果可以这样的话，那确实是比我说的方法效率很多！

**Comment by huiyadanli** [comment]
> genshin data 应该有标记壶子的 release date，道具栏大概就是按照这个排序的，还能查出漏了哪个奇馈宝箱

这种方法直接定位下拉条位置，速度可快太多了

**Comment by huiyadanli** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/15783049/1fd9ca8a-a161-4d96-92ab-452384af2583)

MHY 已经优化
