### ISSUE TITLE
[suggestion] 请问能添加胡桃的aaz宏嘛

### ISSUE THREAD

**Issue by Sherry12318** [babalae/better-genshin-impact#204]
- Your suggestions / 你的建议
比如长按胡桃就持续aaz

**Comment by huiyadanli** [comment]
可以用新增的脚本语法实现（宏）
https://bgi.huiyadan.com/feats/domain.html#%E6%88%98%E6%96%97%E7%AD%96%E7%95%A5%E8%84%9A%E6%9C%AC-%E9%AB%98%E7%BA%A7%E8%AF%AD%E6%B3%95

**Comment by huiyadanli** [comment]
已支持 https://github.com/babalae/better-genshin-impact/releases/tag/0.27.0
