### ISSUE TITLE
[question] 为什么用的四神挂机，却要识别流浪者

### ISSUE THREAD

**Issue by a99304** [babalae/better-genshin-impact#206]
- Problem Description / 问题描述
- 请尽量提供问题相关的截图/日志等内容
![4D38TUM2TZV KD2JL1$MH5S](https://github.com/babalae/better-genshin-impact/assets/47300698/49c5b197-f084-477c-ad82-586ba42b7de3)

![E(~}(RVZ305FSZOTGF$~N(N](https://github.com/babalae/better-genshin-impact/assets/47300698/98927a1d-d580-4888-a8ee-9067dd4ae1c3)
我看目录里的文件也没有流浪者啊

**Comment by huiyadanli** [comment]
日志稍微有点歧义，后续会隐藏这段日志。

文档中写了解决方案：https://bgi.huiyadan.com/feats/domain.html#%E8%87%AA%E5%8A%A8%E6%88%98%E6%96%97

![image](https://github.com/babalae/better-genshin-impact/assets/15783049/faad01d9-1cb4-474c-b1f5-26888913bdc3)

**Comment by a99304** [comment]
> 日志稍微有点歧义，后续会隐藏这段日志。
> 
> 文档中写了解决方案：https://bgi.huiyadan.com/feats/domain.html#%E8%87%AA%E5%8A%A8%E6%88%98%E6%96%97
> 
> ![image](https://private-user-images.githubusercontent.com/15783049/295777399-faad01d9-1cb4-474c-b1f5-26888913bdc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NDI3MzYsIm5iZiI6MTcwNDk0MjQzNiwicGF0aCI6Ii8xNTc4MzA0OS8yOTU3NzczOTktZmFhZDAxZDktMWNiNC00NzRjLWIxZjUtMjY4ODg5MTNiZGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDAzMDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNmRjYjFmMDY4NTMwYTFlYzI4Y2FjNWYzOGM0ZDVlNzE2MDg4M2FiYjNjOTRjMzc2YjY5MTRiMTIyMTRmZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GdT2LrpFzMMjCyfqZqbxjFs9mrUfcP_Gfnf1LwggJMs)

使用了，然后就只能让钟离放个e和大招 切不了人 顺序是对的

**Comment by huiyadanli** [comment]
游戏分辨率是1080p？战斗策略选择正确了吗？

**Comment by a99304** [comment]
> 游戏分辨率是1080p？战斗策略选择正确了吗？

1080p 1920*1080 战斗策略就是文件自带的那个

**Comment by huiyadanli** [comment]
配置截图、人物不行动后的截图发出来

**Comment by a99304** [comment]
> 配置截图、人物不行动后的截图发出来

重启好了
