### ISSUE TITLE
[bug] 自动伐木功能，出现截图失败，有概率程序会卡住

### ISSUE THREAD

**Issue by NOWorEVER** [babalae/better-genshin-impact#207]
使用自动伐木功能
- 系统环境 / System Environment：
Windows10 22H2 19045.3803

- BetterGI版本号 / BetterGI Version：
0.21.1

- 问题描述 / Description of the issue：
自动伐木功能，出现截图失败，有概率程序会卡住

- 复现步骤 / Reproduction steps：
无法确认，开启自动伐木，待机，有概率出现
![image](https://github.com/babalae/better-genshin-impact/assets/57054154/49fc5dd9-969d-451a-ae58-a4456da5ad25)

**Comment by NOWorEVER** [comment]
就算弹出该错误，也有概率系统可以正常完成所有操作，就是循环砍树，但是错误报告会显示在后台

**Comment by huiyadanli** [comment]
相同问题 #162

暂时没啥好的解决方式，到时候看看能不能接入其他录屏库吧

**Comment by huiyadanli** [comment]
0.22 版本新增了重试次数，延长了重试时间。可以再试试
