### ISSUE TITLE
[bug] 自动伐木无法识别到伐木按钮

### ISSUE THREAD

**Issue by TlyJ** [babalae/better-genshin-impact#208]
- 系统环境 / System Environment：win 10 2019 ltsc

- BetterGI版本号 / BetterGI Version：0.21.1

- 问题描述 / Description of the issue：已经开启王树瑞佑，但是自动伐木识别不到

- 复现步骤 / Reproduction steps：
- 
![123微信图片_20240111183129](https://github.com/babalae/better-genshin-impact/assets/16345413/e6da2378-9a4a-4958-afe8-bbdb30478886)

**Comment by huiyadanli** [comment]
旋转视角后重试？

**Comment by TlyJ** [comment]
> 旋转视角后重试？

旋转视角，切换角色都试过了都没效果，不知道是不是跟我在vmware虚拟机里面运行有关？

**Comment by huiyadanli** [comment]
请先尝试其他自动拾取、自动剧情功能。

然后按照常见问题排查
https://bgi.huiyadan.com/faq.html

大概率调整截图方式就能解决问题

**Comment by TlyJ** [comment]
> 请先尝试其他自动拾取、自动剧情功能。
> 
> 然后按照常见问题排查 https://bgi.huiyadan.com/faq.html
> 
> 大概率调整截图方式就能解决问题

自动拾取、自动剧情都试过了，切换过三种截图方式也不行。。。

**Comment by huiyadanli** [comment]
自动拾取、自动剧情是正常的吗？

**Comment by TlyJ** [comment]
、

> 自动拾取、自动剧情是正常的吗？

也不行

**Comment by huiyadanli** [comment]
可以确认是无法截图的问题了。

尝试关闭杀毒软件，使用BitBlt截图方式重试。

这不是BetterGI的问题，请自行排查。
