### ISSUE TITLE
[suggestion] 希望宏功能可以对不同角色执行不同的操作序列

### ISSUE THREAD

**Issue by himno** [babalae/better-genshin-impact#209]
看到说有计划实现宏功能，希望可以有这样的效果：
同一个快捷键，当不同角色在场的时候可以执行不同的操作。

目前我是用AHK实现这个功能，方法不是很优雅，如果BGI能支持就好了。

**Comment by huiyadanli** [comment]
#203 战斗 第五项 优化

**Comment by himno** [comment]
> #203 战斗 第五项 优化

原来已经有规划了啊！期待功能上线！

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.27.0
