### ISSUE TITLE
增加对b服账号的支持 

### ISSUE THREAD

**Issue by wangdy21** [babalae/better-genshin-impact#210]
账号是b服的，游戏是b站下载，但是用BetterGI启动默认官服账号，请问能否支持b服账号登陆

**Comment by huiyadanli** [comment]
你这是电脑中装了两个原神吧，修改启动目录到B服原神即可。BetterGI当前是无法控制启动的账号是什么的。

![image](https://github.com/babalae/better-genshin-impact/assets/15783049/61eba523-54cb-4ecb-9d68-dbdcd799ebb1)

**Comment by wangdy21** [comment]
好的谢谢












王得懿
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月13日(周六) 晚上7:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [babalae/better-genshin-impact] 增加对b服账号的支持  (Issue #210)




 
你这是电脑中装了两个原神吧，修改启动目录到B服原神即可。BetterGI当前是无法控制启动的账号是什么的。
 
image.png (view on web)
