### ISSUE TITLE
[suggestion] 识别账号未登录

### ISSUE THREAD

**Issue by NOWorEVER** [babalae/better-genshin-impact#211]
- Your suggestions / 你的建议

自动伐木的时候有概率出现账号被踢出情况，就是变成未登录状态
能否在识别到这个图标的时候退出伐木状态，这个也是属于截图失败等异常情况之一
![image](https://github.com/babalae/better-genshin-impact/assets/57054154/a2cf8bae-976d-4ef1-954e-d0a9c7ff9627)

**Comment by huiyadanli** [comment]
1. 账号被踢出，不属于普遍且常见现象
2. 这种情况1分钟左右后会自动退出伐木状态

综上，这个建议不会被采纳

**Comment by emako** [comment]
以前有人反馈过，被踢是网络问题
