### ISSUE TITLE
[suggestion] 独立任务：大地图自动标点

### ISSUE THREAD

**Issue by imaegoo** [babalae/better-genshin-impact#214]
- Your suggestions / 你的建议

探索/收集时，总是需要 Alt + Tab 在网页版大地图和游戏界面间来回切换，如果能提前将 **神瞳/特产/怪物/矿/宝箱/仙灵/挑战** 等直接标记在游戏内，体验就会提高很多。

比如我喜欢在新地图中先将所有神瞳全都标记到游戏内地图上，找到一个删除一个。

所以我希望工具能支持：基于已有资源地图（例如观测枢的大地图、空荧酒馆的大地图等）的数据，通过模拟点击，自动在游戏内的大地图上标记各种资源的能力。

**Comment by huiyadanli** [comment]
这个功能以前有人实现过，B站上可以搜到视频。

我更加倾向于这种方式实现类似的效果 #102

**Comment by imaegoo** [comment]
感谢回复！_我自认为_ 通过遮罩实现起来比直接在游戏内模拟点击标点要难许多，因为

1. 地图移动时，遮罩层也需要随之移动，需要实时识别
2. 地图包含地上地图和地下地图，增加识别难度

另外，遮罩只能在电脑上显示，模拟点击标点则会记录到游戏账号中。之后即使关闭BetterGI、或是手机登录，也能看到标点。

所以我倾向于在游戏内模拟点击标点，我之前使用过具有该功能的工具，但他们都已经停止更新了。

**Comment by huiyadanli** [comment]
考虑后短期内不会实现这个功能。

倒是对自动标自定义图案标点比较感兴趣。
