### ISSUE TITLE
七胜召唤添加默认角色配置，方便七胜召唤脚本的编写

### ISSUE THREAD

**Issue by huiyadanli** [babalae/better-genshin-impact#217]
数据源参考：
https://github.com/MadeBaruna/paimon-moe/blob/main/src/data/tcg/zh.json
https://github.com/dvaJi/genshin-data/tree/master/src/data/chinese-simplified/tcg_characters

处理后的json数据，感谢 @haokaiyang 提供
[tcg_character_zh_nodesc.json](https://github.com/babalae/better-genshin-impact/files/13940723/tcg_character_zh_nodesc.json)

二次处理：
```
id -> nameEn
_id -> id
{REALNAME[ID(1)|DELAYHANDLE(true)]} -> 流浪者
```

二次处理后：
[tcg.json](https://github.com/babalae/better-genshin-impact/files/13941019/tcg.json)

相关代码：
[Skill.cs](https://github.com/babalae/better-genshin-impact/blob/main/BetterGenshinImpact/GameTask/AutoGeniusInvokation/Model/Skill.cs)
[ScriptParser.cs](https://github.com/babalae/better-genshin-impact/blob/main/BetterGenshinImpact/GameTask/AutoGeniusInvokation/ScriptParser.cs)

注意点：
被动技能( `skillTag = 被动技能` ) 要排除

未完待续...

**Comment by haokaiyang** [comment]
[tcg4.3.json](https://github.com/babalae/better-genshin-impact/files/13983816/tcg4.3.json)
按二次处理后的格式上传

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/blob/main/BetterGenshinImpact/GameTask/AutoGeniusInvokation/Assets/tcg_character_card.json

已经完成
