### ISSUE TITLE
[bug] 自动秘境领取奖励时使用浓缩树脂领取失败

### ISSUE THREAD

**Issue by zhaoziang1626** [babalae/better-genshin-impact#218]
- 系统环境 / System Environment：
win10

- BetterGI版本号 / BetterGI Version：
0.22

- 问题描述 / Description of the issue：
自动秘境领取奖励时使用浓缩树脂领取失败，鼠标移到浓缩树脂那里没有点击成功直接移到右上角了

- 复现步骤 / Reproduction steps：
自动秘境打完一遍跑到树旁边之后

**Comment by huiyadanli** [comment]
自动战斗结束时，战斗任务被取消，部分行动按键按下后没有松开。

使用龙王的时候这个问题比较常见

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.23.0 已修复
