### ISSUE TITLE
用安装包安装不会覆盖原文件[question] 

### ISSUE THREAD

**Issue by wwpruilin** [babalae/better-genshin-impact#221]
用安装包安装更新时是在旧程序文件夹内有新建了一个文件夹

Uploading 2024-01-16 21-44-18_20240116_21534250.mp4…

**Comment by huiyadanli** [comment]
![OGAH Y}6PKR678BX $_WK%I](https://github.com/babalae/better-genshin-impact/assets/15783049/7af63749-cb57-499d-9dde-b2d68caa6389)


因为安装包本来就会释放两层BetterGI
