### ISSUE TITLE
[suggestion] 自动过剧情添加关闭文档

### ISSUE THREAD

**Issue by NOWorEVER** [babalae/better-genshin-impact#223]
- Your suggestions / 你的建议
在做任务的过程中有出现这种文档界面，是否可以根据这两个特征图形进行关闭文档？
![image](https://github.com/babalae/better-genshin-impact/assets/57054154/96b11ceb-7158-45e2-b519-3dda8a329781)

**Comment by huiyadanli** [comment]
这个功能已经有，在自动剧情播放按钮存在2s内出现关闭按钮会自动点击

**Comment by NOWorEVER** [comment]
是吗？早上自动化的时候没反应，然后自己手点了

**Comment by huiyadanli** [comment]
要么2s时间太短了，要么是前面播放中识别消失的太早了。

**Comment by huiyadanli** [comment]
时间 2s -> 3s 我个人使用暂时没遇到这个问题

**Comment by NOWorEVER** [comment]
早上又做了一个看文档的任务，还是没有点击关闭

**Comment by NOWorEVER** [comment]
噢噢， 你逻辑是在自动剧情播放按钮存在2s内，但是有时候他是直接读文档的。能不能加一个左边这个图标的识别方法？

**Comment by huiyadanli** [comment]
会影响正常游玩，这个 x 在很多地方都存在。。。

**Comment by NOWorEVER** [comment]
前提判断是左边那个【文档】图标出现呢

**Comment by huiyadanli** [comment]
你就没想过有人是要开着自动剧情主动阅读这个文档的？以前这个2s延时是不存在的，问题非常多
