### ISSUE TITLE
[bug]自动秘境bug 

### ISSUE THREAD

**Issue by kn1TionluDz** [babalae/better-genshin-impact#224]
- Your suggestions / 你的建议

用龙王队打枫丹秘境的时候总是在使用树脂的时候出问题，还没点到使用树脂就开始点跳过的位置了，另一个号使用宵宫队基本没问题，同一个设备同一个软件，想不出是啥问题
![`K){Q5F(6~DRSF9Q9FWVP 1](https://github.com/babalae/better-genshin-impact/assets/153828373/6fcb5d19-0b75-4c06-a432-1973896add0b)

**Comment by huiyadanli** [comment]
自动战斗结束的时候有些按键按下后没有松开导致的这个问题。

也就是龙王按下左键后没松开，然后后续点击按下就没反应了。

下版本会修复：
1. 战斗中断的时候keydown后必须保证keyup触发
2. 使用树脂的时候双击

**Comment by zkmbdbbdd** [comment]
自动秘境bug：
一进去经常跑过头了没按到F开始战斗
打完了识别不到古树，镜头一直在左右晃动，枫丹的新本，剧团套猎人套

**Comment by huiyadanli** [comment]
> 自动秘境bug： 一进去经常跑过头了没按到F开始战斗 打完了识别不到古树，镜头一直在左右晃动，枫丹的新本，剧团套猎人套

@zkmbdbbdd  先看文档，这个本镜头乱晃肯定用的不是1080p

**Comment by zkmbdbbdd** [comment]
> > 自动秘境bug： 一进去经常跑过头了没按到F开始战斗 打完了识别不到古树，镜头一直在左右晃动，枫丹的新本，剧团套猎人套
> 
> @zkmbdbbdd 先看文档，这个本镜头乱晃肯定用的不是1080p

我看了呀，游戏分辨率是改成了1080p，难道系统的分辨率也得改吗

**Comment by huiyadanli** [comment]
@zkmbdbbdd 开新issue 发截图、视频

**Comment by zkmbdbbdd** [comment]
@huiyadanli
我改了系统分辨率，可以了，是我自己的问题

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.23.0  已经修复龙王队伍，树脂使用的问题
