### ISSUE TITLE
[question] 在蒙德璃月的凯瑟琳不会自动点每日委托奖励

### ISSUE THREAD

**Issue by wwpruilin** [babalae/better-genshin-impact#225]
在蒙德璃月的凯瑟琳不会自动点每日委托奖励
![2}P 4OFH KSJG$5CCX_LULT](https://github.com/babalae/better-genshin-impact/assets/116276194/7868c799-9461-4196-85f5-6814a8df4b2a)

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.23.0

已修复
