### ISSUE TITLE
[bug]  无法识别到石化古树,地图定位线乱跳

### ISSUE THREAD

**Issue by Yin-yao** [babalae/better-genshin-impact#226]
- 系统环境 / System Environment：

- BetterGI版本号 / BetterGI Version：

- 问题描述 / Description of the issue：

- 复现步骤 / Reproduction steps：

**Comment by Yin-yao** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/52100321/c14b28f0-6552-4663-b965-79ca5f26358f)

**Comment by Yin-yao** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/52100321/c0092da0-8fc8-4484-a664-ed0585aace5b)
![image](https://github.com/babalae/better-genshin-impact/assets/52100321/5e56d8e2-c02e-4be6-9eac-01f0943b9b01)
![image](https://github.com/babalae/better-genshin-impact/assets/52100321/83433269-f32d-4331-8f53-6e9b776f05fa)
![image](https://github.com/babalae/better-genshin-impact/assets/52100321/191dd7c9-44bc-4e77-924e-2bab445f7ef2)
![image](https://github.com/babalae/better-genshin-impact/assets/52100321/d619ac88-8a67-476f-9597-9b74e83b8636)

**Comment by huiyadanli** [comment]
分辨率不对，请使用1920x1080

**Comment by Yin-yao** [comment]
> 分辨率，请使用1920x1080

okok
