### ISSUE TITLE
七圣召唤增加分辨率+游戏当前语言判断，更加友好的提示

### ISSUE THREAD

**Issue by ZM-J** [babalae/better-genshin-impact#23]
如题 无角色识别结果

**Comment by ZM-J** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/21689514/28702875-1bcd-479e-a822-0841336fbac0)

取消了影幻牌面也不太行，不知道为啥

**Comment by emako** [comment]
最好增加分辨率+游戏当前语言判断，不符合则提示 @huiyadanli

**Comment by huiyadanli** [comment]
确实得加上，七圣召唤测试下来非1080p的情况下基本是处于完全不能用的状态。
