### ISSUE TITLE
自动领取『每日委托』奖励加上关闭领取界面

### ISSUE THREAD

**Issue by wwpruilin** [babalae/better-genshin-impact#230]
- Your suggestions / 你的建议

![image](https://github.com/babalae/better-genshin-impact/assets/116276194/c5873a0d-41ad-4ffc-b8bf-5aec1fe5639b)

**Comment by wwpruilin** [comment]
就是自动关闭这个界面

**Comment by huiyadanli** [comment]
[0.21.0](https://github.com/babalae/better-genshin-impact/releases/tag/0.21.0) 版本尝试加了，但是有问题hhh，这回修好了，下版本上线

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.23.0 已添加
