### ISSUE TITLE
[suggestion] 适配手机端ui

### ISSUE THREAD

**Issue by 1608757256** [babalae/better-genshin-impact#231]
- Your suggestions / 你的建议
可以适配手机端ui吗，这对串流玩原神会很方便
【手机串流玩原神，PC端使用触屏UI】 https://www.bilibili.com/video/BV15u4y1M7Ko/?share_source=copy_web&vd_source=b2bbb2236a00930cb74f4a722c9495ee

**Comment by huiyadanli** [comment]
不考虑
