### ISSUE TITLE
[suggestion] 自动剧情  做任务时某些NPC，唤起对话时应该选择任务而不是默认最后一个选项

### ISSUE THREAD

**Issue by xming521** [babalae/better-genshin-impact#232]
- Your suggestions / 你的建议
自动剧情  做任务时某些NPC，唤起对话时应该选择任务而不是默认最后一个选项，最后一个选项会导致直接退出。
可以加个感叹号检测？或者默认选第一个？

![image](https://github.com/babalae/better-genshin-impact/assets/32786500/0b370469-bde4-4461-b6cb-4e70922f2e31)

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.24.0  已优化
