### ISSUE TITLE
[suggestion] 关于自动剧情的一点小想法

### ISSUE THREAD

**Issue by Goalsh** [babalae/better-genshin-impact#233]
一般而言，需要跳过的剧情往往都有很明显的特征，它们的每一个选项的图标都是完全一样的，并且选项文字的颜色均为白色。通过识别图标和文字颜色，几乎可以解决所有npc交互选项误跳过的问题，不知道该方案可不可行。

<img width="1280" alt="屏幕截图 2024-01-21 014552" src="https://github.com/babalae/better-genshin-impact/assets/69134445/34b05435-903a-47fe-8b5d-aac96932e82f">

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.24.0  已优化
