### ISSUE TITLE
[bug] 璃月地区凯瑟琳不能领取每日任务奖励，

### ISSUE THREAD

**Issue by ones-w** [babalae/better-genshin-impact#234]
- 系统环境 / System Environment：

- BetterGI版本号 / BetterGI Version：
0.20.0

- 问题描述 / Description of the issue：
到璃月凯瑟琳触发对话以后，直接领取了每日派遣，然后每日奖励，不会自动领取了，看左上角的红框会跳来跳去，怀疑可能是这方面的影响?

- 复现步骤 / Reproduction steps：

**Comment by ones-w** [comment]
补充一下，之前在枫丹凯瑟琳倒是正常。今天做完活动在璃月领奖励，出现的这问题

**Comment by huiyadanli** [comment]
请关注 #225，重复问题，下版本修复
