### ISSUE TITLE
自动伐木在木材已满的情况下，按下ESC会消除木材已满的提示

### ISSUE THREAD

**Issue by huiyadanli** [babalae/better-genshin-impact#235]
@qq617753694 发现的问题：自动砍树，一个点位采集多种木材，如果其中一个木材达到上限，就会停住不动了

导致原因是 ESC 消除了木材已满的提示，导致退出菜单无法唤出。

![0DE6)AU}@`TFR)$GD%1}`2J](https://github.com/babalae/better-genshin-impact/assets/15783049/0584de96-4daf-4e27-b683-c3be203f0947)

多种木材继续采集解决方法：

1. 换木材点位
2. 添加小道具使用后的延迟

![85)$QRN8OOC0OC1}BP_KXZD](https://github.com/babalae/better-genshin-impact/assets/15783049/9c2ad313-49a1-4d36-ab51-1d1683d283fb)

**Comment by emako** [comment]
这个之前遇到过，方案是按两次ESC即可

**Comment by emako** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/24737061/51b923f3-3a95-4097-b68a-7d86a5eb3ec1)
https://github.com/GenshinMatrix/genshin-woodmen

**Comment by huiyadanli** [comment]
解决方案：
1. 不处理，把延时拉长，提示会自动消失（但是伐木就慢了）
2. 加一个选项默认按两下ESC（简单）
3. OCR到相关文字，则多按一下ESC（对电脑性能有要求）

**Comment by emako** [comment]
先实现方案3？

**Comment by huiyadanli** [comment]
我选择和你一样先加方案2

**Comment by huiyadanli** [comment]
发现我识别了菜单的弹出。。没识别到弹出菜单直接再按一次ESC就行。。

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.30.0
