### ISSUE TITLE
PaddleOcr预热失败

### ISSUE THREAD

**Issue by 13055751** [babalae/better-genshin-impact#236]
- 系统环境 / System Environment：Windows10

- BetterGI版本号 / BetterGI Version：0.20.0

- 问题描述 / Description of the issue：预热失败
![Uploading QQ截图20240122125855.png…]()

- 复现步骤 / Reproduction steps：不知道

**Comment by 13055751** [comment]
![Uploading QQ截图20240122125855.png…]()

**Comment by 13055751** [comment]
![QQ截图20240122125855](https://github.com/babalae/better-genshin-impact/assets/122584322/3212c662-97a0-450f-b7f5-91fa5412900c)

**Comment by huiyadanli** [comment]
https://bgi.huiyadan.com/faq.html#%E2%9D%93%E6%8F%90%E7%A4%BA-paddleocr%E9%A2%84%E7%83%AD%E5%A4%B1%E8%B4%A5-%E5%BA%94%E8%AF%A5%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3

**Comment by 13055751** [comment]
> 文档解决方案一个个试试：https://bgi.huiyadan.com/faq.html#%E2%9D%93%E6%8F%90%E7%A4%BA-paddleocr%E9%A2%84%E7%83%AD%E5%A4%B1%E8%B4%A5-%E5%BA%94%E8%AF%A5%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3

都试过了

**Comment by 13055751** [comment]
这个问题应该跟电脑配置没关系吧

**Comment by huiyadanli** [comment]
无关，一般是系统环境问题。

**Comment by 13055751** [comment]
> 无关，一般是系统环境问题。

系统是刚重装的专业版

**Comment by huiyadanli** [comment]
这个你只能自行寻找解决方案了

**Comment by huiyadanli** [comment]
参考 #283 的解决方案
