### ISSUE TITLE
自动关闭月卡领取界面

### ISSUE THREAD

**Issue by ruilin01** [babalae/better-genshin-impact#237]
- Your suggestions / 你的建议

![image](https://github.com/babalae/better-genshin-impact/assets/116276194/06314271-5670-44be-86a9-70d45778c218)

**Comment by huiyadanli** [comment]
看上去可以和 #220 连在一块，两个都作为可选项

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.25.0 已添加
