### ISSUE TITLE
自动邀约任务

### ISSUE THREAD

**Issue by zxygzxy** [babalae/better-genshin-impact#24]
能不能出个自动邀约任务的按钮啊，邀约和普通任务的按钮不一样，没法点，能否出个点邀约框的功能，如果能判别有没有✔就更好了

**Comment by huiyadanli** [comment]
在下个邀约开启后，会进入开发。

**Comment by zxygzxy** [comment]
好的好的

**Comment by huiyadanli** [comment]
done
https://github.com/babalae/better-genshin-impact/releases/tag/0.26.0
