### ISSUE TITLE
[bug] 七圣召唤信息栏阻挡敌我方回合判断

### ISSUE THREAD

**Issue by gongfuture** [babalae/better-genshin-impact#242]
- 系统环境 / System Environment：
版本	Windows 10 专业版
版本号	22H2
安装日期	‎2023/‎1/‎13 ‎周五
操作系统内部版本	19045.3996
体验	Windows Feature Experience Pack 1000.19053.1000.0

- BetterGI版本号 / BetterGI Version：
0.23.0

- 问题描述 / Description of the issue：
七圣召唤相关，不确定是否仅此一个阵容有此问题，迪希雅开大有两个阶段，第二阶段后如被敌方超载击杀会显示卡牌信息，不知道是自动化点击的还是自动显示的，此信息过长会阻挡敌我回合截图。确认关闭了设置中的敌方卡牌显示
<img width="960" alt="Snipaste_2024-01-26_13-36-50" src="https://github.com/babalae/better-genshin-impact/assets/60888755/ece62fe2-dacf-44f9-9444-927f3ae18ae7">

- 复现步骤 / Reproduction steps：
使用5号牌组 迪希雅白术皇女 ，持续至迪希雅开完两次大后，此套牌组这个问题在我这里的三个每周挑战稳定复现

**Comment by gongfuture** [comment]
换了一个配队出现了类似情况

<img width="960" alt="Snipaste_2024-01-26_14-11-12" src="https://github.com/babalae/better-genshin-impact/assets/60888755/cd65d41c-88ec-4cd7-9c09-9e28716f1e39">

**Comment by gongfuture** [comment]
这是最上面的log，刚发的这次不知道为啥没有log文件
[better-genshin-impact20240126.log](https://github.com/babalae/better-genshin-impact/files/14060965/better-genshin-impact20240126.log)

**Comment by huiyadanli** [comment]
这两种的原因明显不一样，不能归为一类而谈。 

而且你这两种场景已经在文档中明确表示不支持了。

![image](https://github.com/babalae/better-genshin-impact/assets/15783049/960230ef-934f-4c4c-97e5-655f7714af1f)


https://bgi.huiyadan.com/doc.html#%E8%87%AA%E5%8A%A8%E4%B8%83%E5%9C%A3%E5%8F%AC%E5%94%A4

请使用8号推荐卡组，减少此类问题的发生

**Comment by gongfuture** [comment]
啊原来是超载击杀时的判定问题，我以为是识别对方己方回合图标的问题才提的issue，8号卡组我用过，但是因为缺少回血机制，有时候打不过，所以不常用
