### ISSUE TITLE
[suggestion] 希望快捷键可设置组合键和仅原神窗口聚焦时响应

### ISSUE THREAD

**Issue by gongfuture** [babalae/better-genshin-impact#243]
- Your suggestions / 你的建议
目前的快捷键响应好像是全局的？我在原神外操作的时候容易触发bettergi功能，导致应用运行错误
组合键的话，在 #115 也有提及

**Comment by huiyadanli** [comment]
近期会有所改造，添加新的热键实现方式，windows自带的全局热键确实不好用

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.24.0  已优化
