### ISSUE TITLE
黑白名单等列表json，通用的编辑界面

### ISSUE THREAD

**Issue by huiyadanli** [babalae/better-genshin-impact#245]
针对类似这种json的通用修改UI展示
```json
[
    "天原银莲",
    "烈焰花花蕊",
    "螃蟹",
    "鳗肉",
    "冰雾花花朵",
    "异界余影",
    "海贼的日志",
    "传送"
]
```

界面参考，当前只需要单列即可

![image](https://github.com/babalae/better-genshin-impact/assets/15783049/1a53c363-318d-4f0f-ba10-94ab1070940a)

**Comment by Mr-Quin** [comment]
个人认为横着排列更好
![image](https://github.com/babalae/better-genshin-impact/assets/8700123/e6d1f27c-d65b-41ec-8f68-9601d979c667)

**Comment by huiyadanli** [comment]
我的需求只要一半就行hhh，黑名单和白名单单独弹出即可。实际还会用在其他类似的编辑功能上，所以比较看重通用性。

（还没看代码，晚上我看看。我VS的xaml预览好像寄了...

![image](https://github.com/babalae/better-genshin-impact/assets/15783049/d6dfc617-a404-44ea-9a3a-0aee4278fe66)

**Comment by Mr-Quin** [comment]
ok
这个功能挺好的，感觉策略编辑什么都可以用，不过那就不是json了

**Comment by Lightczx** [comment]
不要直接用文本框
我们设计的是使用列表
加上转移按钮/或者拖放操作实现编辑

**Comment by emako** [comment]
> 我的需求只要一半就行hhh，黑名单和白名单单独弹出即可。实际还会用在其他类似的编辑功能上，所以比较看重通用性。
> 
> （还没看代码，晚上我看看。我VS的xaml预览好像寄了...
> 
> ![image](https://private-user-images.githubusercontent.com/15783049/311954223-d6dfc617-a404-44ea-9a3a-0aee4278fe66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNDczNTcsIm5iZiI6MTcxMDI0NzA1NywicGF0aCI6Ii8xNTc4MzA0OS8zMTE5NTQyMjMtZDZkZmM2MTctYTQwNC00NGVhLTlhM2EtMGFlZTQyNzhmZTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDEyMzczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2MWM0ZjA3ODU4ZGZlODBmMWE0YWRhNjlmMjBjMWM1YTg0YjYxNGMwNjAzOGZmYmM3NjkzODE2MjE4NmRiOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rXnu9Otz_KuKVlXy1SJwxp_oN6owCyDWQc7CzRZFXKg)

昨天就想说了，这算个抛转引玉，等你优化UX

**Comment by emako** [comment]
> ok 这个功能挺好的，感觉策略编辑什么都可以用，不过那就不是json了

可以自定义高亮语法

**Comment by Lightczx** [comment]
> 大于4000个数据用列表反而更难使用

做搜索框就行了

**Comment by huiyadanli** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/15783049/01c74539-33ea-4d7e-8404-cc5710c975d2)

改成通用框了。

然后还发现一个问题。保存提示出现后，再关闭编辑窗口，主窗口会最小化；直接关闭，主窗口不会最小化。

我起初猜测和`MessageBox`有关，不过换了个WPF-UI的提示框以后问题照旧。

**Comment by Mr-Quin** [comment]
以后有加入脚本的计划的话，要不直接嵌入一个再强大一点的编辑器，monaco这样的提供intellisense

**Comment by huiyadanli** [comment]
> 以后有加入脚本的计划的话，要不直接嵌入一个再强大一点的编辑器，monaco这样的提供intellisense

我更加倾向于外置hhh，让其他编辑器支持或者我直接提供一个类似RPA功能的网页给用户用。

**Comment by emako** [comment]
跟messagebox有关，dialog关掉会自动置顶上个聚焦窗口，上一个窗口就是messagebox但被你关了找不到，应该是说这个问题？

**Comment by huiyadanli** [comment]
> 跟messagebox有关，dialog关掉会自动置顶上个聚焦窗口，上一个窗口就是messagebox但被你关了找不到，应该是说这个问题？

点 x 可有自动置顶上个聚焦窗口的操作吗

**Comment by huiyadanli** [comment]
先发版了

https://github.com/babalae/better-genshin-impact/releases/tag/0.26.0
