### ISSUE TITLE
[bug] 地下锚点无法自动点击快速传送

### ISSUE THREAD

**Issue by gongfuture** [babalae/better-genshin-impact#247]
- 系统环境 / System Environment：
版本	Windows 10 专业版
版本号	22H2
安装日期	‎2023/‎1/‎13 ‎周五
操作系统内部版本	19045.3996
体验	Windows Feature Experience Pack 1000.19053.1000.0

- BetterGI版本号 / BetterGI Version：
0.23.0

- 问题描述 / Description of the issue：
地下锚点无法自动点击，地下锚点和普通锚点同时出现时，即使地下锚点在上也依旧选择普通锚点

- 复现步骤 / Reproduction steps：
打开快速传送后选择任意地下锚点

**Comment by AirHolic** [comment]
新圣遗物本也一样，地上传送锚点优先级很高，不放大地图不会传

**Comment by huiyadanli** [comment]
已经改造成优先选排序第一的传送点，下版本上线

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.24.0  已优化
