### ISSUE TITLE
速速适配枫丹鱼类识别

### ISSUE THREAD

**Issue by Sagili365** [babalae/better-genshin-impact#25]
请求速速适配枫丹全自动钓鱼，自动选鱼饵等，等不急辣

**Comment by huiyadanli** [comment]
如果有人能够贡献训练集，或者协助训练。可以很快适配

**Comment by huiyadanli** [comment]
训练集分类参考

| 分类名                                    | 中文         |
|----------------------------------------|------------|
| aizen medaka                           | 蓝染花鳉       |
| crystalfish                            | 水晶宴        |
| dawncatcher                            | 擒霞客        |
| glaze medaka                           | 琉璃花鳉       |
| medaka                                 | 花鳉         |
| sweet-flower medaka                    | 甜甜花鳉       |
| akai maou                              | 赤魔王        |
| betta                                  | 斗棘鱼        |
| lunged stickleback                     | 肺棘鱼        |
| snowstrider                            | 雪中君        |
| venomspine fish                        | 鸩棘鱼        |
| abiding angelfish                      | 长生仙        |
| brown shirakodai                       | 流纹褐蝶鱼      |
| purple shirakodai                      | 流纹京紫蝶鱼     |
| raimei angelfish                       | 雷鸣仙        |
| tea-colored shirakodai                 | 流纹茶蝶鱼      |
| bitter pufferfish                      | 苦炮鲀        |
| divda ray                              | 迪芙妲鳐       |
| formalo ray                            | 佛玛洛鳐       |
| golden koi                             | 金赤假龙       |
| pufferfish                             | 苦炮鲀2       |
| rusty koi                              | 锖假龙        |
| halcyon jade axe marlin                | 翡玉斧枪鱼      |
| lazurite axe marlin                    | 青金斧枪鱼      |
| peach of the deep waves                | 沉波蜜桃       |
| sandstorm angler                       | 吹沙角鲀       |
| streaming axe marlin                   | 海涛斧枪鱼      |
| sunset cloud angler                    | 暮云角鲀       |
| true fruit angler                      | 真果角鲀       |
| blazing heartfeather bass              | 烘烘心羽鲈      |
| rippling heartfeather bass             | 波波心羽鲈      |
| maintenance mek: initial configuration | 维护机关·初始能力型 |
| maintenance mek: platinum collection   | 维护机关·白金典藏型 |
| maintenance mek: situation controller  | 维护机关·态势控制者 |
| maintenance mek: water body cleaner    | 维护机关·水域清理者 |

**Comment by qhrmwx** [comment]
+1，水神不能没有水管，就像耶路撒冷不能没有敌法

**Comment by Mikachu2333** [comment]
我有时间，但受限于电脑无法训练，只能帮助打标。

所以我能做啥？有教程吗

**Comment by huiyadanli** [comment]
@Mikachu2333 好好好，你是第一位主动找我的，新建了个训练相关的群，加群 863012276，注明 Github 账号

**Comment by huiyadanli** [comment]
0.25 版本开始支持枫丹鱼类
