### ISSUE TITLE
[suggestion] webhook 数据上报

### ISSUE THREAD

**Issue by Mr-Quin** [babalae/better-genshin-impact#251]
- Your suggestions / 你的建议

希望加入某种数据上报的功能。我的想法是添加一个“webhook”的设置选项，在一些情况下向webhook发送消息，再由接收端对这些消息进行处理。这样子感觉比较灵活，也不需要太多代码就能实现，接收端可以是另一个项目

使用场景
- 数据统计
自动拾取，自动伐木，自动剧情时可以在每次动作后向webhook发送消息，由接受端负责数据统计
- 状态通知
在一些耗时比较长的任务完成后或者出现问题时进行通知，比如七圣召唤。需由接收端对接通知服务，微信，Discord之类的
- lifecycle events
在程序出现问题或者什么情况时进行通知，一定程度上等同于远程日志

**Comment by emako** [comment]
希望加个：游戏时长统计

**Comment by huiyadanli** [comment]
@emako 任务时常统计？还是类似starward一样的整体游戏时常统计？统计发送到通知模板上？

感觉得单开个issue.

**Comment by huiyadanli** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/15783049/50b86aae-e926-41f9-9081-7af47e361db1)
（大致的示例）


准备添加一些个人用的通知渠道，并尝试配置化界面（通过配置直接生成对应的界面Card以及需要输入的配置参数）

**Comment by Because66666** [comment]
针对0.39.1正式版的bettergi，写了一个简易的前端[开源地址](https://github.com/Because66666/better_gi_miniweb)。
效果如图：

![Image](https://github.com/user-attachments/assets/716642b1-157f-4fc6-a2ac-cd5cb078c674)
不过是本地运行。可以配置端口转发到公网，得到一个简易的网页端访问查看。设想是在手机上保存一个网页快捷方式以查看。
