### ISSUE TITLE
[bug] 太山府内的石化古树无法识别

### ISSUE THREAD

**Issue by Xiaoqianghepipi** [babalae/better-genshin-impact#252]
太山府内的石化古树无法识别
太山府内的石化古树无法识别

- 系统环境 / System Environment：
- win10 21H2 19044.3930 LTSC
win10 21H2 19044.3930 LTSC

- BetterGI版本号 / BetterGI Version：
- 0.23.0
0.23.0

- 问题描述 / Description of the issue：
- 太山府内的石化古树无法识别
太山府内的石化古树无法识别

- 复现步骤 / Reproduction steps：
- 进入太山府开启自动秘境
进入太山府开启自动秘境

**Comment by huiyadanli** [comment]
测试可以识别，请描述具体场景。最好能够录个视频。

**Comment by Xiaoqianghepipi** [comment]
![dsawdsa](https://github.com/babalae/better-genshin-impact/assets/68947244/47b5745c-9d25-4338-a857-04c02d7c6db5)
就是这棵树，在打开自动秘境的时候就一直卡在那里，不再继续行动

**Comment by huiyadanli** [comment]
打开自动秘境是不会识别古树的，我无法理解你描述的内容。

请先阅读使用说明：https://bgi.huiyadan.com/feats/domain.html

并确认自动拾取之类的功能是否正常使用

**Comment by Xiaoqianghepipi** [comment]
现在又可以了，应该是队伍配置的问题，重新配置了下队伍就可以用了，不好意思
