### ISSUE TITLE
未赋予管理员启动的情况下，提示并自动关闭程序

### ISSUE THREAD

**Issue by huiyadanli** [babalae/better-genshin-impact#255]
RT

**Comment by emako** [comment]
用户都不给你赋予了，还有什么好提示的呢

**Comment by huiyadanli** [comment]
BetterGI没有管理员权限无法进行任何模拟操作，所以提示“因为原神是以管理员权限启动的，BetterGI不以管理员权限启动的话没有权限模拟键鼠操作，请以管理员权限启动BetterGI”后直接退出。

有些用户抱有侥幸心理要使用非管理员权限启动，然后后发现功能不可用后提问说“xxx功能不可使用”。

**Comment by huiyadanli** [comment]
仅加入提示，主窗口依旧展示，防止和 .NET 运行库缺失但无错误提示的情况混淆

**Comment by Mikachu2333** [comment]
很想塞进去个N_Sudo自动提权……

介绍：
https://github.com/M2TeamArchived/NSudo/blob/master/Manual/%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C.md

**Comment by huiyadanli** [comment]
> 很希望实现自动提权……
> 
> 可能与此相关的：Nsudo [M2TeamArchived/NSudo@`master`/Manual/%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C.md](https://github.com/M2TeamArchived/NSudo/blob/master/Manual/%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C.md?rgh-link-date=2024-02-23T17%3A29%3A16Z)

已经有自动提权了，这个报错是用户在UAC界面未赋予管理员权限的提示。
