### ISSUE TITLE
[bug] 有时候在椅子旁边，会误识别成宝箱，一直自动点击坐下，起身了也立马点击坐下，导致卡在那个位置，跑不掉(乐了，这个椅子会吃人)

### ISSUE THREAD

**Issue by ones-w** [babalae/better-genshin-impact#257]
- 系统环境 / System Environment：

- BetterGI版本号 / BetterGI Version：
0.23.0

- 问题描述 / Description of the issue：
有时候在椅子旁边，会误识别成宝箱，一直自动点击坐下，起身了也立马点击坐下，导致卡在那个位置，跑不掉(乐了，这个椅子会吃人)

- 复现步骤 / Reproduction steps：

**Comment by huiyadanli** [comment]
左下角日志提供下，把错误识别的内容，加入黑名单即可

**Comment by ones-w** [comment]
<img width="1000" alt="微信截图_20240209222014" src="https://github.com/babalae/better-genshin-impact/assets/58326208/2a267bfc-ed0e-482c-af25-8c7a757e9b5e">
具体地点在地图红框标识的传送点进去的空间里。
看日志也没有其他的提示，有些奇怪

**Comment by ones-w** [comment]
补充一下，似乎加入黑名单也没用。GI重启过的。
<img width="280" alt="微信截图_20240209222617" src="https://github.com/babalae/better-genshin-impact/assets/58326208/15c0e60e-f306-486d-92af-417af7b99036">

**Comment by huiyadanli** [comment]
看上去是一直识别成”普通的宝箱“了
