### ISSUE TITLE
[bug] 自动剧情有时候失效

### ISSUE THREAD

**Issue by ones-w** [babalae/better-genshin-impact#258]
- 系统环境 / System Environment：

- BetterGI版本号 / BetterGI Version：
0.23.0

- 问题描述 / Description of the issue：
<img width="1274" alt="微信截图_20240209220613" src="https://github.com/babalae/better-genshin-impact/assets/58326208/7dbd0f7c-b598-476b-9992-13deb98ec99f">
如图，有时候开启自动剧情功能，不生效，要自己手动点击。而且开启自动拾取时，会出现“交互或拾取的info信息”

- 复现步骤 / Reproduction steps：

**Comment by huiyadanli** [comment]
https://bgi.huiyadan.com/doc.html#%E8%87%AA%E5%8A%A8%E5%89%A7%E6%83%85

![image](https://github.com/babalae/better-genshin-impact/assets/15783049/d6066c09-eb91-4ccd-9e00-4f758b6a48b1)
