### ISSUE TITLE
[question] Windows系统更新之后，自动剧情没有效果了

### ISSUE THREAD

**Issue by joker1307** [babalae/better-genshin-impact#259]
- Problem Description / 问题描述
- 请尽量提供问题相关的截图/日志等内容
![image](https://github.com/babalae/better-genshin-impact/assets/41231639/3dba6229-a27c-4f02-8a19-2a2fcafbb0cc)

**Comment by huiyadanli** [comment]
换截图方式

https://bgi.huiyadan.com/faq.html

**Comment by joker1307** [comment]
已解决
