### ISSUE TITLE
[bug] 0.24快捷键的两个小问题

### ISSUE THREAD

**Issue by TheTychoStar** [babalae/better-genshin-impact#260]
- 系统环境 / System Environment：WIN11

- BetterGI版本号 / BetterGI Version：0.24

- 问题描述 / Description of the issue：

1. 监听模式下，按下快捷键时，游戏内对应的原有功能也会被触发。例如每次按F1会在开启/关闭自动拾取的同时打开冒险手册界面，全局模式下则无此问题。虽然不影响BetterGI本身的功能使用，但每次按完要多一次手动关闭界面的操作。监听模式下不能使用组合键，而全局模式又会屏蔽掉原神本身的快捷键，难以兼顾。目前看来只有在全局模式下使用组合键才能兼顾BetterGI和原神本身的快捷键（我自己是自动拾取设置成Ctrl+F1，这样游戏里F1还是可以打开冒险手册）。
2. 将快捷键从监听修改成全局模式时，会导致该快捷键按一次产生两次效果。例如将自动拾取的快捷键从监听模式F1修改为全局模式F1，此时在游戏内按下F1，会显示两行提示文字：一行自动拾取开启+一行自动拾取关闭。此时无论启动或停止BetterGI的全局开关(F11)都不能修复该问题。当退出BetterGI进程并重新运行时，快捷键才能正常工作（只执行一次指令）。

- 复现步骤 / Reproduction steps：

**Comment by huiyadanli** [comment]
感谢反馈
1. 监听模式下，无法覆盖游戏本身的监听。这种情况说正常的，这不是bug。F开头的功能键可以用全局热键。
2. 这是bug，已经修复。暂时不发版

**Comment by TheTychoStar** [comment]
嗯明白了感谢大佬。这样的话是否可以考虑把默认的F快捷键还是改为全局模式？或者默认监听模式但是F开头的都改成Ctrl/Alt+FN的组合键。这样或许对于初次使用BetterGI的用户可能体验会更好一些。
