### ISSUE TITLE
[bug] 自动剧情

### ISSUE THREAD

**Issue by PythonOneTWOTHree0515** [babalae/better-genshin-impact#261]
- 系统环境 / System Environment：
win10

- BetterGI版本号 / BetterGI Version：

0.24.1
- 问题描述 / Description of the issue：

剧情出现选择时，偶尔会出现鼠标持续在不存在选项的位置移动并点击
- 复现步骤 / Reproduction steps：

进入原神草神主线，花神会，时间循环部分的剧情中出现（选定了选项 固定为第一个）

**Comment by PythonOneTWOTHree0515** [comment]
出现该bug时，貌似是先在第一个选项上进行过点击，但并未成功，失败后，移动点击的位置就不对了

**Comment by huiyadanli** [comment]
有无截图或者录屏，可能是其他区域有文字被识别到去点击了

**Comment by PythonOneTWOTHree0515** [comment]
> 有无截图或者录屏，可能是其他区域有文字被识别到去点击了

录像如下，点击区域没有文字出现，，，而且这个视频录完后，过了一段时间，它又自己跳回了选项点击，继续进行了剧情，之前我都是手动关闭自动剧情，选完后再开启继续的。
https://github.com/babalae/better-genshin-impact/assets/50647806/e3c93f96-7bf7-4b0d-b29d-e8bf4a47fc6a

**Comment by huiyadanli** [comment]
看上去是快捷键误触发的问题，建议使用`0.24.1`版本，删掉所有快捷键配置后重试

**Comment by huiyadanli** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/15783049/ea1eb9a4-8980-426d-a0d9-fea8fba618dc)

复现出来了，是BUG，OCR可能返回空结果

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.25.0 已修复
