### ISSUE TITLE
[bug] 使用Windowsgc截图模式时  上版本无问题 .24版本鼠标视角晃动不跟手

### ISSUE THREAD

**Issue by ShinyHeinrich** [babalae/better-genshin-impact#262]
- 系统环境 / System Environment：Win11

- BetterGI版本号 / BetterGI Version：0.24.1

- 问题描述 / Description of the issue：视角晃动不跟手 
正常情况堪比转圈圈的晃动 出现问题时连半屏都没转过去 而且还有延迟

- 复现步骤 / Reproduction steps：Windowsgc截图模式 .23正常 .24出现    已回退.23一次 使用正常  后再更新 再复现

**Comment by huiyadanli** [comment]
24 版本针对wgc优化增加性能的消耗会增加。。你这种情况就是bgi消耗的性能太多了，造成游戏掉帧了

**Comment by ShinyHeinrich** [comment]
> 24 版本针对wgc优化增加性能的消耗会增加。。你这种情况就是bgi消耗的性能太多了，造成游戏掉帧了

14600k 4070ti 内存7000 上版本完全正常120帧跑满  这次完全不能用视角都转不动  恐怕不只是性能消耗的多吧    要不我完全删了重装试试?

**Comment by huiyadanli** [comment]
120帧的原因，你要不回到23老版本

**Comment by ShinyHeinrich** [comment]
> 120帧的原因，你可以任务管理器看下bgi的占用
> 
> 你不要回到23老版本。后面我会退回这个字符串，把这个可选项

好的 谢谢 我已经回到23了

**Comment by ShinyHeinrich** [comment]
> 120帧的原因，你可以任务管理器看下bgi的占用
> 
> 你不要回到23老版本。后面我会退回这个字符串，把这个可选项

对了 我记得我下午的时候看过占用  原神是最多的20% 剩下的也不算特别高  总占用也就是40左右

**Comment by ShinyHeinrich** [comment]
> 120帧的原因，你可以任务管理器看下bgi的占用
> 
> 你要不回到23老版本。后面我会回退这个改动，把这个作为可选项

你好 我今天又试了下新版本  我把键鼠监听那边的选项改了一下 就只是纯粹的掉帧了 没有不跟手或者延迟  可能是这个周边的问题吗?

**Comment by huiyadanli** [comment]
> > 120帧的原因，你可以任务管理器看下bgi的占用
> > 你要不回到23老版本。后面我会回退这个改动，把这个作为可选项
> 
> 你好 我今天又试了下新版本 我把键鼠监听那边的选项改了一下 就只是纯粹的掉帧了 没有不跟手或者延迟 可能是这个周边的问题吗?

0.24.1 版本解决了快捷键迁移的问题。。。也有可能是快捷键误触了

**Comment by huiyadanli** [comment]
0.25版本，关闭这个选项即可：

![image](https://github.com/babalae/better-genshin-impact/assets/15783049/6b0703a0-3e6f-4151-943b-0754568acc9b)
