### ISSUE TITLE
[suggestion] 添加【自动解锁烹饪熟练程度】功能

### ISSUE THREAD

**Issue by GazzyLifeSense** [babalae/better-genshin-impact#266]
- Your suggestions / 你的建议

**Comment by qhbdw8** [comment]
+1 这个挺需要的  因为有几个需要做菜解锁的成就

**Comment by Fightxing** [comment]
一个可能的实现思路：
设置为独立任务，启动任务后第一次记录用户烹饪菜肴的点击位置和时间间隔，随后持续运行直到手动停止

**Comment by huiyadanli** [comment]
几行代码就能实现的功能，一直不想做是因为自身没需求，近期频繁有人提就加上了。已完成未发布。

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.30.0

已经新增

**Comment by Gimhoy** [comment]
太棒了
