### ISSUE TITLE
[suggestion] 七圣召唤充能数后台记录

### ISSUE THREAD

**Issue by HaloStudent233** [babalae/better-genshin-impact#267]
- Your suggestions / 你的建议
因为在使用部分组合时（包括推荐组合)，充能数很容易识别错误(甚至会识别出10这种奇怪的充能)，导致战斗中充能未满但是识别充能满了而出现卡死的问题。
因此，在后台记录角色目前的充能数还是有必要的，可以避免识别错误带来的卡死

**Comment by huiyadanli** [comment]
充能识别暂时是仅识别，无逻辑的。不影响七圣召唤整体进程。

**Comment by HaloStudent233** [comment]
> 充能识别暂时是仅识别，无逻辑的。不影响七圣召唤整体进程。

但是充能满了就会放大招，如果实际没有满就会卡在"充能不足"

**Comment by huiyadanli** [comment]
> > 充能识别暂时是仅识别，无逻辑的。不影响七圣召唤整体进程。
> 
> 但是充能满了就会放大招，如果实际没有满就会卡在"充能不足"

放大招是写死在整个七圣召唤策略里面的，实际角色死亡也会去放大招，这样就卡死了。文档中有说明这些不支持的情景

**Comment by HaloStudent233** [comment]
> > > 充能识别暂时是仅识别，无逻辑的。不影响七圣召唤整体进程。
> > 
> > 
> > 但是充能满了就会放大招，如果实际没有满就会卡在"充能不足"
> 
> 放大招是写死在整个七圣召唤策略里面的，实际角色死亡也会去放大招，这样就卡死了。文档中有说明这些不支持的情景

相当于程序只是复现操作流程，没有任何出击策略?
之前有一次不知道为什么卡在充能不足了（思考

**Comment by huiyadanli** [comment]
是的，也就是说某一步卡住可能是前面步骤有存在失败
