### ISSUE TITLE
[question] PaddleOcr预热异常

### ISSUE THREAD

**Issue by kiaa77483** [babalae/better-genshin-impact#269]
用了幾個版本都是一樣的問題
[better-genshin-impact20240217.log](https://github.com/babalae/better-genshin-impact/files/14317860/better-genshin-impact20240217.log)

**Comment by huiyadanli** [comment]
看上去是属于暂时无解的场景，不知道缺失了什么依赖库。

尝试以下四种解决方案：
https://bgi.huiyadan.com/faq.html#%E2%9D%93%E6%8F%90%E7%A4%BA-paddleocr%E9%A2%84%E7%83%AD%E5%A4%B1%E8%B4%A5-%E5%BA%94%E8%AF%A5%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3

**Comment by kiaa77483** [comment]
好的 我再試試看 謝謝
