### ISSUE TITLE
自动剧情总是会选择退出剧情的选项

### ISSUE THREAD

**Issue by qhrmwx** [babalae/better-genshin-impact#27]
能不能改下逻辑去选择最下方选项之外的选项

**Comment by huiyadanli** [comment]
不可以，选其他的选项会产生更多问题，比如死循环等。

未来可能会细分更多类型的选项进行选择。https://github.com/babalae/better-genshin-impact/issues/16

特殊情况请用快捷关闭自动剧情手动操作。
