### ISSUE TITLE
[bug] 七圣召唤在某些时候会卡在等待，不再攻击

### ISSUE THREAD

**Issue by Xiaoqianghepipi** [babalae/better-genshin-impact#272]
- 系统环境 / System Environment：
Windows10 版本 21 H2 （操作统内部版本 19044 ． 4046 ）

- BetterGI版本号 / BetterGI Version：

0.24.1
- 问题描述 / Description of the issue：
七圣召唤在某些时候会卡在等待，不再攻击

- 复现步骤 / Reproduction steps：
打开七圣召唤，开始打牌
![无标题](https://github.com/babalae/better-genshin-impact/assets/68947244/09b4b215-8243-4a1b-aa77-f39b190bb8c3)

**Comment by huiyadanli** [comment]
这个截图看不出来啥，最好有录屏。

有些场景本身不支持。或者前置步骤执行出错会导致后续操作卡住。

**Comment by Xiaoqianghepipi** [comment]
这是视频（用的N卡录制，无法显示log）
https://upfile.live/zh-cn/files/23f90a6c

**Comment by huiyadanli** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/15783049/7264cb92-3bcd-4148-8e95-5360c7e435cd)

https://bgi.huiyadan.com/doc.html#%E8%87%AA%E5%8A%A8%E4%B8%83%E5%9C%A3%E5%8F%AC%E5%94%A4

请先阅读使用文档。

这种情况下尝试更换其他卡组
