### ISSUE TITLE
[bug] 开启自动剧情后，通过alt+f4退出云原神时鼠标乱点

### ISSUE THREAD

**Issue by Decem6er** [babalae/better-genshin-impact#276]
- 系统环境 / System Environment：
版本	Windows 11 专业版
版本	23H2
安装日期	‎2022/‎7/‎17
操作系统版本	22631.3227
体验	Windows Feature Experience Pack 1000.22687.1000.0

- BetterGI版本号 / BetterGI Version：
0.24.1

- 问题描述 / Description of the issue：
 在云原神全屏幕情况下，开启自动剧情后，通过alt+f4退出云原神时，鼠标乱点几秒钟，然后恢复正常。但最严重时会完全无法操作，一直交替点击左上角和右下角，无法点击云原神的对话框退出云原神，也无法打开BetterGI退出

- 复现步骤 / Reproduction steps：
1. 按如图方式配置BetterGI：
![image](https://github.com/babalae/better-genshin-impact/assets/16839570/fa74b33d-f581-4d52-b148-9d5b9072a31f)
![image](https://github.com/babalae/better-genshin-impact/assets/16839570/bbc2014e-1bc2-4511-ba56-d4b0528dc299)

2. 启动云原神
3. 进入剧情，切换到自动，此时运行正常
4. 剧情正常走完
5. 按下 Alt + F4
6. 出现问题

注：也许不一定和自动剧情有关

**Comment by huiyadanli** [comment]
看下快捷键配置是否配置了F4。。。

**Comment by Decem6er** [comment]
成了，原来如此，谢谢

> 看下快捷键配置是否配置了F4。。。

**Comment by huiyadanli** [comment]
功能键建议切换回全局热键的模式
