### ISSUE TITLE
[suggestion] 能给一个那维莱特转圈圈的速度调整吗？

### ISSUE THREAD

**Issue by wuyicong111** [babalae/better-genshin-impact#279]
- Your suggestions / 你的建议
我的鼠标dpi比较低，转圈的时候速度不够，又不想频繁调整dpi，能加一个转速调节吗？

**Comment by Adogs1** [comment]
还未发布？

**Comment by huiyadanli** [comment]
刚发 https://github.com/babalae/better-genshin-impact/releases/tag/0.25.0

**Comment by Adogs1** [comment]
> 刚发 https://github.com/babalae/better-genshin-impact/releases/tag/0.25.0

更一下蓝奏云吧，GitHub太慢了
