### ISSUE TITLE
单例模式和系统托盘

### ISSUE THREAD

**Issue by yzqdev** [babalae/better-genshin-impact#28]
各位大佬好呀,这里是两个建议,单例模式和系统托盘
1. 多次打开BetterGI.exe会出现多个BetterGI的窗口,其实可以在第二次打开BetterGi.exe,让BetterGI窗口跳出来
2. 允许BetterGI在后台运行,点击关闭后可以隐藏到系统托盘,以免不小心点击了关闭按钮,BetterGI退出了

不知大佬意见如何?

**Comment by emako** [comment]
单例模式：https://github.com/babalae/better-genshin-impact/commit/ecfaba72527f26b75f7acc24918e5980313439e7
