### ISSUE TITLE
[bug] PaddleOcr预热失败

### ISSUE THREAD

**Issue by kuang3** [babalae/better-genshin-impact#283]
- 系统环境 / System Environment：
Windows 10 pro 64 位操作系统

- BetterGI版本号 / BetterGI Version：
BetterGI_v0.24.1

- 问题描述 / Description of the issue：
预热启动失败
![QQ截图20240227113115](https://github.com/babalae/better-genshin-impact/assets/51186654/18df9068-9319-4b2a-a8d8-eef911ac7005)

- 复现步骤 / Reproduction steps：
双击启动BetterGI.exe

**Comment by kuang3** [comment]
已经按照文档安装了VC_redist.x64和winsdksetup【windows sdk】重启后桌面管理员权限运行

**Comment by huiyadanli** [comment]
参考 #269

暂无这种场景下的解决办法

**Comment by emako** [comment]
楼主是什么CPU？

**Comment by emako** [comment]
错误信息指出无法加载共享库 'paddle_inference_c'，并且列出了一些依赖库的加载状态，其中 'mklml.dll' 和 'mkldnn.dll' 显示为失败（FAIL）。

**Comment by emako** [comment]
https://www.nuget.org/packages/Sdcb.PaddleInference.runtime.win64.mkl @huiyadanli

**Comment by skyofsimba** [comment]
能给个详细操作说明吗？
这个nuget不会用，没用过啊？

**Comment by huiyadanli** [comment]
https://wwk.lanzouq.com/ioU1f1tvgnwd

下载后把里面的4个dll文件放到软件根目录，并覆盖

![dbf3ae9cbd6efcfb7c5ec0a6bd2633af](https://github.com/babalae/better-genshin-impact/assets/15783049/93fdece3-19b3-4d73-95d5-f23296eb4536)
