### ISSUE TITLE
[bug] 在WGC模式下自动剧情在无剧情下自动点击黑屏等，抢输入动作，导致操作卡顿不跟手

### ISSUE THREAD

**Issue by FFFlyer** [babalae/better-genshin-impact#286]
- 系统环境 / System Environment：Win10 LTSC 21H2 3Amd平台

- BetterGI版本号 / BetterGI Version：版本>0.23.0

- 问题描述 / Description of the issue：启动BGI后，在WGC模式下（其他两个模式掉帧……），自动剧情在无剧情下自动点击黑屏等，抢输入动作，导致操作卡顿不跟手

- 复现步骤 / Reproduction steps：0.24.0 0.24.1 及最新的0.25.0都有该情况，退回0.23.0及之前都正常

截图：
![图片](https://github.com/babalae/better-genshin-impact/assets/26003418/c6101be5-8823-49c0-955a-288678758051)
![图片](https://github.com/babalae/better-genshin-impact/assets/26003418/62ad23ec-35db-428c-a154-1cb66fbdda9c)
关掉自动剧情就不会出现该情况，开启自动剧情则即使重启BGI也继续出现该情况

**Comment by huiyadanli** [comment]
在WGC模式下，0.24的一个缓存改动，可能会导致解锁帧率的情况下掉帧。


关闭这个选项即可：
![~QG K%IDBF`3C@_M$UGGN7F](https://github.com/babalae/better-genshin-impact/assets/15783049/8d9d18c5-8795-44ae-9492-dab7f5336d89)

**Comment by huiyadanli** [comment]
相关issue #262

**Comment by shenbingxiaojiang** [comment]
> 相关issue #262
可否加入开关自动点击黑屏按钮，关闭位图缓存做出一些动作有些延迟

**Comment by huiyadanli** [comment]
@shenbingxiaojiang 这是掩耳盗铃，实际就是拿到了黑屏图片
