### ISSUE TITLE
[suggestion] 增加全局热键选项

### ISSUE THREAD

**Issue by zmy1828** [babalae/better-genshin-impact#289]
- Your suggestions / 你的建议
旧版本中，快速购买、那维莱特转圈功能都可以未启动BGI的情况下使用，并且多次点击快速购买快捷键可以排队完成任务，现版本则无法进行此种操作，希望能将旧版功能增加为可设置选项。

**Comment by huiyadanli** [comment]
现在全局热键就是可选项，在快捷键页面可以针对每个功能选择是“全局热键”还是“键鼠监听”。

那维莱特转圈功能 在“全局热键”情况下，长按可能停不下来的。。。

**Comment by huiyadanli** [comment]
差点忘记这两个被我置灰了。你可以启动后关闭所有实时任务使用键盘监听快捷键

**Comment by huiyadanli** [comment]
手动修改软件根目录下的 `User\config.json` 就能够继续使用全局热键

比如：
``` json
    "turnAroundHotkey": "XButton2",
    "turnAroundHotkeyType": "KeyboardMonitor",  // 那维莱特转圈
    "enhanceArtifactHotkey": "",
    "enhanceArtifactHotkeyType": "KeyboardMonitor", // 快速强化圣遗物
    "quickBuyHotkey": "",
    "quickBuyHotkeyType": "KeyboardMonitor",   // 快速购买
```
把 `KeyboardMonitor` 修改成 `GlobalRegister` 即可。

也就是那维莱特转圈改成全局热键的结果：

```
    "turnAroundHotkeyType": "GlobalRegister",  // 那维莱特转圈 全局热键
```

![image](https://github.com/babalae/better-genshin-impact/assets/15783049/40171806-1fa4-4a1d-9829-9358718a5a83)
