### ISSUE TITLE
自动升级圣遗物，希望加一个升级完鼠标自动移到快捷放入

### ISSUE THREAD

**Issue by Kingxs840** [babalae/better-genshin-impact#30]
好用

**Comment by huiyadanli** [comment]
4.3 过后原神将会删除这个圣遗物强化结果展示，感觉现在开发意义也不大了

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/commit/6a7123ff7255f84a7059e1d98823e572e9292bc4

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.15.0
