### ISSUE TITLE
能不能加个一键吃料理，跟自动传送一样。

### ISSUE THREAD

**Issue by Veforon** [babalae/better-genshin-impact#307]
能不能加个一键吃料理，跟自动传送一样。

**Comment by Veforon** [comment]
> 能不能加个一键吃料理，跟自动传送一样。

或者是跟自动拾取一样，设一个黑白名单。自动点击料理使用。

**Comment by huiyadanli** [comment]
我的理解是按下某个键，根据配置，按下B键打开背包去找到指定料理，然后使用？

主要是用于吃buff料理？

**Comment by Celtyee** [comment]
> 我的理解是按下某个键，根据配置，按下B键打开背包去找到指定料理，然后使用？
> 
> 主要是用于吃buff料理？

佬佬你好，关于这个具体实现想法我写在了这个issue里面: [#353 ](https://github.com/babalae/better-genshin-impact/issues/353#issue-2244314788)

**Comment by huiyadanli** [comment]
以#353为准
