### ISSUE TITLE
[feature request] 图像识别实现米游社每日签到

### ISSUE THREAD

**Issue by emako** [babalae/better-genshin-impact#31]
![image](https://github.com/babalae/better-genshin-impact/assets/24737061/12bf8eaf-fe62-4dcc-9a91-9bb5e20e3ead)
Windows11 only 的自动签到实现，米游社安装方式：[https://github.com/GenshinMatrix/Fischless/tree/main/src/Plugins/Fischless.Plugin.LaunchHyperion](https://github.com/GenshinMatrix/Fischless/tree/main/src/Plugins/Fischless.Plugin.LaunchHyperion)

**Comment by huiyadanli** [comment]
不同电脑分辨率不同，图像识别有局限性，优先使用 autoxjs 方案。

http://doc.autoxjs.com/#/widgetsBasedAutomation

脚本编写完成后，直接打包apk，程序调用adb执行。

**Comment by emako** [comment]
得空了试试看

**Comment by emako** [comment]
功能价值不高，弃坑

**Comment by huiyadanli** [comment]
> 功能价值不高，弃坑

等哪天安卓功能默认实装的时候，价值就高了

**Comment by Lua12138** [comment]
唔，对于像小米服这种，无PC版本的，是否有可能通过模拟器或者scrcpy（物理设备）来实现操作呢，模拟器的优势是比较方便的控制分辨率。
