### ISSUE TITLE
[bug] 伐木大约20分钟（50轮）就原神客户端闪退

### ISSUE THREAD

**Issue by 11389698** [babalae/better-genshin-impact#311]
- 系统环境 / System Environment：Intel(R) Core(TM) i7-11800H，RTX3060，Windows 10 专业版，64位

- BetterGI版本号 / BetterGI Version：
![image](https://github.com/babalae/better-genshin-impact/assets/79733561/e32db518-6a23-44ea-9c28-db773d96841a)

- 问题描述 / Description of the issue：伐木大约20分钟（50轮）就原神客户端闪退，bgi软件没变化，上次出现该问题软件有报错，这次没报错，

- 复现步骤 / Reproduction steps：

尝试复现后，可靠性记录如下
![image](https://github.com/babalae/better-genshin-impact/assets/79733561/8dd2052b-57dd-4107-810c-d48eb34927f1)

二次复现，报错代码，可靠性记录未生成记录
![image](https://github.com/babalae/better-genshin-impact/assets/79733561/ce0dd39b-c2bb-4245-abc2-0be26d6fbba5)

第三次复现，电脑卡死后原神闪退，无报错，无可靠性记录

运行中BetterGI程序的内存一直增长，显示屏分辨率2560*1600

**Comment by huiyadanli** [comment]
感觉是内存没回收的问题，我尝试复现下

**Comment by huiyadanli** [comment]
伐木50轮未复现，我的16G内存稳定在300M~400M占用，但是我可以先改造可能存在问题的代码。

请问你的内存大小是多少，较大的内存可能回收策略会不一样

**Comment by 11389698** [comment]
> 伐木50轮未复现，我的16G内存稳定在300M~400M占用，但是我可以先改造可能存在问题的代码。
> 
> 请问你的内存大小是多少，较大的内存可能回收策略会不一样

16G，但是开原神时空闲内存大约小于5G

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.26.0

0.26.0 做了一定的内存回收优化，测试下

**Comment by 11389698** [comment]
> https://github.com/babalae/better-genshin-impact/releases/tag/0.26.0
> 
> 0.26.0 做了一定的内存回收优化，测试下

本次循环大约70分钟，其中内存增长速度比0.25.1版本有大幅减少。
运行开始大约300MB，以每秒2 MB左右增长，每轮伐木中，内存会降低20～30MB然后一下子跳跃式增加70～120MB。（一开始我以为这个就是回收策略）
到达3.3 GB的时候回落至小于0.5GB，随后一直增加至5.2 GB后回落至4.2 GB。

后面不想测了，因为伐木上限了，而且电脑内存占用超过80%后增长开始缓慢且变卡。
这次一轮12根大概不到一小时就上限了，下次试试每轮根数少点应该能运行两小时

**Comment by huiyadanli** [comment]
https://f.ws59.cn/f/dn4xlkpb3ww 

链接24h后失效，尝试下这个版本，直接粗暴的添加了手动强制内存回收。应该不会有问题了

**Comment by 11389698** [comment]
> https://f.ws59.cn/f/dn4xlkpb3ww
> 
> 链接24h后失效，尝试下这个版本，直接粗暴的添加了手动强制内存回收。应该不会有问题了

连续运行30分钟，全程内存占用不超过300MB，但是到后面越来越低，最低50MB

**Comment by huiyadanli** [comment]
。。。这么夸张，越来越低确实是有可能的，毕竟独立任务实际消耗的并不多

这个问题我看已经解决了
