### ISSUE TITLE
[bug] 自动邀约好像没做DPI识别

### ISSUE THREAD

**Issue by nyano** [babalae/better-genshin-impact#314]
- 系统环境 / System Environment：

- BetterGI版本号 / BetterGI Version：

- 问题描述 / Description of the issue：

![image](https://github.com/babalae/better-genshin-impact/assets/5079651/63f6c951-ea7d-4529-887f-6e46a0304fc6)

- 复现步骤 / Reproduction steps：
实际点击了按钮的右下方，应该是DPI问题

**Comment by huiyadanli** [comment]
测试dpi缩放无问题，出问题的是带mask模板匹配的识别率不够高。估计只能正常运行在1920x1080分辨率下

预计未来在 #95 方式下修复此问题
