### ISSUE TITLE
[suggestion] 添加录制行为的功能，并转化为脚本

### ISSUE THREAD

**Issue by Jarcis-cy** [babalae/better-genshin-impact#315]
## 概述
通过录制操作者的行为，实现重复复现操作，做到自动捡材料，捡狗粮，自动寻路钓鱼等的操作（理论上能够做到更多）

## 可能的实现方式
1. 将地图完整的记录下来，并为每个可传送点进行编号
2. 要求录制者每次行为的开始都是打开地图进行传送
3. 在传送时，根据地图匹配，记录下传送点的编号
4. 监听录制者的键盘和鼠标事件，记录下来键盘和鼠标的操作
5. 当录制结束后，将录制到的内容转换成类似战斗脚本的内容
6. 使用者可以导入脚本，进行测试，并进行微调

## 可能存在的问题
1. 因为使用角色的不同，导致移动，爬行等行为的偏差（所以建议使用相同角色进行操作）
2. 如果是打怪这种行为，可能会因为数值问题，导致出现不可避免地偏差，所以感觉自动打怪较难实现
3. 使用者在使用时误触导致视角偏差，导致离最终目的地很远（所以可能的话开始后，至少能锁一下调用Windows API锁一下鼠标？）
4. 传送后，视角的不固定的，理论上可以通过看小地图，来识别到当前的朝向，然后进行调整？

因为只写过python和golang，没写过C#，所以也不知道提的合不合理

还是感谢作者能将这么好用的工具开发出来！

**Comment by peach-water** [comment]
自动捡材料，捡狗粮的需求早有人提了 #85 。
1. 这种最大的问题是从锚点出发，随着路程增加误差会累积，导致不能完成自动化跑路线的任务。现在暂时没有能够修正误差的方法。

2. 关于录制脚本跑路线。先不说不同电脑鼠标移动速度设置不同，同一台电脑上录制的脚本能否成功运行也需要一点点运气。我尝试了按键精灵、Keymousego等脚本录制，也自己写过。感觉原神像是容易吞掉部分操作，尤其是鼠标移动事件，转向视角总是出现一点点的偏差。

**Comment by Jarcis-cy** [comment]
> 自动捡材料，捡狗粮的需求早有人提了 #85 。
> 
> 1. 这种最大的问题是从锚点出发，随着路程增加误差会累积，导致不能完成自动化跑路线的任务。现在暂时没有能够修正误差的方法。
> 2. 关于录制脚本跑路线。先不说不同电脑鼠标移动速度设置不同，同一台电脑上录制的脚本能否成功运行也需要一点点运气。我尝试了按键精灵、Keymousego等脚本录制，也自己写过。感觉原神像是容易吞掉部分操作，尤其是鼠标移动事件，转向视角总是出现一点点的偏差。

其实如果最后能输出为脚本，就能微调了，直接调试转向和移动，录制只是为了能够生成一个初始的脚本，然后要进行微调才能排除个人电脑的各种因素，理论上视角的转换可以不看鼠标的实践，而是看小地图上面的那个白色区域的转动来实现？

不知道能不能行

**Comment by Jarcis-cy** [comment]
在调试好脚本后，固定角色，仅使用脚本操控视角转移+移动的情况下，结合小地图视角校准，应该在所有的同窗口尺寸的情况下都能使用吧

**Comment by peach-water** [comment]
> > 自动捡材料，捡狗粮的需求早有人提了 #85 。
> > 
> > 1. 这种最大的问题是从锚点出发，随着路程增加误差会累积，导致不能完成自动化跑路线的任务。现在暂时没有能够修正误差的方法。
> > 2. 关于录制脚本跑路线。先不说不同电脑鼠标移动速度设置不同，同一台电脑上录制的脚本能否成功运行也需要一点点运气。我尝试了按键精灵、Keymousego等脚本录制，也自己写过。感觉原神像是容易吞掉部分操作，尤其是鼠标移动事件，转向视角总是出现一点点的偏差。
> 
> 其实如果最后能输出为脚本，就能微调了，直接调试转向和移动，录制只是为了能够生成一个初始的脚本，然后要进行微调才能排除个人电脑的各种因素，理论上视角的转换可以不看鼠标的实践，而是看小地图上面的那个白色区域的转动来实现？
> 
> 不知道能不能行

微调不太好做，小地图本身就精度不太够，对于细微的角度变化检测不出来；另外小地图上特征不明显，也不适合作为路径追踪的对象。

至于脚本什么的，都很好实现。

**Comment by Jarcis-cy** [comment]
我当时想的是因为代表人物的小箭头在小地图中的位置是固定的，且形状是固定的，还有一个浅白色的视角作为辅助判断，应该能以此作为定位，如果这个精度不够的话，可能确实没啥好办法了

要是能固定指向北方，可能都好调，所以检测小箭头没有指向北方，就先指向北方这个操作理论上也是精度不够的对吗

**Comment by Jarcis-cy** [comment]
或者如果变成传送之后，视角先原地转圈，然后通过图像匹配，匹配传送点，然后让人物正对传送点，再根据设置的信息进行转向呢，这样是不是也可行？

**Comment by peach-water** [comment]
> 或者如果变成传送之后，视角先原地转圈，然后通过图像匹配，匹配传送点，然后让人物正对传送点，再根据设置的信息进行转向呢，这样是不是也可行？

这也没解决微调不精准的问题呀。再说，传送后视角都是固定的，为什么要先面对传送锚点呢。

另外，关于图像匹配检测，例如现在自动秘境的找树的效果，已经是足够独特的目标，有时候还是容易因为一些技能视角阻挡导致识别失败（现在是结束战斗后等一段事件开始找，这样解决问题）。等到路径上的图像匹配那就不好说会怎么样（虽然也许可以通过堆数据量解决）。

脚本效果不佳的问题本质上还是不能很好的跟踪自身的位置信息，还没想到有什么具备足够特征的对象来跟踪。

**Comment by Jarcis-cy** [comment]
> > 或者如果变成传送之后，视角先原地转圈，然后通过图像匹配，匹配传送点，然后让人物正对传送点，再根据设置的信息进行转向呢，这样是不是也可行？
> 
> 这也没解决微调不精准的问题呀。再说，传送后视角都是固定的，为什么要先面对传送锚点呢。
> 
> 另外，关于图像匹配检测，例如现在自动秘境的找树的效果，已经是足够独特的目标，有时候还是容易因为一些技能视角阻挡导致识别失败（现在是结束战斗后等一段事件开始找，这样解决问题）。等到路径上的图像匹配那就不好说会怎么样（虽然也许可以通过堆数据量解决）。
> 
> 脚本效果不佳的问题本质上还是不能很好的跟踪自身的位置信息，还没想到有什么具备足够特征的对象来跟踪。

原来如此我昨天简单测试了一下传送好像它的视角是不固定的，可能当时测试的有问题吧。

那好像确实寄了😭

**Comment by huiyadanli** [comment]
我这边会做类似的功能，比录制更加简单。

后续的流程是直接 书写脚本->测试->调整->测试 循环。

会根据地图上设定的路线直接寻路。

相关的技术基本已经成熟：

1. 人物朝向的识别 （完成）
2. 相机视角的识别 （完成，但是部分地区识别率较低）
3. 小地图的识别（进行中）

2 确实在某些情况识别不准确，但是实际是可以靠按住w+人物朝向蓝标的识别来修正

**Comment by Jarcis-cy** [comment]
期待新功能，直接起飞！！

**Comment by peach-water** [comment]
这个好耶，我一直有捡狗粮的路线想整

**Comment by Jarcis-cy** [comment]
> 我这边会做类似的功能，表现形式不一定是录制。
> 
> 后续的流程是直接 书写脚本->测试->调整->测试 循环。
> 
> 会根据地图上设定的路线直接寻路。
> 
> 相关的技术基本已经成熟：
> 
> 1. 人物朝向的识别 （完成）
> 2. 相机视角的识别 （完成，但是部分地区识别率较低）
> 3. 小地图的识别（进行中）
> 
> 相机视角的识别 确实在某些情况识别不准确，但是实际是可以靠按住w+人物朝向蓝标的识别来修正

似乎是4.8更新后的新功能？现在的小地图支持跟随人物转动而转动了，这会对小地图识别有帮助吗

**Comment by huiyadanli** [comment]
这个功能从1.0开始就有，没啥帮助

**Comment by Jarcis-cy** [comment]
> 这个功能从1.0开始就有，没啥帮助

好吧，之前从来没注意过🤣

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.34

地图追踪 + 键鼠录制都已经实现
