### ISSUE TITLE
[suggestion] 可否做一个聊天的标签功能？

### ISSUE THREAD

**Issue by Xmug** [babalae/better-genshin-impact#316]
- Your suggestions / 你的建议

实现方式可以是在打开聊天时添加几个按钮，用户按下按钮自动往聊天框中加标签。
原理参考【原神 4.5／星铁新富文本 bug 原理大致分析-哔哩哔哩】 https://b23.tv/gpRibYb

**Comment by huiyadanli** [comment]
暂不考虑，等我做出来，这玩意可能已经被和谐了。

除非它一直不被和谐。而且BetterGI做这个事情可能不太合适。
