### ISSUE TITLE
大地图匹配的一些参数

### ISSUE THREAD

**Issue by huiyadanli** [babalae/better-genshin-impact#318]
本层持续更新作为记录

前提：游戏画面标准为 16 : 9

**大地图匹配参考GIA，采用缩放后模板匹配的方式。**

关键标准：
* 原始地图采用 1024x1024 区块拼接而成，大小：14336x13312（14:13）
* 以通过 <kbd>F1</kbd> 开书进入副本展现的游戏大地图作为标准缩放，1080P的标准
* 游戏画面大小同比缩放时，地图也是同比缩放的

叠图后发现两者比例是 游戏内大地图 : 原始地图 = 800 : 1024 = 25 : 32

![叠图](https://github.com/babalae/better-genshin-impact/assets/15783049/5d962cdd-9843-4948-9262-6de7c8654670)

原始地图缩放到 1400x1300 作为被匹配图，缩小 10.24 倍，所以游戏大地图截图也需要同比缩小 8 倍，也就是无论多少大小的游戏画面都缩放到 240x135

匹配验证：
![匹配验证](https://github.com/babalae/better-genshin-impact/assets/15783049/6e57dcd5-a0ef-44ab-8920-18d77267b2d4)

**Comment by huiyadanli** [comment]
测试后发现以下问题：
1. 蓝黑色边界区域较大的情况下，无法正确匹配
2. 大地图周边控件影响匹配

尝试进行以下方案
1. 蓝黑内容直接涂黑（在 CCoeffNormed 匹配方式下，涂黑约等于遮罩）
2. 对无用部分进行裁剪（左160，上80，下96）

**Comment by huiyadanli** [comment]
点位数据使用：https://github.com/Xcating/Json_Integration

计算验证后发现：

和1024大小区块坐标完全一致

设坐标为 [a,b,c]

![3baf8a71d7403b941980aefe00a61267](https://github.com/babalae/better-genshin-impact/assets/15783049/7205db76-f6e6-4f0d-9606-43456431e23e)

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/blob/c88644f7a6abb3216be55069fb511cf53c89aad2/BetterGenshinImpact/GameTask/AutoTrackPath/AutoTrackPathTask.cs#L383 

大地图定位和传送到指定坐标

**Comment by Limint** [comment]
关于大地图右侧缩放条对应的缩放比例

当放大至最大时，右侧滑块在最上方，此时点击下方➖按钮，滑块会下移1/5段，点击五次后，滑块将位于滑槽最下方。
所以一共有 6 级缩放，记为6级~1级，
地图上相同距离在由大到小 6 级缩放下的像素比为 1：1/2：1/3：1/4：1/5：1/6，即 60：30：20：15：12：10。
6 级放大下，大地图和 2048 原始地图的像素比约为 7 ：6，
所以 6~1 级放大下的大地图和 2048 原始地图的像素比约为 1/6：1/12：1/18：1/24：1/30：1/36：1/7。
（实际测的精确值，1 级放大的大地图与 2048 原始地图比为 7：35.95）

前面验证的是4级放大的大地图和1024原始地图像素比为 25：32，这里是 7：9，都为 0.78 左右，基本是吻合的。

滚轮滚动一下对应滑块移动的距离与帧率成反比。
具体地，滑块由最上方到最下方，在 60 帧下，需要滚动 61 次，在120 帧下，需要滚动 122 次。

**Comment by huiyadanli** [comment]
缩放按钮是等比例的

![Image](https://github.com/user-attachments/assets/3a5ce6cf-ef7e-498e-b194-174f55166888)

**Comment by Limint** [comment]
关于主界面小地图位置和尺寸，
模板是 1600:900, 小地图左上角位置或者说偏移量为 (50, 14), 小地图尺寸为 (180, 180) (外边框尺寸，解包中 UI_MiniMap_RingForm 的大小)
当实际屏幕宽长比小于 1:2 或大于 2:1 时, 模板的偏移量为 (110, 14)

当实际屏幕宽长比小于 16:9 时, 按宽度来计算, 
实际偏移量 = 模板偏移量 / 模板宽度 * 实际宽度, 0.5舍, 即减0.5后向上取整
实际尺寸 = 模板偏移量 / 模板宽度 * 实际宽度, 0.6入, 即加0.4后向下取整

当实际屏幕宽长比大于 16:9 时, 按长度来计算, 
实际偏移量 = 模板偏移量 / 模板长度 * 实际长度, 同上
实际尺寸 = 模板偏移量 / 模板长度 * 实际长度, 同上

实际尺寸在0.6附近舍入的时候可能会发生长宽差1像素，原因未知。

**Comment by huiyadanli** [comment]
1080P下小地图和1024级别原始图的比例是 1:1.66 也就是 3:5 

<img width="1103" height="1076" alt="Image" src="https://github.com/user-attachments/assets/91d0ee92-eed9-46f6-80e0-54d4b3255e7c" />


主界面小地图位置和尺寸 补充

1080P下小地图离左上角位置 (50*1.2,14*1.2)，也就是 (62,19)

```
public class MapAssets : BaseAssets<MapAssets>
{
    public Rect MimiMapRect { get; }

    public MapAssets()
    {
        MimiMapRect = new Rect((int)Math.Round(62 * AssetScale), (int)Math.Round(19 * AssetScale), (int)Math.Round(212 * AssetScale), (int)Math.Round(212 * AssetScale));
    }
}

```
