### ISSUE TITLE
交互黑名单中已加入钓鱼，但总是识别成调查导致自动交互

### ISSUE THREAD

**Issue by Sagili365** [babalae/better-genshin-impact#32]
交互黑名单中已加入钓鱼，但总是识别成调查导致自动交互进入钓鱼
![image](https://github.com/babalae/better-genshin-impact/assets/102888970/260d4ed6-625f-469b-8c53-3344c3e2c245)

![image](https://github.com/babalae/better-genshin-impact/assets/102888970/41da1cef-5a10-453b-8a66-ed04c306bcaf)

**Comment by Sagili365** [comment]
识别过快甚至会导致走不出这个钓鱼点了，疯狂识别（）
![image](https://github.com/babalae/better-genshin-impact/assets/102888970/cbe187ca-de4b-4588-a82c-f3632670c317)

**Comment by huiyadanli** [comment]
文字识别识别错了。。识别成“调查了”。

![image](https://github.com/babalae/better-genshin-impact/assets/15783049/c4e3a45c-bb31-49c7-9500-4e0ada5fddff)

**Comment by huiyadanli** [comment]
我这边可以提供的方案就是，退出钓鱼的瞬间，自动拾取延迟启用。

**Comment by huiyadanli** [comment]
更新了 Yap 最新的识别模型。测试并加入了几个误识别项。

![image](https://github.com/babalae/better-genshin-impact/assets/15783049/ab788eac-e04c-414a-961c-7432aec95db4)

https://github.com/babalae/better-genshin-impact/commit/4e2bd0372e4e41fd09e26f7bc661d319058a977d

预计 0.15.0 修复这个问题
