### ISSUE TITLE
右上角关闭按钮优化建议

### ISSUE THREAD

**Issue by chengdong8023** [babalae/better-genshin-impact#324]
右上角点击叉号会直接关闭插件，经常习惯于点击叉号导致插件关闭，需要退出游戏再重新打开插件，希望新增设置叉号是直接关闭退出还是最小化到托盘，类似网易云的设置
![Snipaste_2024-03-25_10-56-15](https://github.com/babalae/better-genshin-impact/assets/140130689/97da02e3-6eb2-4275-8fa6-2a095caabbac)

**Comment by huiyadanli** [comment]
> @huiyadanli 这样的话还要单独的最小化到托盘按钮吗

保留吧，没啥影响

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.27.0
