### ISSUE TITLE
[question] 为什么使用自动拾取功能后，路过物品时会卡顿掉帧😭

### ISSUE THREAD

**Issue by Ann1eso** [babalae/better-genshin-impact#326]
- Problem Description / 问题描述
- 请尽量提供问题相关的截图/日志等内容

**Comment by huiyadanli** [comment]
正常现象 #99

**Comment by huiyadanli** [comment]
更换了OCR引擎，尝试下 https://github.com/babalae/better-genshin-impact/releases/tag/0.29.0
