### ISSUE TITLE
[suggestion] 可以出【一键长草】模式吗

### ISSUE THREAD

**Issue by gjhhust** [babalae/better-genshin-impact#329]
- Your suggestions / 你的建议

类似明日方舟的MAA，我最初搜索原神的辅助脚本的念头也是希望一键代替我完成每日任务等等每日繁琐的重复东西，自己更多的投入剧情推进。
我希望能出一个【一键长草】功能，完成每日固定的东西，比如四个每日委托，领取固定原石，每日任务等等

**Comment by huiyadanli** [comment]
没有计划做自动每日，只会自动刷本
