### ISSUE TITLE
[suggestion] 邀约相关

### ISSUE THREAD

**Issue by 11389698** [babalae/better-genshin-impact#335]
- Your suggestions / 你的建议
一：![83J{WBT@X_78BSN0W$1~2{P](https://github.com/babalae/better-genshin-impact/assets/79733561/8edd19b8-3777-4846-ac39-ece9b699054a)
邀约到类似画面卡死。
二：希望可以识别邀约中左上角的跳过键并点击
三：在高亮背景（珊瑚宫），派蒙（发言时的晃动的披风），指针光标遮挡，等情况下会出现邀约专属特殊选项识别异常，可能导致不选择未读项而选择已读项。
四：邀约结束出现画片时可以不按叉叉而是点回顾

**Comment by huiyadanli** [comment]
1. 蓝色下标需要和自动剧情中的教程下标做区分，不期望跳过教程，期望跳过邀约内容。最好有更多的图片素材，以及具体邀约内容与触发分支点
2. 跳过以后往往是要手动选择分支的，现在自动邀约没法自动遍历所有分支
3. 需要相关截图，或者视频
4. 这个目的是？需要相关截图，或者视频

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.31.0
