### ISSUE TITLE
[suggestion] 希望能加个玩家自己规划线路然后ai去执行

### ISSUE THREAD

**Issue by gfriendyelin** [babalae/better-genshin-impact#337]
- Your suggestions / 你的建议
具体可以使用空莹酒馆画线路，然后ai按路线走，配合自动收集和自动战斗获取大量的材料和摩拉，解放双手

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.34
自动采集
