### ISSUE TITLE
[suggestion] ”自动剧情“会默认点”切换洞天形态“，这很不方便。

### ISSUE THREAD

**Issue by nizhuan-jjr** [babalae/better-genshin-impact#341]
- Your suggestions / 你的建议
目前没有设置能屏蔽这个，自动剧情时跟阿圆对话，会自动点”切换洞天形态“，但是一般来说，主要就是领宝钱、好感，最多再收个摆设，很少会用到”切换洞天形态“的吧？
希望能有设置让”自动剧情“不点到”切换洞天形态“。

![2024-04-01_093750](https://github.com/babalae/better-genshin-impact/assets/3255986/082dbd19-6fb0-4ad7-8ba8-4302df476ea5)
![2024-04-01_093812](https://github.com/babalae/better-genshin-impact/assets/3255986/d32c88f3-a62d-4363-b30e-dbfd34d271e7)

**Comment by huiyadanli** [comment]
只要这个字体不是橙色就不会优先点击，把小红点点掉就行了

![image](https://github.com/babalae/better-genshin-impact/assets/15783049/af215560-6b54-4cd4-a190-3d6439026bf9)

**Comment by nizhuan-jjr** [comment]
好吧，搞定了
