### ISSUE TITLE
[bug] 自动过剧情的图像识别瑕疵

### ISSUE THREAD

**Issue by wormshi** [babalae/better-genshin-impact#346]
- 系统环境 / System Environment：win10，电脑端原神

- BetterGI版本号 / BetterGI Version：0.26.2

- 问题描述 / Description of the issue：自动点剧情的对话选项点歪了，通过图像识别定位到了非选项框的地方

- 复现步骤 / Reproduction steps：
![无标题](https://github.com/babalae/better-genshin-impact/assets/85731001/77d175f0-bb63-4647-a72e-03d1de384e20)
自动定位到了图片中背包中心的齿轮处

**Comment by huiyadanli** [comment]
其他场景会歪吗？可能是OCR出现了奇怪的问题，最好附上此时的日志

**Comment by wormshi** [comment]
> 其他场景会歪吗？可能是OCR出现了奇怪的问题，最好附上此时的日志

其他场景正常。我在游玩过程中不开日志，是否有自动日志存在软件的路径下？
