### ISSUE TITLE
自动拾取能否自主选择触发的键位？

### ISSUE THREAD

**Issue by wormshi** [babalae/better-genshin-impact#347]
我的键位改了，战技和互动的键位互换了，我没在软件主页找到改键位的地方

**Comment by huiyadanli** [comment]
暂时无法修改

**Comment by G-T-L** [comment]
只需要自动拾取的话先用这个吧https://github.com/Alex-Beng/Yap
（反正两作者关系好引流下问题不大 确信）
不过还是希望作者啥时候能把交互键自定义整上的，毕竟钓鱼啥的我改了键都用不了

**Comment by shixiawuheng** [comment]
我也有这个困扰,我都打算看看源码去改了,可惜对C#不是很熟悉

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.31.0
