### ISSUE TITLE
[suggestion] 关于未来用户脚本自动采集

### ISSUE THREAD

**Issue by jingkarqi** [babalae/better-genshin-impact#349]
在到达采集目的地（狗粮/特产/矿物）后会采用哪种目标识别方式？是直接小地图定位还是用yolo？如果是yolo我可以帮忙打标🤤🤤

**Comment by huiyadanli** [comment]
小地图定位到附近，YOLO寻找目标。

这块现在YOLO训练还未开始，暂未决定好具体需要识别哪些目标。

**Comment by jingkarqi** [comment]
> 小地图定位到附近，YOLO寻找目标。
> 
> 这块现在YOLO训练还未开始，暂未决定好具体需要识别哪些目标。

我先列个表挑一挑
- [ ] 各种掉落物
- [ ] 矿产(更新后有新的物品就得重新训练吧)
- [ ] 植物(同上)
- [ ] 各个等级的宝箱
- [ ] 晶蝶？(这个采集起来有点难度)
- [ ] 闪光（狗粮）
- [ ] 摩拉盒
- [ ] 快速运动方式（须弥四叶印等）
- [ ] 怪物（刷材料路线）

**Comment by huiyadanli** [comment]
先入群吧 [863012276](http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=YOyOxUzXKquJyUuO2z0W1Lrh4iX9ROme&authKey=tckwvC5AC4BuEAKOdxVPr8QsXR1AqwQuzIUiswo9JT%2FpnPniRCoyoEY6IGkljdAo&noverify=0&group_code=863012276)

我最近暂时没时间整理数据和打标（只能布置任务了

**Comment by jingkarqi** [comment]
> 先入群吧 [863012276](http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=YOyOxUzXKquJyUuO2z0W1Lrh4iX9ROme&authKey=tckwvC5AC4BuEAKOdxVPr8QsXR1AqwQuzIUiswo9JT%2FpnPniRCoyoEY6IGkljdAo&noverify=0&group_code=863012276)
> 
> 我最近暂时没时间整理数据和打标（只能布置任务了 😂

问一下这些目标使用统一一个大模型还是每种物品单独使用一个小模型？
大模型只用下载一次，但是训练成本高，每次更新物品要重新训练，客户端运行成本也高
小模型的话，每次用户要新增物品的话就要自己下单独模型，新增物品只需要单独训练，但是要提供下载服务器（也可以给github镜像）
我现在训练了单独一个清心的模型，数据集不多

**Comment by huiyadanli** [comment]
肯定是统一使用一个大模型，实际使用场景不会只识别一个东西的

**Comment by peach-water** [comment]
> 先入群吧 [863012276](http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=YOyOxUzXKquJyUuO2z0W1Lrh4iX9ROme&authKey=tckwvC5AC4BuEAKOdxVPr8QsXR1AqwQuzIUiswo9JT%2FpnPniRCoyoEY6IGkljdAo&noverify=0&group_code=863012276)
> 
> 我最近暂时没时间整理数据和打标（只能布置任务了 😂

原来有个炼丹群啊，才看到

**Comment by Pevernow** [comment]
@huiyadanli 你可能需要zero shot object detection 

YOLO World

**Comment by huiyadanli** [comment]
大世界模型训练一期已经开始，需要标注的物体

* 敌对生物血条（红色）
* 进入战斗后的敌对生物位置指示（红色三角）
* 掉落物
* 矿石掉落物
* 宝箱
* 上锁宝箱
* 路径追踪时的金色闪光（先不做）
