### ISSUE TITLE
是否考虑添加对游戏的直接启动

### ISSUE THREAD

**Issue by Xarth-Mai** [babalae/better-genshin-impact#35]
如题 期望点击开始按钮时如果未检测到游戏进程则自动启动上次hook的进程

**Comment by huiyadanli** [comment]
未来会加入账号切换和游戏直接启动

**Comment by Xarth-Mai** [comment]
😡

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.18.0
