### ISSUE TITLE
[suggestion] 自动剧情可选择不自动选择对话或补全NPC白名单

### ISSUE THREAD

**Issue by snouker** [babalae/better-genshin-impact#350]
- Your suggestions / 你的建议
  - 被自动点击的NPC:
    - 克罗丽丝(蒙德-坠星山谷-植物学家)
    - 神奇的霍普金斯(蒙德-清泉镇  买圣水的)
    - 阿山婆(璃月-璃月港-玩具摊摊主)
    - 博来(璃月-璃月港-[万有铺子]老板)
    - 老孙(璃月-璃月港-鱼贩)
    - 老高(璃月-璃月港-鱼贩)
   - 也许可以尝试识别商店对话中的标签图标.[米游社-观测枢wiki-NPC&商店](https://bbs.mihoyo.com/ys/obc/channel/map/189/20)中类型选择商店也可以列出(包含限时活动商店)

**Comment by huiyadanli** [comment]
有无商贩聊天选项比较通用的排除名，比如“购买”、“兑换”之类的

**Comment by snouker** [comment]
[temp.json](https://github.com/babalae/better-genshin-impact/files/14957523/temp.json)
24-4-11从观测枢(米游社)获取的商人列表,脚本处理了一些,人工调整了一些缺失和重复内容,技术不足要累死人了

格式:
```javascript
[
    {
        "content_id": 501047, //来自观测枢,https://bbs.mihoyo.com/ys/obc/content/501047/detail为具体条目地址
        "ext": "{\"c_20\":{\"filter\":{\"text\":\"[\\\"地区\/蒙德\\\",\\\"类型\/活动\\\",\\\"类型\/商人\\\"]\"}}}", //来自观测枢,可用于分类和过滤
        "title": "芙里达【「后勤小队」骑士】", //来自观测枢,NPC名称【称号】
        "content": [
            "【提升经营效率。】——打开经营助益界面（第二阶段解锁）", //来自观测枢和游戏内,【游戏内文本】——调整过的观测枢描述
            ...
        ] //对话条目数组
    },
    ...
]
```

**Comment by huiyadanli** [comment]
我使用正则提取了里面所有的对话选项 `\"【(.*)】.*\"` ，并去重排序

```
买。
买「超 · 新鲜」的鱼
买新鲜的鱼
买点东西。
你在这里卖什么？
你这里卖什么？
你这里除了璞石还卖什么吗？
关于摆设⋯
关于摆设。
关于甜的···
只卖酒吗？
可以卖一些猎物给我吗？
可以卖给我一些植物吗？
吃的可以打包吗？
如何才能获得强大的力量？
委托锻造⋯
您这里卖什么？
想买些东西⋯
想买些武器。
想买武器。
想找些特别的纪念品。
想挑些趁手的武器。
想看看商品。
想看看有什么东西。
想看看菜单···
想看看菜单。
想看看风筝。
想研制新配方。
想要兑换⋯
想进行酒保挑战。
想选些纪念品。
我也想要新鲜的肉。
我想买些东西。
我想买些书
我想买些书。
我想买些古董。
我想买些吃的。
我想买些吃的可以吗？
我想买些小吃。
我想买些矿石。
我想买些花。
我想买些药材。
我想买些食物⋯
我想买些饮料。
我想买些鱼
我想打包可以吗？
我想打包带走。
我有想买的东西。
我看看商品···
我要购物。
我需要一些钓鱼用品
我需要一些钓鱼用品。
挑选商品。
提升经营效率。
有什么卖的。
有什么卖的？
有什么吃的？
有什么在卖？
有什么好东西吗？
有没有特别商品？
有菜单吗？
来一杯团子牛奶！
来点兰那罗特产
来点精选货物。
来点鱼。
查询「牌手等级」。
物资采购。
现在在卖什么？
看看。
看看书。
看看卡牌商店的商品。
看看菜单。
看看货？
能交换什么呢⋯
让我看看菜单···
讲述与兰那罗的冒险。
请给我来些茶水。
购买「四方八方之网」。
这里卖些什么？
这里卖什么？
进行酒馆牌局挑战。
都卖些什么？
饿了。
```

**Comment by snouker** [comment]
自动剧情的分支对话不自动选择的设置可以做吗?

**Comment by huiyadanli** [comment]
> 自动剧情的分支对话不自动选择的设置可以做吗?

没看懂，如何判断是分支对话

**Comment by snouker** [comment]
我说的分支对话指有选择的对话
当前只能自动选择第一个和第二个,但是在我跟攻略是存在选择不定项的情况,看起来不难做
我想的实现是:

`BetterGenshinImpact.GameTask.AutoSkip`的 [AutoSkipConfig._clickFirstOptionEnabled ](https://github.com/babalae/better-genshin-impact/blob/f1ac26155a1094eeb446ea4ce1192aced22a0280/BetterGenshinImpact/GameTask/AutoSkip/AutoSkipConfig.cs#L54)做成选择第一,负一和不选的选项.

在设置为不选时`BetterGenshinImpact.GameTask.AutoSkip`的 [AutoSkipTrigger.ChatOptionChoose](https://github.com/babalae/better-genshin-impact/blob/f1ac26155a1094eeb446ea4ce1192aced22a0280/BetterGenshinImpact/GameTask/AutoSkip/AutoSkipTrigger.cs#L371)直接返回false或是修改 482行和490行的判断

**Comment by huiyadanli** [comment]
你这都已经会改了，不如直接发起PR？ :joy: 我觉的这么改没问题

**Comment by snouker** [comment]
1. 我没有C++和git的相关经验和开发套件,我能描述但是修改较难
2. 我不希望成为贡献者.我除了遇到问题,几乎不会贡献代码,而且代码质量低,不规范.我的三分钟热情配不上贡献者的荣誉

综上,麻烦开发者了

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.27.0
