### ISSUE TITLE
[question] 0.27.1版本免安装包windows defender报毒

### ISSUE THREAD

**Issue by ICYosoro** [babalae/better-genshin-impact#356]
从蓝奏云连接下载最新版本的免安装包会被windows defender拦截

![image](https://github.com/babalae/better-genshin-impact/assets/41278239/0c19795c-d10f-4411-818d-e5bb7f16d09e)

**Comment by huiyadanli** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/15783049/39b76c0f-4826-458f-93d3-a78c14be27d2)

Windows Defender 扫描未见异常

https://www.virscan.org/report/61a73f08b90c71001a6fb9ce340acae06c17c814a0edaccdd27138adcaa2f821

virscan全员通过

![image](https://github.com/babalae/better-genshin-impact/assets/15783049/b50bbd7b-3a2d-474e-b215-4adaf0f5dcb4)



请对比文件信息

SHA256：
61a73f08b90c71001a6fb9ce340acae06c17c814a0edaccdd27138adcaa2f821
SHA1：
0a3d0fdc3fe9dd57cfb1ba7278603334963032bb
MD5：
514292d998317d778076c5e0b197732f
CRC32：
CBB38370

**Comment by ICYosoro** [comment]
可能是我电脑windows defender抽风了，我换了另一台电脑也没有问题。
