### ISSUE TITLE
自动刷突发事件（获取摩拉、好感、和材料）

### ISSUE THREAD

**Issue by G-T-L** [babalae/better-genshin-impact#357]
这个锚点每次传送过来都会刷出打盗宝团的突发事件，能否像自动伐木一样，调用自动战斗每次把盗宝团打完然后传送回锚点，再下线重登刷新这个突发，收益有突发事件本身的收益（上限十次约1w5莫拉和100好感），以及打盗宝团掉落的莫拉和掉落物（普通怪每日上限4000，约15w莫拉加质变议材料管够）
![Snipaste_2024-04-21_17-23-13](https://github.com/babalae/better-genshin-impact/assets/20348794/14da3248-4c7e-44db-94f4-0aa5fdc83529)

**Comment by G-T-L** [comment]
或者在这个地方重新上线也能刷出来，直接用自动战斗的脚本自动刷应该也行，就每次上线，钟离开盾，夜兰射箭勾过来，然后靠啥的自动打，只要人物不发生位移应该就能一直刷吧
![image](https://github.com/babalae/better-genshin-impact/assets/20348794/73e165f9-ce6a-491b-aa50-3880268c83d7)

**Comment by huiyadanli** [comment]
@Alex-Beng


https://github.com/babalae/better-genshin-impact/assets/15783049/09b30ed2-116f-473c-b3dc-945656f4c3f7

**Comment by huiyadanli** [comment]
我这边计划是后续通过脚配合传送与寻路到达指定地点，然后执行自动战斗

**Comment by Alex-Beng** [comment]
我这边的计划是先模仿学习再强化学习fine tune，目前是模仿学习整个训练+部署基本都做完了，但是效果很差（实际上应该说是效果差才会想到去强化学习微调）。目前刚入职，已经很久没推进度了。

基于学习的方法比人工策略（就是脚本啦）的好处在于新增任务只需要示教，坏处是需要花时间让机器learning，且应该要强化学习微调，且每个任务都需要一个权重，任务多了之后需要大量的磁盘来存放。当然，终极目标可以训练一整个大网络完全模拟人类每天的操作（那为啥玩游戏啊）。

PS：实际上可以等鸭蛋弄个脚本，然后我用脚本示教（bushi）

**Comment by G-T-L** [comment]
> 我这边计划是后续通过脚配合传送与寻路到达指定地点，然后执行自动战斗

自动寻路还是帅的啊，虽然单就这个特殊场景来说，在图2的位置靠弓箭手拉怪原地等怪跑过来的话能省去寻路部分，不过要是自动寻路啥的都做出来了，那是不是捡狗粮啥的都指日可待了

**Comment by goldenapple1** [comment]
实际上是重复问题 https://github.com/babalae/better-genshin-impact/issues/215

**Comment by huiyadanli** [comment]
传送脚本 + 键鼠录制可以实现

https://github.com/babalae/better-genshin-impact/releases/tag/0.34
