### ISSUE TITLE
钓鱼框识别还是有问题

### ISSUE THREAD

**Issue by 745404527** [babalae/better-genshin-impact#36]
100%钓不上来，不是手动提竿导致的问题

1. 有时会出现识别“鱼儿上钩啦！” 导致完全不识别正确的钓鱼框
![自动钓鱼1](https://github.com/babalae/better-genshin-impact/assets/61670738/a9e5755e-7bba-414d-b7b5-19e2274f2b1a)

2. 有时候会出现 钓鱼标 完全出框的情况，然后一直僵持在那里，最后失败
![自动钓鱼2](https://github.com/babalae/better-genshin-impact/assets/61670738/1e9090ea-bd95-4fc0-a1d1-89e40656b8b1)

**Comment by huiyadanli** [comment]
你的游戏亮度设置不正常，请使用默认亮度

**Comment by huiyadanli** [comment]
识别“鱼儿上钩啦！” 是自动提杆的识别。你抛竿后不需要任何手动操作。

你这截图，连识别到框的区域都看不到了。

试试老版本 https://github.com/babalae/genshin-fishing-toy

或者直接上传录屏
