### ISSUE TITLE
[bug] 自动邀约在左下角的显示有问题,怎么切换的显示都是[关闭],就算开启状态也会显示[关闭]

### ISSUE THREAD

**Issue by xxqq170** [babalae/better-genshin-impact#360]
- 系统环境 / System Environment：win10

- BetterGI版本号 / BetterGI Version：0.27.1

- 问题描述 / Description of the issue：自动邀约在左下角的显示有问题,怎么切换的显示都是[关闭],就算开启状态也会显示[关闭]

- 复现步骤 / Reproduction steps：设置好快捷键后,尝试开启或关闭自动邀约

**Comment by huiyadanli** [comment]
是有问题，纯显示问题，实际开关还是有效的

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.28.0
