### ISSUE TITLE
[question] 在View文件夹下的MainWindow.xaml无法使用XAML设计器

### ISSUE THREAD

**Issue by cyhzm** [babalae/better-genshin-impact#364]
- Problem Description / 问题描述
- 无法使用XAML设计器 但是可以直接生成编译打开
- 我已安装所需要的.NET 7.0 SDK
- 请尽量提供问题相关的截图/日志等内容
- 下图为使用XAML编辑器时的图片（但是在我的另一台arm64机器上 可以正常编辑且显示）
![image](https://github.com/babalae/better-genshin-impact/assets/61940215/3a1bd79f-008b-46bc-85b9-e47db735b6cd)
下图为直接生成编译的图片
![image](https://github.com/babalae/better-genshin-impact/assets/61940215/93d5a573-d1fd-4f8e-8e1e-d3000df82171)

**Comment by huiyadanli** [comment]
我无法解答这个问题，因为我的XAML设计器无法正常显示（但不报错）。

早期还是好的，即便回退到早期版本也无法正常显示，怀疑跟UI框架和VS有关
