### ISSUE TITLE
[suggestion] 建议增加“显示日志窗口”功能快捷键设置

### ISSUE THREAD

**Issue by huxc573** [babalae/better-genshin-impact#366]
- Your suggestions / 你的建议

打日常或秘籍有时候需要日志窗口，过剧情需要关闭，每次切换只能去软件中开关，感觉比较麻烦。希望可以增加“显示日志窗口”功能快捷键设置，

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.31.0
