### ISSUE TITLE
角色名称校验失败：千织[bug] 

### ISSUE THREAD

**Issue by Night8848** [babalae/better-genshin-impact#367]
- 系统环境 / System Environment：
- win11 22H2

- BetterGI版本号 / BetterGI Version：
- 0.27.1

- 问题描述 / Description of the issue：
- 自动战斗时无法识别角色“千织”

- 复现步骤 / Reproduction steps：
-创建包含千织的自动战斗文件，启动自动战斗或者自动秘境，报错：“角色名称校验失败：‘千织’”
![image_483](https://github.com/babalae/better-genshin-impact/assets/43611454/442e02f9-2064-4afa-aa00-a2130f30ab76)

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.28.0
