### ISSUE TITLE
每日任务不识别，无法自动提交

### ISSUE THREAD

**Issue by zxygzxy** [babalae/better-genshin-impact#37]
自动每日委托在枫丹没反应，不确定在别的地方是不是这样，还是说必须在别的地方才能识别到

**Comment by huiyadanli** [comment]
左上角未识别到剧情状态的情况下，可能会出现这种情况。

建议使用BitBlt的捕获方式。

如果不是上面两种原因，那就是BUG了

**Comment by zxygzxy** [comment]
捕获方式是BitBit，然后界面是这样，那个Ⅱ偶尔能捕获到，但是剧情中能捕获到，估计是BUG了
![Uploading QQ截图20231119160727.png…]()

**Comment by zxygzxy** [comment]
捕获方式是BitBit，那个Ⅱ偶尔能捕获到，但是剧情中三个字能捕获到，估计是BUG了，图片不会传……大概就是这个意思吧

**Comment by zxygzxy** [comment]
捕获方式是BitBit，那个Ⅱ偶尔能捕获到，但是播放中三个字能捕获到，估计是BUG了，图片不会传……大概就是这个意思吧

**Comment by huiyadanli** [comment]
如果重启软件，并换多个视角也无法点击的情况下，那肯定是BUG。。。

但是这个BUG我这边无法稳定复现，暂时看不出问题出在哪了

**Comment by zxygzxy** [comment]
emmmm……我好像知道了，我游戏窗口不是16：9，刚刚调到16：9就可以了，能不能适配下别的比例啊QAQ

**Comment by huiyadanli** [comment]
不科学，这个功能只要不是特别奇怪比例的分辨率，都可以适配。 

未来会把每个功能的识别区域作为配置项开放给用户，短时间内不会为特殊分辨率适配。

**Comment by zxygzxy** [comment]
我也觉得不科学，因为别的功能是正常的，然后我之前用的比例是1280*800，圣遗物功能也没法用，没试过16：9的圣遗物功能是不是正常的

**Comment by huiyadanli** [comment]
大部分功能都是按照16:9开发的，当前还是以功能为先的

**Comment by huiyadanli** [comment]
多分辨率适配后续关注 #66
