### ISSUE TITLE
[question] BGI打不开，启动没有反应的问题

### ISSUE THREAD

**Issue by chenyuhan12138** [babalae/better-genshin-impact#372]
- Problem Description / 问题描述
- 请尽量提供问题相关的截图/日志等内容
在更新之前使用的是0.26.2版本，某次打开以后提示更新，遂下载0.27.1版本进行替换(之前的全删掉后进行替换)，替换后betterGi主程序打不开(管理员身份运行也一样)，并且没有任何提示。 后续下载老版本（0.26和0.25）以后也打不开了，同样没有任何提示。下载exe格式的安装程序也打不开，有没有遇到过的老哥能够提供一下排查方案

**Comment by emako** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/24737061/a09b01a6-f9e7-4d2d-8951-1dda4838c1b9)
![image](https://github.com/babalae/better-genshin-impact/assets/24737061/c8471f75-a0ef-4043-8e37-d1c793dc1bf3)

**Comment by huiyadanli** [comment]
试试用胡桃启动BGI？

**Comment by chenyuhan12138** [comment]
找到原因了 , 之前windows会弹窗提醒, 然后选仍要运行就行了     现在他不弹窗
![Uploading 357ea0ba3e56795aa7660184c3587c8b.png…]()

**Comment by chenyuhan12138** [comment]
找到原因了 , 之前windows会弹窗提醒, 然后选仍要运行就行了 现在他不弹窗
![357ea0ba3e56795aa7660184c3587c8b](https://github.com/babalae/better-genshin-impact/assets/42503874/953d30b0-cf40-4900-95eb-e6af2b3d13df)
