### ISSUE TITLE
[bug] 无法启动自动钓鱼，会一直报错边界溢出

### ISSUE THREAD

**Issue by elonzh** [babalae/better-genshin-impact#374]
- 系统环境 / System Environment：

Edition	Windows 11 Pro
Version	23H2
Installed on	‎2023/‎2/‎22
OS build	22635.2921
Experience	Windows Feature Experience Pack 1000.22684.1000.0

- BetterGI版本号 / BetterGI Version：

0.27.1

- 问题描述 / Description of the issue：

![image](https://github.com/babalae/better-genshin-impact/assets/8749411/33b6e73a-7dce-4c8b-9877-088804c7aa92)

- 复现步骤 / Reproduction steps：

- 启动 BetterGI 软件
- 开启自动钓鱼
- 无论哪种截图模式均会触发此报错

---

看上去两周前移除了相关代码:

https://github.com/babalae/better-genshin-impact/commit/d917720c9e205e640c88d948be76a790a40a04b8

**Comment by huiyadanli** [comment]
切换分辨率后不重启软件会出现这个问题，0.27版本重启软件后应该恢复正常。或者直接使用0.26版本

**Comment by huiyadanli** [comment]
已修复该问题
https://github.com/babalae/better-genshin-impact/releases/tag/0.28.0
