### ISSUE TITLE
[bug] 自动邀约--鹿野院平藏

### ISSUE THREAD

**Issue by mzj21** [babalae/better-genshin-impact#375]
- 系统环境 / System Environment：WIN10

- BetterGI版本号 / BetterGI Version：0.28.0

- 问题描述 / Description of the issue：
结局一需要选择右边2个选项之一，实际匹配文本有问题，一直选《我觉得你的梦太玄乎，所以你得先跟我回去，有人在担心你的安危。》，建议改成《我帮你查》。后面还有个选项应为《你有点说服我了》。实测可行。

- 复现步骤 / Reproduction steps：
![image](https://github.com/babalae/better-genshin-impact/assets/12492333/f418bc5f-768b-4238-a048-f3157979eee7)
![image](https://github.com/babalae/better-genshin-impact/assets/12492333/d5b81a9f-5e4a-4b68-b2d6-0fd6657b0a95)
![image](https://github.com/babalae/better-genshin-impact/assets/12492333/176ead97-1b75-408c-9a9e-5a3daeb10236)
![image](https://github.com/babalae/better-genshin-impact/assets/12492333/15ad2001-38a6-4311-b9ad-220ec80162bd)
![image](https://github.com/babalae/better-genshin-impact/assets/12492333/114dbaea-ad47-4e58-87a9-60f7c0d74467)

**Comment by wy3057** [comment]
谢谢😊，当时做的时候可能就有一点问题

**Comment by wy3057** [comment]
✧*｡٩(^㉨^*)و✧*｡

**Comment by wy3057** [comment]
修改好了，下个版本应该不会有这问题了

**Comment by huiyadanli** [comment]
已经修复，可以参考 #386 的方式更新配置文件。

也可以等待版本更新
