### ISSUE TITLE
[bug] 重云邀约无法进行结局五

### ISSUE THREAD

**Issue by 1127626014** [babalae/better-genshin-impact#377]
- 系统环境 / System Environment：WIN11

- BetterGI版本号 / BetterGI Version：0.28.0

- 问题描述 / Description of the issue：在重云的决心处开始无法到达结局五

- 复现步骤 / Reproduction steps：

![tmp2479](https://github.com/babalae/better-genshin-impact/assets/57735361/6ee33508-0576-41f3-a339-85b8a21b3b43)
![tmpE6A1](https://github.com/babalae/better-genshin-impact/assets/57735361/cbdd40e3-0b3c-47c7-8822-7aa637f21518)

**Comment by huiyadanli** [comment]
已经修复，可以参考 #386 的方式更新配置文件。

也可以等待版本更新
