### ISSUE TITLE
【BUG】七圣召唤0.14.1相关问题

### ISSUE THREAD

**Issue by nyano** [babalae/better-genshin-impact#38]
建议：
1.添加刷新目录识别功能，添加卡组策略后可以按钮刷新，而不需要关掉重开
2.添加暂停功能，允许期间手动操作，然后继续

BUG:
1.骰子识别不正确（大概率事件）
![image](https://github.com/babalae/better-genshin-impact/assets/5079651/3172c5f8-4445-4c86-aa98-efae608012e7)
![image](https://github.com/babalae/better-genshin-impact/assets/5079651/b2e0fcf6-28fc-4b5d-aca0-f60176b8d5b9)
不知道识别的是哪个点？左侧和右侧都有骰子数，经常数量识别错误

2.对方操作期间造成我方角色便当后，无法识别并选择新角色，卡住 =》好像老版本我记得行的啊？

3.卡组：刻晴雷神甘雨卡组 不知道为什么，总是前几个回合就直接点雷神大招了，但是没充能

4.左上角可以识别对方状态、结束回合等？现在好像是识别中间按钮？等待时间的问题
![image](https://github.com/babalae/better-genshin-impact/assets/5079651/ff51fdb7-21da-42ef-bba9-a10ab8ce0619)
=》大量的 等待对方回合中
![image](https://github.com/babalae/better-genshin-impact/assets/5079651/92d57745-8edd-4299-bfb9-87b3e1d0cf6d)

其他：
1.在6500CPU中，0.13版本 自动拾取如果在黑名单内的，会一直识别造成严重卡顿（新版本未测呢）=》较差的硬件环境
2.希望自动播放剧情不要以左上角自动为依据（或添加设置为非自动时，也能自动播放剧情）
3.日志窗口好像不能移动了？齐声召唤界面都不咋看得清了，或者可以加上背景磨砂么？
4.我的快捷键设置每次重开不知道为什么不保存
5.能添加截图模式启动对原神进程的识别，可以自动对关掉进程和重新打开进程自动的启用和关闭（添加个按钮？）而不需要手动点

我最实用的还是七圣召唤，但是即使用群里的策略，还是打每周胜率一半一半，卡死率需手动也一半一半

**Comment by huiyadanli** [comment]
感谢你的反馈。

七圣召唤：

![image](https://github.com/babalae/better-genshin-impact/assets/15783049/d2313a4d-d854-4f5e-8176-86ad6000817e)

1. 右侧骰子识别率可能相较老版本变低了（主要是风、岩骰子），近期正在解决这个问题，或者考虑会直接把老代码弄回来。
2. 角色被击败时被超载、被强制换人，会无法判断角色是否被击败。
3. 当前无充能判断，刻晴雷神甘雨卡组，可能在被冻结的情况下无法进行后续步骤。当然前面有几步执行失败的情况下也可能出现这种情况。
4. 现在确实是识别的中间的情况，额外等待的日志是为了防止一些特殊情况导致回合判断出错的情况。后面可能考虑会识别这块文字（实际也没那么靠谱）。

TODO: 1

其他：
1. 和黑名单无关，只是一直在识别导致的。实时触发任务除了钓鱼的收杆和拉条之外，其余都对系统资源有着大量消耗（钓鱼的自动抛竿消耗也很大），不断的图像识别匹配、OCR。
2. 以后可能会改，暂时不会改。多点一下也不费事对吧。我认为这是一个常见切换项目。而且依据左上角也是出于性能优化的角度考虑的。
3. 后续会在设置功能中添加选项控制。
4. 这个是BUG，部分系统会出现这种情况，近期会修复。
5. 会添加快捷键开关。完全自动适配的原神启动关闭的话，后续看情况添加。当前的设想是直接BetterGI控制原神启停。

TODO: 3、4、5

**Comment by huiyadanli** [comment]
七圣召唤：1
其他：4

已经修复

**Comment by huiyadanli** [comment]
0.18 添加了对原神的启动

剩余日志窗口移动的问题
