### ISSUE TITLE
更新到最新0.28.0软件过后，自动传送功能，自动剧情，自动拾物功能都无法使用了

### ISSUE THREAD

**Issue by Johnxjj** [babalae/better-genshin-impact#382]
- 系统环境 / System Environment：win11 AMD Ryzen 7 5800H with Radeon Graphics

- BetterGI版本号 / BetterGI Version：0.28.0

- 问题描述 / Description of the issue：更新到最新0.28.0软件过后，自动传送功能，自动剧情，自动拾物功能都无法使用了

- 复现步骤 / Reproduction steps：开机启动就无法使用

**Comment by Johnxjj** [comment]
已经确认，是更新到win11，原神窗口优化的原因。

**Comment by huiyadanli** [comment]
换截图方式，或者 https://github.com/babalae/better-genshin-impact/issues/92
