### ISSUE TITLE
[bug] 0.28.0一出现选项就卡

### ISSUE THREAD

**Issue by zywww** [babalae/better-genshin-impact#383]
- 系统环境 / System Environment：
windows11

- BetterGI版本号 / BetterGI Version：

0.28.0
- 问题描述 / Description of the issue：
一出现选项就卡

- 复现步骤 / Reproduction steps：
随便一个选项都会变卡
![image](https://github.com/babalae/better-genshin-impact/assets/8992990/2b0fb6fb-82be-4eba-b186-4ff72d9f03ec)

**Comment by zywww** [comment]
关掉自动拾取就不卡了，那应该是 自动拾取 有问题

**Comment by huiyadanli** [comment]
#326
#99

**Comment by Lewis-Peter** [comment]
我也遇到了，我遇到的状况是鼠标非常非常卡，键盘却没什么问题

**Comment by zywww** [comment]
> #326 #99

在0.27是没有这种情况的

**Comment by gongfuture** [comment]
> > #326 #99
> 
> 在0.27是没有这种情况的

附议，0.27也没有这么高占用

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/commit/bcec9cfc6b294a063170196284cf4e0479d43206

已经加入引擎选择功能，分别是 [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR) 和 [Yap](https://github.com/Alex-Beng/Yap)。Paddle速度慢一些但是性能消耗会减半

**Comment by huiyadanli** [comment]
更换了OCR引擎，尝试下 https://github.com/babalae/better-genshin-impact/releases/tag/0.29.0

**Comment by zywww** [comment]
更新到2.9.4版本后，使用了一会，没出现卡顿情况。

**Comment by zywww** [comment]
更新到2.9.4版本后，使用了一会，没出现卡顿情况。

**Comment by zywww** [comment]
卡顿比2.8好，不过好像还是有一点点卡，cpu占用如图
![image](https://github.com/babalae/better-genshin-impact/assets/8992990/9c9fb071-f220-4058-97f7-57b8fe9e377b)
![image](https://github.com/babalae/better-genshin-impact/assets/8992990/06888dfb-d3c5-47d5-b896-1c17ca32b828)

**Comment by zywww** [comment]
感谢！

**Comment by huiyadanli** [comment]
后续会继续优化，见 #99
