### ISSUE TITLE
[bug] 主页面的开关无法控制独立任务启停

### ISSUE THREAD

**Issue by Mikachu2333** [babalae/better-genshin-impact#388]
## 主页面的开关应当使所有任务完全停止
![图片](https://github.com/babalae/better-genshin-impact/assets/63829496/6362b8d4-3962-43e9-9abf-b64498095a16)

## 复现：
在原神中启动bgi，并打开“独立任务”->“音游”，点击主页面“停止bgi”，音游自动按键未停止运行。

**Comment by Mikachu2333** [comment]
上次没搜出来（

关键词不大对看起来是

**Comment by huiyadanli** [comment]
#660 终于重写了
