### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by wuhankunsimida** [babalae/better-genshin-impact#390]
- 系统环境 / System Environment：

- BetterGI版本号 / BetterGI Version：0.29.4

- 问题描述 / Description of the issue：

![)PQHGD Y$@}_P 44(Q)EFTT](https://github.com/babalae/better-genshin-impact/assets/169516331/31f98057-4021-4632-a25a-076a8a7c124c)

- 复现步骤 / Reproduction steps：

**Comment by wuhankunsimida** [comment]
a

**Comment by huiyadanli** [comment]
https://bgi.huiyadan.com/faq.html#%E2%9D%93%E6%8F%90%E7%A4%BA-paddleocr%E9%A2%84%E7%83%AD%E5%A4%B1%E8%B4%A5-%E5%BA%94%E8%AF%A5%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3
