### ISSUE TITLE
[bug] 自动邀约无法进入久岐忍结局3和4

### ISSUE THREAD

**Issue by Ecila0310** [babalae/better-genshin-impact#391]
- 系统环境 / System Environment：Win11

- BetterGI版本号 / BetterGI Version：0.29.4

- 问题描述 / Description of the issue：自动邀约无法进入久岐忍结局3和4 处置之方后面的分歧有问题

- 复现步骤 / Reproduction steps：

![QQ截图20240511160036](https://github.com/babalae/better-genshin-impact/assets/165870845/afce8eca-69b1-4b73-94f9-5abda822667d)
![QQ截图20240511155926](https://github.com/babalae/better-genshin-impact/assets/165870845/52e40110-aaa7-42e9-8d0b-13976ae61972)

**Comment by wy3057** [comment]
可以详细的描写一下问题嘛，我看你这个似乎关于三和四的邀约没有正确启动，文本是没有问题的

**Comment by wy3057** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/87601913/3938c55c-c185-4b99-8a09-1fac993fd346)

**Comment by huiyadanli** [comment]
结局3、4的关键文本是：“让我来代劳”

暂时未看出问题，可能是OCR文本识别有误导致的
