### ISSUE TITLE
[bug]2.9快速传送功能好像出现问题 

### ISSUE THREAD

**Issue by BOOSTMKII** [babalae/better-genshin-impact#392]
- 系统环境 / System Environment：

- BetterGI版本号 / BetterGI Version：
[BetterGI_v0.29.4.7z]

- 问题描述 / Description of the issue：
此前快速传送会自动选择传送锚点，更新后却选择任务点，点击单独传送锚点后鼠标也不知为何固定在右下角

- 复现步骤 / Reproduction steps：

**Comment by huiyadanli** [comment]
分辨率问题，已解决
