### ISSUE TITLE
[bug] 云原神使用第二种捕获方式弹出报错

### ISSUE THREAD

**Issue by lalala0312** [babalae/better-genshin-impact#394]
- 系统环境 / System Environment：
版本                         Windows 10 企业版LTSC
版本号                     1809
安装日期                 2020/11/2
操作系统内部版本  17763.5696

- BetterGI版本号 / BetterGI Version：
0.29.4

- 问题描述 / Description of the issue：
云原神全屏幕情况下，启动BetterGI会弹出程序异常的报错
![image](https://github.com/babalae/better-genshin-impact/assets/41423583/f8973f13-d8af-42ad-add2-4d256f086383)

- 复现步骤 / Reproduction steps：
1.启动云原神
2.如图配置
![image](https://github.com/babalae/better-genshin-impact/assets/41423583/0f772fce-0435-4493-8e77-18c10eaf68f5)
3.点击BetterGI的启动后弹出报错
![image](https://github.com/babalae/better-genshin-impact/assets/41423583/f8973f13-d8af-42ad-add2-4d256f086383)

**Comment by huiyadanli** [comment]
尝试使用手动选择窗口的方式

**Comment by Lightczx** [comment]
@huiyadanli [CreateItemForWindow](https://learn.microsoft.com/zh-cn/windows/win32/api/windows.graphics.capture.interop/nn-windows-graphics-capture-interop-igraphicscaptureiteminterop) 只支持win10 18362 及以上的版本

**Comment by huiyadanli** [comment]
@Lightczx 判断方法给我抄抄

**Comment by emako** [comment]
https://github.com/babalae/better-genshin-impact/blob/main/Build/MicaSetup/Helper/System/OsVersionHelper.cs

**Comment by emako** [comment]
new Version(10, 0, 18362);

**Comment by huiyadanli** [comment]
https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/blob/master/dotnet/WPF/ScreenCapture/README.md

官方示例也写了
> Windows 10 version 1903 or later

**Comment by emako** [comment]
那用IsWindows10_1903_OrGreater判断就行了，不行就提示new PlatformNotSupportedException("仅支持Windows 10 version 1903 or later").ToString()

**Comment by huiyadanli** [comment]
直接在这个版本之前不展示这个截图器选项了

**Comment by huiyadanli** [comment]
![d72ca16219e3e31cc3bca8e2600f3cb0](https://github.com/babalae/better-genshin-impact/assets/15783049/0555238c-612c-49f4-a620-07f21971505e)

**Comment by snouker** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/47094070/a2a16149-a30f-4c72-ab6c-466d298912b2)
@huiyadanli 本人win11被误伤,之前用WindowsGraphicsCapture.现在没改设置,选择框内无显示内容,功能不影响(担心改完无法改回来).

**Comment by huiyadanli** [comment]
@emako 看样子这个方法不靠谱

**Comment by emako** [comment]
@huiyadanli 你逻辑写反了

**Comment by huiyadanli** [comment]
干，还真是
