### ISSUE TITLE
在自动战斗开始后，一键宏识别出现问题[bug] 

### ISSUE THREAD

**Issue by angleyanalbedo** [babalae/better-genshin-impact#396]
- 系统环境 / System Environment：
windows11 
操作系统版本 22631.3527

- BetterGI版本号 / BetterGI Version：
0.29.4

- 问题描述 / Description of the issue：
当你启动自动战斗再将其关闭后，一键宏会失效会将角色全部识别为一个角色 
一键宏只会将角色识别为自动战斗最后出场角色

- 复现步骤 / Reproduction steps：
1. 为了防止未识别角色我已经设置强制指定配对
2. 先启动自动战斗后再切换到bettergi将自动战斗关闭后
3. 当回到游戏时一键宏只能识别一个角色

**Comment by huiyadanli** [comment]
这个问题虽然很简单，但是复现起来确实有一丢丢刁钻

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.30.0
