### ISSUE TITLE
自动风行迷踪的可行性？

### ISSUE THREAD

**Issue by Schwarze-Katze** [babalae/better-genshin-impact#397]
比较不适应捉迷藏的多人对抗玩法。
既然音游能挂机，那捉迷藏也能！（x

目前的思路：
1. 人工定位到捉迷藏开始处，并开启任务
2. 自动点击F对话框，ocr出目前进度，判断是否完成
3. 自动进入游戏并准备
4. 躲藏阶段按住w前进
5. 追捕阶段开始时按下变形键
6. 等待游戏结算
7. 返回步骤2

潜在问题：
1. 目前按照自动伐木的代码搭了半个架子，但我不熟悉c#（笑），debug可能需要dalao协助
2. 局内操作仅适配躲藏，不适配追捕
3. 多人游戏中行为可疑，有被举报风险

**Comment by huiyadanli** [comment]
可是新版本不止要躲藏。需要到达指定地点修复东西。

更加适合这个模式的是直接自动循环绕圈跑和冲刺，吸引猎手，给队友创造机会

**Comment by huiyadanli** [comment]
活动已经关闭。

另：一般不推荐在联机场景使用自动化脚本，可能会破坏他人的游玩体验。

虽然关联PR未被接受，但还是感谢你的idea与尝试
