### ISSUE TITLE
[bug] 多鱼饵钓鱼点自动钓鱼鱼饵选择出错

### ISSUE THREAD

**Issue by Temp314159** [babalae/better-genshin-impact#399]
- BetterGI版本号 / BetterGI Version：
0.29.4

- 问题描述 / Description of the issue：
在有5种鱼饵选择的钓鱼点使用自动钓鱼时，若当前选择的鱼饵与BetterGI要选择的鱼饵不同，则在BetterGI自动切换鱼饵后，会选成最后一个鱼饵。
目测是因为选择鱼饵后会在右侧空白处点一下，但是5个鱼饵太多，原本的空白处此时是最后一个鱼饵。
例如下图沉玉谷古茶树坡钓鱼点。
![p1](https://github.com/babalae/better-genshin-impact/assets/104284758/205786f3-9ee8-4aed-a637-4239f191493e)
![p2](https://github.com/babalae/better-genshin-impact/assets/104284758/a605a847-8f6d-4b73-8597-78369f0ef146)

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.30.0
已修复
