### ISSUE TITLE
自动剧情总关闭锚点详情页

### ISSUE THREAD

**Issue by Xunflash** [babalae/better-genshin-impact#40]
![image](https://github.com/babalae/better-genshin-impact/assets/71567536/4283a415-a9b5-4420-bd93-2c9b6cb40fb6)
如题自动剧情总关闭锚点详情页，反复点击多次才不自动关闭

**Comment by huiyadanli** [comment]
bug已修复，下次发布解决

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.15.0
