### ISSUE TITLE
解锁帧率？[suggestion] 

### ISSUE THREAD

**Issue by ylf8649** [babalae/better-genshin-impact#402]
- Your suggestions / 你的建议

可否增加原神启动自动解锁帧率的可选功能
可选功能如下
    可调分辨率
    是否开启解锁帧率限制

类似如图
![PixPin_2024-05-17_10-07-43](https://github.com/babalae/better-genshin-impact/assets/99555235/1e1f74ed-3535-4091-968a-b2f27653f623)

**Comment by emako** [comment]
#158 重复的ISSUE

**Comment by emako** [comment]
加功能倒是简单，BGI也是用Vanara，https://github.com/GenshinMatrix/Fischless/tree/main/src/Desktop/Fischless.Fetch/Unlocker

**Comment by ylf8649** [comment]
> 加功能倒是简单，BGI也是用Vanara，https://github.com/GenshinMatrix/Fischless/tree/main/src/Desktop/Fischless.Fetch/Unlocker

那就坐等更新啦

**Comment by ylf8649** [comment]
> 加功能倒是简单，BGI也是用Vanara，https://github.com/GenshinMatrix/Fischless/tree/main/src/Desktop/Fischless.Fetch/Unlocker

主要是不想开两三个原神助手- =

**Comment by huiyadanli** [comment]
同#158所述，短时间内不会添加。

不是技术问题。

BGI本身就偏向与辅助性质并且承诺不会介入游戏内存，而解锁整理是修改了unity的内存实现的。容易产生混淆与误解
