### ISSUE TITLE
[bug] v0.29.4 无法自动拾取

### ISSUE THREAD

**Issue by H-MK** [babalae/better-genshin-impact#406]
- 系统环境 / System Environment：win10 x64 22H2 **雷电外接显卡坞**

- BetterGI版本号 / BetterGI Version：0.29.4

- 问题描述 / Description of the issue：0.29.4大概率出现无法自动拾取，小概率自动拾取非常慢（5秒以上），小概率正常。**0.26.2自动拾取功能正常**。

- 复现步骤 / Reproduction steps：可以看下显卡OSD上的时间
<img width="1080" alt="Snipaste_2024-05-23_11-33-47" src="https://github.com/babalae/better-genshin-impact/assets/95403231/2fab46f9-2b53-460e-8b8d-c0d37d6d4b94">
<img width="1080" alt="Snipaste_2024-05-23_11-34-07" src="https://github.com/babalae/better-genshin-impact/assets/95403231/d28469c5-b684-48c8-b1d0-bf50f13f3210">
<img width="585" alt="Snipaste_2024-05-23_11-44-21" src="https://github.com/babalae/better-genshin-impact/assets/95403231/3d39a246-cbf2-4390-b7dd-89e3a4d1fcd9">
应该是截图失败

**Comment by huiyadanli** [comment]
https://bgi.huiyadan.com/quickstart.html

**Comment by huiyadanli** [comment]
分辨率问题，下版本会修
