### ISSUE TITLE
[bug] 软件崩溃（第三方OSD软件引起）可以关闭了

### ISSUE THREAD

**Issue by H-MK** [babalae/better-genshin-impact#407]
- 系统环境 / System Environment：win10 x64 22H2 **雷电外接显卡坞**

- BetterGI版本号 / BetterGI Version：0.29.4 0.26.2

- 问题描述 / Description of the issue：崩溃退出；
[错误日志.zip](https://github.com/babalae/better-genshin-impact/files/15411280/default.zip)

- 复现步骤 / Reproduction steps：最大化软件后崩溃；随机在点击一些选项后概率出现崩溃，白框覆盖或鼠标卡顿

<img width="602" alt="Snipaste_2024-05-23_11-50-24" src="https://github.com/babalae/better-genshin-impact/assets/95403231/03c9add8-5309-40ca-9f69-78f98f358403">
<img width="675" alt="Snipaste_2024-05-23_11-54-37" src="https://github.com/babalae/better-genshin-impact/assets/95403231/507f5afc-ab88-4823-b80c-451d2ba3c073">

**Comment by huiyadanli** [comment]
没见过的场景。。

**Comment by H-MK** [comment]
> 没见过的场景。。

刚刚又仔细看了下windows的错误日志，伴随着 BetterGI.exe的错误，总是有GPU Tweak III.exe。
GPU Tweak III是华硕显卡的管理软件，其中有OSD显示的功能。与 BetterGI的OSD相关功能冲突？
不开启GPU Tweak III， BetterGI就不会崩溃。
<img width="595" alt="Snipaste_2024-05-23_13-11-57" src="https://github.com/babalae/better-genshin-impact/assets/95403231/7579fb14-a7d6-40dd-94d2-e1eff178f65d">

**Comment by H-MK** [comment]
我把BetterGI.exe加入了GPU Tweak III的黑名单，似乎问题得到了解决。至少现在最大化没有崩溃了。
应该就是这个问题。
![Uploading Snipaste_2024-05-23_13-16-39.png…]()

**Comment by H-MK** [comment]
![Uploading Snipaste_2024-05-23_13-16-39.png…]()

**Comment by H-MK** [comment]
我把BetterGI.exe加入了GPU Tweak III的黑名单，似乎问题得到了解决。至少现在最大化没有崩溃了。
应该就是这个问题。

**Comment by emako** [comment]
DX9的老东西跟GPU修改器冲突似乎是理所当然
