### ISSUE TITLE
几个使用bug

### ISSUE THREAD

**Issue by Xunflash** [babalae/better-genshin-impact#41]
- [x] 自动钓鱼在钓鱼中关闭（好像是预抛竿）会继续后面的流程，并不会立即停止
- [ ] 周本/世界boss征讨之花会误判为自动拾取
- [x] 到钓鱼点的时候会误判为自动拾取打开界面
- [ ] 部分文本识别错误

![image](https://github.com/babalae/better-genshin-impact/assets/71567536/ffc93422-63b0-4f9d-82e1-488348a848ac)

**Comment by huiyadanli** [comment]
1. 确实无法立即停止，优化优先级较低。
2~4 OCR识别有误是难免的，直接把误识别的词汇加入到黑名单就能解决这个问题。针对这块已经近期有过优化，尤其是钓鱼的误拾取，下版本上线

**Comment by huiyadanli** [comment]
1 已经部分优化
2~4 钓鱼误触也优化了
https://github.com/babalae/better-genshin-impact/releases/tag/0.16.0
