### ISSUE TITLE
[bug] 在2k全屏显示下，左上角东南西北标识的位置错位了

### ISSUE THREAD

**Issue by colorful414** [babalae/better-genshin-impact#412]
- 系统环境 / System Environment：
win11 23H2

- BetterGI版本号 / BetterGI Version：
0.30

- 问题描述 / Description of the issue：

左上角地图的东南西北标识位置错误
- 复现步骤 / Reproduction steps：

**Comment by huiyadanli** [comment]
0.30.2版本修复了这个问题
