### ISSUE TITLE
[bug] 凯瑟琳每日自动领取委托/自动重新派遣关闭功能无效

### ISSUE THREAD

**Issue by Doubi-dada** [babalae/better-genshin-impact#417]
- 系统环境 / System Environment：
window10LTS

- BetterGI版本号 / BetterGI Version：
0.30.0

- 问题描述 / Description of the issue：
实时触发-自动剧情下的凯瑟琳每日自动领取委托/自动重新派遣 功能关闭后仍会触发，关闭功能无效
![image](https://github.com/babalae/better-genshin-impact/assets/60688459/9419296c-ae85-42c1-88a0-230b7e6d71f0)

- 复现步骤 / Reproduction steps：

**Comment by huiyadanli** [comment]
fixed https://github.com/babalae/better-genshin-impact/releases/tag/0.31.0
