### ISSUE TITLE
自动钓鱼鱼饵选择建议

### ISSUE THREAD

**Issue by Xunflash** [babalae/better-genshin-impact#42]
自动钓鱼能不能添加一个配置项配置只选择某一种鱼饵，到钓鱼点的时候老乱选鱼饵（或者是我没用明白，wiki好像也没钓鱼的逻辑）

**Comment by huiyadanli** [comment]
会根据当前识别到的最多鱼种类来选择鱼饵，当鱼池内鱼较少，或者频繁被遮挡的时候，就会出现这种情况。

本质是训练集不够的问题。加上物体追踪的能力可能可以解决（300M的模型

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.25.0 已修复
