### ISSUE TITLE
几个不成熟的建议

### ISSUE THREAD

**Issue by GJingBo** [babalae/better-genshin-impact#423]
1、右键返回上一层，例如：领取邮件可以右键关闭窗口；强化圣遗物右键关闭。
2、刷圣遗物领取物品时自动跳过。
3、角色技能CD显示，盾量显示（其实这个应该米哈游做，从1.x开始提一直不做）。
4、极速传送在副本内不传送或者添加个黑名单把副本添加进去。

不成熟的建议，现在已经很好了，祝大佬工作顺利。

**Comment by huiyadanli** [comment]
1. 按ESC。右键作为一个常用按钮，绑定其他功能在正常游玩游戏的时候识别会造成游戏卡顿
2. 跳过的识别没有明显标记物，作为一个常驻功能使用次数实在太少。和付出的识别性能损耗完全不成正比。另，自动秘境带有领取自动跳过。
3. #119
4. 无法判断你是否在副本内。如果是副本不传送，请使用长按快捷键传送的功能。
