### ISSUE TITLE
[suggestion] 关于在凯瑟琳处领取奖励时的延迟

### ISSUE THREAD

**Issue by goldenapple1** [babalae/better-genshin-impact#425]
- Your suggestions / 你的建议

在当前版本的BGI中，凯瑟琳的自动领取每日委托和自动重新派遣的选项会使用“对话选项前的延迟”的延迟时间，但实际上在凯瑟琳那里领东西的时候，没人会在乎她到底说了什么。所以我的建议是，能否让领取奖励时的延迟变成0，但是过其他对话的时候还是保持用户设置的延迟。

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.31.0
