### ISSUE TITLE
b服无法正常使用自动伐木[suggestion] 

### ISSUE THREAD

**Issue by KIC8462852M** [babalae/better-genshin-impact#428]
- Your suggestions / 你的建议

b服很多时候进游戏后需要先点一下鼠标左键才能进行后续操作，导致自动伐木失效，建议在自动伐木中加入每次按z建前点击一下鼠标左键的动作

**Comment by huiyadanli** [comment]
这个操作很久以前就已经实现了，近期几个B服玩家测试无问题
