### ISSUE TITLE
自动拾取会误触鸣神大社的御神签箱

### ISSUE THREAD

**Issue by 144-144** [babalae/better-genshin-impact#431]
- 系统环境 / System Environment：
windows 10

- BetterGI版本号 / BetterGI Version：
0.30.2

- 问题描述 / Description of the issue：
自动拾取会误触鸣神大社的御神签箱，
虽然这个问题可以通过配置黑名单解决，但是如果开发者能提前写在黑名单就更好了

- 复现步骤 / Reproduction steps：
1.打开自动拾取
2.打开原神，走到鸣神大社的御神签箱旁
3.自动触发对话
4.然后走完对话
5.回到步骤3

**Comment by H-MK** [comment]
每个版本更新我都是复制之前版本的黑白名单文件。

**Comment by huiyadanli** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/15783049/7475cedf-3ae8-4f73-b1d3-b3c18d936573)

测试 Paddle 还是很稳的：「御神签箱」

换成 Yap 比较容易识别成：御神签箱

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.31.0
