### ISSUE TITLE
[suggestion]希望将“与凯瑟琳对话”的2个功能独立出来，添加自动传送、走到凯瑟琳处然后对话的功能。

### ISSUE THREAD

**Issue by BaoyunMa** [babalae/better-genshin-impact#439]
- Your suggestions / 你的建议

希望将 自动领取每日委托奖励 与 自动重新派遣 独立出来。

# 优点
1. 可以扩充更多功能，例如自动传送、走到凯瑟琳处然后对话。（主要）
2. 在执行领取委托奖励任务时，可以针对领取委托特殊优化，以提升速度。
3. 一些时候，领取委托奖励 与 其他剧情 两个场景的配置不同，例如委托奖励需要快速跳过对话，而普通剧情不希望跳过对话。若分开，可以免去关闭“游戏内自动剧情按钮”。

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.38
