### ISSUE TITLE
[suggestion] 自动邀约下，希望邀约选项出现后等待一段时间再点击。

### ISSUE THREAD

**Issue by 144-144** [babalae/better-genshin-impact#440]
- Your suggestions / 你的建议

在自动邀约功能下，希望邀约选项出现后等待一段时间再选择，

对于具体等待多长时间，可以设置固定时间。

不知道能否计算出地下的文本长度，估算出等待时间，这样应该会更智能吧，也可以放在自动剧情功能上。

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.31.0
