### ISSUE TITLE
[suggestion] 全新的MaskWindow方案

### ISSUE THREAD

**Issue by emako** [babalae/better-genshin-impact#441]
- Your suggestions / 你的建议

![GIF](https://github.com/babalae/better-genshin-impact/assets/24737061/b8ad9ec5-6398-445e-ad08-403d692740c2)

**Comment by emako** [comment]
乞うご期待（多分

**Comment by emako** [comment]
win32api示例：https://github.com/lemutec/PresentMonFps/blob/v2/demo/PresentMon.SampleWPF/MaskWindow.xaml.cs

**Comment by emako** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/24737061/5dd2ec50-a1b4-43b3-9898-ee9cb036d0d7)
示例效果是左上角实时显示FPS

**Comment by huiyadanli** [comment]
![演示](https://github.com/user-attachments/assets/8c741740-fe67-482b-858e-fecad9219344)

好用到哭泣

**Comment by huiyadanli** [comment]
游戏关闭会导致MaskWindow被关闭

**Comment by emako** [comment]
#481
