### ISSUE TITLE
[bug] 软件窗口的标题栏文字排列不对齐

### ISSUE THREAD

**Issue by DuckDeng** [babalae/better-genshin-impact#442]
- 系统环境 / System Environment：
Win11 23H2

- BetterGI版本号 / BetterGI Version：
0.31.1

- 问题描述 / Description of the issue：
软件窗口的标题栏文字排列不对齐。标题和图标应该显示在色块居中位置。
![image](https://github.com/babalae/better-genshin-impact/assets/64295725/0a0e78db-9367-41f0-885c-9298a37803c7)

- 复现步骤 / Reproduction steps：

无需

**Comment by huiyadanli** [comment]
UI框架的问题，暂时不知道如何解决

**Comment by huiyadanli** [comment]
https://github.com/lepoco/wpfui/issues/595
