### ISSUE TITLE
[bug] 更新提示弹窗位置未适配高分屏DPI缩放

### ISSUE THREAD

**Issue by ccjjxx99** [babalae/better-genshin-impact#446]
每次打开检测到更新时，在我的一台老台式上弹窗位置是居中的，因为我的屏幕是100%的缩放大小。

在高分辨率笔记本上，我的缩放大小是200%，这时更新提示弹窗在电脑的最右下角（如图所示），很难注意到。

我猜测是以左上角为原点定位，但是距离单位没有根据屏幕缩放DPI来调整，万一有人缩放大小大于200%，是不是弹窗位置就跑到屏幕外面了。望修复。

![image](https://github.com/babalae/better-genshin-impact/assets/32434705/a8e1a593-b6b6-4334-9920-15a18d745294)

**Comment by emako** [comment]
wpfui的ContentDialog一堆堆BUG，后续用自己的替代吧

**Comment by huiyadanli** [comment]
@emako 扒一个过来，我想要改成显示readme的

**Comment by emako** [comment]
什么README

**Comment by huiyadanli** [comment]
> 什么README

想错了，我直接改成了一个window好了，到时候要显示更新日志

**Comment by huiyadanli** [comment]
#450

**Comment by emako** [comment]
https://github.com/lepoco/wpfui/pull/1130
