### ISSUE TITLE
[question] 重启后自动删除很多东西

### ISSUE THREAD

**Issue by Cat27182818** [babalae/better-genshin-impact#448]
- Problem Description / 问题描述
- 请尽量提供问题相关的截图/日志等内容
- 
- 安装后运行无任何问题
- 重启后自动被删除，Windows安全中心排除了该文件夹仍然会被删除
- 保护历史记录截图如下：

![屏幕截图 2024-06-13 124426](https://github.com/babalae/better-genshin-impact/assets/55133501/33d017a5-907d-4353-bade-a2fbac62846b)

**Comment by huiyadanli** [comment]
从保护记录来看确实不是WD删除的

近期遇到多人反馈无杀毒软件拦截但是被自动删除的问题。

已知本软件不会自动删除自己

那剩余最大的可能性

* 安全软件 or 系统机制
* 有其他第三方软件在删除 BetterGI

能否提供具体删除的文件信息，和其所在目录？

是否安装了其他安全软件？

**Comment by Cat27182818** [comment]
1.
所在目录为
E:\BetterGI\BetterGI
删完了算上log就剩651kb，然而log占640kb，基本全没了
2.
没安装其他安全软件
3.
重启后安装不会删除
开机后手动启动的其他软件，只有：
原神，3dmigoto（用于打mod），火狐浏览器
4.
0.24.1版本肯定没这个问题
现在的版本是0.31.1
但是0.31.1风扇声音更小，显然优化更好

感谢大佬

**Comment by huiyadanli** [comment]
第三点，重启后安装不会删除，然后再重启还会复现这个问题吗？

**Comment by Cat27182818** [comment]
基本解决了。

直接卸载0.24.1，彻底删除，再安装0.31.1，正常配置并使用，不会出问题。

如果卸载0.24.1时，勾选保留数据，同时安装0.31.1时，把剩余数据及配置文件合并到新目录，就会出问题。
此时运行过betterGI，再重启会复现删除bug。
未运行过betterGI，也没合并（重新换了一个目录下载忘记合并了），此时重启不会复现删除bug。

给大佬添麻烦了，抱歉。

**Comment by huiyadanli** [comment]
把类似情况补充到了文档内：


卸载的时候由于文件被占用等问题，会下次重启后删除。（卸载程序会提示：“存在部分文件删除失败，这些文件将在下次重启后自动删除。”）

如果不重启，然后使用新的安装包进行覆盖安装就会出现此类情况。

如果只是为了更新 BetterGI，直接覆盖安装即可，无需卸载后重新安装！


https://bgi.huiyadan.com/faq.html#%E2%9D%93%E9%87%8D%E5%90%AF%E5%90%8E%E7%A8%8B%E5%BA%8F%E8%A2%AB%E5%88%A0%E9%99%A4%E4%BA%86%E6%98%AF%E4%BB%80%E4%B9%88%E6%83%85%E5%86%B5
