### ISSUE TITLE
希望快捷键能够添加对鼠标侧键的支持

### ISSUE THREAD

**Issue by GilgameshSAMA** [babalae/better-genshin-impact#45]
希望快捷键能够添加对鼠标侧键的支持

**Comment by Lightczx** [comment]
@huiyadanli registerHotKey 理论上是不支持侧键的，需要对当前捕获鼠标的窗口 SetWindowHookEx 才能获取侧键按下的事件

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.24.0  已支持
