### ISSUE TITLE
[bug] 自动秘境任务时，在结束自动战斗后，小概率纳西妲的 E 技能处于按下未松开状态

### ISSUE THREAD

**Issue by 144-144** [babalae/better-genshin-impact#451]
- 系统环境 / System Environment：
Windows 10

- BetterGI版本号 / BetterGI Version：
0.31.1

- 问题描述 / Description of the issue：
在自动秘境任务中，纳西妲前台，自动战斗结束后，有小概率处于按下 E 键未松开状态，即纳西妲一直扫描知道时间结束自然结束。

- 复现步骤 / Reproduction steps：
1. 打开自动秘境任务，选择四神挂机队；
2. （自动）进入秘境，开启挑战；
3. （自动）游戏提示挑战结束，同时脚本切换到纳西妲前台，紧接着按下 E 键（好像是这样，没有看清）；
4. （自动）结束战斗脚本， E 键未松开。

**Comment by huiyadanli** [comment]
不会影响最后领取奖励，未松开是和当前的中断机制有关，在不影响自动秘境的情况下不会做修改
