### ISSUE TITLE
[suggestion] 自动邀约时，即将选择选项时，建议添加 按一次空格控制 BetterGI 点击选项 的功能

### ISSUE THREAD

**Issue by 144-144** [babalae/better-genshin-impact#453]
- Your suggestions / 你的建议

自动邀约时，即将选择选项时，建议添加 按一次空格控制 BetterGI 点击选项 的功能，

当前方式是间隔一段时间再点击选项，若使用空格键控制点击，体验应该会更好。

**Comment by huiyadanli** [comment]
直接使用自动剧情带有的延迟就行
