### ISSUE TITLE
不停循環第一个选项 

### ISSUE THREAD

**Issue by moseskong0715** [babalae/better-genshin-impact#456]
![image](https://github.com/babalae/better-genshin-impact/assets/98659104/5f1a1957-e961-4b7c-bc86-65c816c92e38)
不停循環第一个选项
检测重复，可能发现几次重复，换个选项按

**Comment by huiyadanli** [comment]
做检测比较麻烦，不值得为了这类1%的情况去做记录。

可以加上随机选项选择解决这个问题

**Comment by emako** [comment]
1%可不止

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.32 
内加入了随机选择选项的方式，可以规避此类死循环
![image](https://github.com/user-attachments/assets/fadcca0e-267e-4d8d-994a-5cb096cac221)
