### ISSUE TITLE
0.15.0使用的BUG

### ISSUE THREAD

**Issue by whomtao** [babalae/better-genshin-impact#46]
1.在黑名单中明确有“菲米尼”的名字，但是在使用时，依旧会自动与菲米尼进行对话
![微信截图_20231123220711](https://github.com/babalae/better-genshin-impact/assets/35491658/2ecb153e-82fc-4ebd-b68d-777058811ec4)
2.新活动“主板调试”字样，无论是添加到白名单还是黑名单都会自动对话。
添加字样以后，软件“启动”界面内进行“关闭”，再“启动”（没有关闭软件，不知道是不是因为这个导致没有加载配置）

**Comment by huiyadanli** [comment]
1. 可以看下右下角错误识别的内容是什么，加入黑名单即可
2. 需要重启软件生效。。。

**Comment by Autumn-of-One** [comment]
OCR可能不准，看下错误识别的内容是什么添加一下就行

**Comment by whomtao** [comment]
> OCR可能不准，看下错误识别的内容是什么添加一下就行

屏幕上的日志显示的就是"菲米尼"，且“菲米尼”在黑名单里面，不在白名单内。最后还是触发自动拾取了。

**Comment by Autumn-of-One** [comment]
> > OCR可能不准，看下错误识别的内容是什么添加一下就行
> 
> 屏幕上的日志显示的就是"菲米尼"，且“菲米尼”在黑名单里面，不在白名单内。最后还是触发自动拾取了。

“菲米尼”没试，不过“主板调试”识别率为0。
![image](https://github.com/babalae/better-genshin-impact/assets/42486615/b0c6145b-b604-42b0-af5c-cc99d41fb935)

**Comment by huiyadanli** [comment]
@Autumn-of-One 因为这个活动词汇未被训练，所以几乎无法识别

**Comment by huiyadanli** [comment]
#59 

这个模型要重新训练，暂不考虑，只能劳烦在活动区域关闭自动拾取功能
