### ISSUE TITLE
[bug] 无法识别石化古树

### ISSUE THREAD

**Issue by yEs1do** [babalae/better-genshin-impact#466]
- 系统环境 / System Environment：
分辨率 1920x1080
四神队伍，顺序与视频一致

- BetterGI版本号 / BetterGI Version：
0.31.1

- 问题描述 / Description of the issue：
![image](https://github.com/babalae/better-genshin-impact/assets/25378493/d4a9147a-4ffd-41c6-9e02-5b67e3c88b3c)
小地图一直转，黄色直线固定朝上，关闭时提示查找东方向进程结束，应该是找东方没找到？

- 复现步骤 / Reproduction steps：
开启秘境任务，自动战斗结束后查找古树

**Comment by huiyadanli** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/15783049/ca3eaa93-26ff-4e48-afc3-f1a839564b9e)
 
小地图必须是锁定方向的

**Comment by emako** [comment]
小地图没锁定方向给个LOG提示

**Comment by yEs1do** [comment]
> ![image](https://github.com/babalae/better-genshin-impact/assets/15783049/ca3eaa93-26ff-4e48-afc3-f1a839564b9e)
>  
> 小地图必须是锁定方向的

收到！是我疏忽了。
