### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by Cat27182818** [babalae/better-genshin-impact#467]
- 系统环境 / System Environment：
win11

- BetterGI版本号 / BetterGI Version：
0.31.1

- 问题描述 / Description of the issue：
剧团本，自动秘境，5个浓缩，150体力左右，出来还剩71体力，
![屏幕截图 2024-06-24 124008](https://github.com/babalae/better-genshin-impact/assets/55133501/e5ed6bc8-eff7-4872-8681-53031efed111)
![屏幕截图 2024-06-24 124016](https://github.com/babalae/better-genshin-impact/assets/55133501/16137887-502a-4fe8-af6b-8a933496b857)

- 复现步骤 / Reproduction steps：

**Comment by huiyadanli** [comment]
OCR偶尔识别会有问题，重试即可
