### ISSUE TITLE
启动时检查是否有关键文件缺失，缺失时提示

### ISSUE THREAD

**Issue by huiyadanli** [babalae/better-genshin-impact#468]
有很多用户会有剪切exe到桌面当快捷方式的情况

![image](https://github.com/babalae/better-genshin-impact/assets/15783049/5e4088b1-c16b-455f-b769-13365ca2083b)

直接提示：发现有关键程序文件缺失，请不要把主程序exe文件剪切到桌面

**Comment by wy3057** [comment]
Win11怎么设置快捷方式？有时候我们下载安装软件之后，桌面不会生成相应的软件快捷方式，但为了之后可以方便的打开软件，我们还需要手动设置。本期教程小编将为大家带来Win11创建应用桌面快捷方式的方法，我们一起来学习下吧。

　　具体操作如下：

　　1、打开“此电脑”，找到你想要添加桌面快捷方式的文件或软件。


　　2、找到后，右键选中它，点击“显示更多选项”。


　　3、再选择“发送到”-“桌面快捷方式”。


　　4、操作完成后，这样应用软件就有快捷方式了。

**Comment by goldenapple1** [comment]
很难想象开源项目也能遇到赛博丈育

**Comment by peach-water** [comment]
不过检查程序文件是否缺失这个功能确实可以做一个。
