### ISSUE TITLE
[suggestion] 自动拾取会自动与新深渊发生交互

### ISSUE THREAD

**Issue by WoshiRedstone** [babalae/better-genshin-impact#473]
- Your suggestions / 你的建议

新深渊的交互会让自动拾取功能误判，所以建议增加对该交互按钮的排除

**Comment by 144-144** [comment]
其实前几次活动也会误判

**Comment by Amb114** [comment]
> 可以根据左下角日志，自行添加黑名单

想传送进去的时候会点锚点，传送怎么添加黑名单

**Comment by huiyadanli** [comment]
> > 可以根据左下角日志，自行添加黑名单
> 
> 想传送进去的时候会点锚点，传送怎么添加黑名单

传送没有黑名单，只能开关

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.32

新版本已经把新深渊的关键词加入自动拾取黑名单
