### ISSUE TITLE
[question] I have a language problem. Could you please write the tags in English for me? My translation is having issues.

### ISSUE THREAD

**Issue by trunghuyne** [babalae/better-genshin-impact#474]
I have a language problem. Could you please write the tags in English for me? My translation is having issues.
thanks 

![image](https://github.com/babalae/better-genshin-impact/assets/119916277/dec6d6a5-7f81-4218-b92f-9b5a9387f6d3)

**Comment by wy3057** [comment]
1 Mona /  Sucrose /  Jean  
2 Keqing   / Raiden Shogun  /Ganyu 
3 Raiden Shogun /Albedo /Lawachurls 
4 Chongyun /Raiden Shogun  /Shenhe 
5 Dehya / Baizhu /Fischl 
6 Fischl /Collei /Mona
7 Mona/ Baizhu/Fischl
8 Raiden Shogun  /Collei/Keqing （recommand）

**Comment by wy3057** [comment]
If you need a translation for the surprise deck, please let me know.I'd love to help you.

**Comment by trunghuyne** [comment]
> If you need a translation for the surprise deck, please let me know.I'd love to help you.

I don't think it's necessary. Using Team 8's recommendation is good enough. Just need to get the primogems. Thank you very much.
