### ISSUE TITLE
[bug] 七圣召唤我方角色若在回合结束阶段死亡则会卡在切换角色处

### ISSUE THREAD

**Issue by Tsuk1ko** [babalae/better-genshin-impact#475]
- 系统环境 / System Environment：Win10

- BetterGI版本号 / BetterGI Version：0.31.1

- 问题描述 / Description of the issue：当我方角色在回合结束阶段死亡（例如被敌方召唤物击杀），会卡在切换角色处，此时日志显示已经开始等待投骰

![image](https://github.com/babalae/better-genshin-impact/assets/24877906/a5d9e305-6713-4fd3-a82a-56743a29193f)

**Comment by huiyadanli** [comment]
什么卡组

**Comment by Tsuk1ko** [comment]
> 什么卡组

雷神柯莱刻晴

**Comment by Tsuk1ko** [comment]
但是感觉应该不属于这条情况？有点没理解🤔

![image](https://github.com/babalae/better-genshin-impact/assets/24877906/57bfe4ff-3b9e-4536-bc0c-3f09f6dc5f2f)

**Comment by huiyadanli** [comment]
超载死亡没有切人界面，下一个强制出场角色已经被指定，导致无法判断哪个角色被击败
