### ISSUE TITLE
[suggestion] 想要BetterZZZ

### ISSUE THREAD

**Issue by xiaocLoveYou** [babalae/better-genshin-impact#479]
想要更好的绝区零

**Comment by peach-water** [comment]
Better star rail都还没有呢

**Comment by Erosionone** [comment]
> Better star rail都还没有呢

星铁有个【三月七小助手】的项目

**Comment by linglongyoudoufu** [comment]
同求，只要每日任务求可以了

**Comment by Fightxing** [comment]
+1

**Comment by Deali-Axy** [comment]
找到了，[ZenlessZoneZero-OneDragon](https://github.com/DoctorReid/ZenlessZoneZero-OneDragon)，用着还行，有一些小bug，不过确实解放了生产力
