### ISSUE TITLE
开启软件会出现程序异常

### ISSUE THREAD

**Issue by geraltigas** [babalae/better-genshin-impact#48]
<img width="675" alt="Snipaste_2023-11-24_11-11-08" src="https://github.com/babalae/better-genshin-impact/assets/69190887/017da3f3-a9e7-4225-8b70-dd10758daf13">

**Comment by huiyadanli** [comment]
OCR预热报错，部分依靠OCR实现的功能会出现不可用的情况。

这个问题很难定位，因为是内部报错。大概率是系统依赖库有问题，但是不知道是少了哪个依赖。

**Comment by geraltigas** [comment]
点击启动后进一步的报错，无法正常使用。完整的log我没找到
![image](https://github.com/babalae/better-genshin-impact/assets/69190887/5dc50e78-bcf6-4e70-bbaf-b7d93149ff1a)

**Comment by huiyadanli** [comment]
![SXHZIT_HTHN5)%7TC}G4E0C_tmb](https://github.com/babalae/better-genshin-impact/assets/15783049/7ccafd61-4829-4fd2-9380-96054db7121b)


![F12H0Z7I(AY{4RB78LIPRXG](https://github.com/babalae/better-genshin-impact/assets/15783049/c153e25b-4e22-4d1d-a991-cbd21f193874)


类似报错

**Comment by huiyadanli** [comment]
使用最新版本看看报错提示：https://github.com/babalae/better-genshin-impact/releases/tag/0.16.0

**Comment by emako** [comment]
Win11SDK安排：
主页：https://developer.microsoft.com/ja-jp/windows/downloads/windows-sdk/
安装包：https://go.microsoft.com/fwlink/?linkid=2250105

**Comment by emako** [comment]
PADDLE2ONNX.DLL
API-MS-WIN-CRT-RUNTIME-L1-1-0.DLL
API-MS-WIN-CRT-STDIO-L1-1-0.DLL
API-MS-WIN-CRT-MATH-L1-1-0.DLL
API-MS-WIN-CRT-FILESYSTEM-L1-1-0.DLL
API-MS-WIN-CRT-STRING-L1-1-0.DLL
API-MS-WIN-CRT-CONVERT-L1-1-0.DLL
API-MS-WIN-CRT-HEAP-L1-1-0.DLL

ONNXRUNTIME.DLL
API-MS-WIN-CORE-FILE-L1-1-0.DLL
API-MS-WIN-CORE-ERRORHANDLING-L1-1-0.DLL
API-MS-WIN-CORE-STRING-L1-1-0.DLL
API-MS-WIN-CORE-PROCESSENVIRONMENT-L1-1-0.DLL
API-MS-WIN-CRT-RUNTIME-L1-1-0.DLL --duplicate
API-MS-WIN-CRT-STDIO-L1-1-0.DLL
API-MS-WIN-CRT-STRING-L1-1-0.DLL
API-MS-WIN-CRT-CONVERT-L1-1-0.DLL
API-MS-WIN-CRT-FILESYSTEM-L1-1-0.DLL
API-MS-WIN-CRT-HEAP-L1-1-0.DLL
API-MS-WIN-CORE-SYNCH-L1-2-0.DLL
API-MS-WIN-CORE-SYNCH-L1-1-0.DLL
API-MS-WIN-CORE-RTLSUPPORT-L1-1-0.DLL
API-MS-WIN-CORE-PROCESSTHREADS-L1-1-0.DLL
API-MS-WIN-CORE-PROCESSTHREADS-L1-1-1.DLL
API-MS-WIN-CORE-PROFILE-L1-1-0.DLL
API-MS-WIN-CORE-SYSINFO-L1-1-0.DLL
API-MS-WIN-CORE-INTERLOCKED-L1-1-0.DLL
API-MS-WIN-CORE-DEBUG-L1-1-0.DLL
API-MS-WIN-CORE-LIBRARYLOADER-L1-2-0.DLL  ---TBD
API-MS-WIN-CORE-HEAP-L1-1-0.DLL
API-MS-WIN-CORE-FILE-L1-2-0.DLL
API-MS-WIN-CORE-MEMORY-L1-1-0.DLL
API-MS-WIN-CORE-LOCALIZATION-L1-2-0.DLL
API-MS-WIN-CORE-HANDLE-L1-1-0.DLL
API-MS-WIN-CORE-PROCESSTOPOLOGY-L1-1-0.DLL ---TBD
API-MS-WIN-CORE-PATH-L1-1-0.DLL ---TBD
API-MS-WIN-EVENTING-PROVIDER-L1-1-0.DLL ---TBD
API-MS-WIN-CORE-SYSINFO-L1-2-0.DLL ---TBD
API-MS-WIN-CRT-TIME-L1-1-0.DLL
API-MS-WIN-CRT-LOCALE-L1-1-0.DLL
API-MS-WIN-CRT-MATH-L1-1-0.DLL
API-MS-WIN-CORE-HEAP-L2-1-0.DLL --TBD


ONNXRUNTIME_PROVIDERS_SHARED.DLL
API-MS-WIN-CRT-RUNTIME-L1-1-0.DLL --duplicate
API-MS-WIN-CORE-RTLSUPPORT-L1-1-0.DLL
API-MS-WIN-CORE-ERRORHANDLING-L1-1-0.DLL
API-MS-WIN-CORE-PROCESSTHREADS-L1-1-0.DLL
API-MS-WIN-CORE-PROCESSTHREADS-L1-1-1.DLL
API-MS-WIN-CORE-PROFILE-L1-1-0.DLL
API-MS-WIN-CORE-SYSINFO-L1-1-0.DLL
API-MS-WIN-CORE-LIBRARYLOADER-L1-2-0.DLL --TBD
API-MS-WIN-CORE-INTERLOCKED-L1-1-0.DLL
API-MS-WIN-CORE-DEBUG-L1-1-0.DLL

**Comment by huiyadanli** [comment]
以 https://github.com/babalae/better-genshin-impact/issues/132 为准。

且报错信息已经优化了，可以抛出更加多的数据
