### ISSUE TITLE
[question] 自动拾取等功能用不了，求助

### ISSUE THREAD

**Issue by 0cider0** [babalae/better-genshin-impact#480]
自动剧情用着很好，但其他功能（自动拾取，自动钓鱼，七圣召唤）都没反应
七圣召唤能识别到对局进行到哪一步了，但不会自动对战
有试过重装老版本，加入火绒白名单，关闭火绒
![1](https://github.com/babalae/better-genshin-impact/assets/175230217/fb004c10-450e-42c6-b7bd-6a2bde0e6768)

**Comment by huiyadanli** [comment]
窗体大小我看截图是 `16:9`的，但是你的窗口内两边有黑边，导致游戏画面并不是 `16:9`，所以功能无法正常使用

**Comment by 0cider0** [comment]
太感谢了！玩这么久居然都没注意到有黑边
