### ISSUE TITLE
解决MaskWindow提前实例化产生的各种问题

### ISSUE THREAD

**Issue by huiyadanli** [babalae/better-genshin-impact#481]
核心卡点：

https://github.com/babalae/better-genshin-impact/blob/98d7ebd217874e6925f4d9c3831c9404fb990c22/BetterGenshinImpact/App.xaml.cs#L48-L59

**Comment by emako** [comment]
https://www.nuget.org/packages/Serilog.Sinks.RichTextBoxEx.Wpf

**Comment by emako** [comment]
ed20c8b

**Comment by emako** [comment]
存在这种问题，MaskWindow不在的时候的log就看不见了，因为RichTextBox控件不存在所以被忽略。
![image](https://github.com/user-attachments/assets/78829767-a476-4763-a7ac-86ef68dc17b0)

**Comment by emako** [comment]
待你把MaskWindow的单例模式去掉就能先用起来了

**Comment by huiyadanli** [comment]
> 存在这种问题，MaskWindow不在的时候的log就看不见了，因为RichTextBox控件不存在所以被忽略。 ![image](https://private-user-images.githubusercontent.com/24737061/348366564-78829767-a476-4763-a7ac-86ef68dc17b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MzEwMTUsIm5iZiI6MTcyMDgzMDcxNSwicGF0aCI6Ii8yNDczNzA2MS8zNDgzNjY1NjQtNzg4Mjk3NjctYTQ3Ni00NzYzLWE3YWMtODZlZjY4ZGMxN2IwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDAwMzE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MTYwOWM1MGFhM2NkMjNmNzg3Yzk0NzA5MWVlZWFmNTg0MWUwNDc1MGFjMWU5NzcxNWE1NzhlMTQ2M2MzMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hWvU_P7pE5n7vjTcFvTpse72P-4mZ4q2bWB1-tkWiXo)

这种情况是在预期内的，完全可以接受的

**Comment by huiyadanli** [comment]
可以用了
