### ISSUE TITLE
[suggestion] 希望能有安卓平台的BetterGI

### ISSUE THREAD

**Issue by Amb114** [babalae/better-genshin-impact#482]
- Your suggestions / 你的建议
有时候用电脑不方便，我就用手机/平板玩原神（自从原神出极高渲染精度，平板画质能看了），有时候我身边人也会用手机/平板玩原神，如果能移植安卓应该能让这个程序普及程度增加很多，只是不知道难不难实现

**Comment by huiyadanli** [comment]
不会移动端，不考虑

**Comment by Alex-Beng** [comment]
附议，ipad画质也相当好了
