### ISSUE TITLE
[suggestion] 可以弄一个自动锄地吗

### ISSUE THREAD

**Issue by 1049731887** [babalae/better-genshin-impact#483]
- Your suggestions / 你的建议

自动大世界拾取材料，大概只需要根据地图识别结果播放按键操作即可，可能需要检测攀爬和游泳状态

自动大世界打怪，遇到怪自动开启战斗模式，自动转圈圈拾取

**Comment by 1049731887** [comment]
别人的方案是录制寻路脚本，到达目的地触发自动战斗，战斗完成后蚊香型走动捡东西。
如果是捡材料的话，那就简单。
按现在的社区规模来看，应该会有很多人制作脚本的

**Comment by huiyadanli** [comment]
bgi.sh

已经逐步添加锄地脚本
