### ISSUE TITLE
水龙转圈圈4.8改动后使用问题

### ISSUE THREAD

**Issue by Erosionone** [babalae/better-genshin-impact#484]
目前是ban了360度转圈圈，但面前的小角度摇摆不受影响，有人说180是+-90°。但是转到90°之前似乎往回转就能再+90°。也就是说90°-1°循环是可以达到全屏 aoe的效果的，希望能测试一下能不能行。

**Comment by huiyadanli** [comment]
可以先尝试下用手操能不能实现

**Comment by Erosionone** [comment]
> 可以先尝试下用手操能不能实现

水龙0.4秒出一次伤害，也就是0.4秒要转一圈，快了慢了都丢伤害，手操做不到的

**Comment by goldenapple1** [comment]
我这边不知道什么原因在使用这个功能的时候出现了很严重的掉帧，掉帧之后水龙晃动的角度比手操的更小，目前的默认鼠标移动距离应该需要大幅下调，或者可能是移动间隔为0导致的？

**Comment by huiyadanli** [comment]
> 我这边不知道什么原因在使用这个功能的时候出现了很严重的掉帧，掉帧之后水龙晃动的角度比手操的更小，目前的默认鼠标移动距离应该需要大幅下调，或者可能是移动间隔为0导致的？

时间间隔调整为0就会卡了

**Comment by Erosionone** [comment]
改动退回了
