### ISSUE TITLE
[bug] 4.8 龙王回退后用转圈功能会卡住，松开按键后才开转

### ISSUE THREAD

**Issue by htshts1115** [babalae/better-genshin-impact#489]
- 系统环境 / System Environment：
win10

- BetterGI版本号 / BetterGI Version：
最新版

- 问题描述 / Description of the issue：
4.7一切正常，4.8龙王转圈回退后测试，按住转圈键画面整个卡住，松开后会转一小段时间

- 复现步骤 / Reproduction steps：
如上

**Comment by huiyadanli** [comment]
![image](https://github.com/user-attachments/assets/47bd7d9a-ac32-4b56-a2fe-736915422b40)

自行尝试调大时间间隔，缩小移动距离

**Comment by htshts1115** [comment]
感谢！调成图中的500,10 可以正常转圈了
