### ISSUE TITLE
那维莱特跟新修复后，无法使用一键转圈[bug] 

### ISSUE THREAD

**Issue by enlia** [babalae/better-genshin-impact#493]
- 系统环境 / System Environment：
win11 5600G 4070

- BetterGI版本号 / BetterGI Version：
0.31.1

- 问题描述 / Description of the issue：
原神修改龙王转圈后，【我删除了原神】，然后官方恢复原样，我又【下载回来了】。【网络环境从有线切换为了无线】但这时我使用一键转圈，画面会卡住不动，当松开按键后，画面会突然快速旋转，将期间所有的操作都进行一遍。【看起来和卡了一摸一样，但我玩老头环啊什么的都不卡】

- 复现步骤 / Reproduction steps：
龙王那维莱特，一键转圈

**Comment by enlia** [comment]
期间我调整了各种画质，拉到最低也会画面卡住

**Comment by huiyadanli** [comment]
调整时间间隔，参考： https://github.com/babalae/better-genshin-impact/issues/489
