### ISSUE TITLE
[bug] b服登录页面更新，自动伐木失败

### ISSUE THREAD

**Issue by jhll1124** [babalae/better-genshin-impact#495]
- 系统环境 / System Environment：
Windows 11 专业版23H2 22631.3880

- BetterGI版本号 / BetterGI Version：
0.31.1

- 问题描述 / Description of the issue：
b服登录页面更新，添加验证码登录功能，导致登录按钮位置改变，自动伐木点击登录按钮失败

- 复现步骤 / Reproduction steps：
登录游戏/使用自动伐木

**Comment by emako** [comment]
有截图吗?

**Comment by jhll1124** [comment]
![%pn_1721712538_3840x2160](https://github.com/user-attachments/assets/9ee113e7-106b-4c03-82c3-af42ed43bba8)

**Comment by WoshiRedstone** [comment]
> e

b服的登陆器是一个独立的窗口，不会被捕获，可能无法解决了

**Comment by emako** [comment]
https://ci.appveyor.com/project/huiyadanli/better-genshin-impact/builds/50341635
