### ISSUE TITLE
为启动游戏加入解锁帧率和无边框窗口选项

### ISSUE THREAD

**Issue by Andrea-lyz** [babalae/better-genshin-impact#50]
如标题

**Comment by huiyadanli** [comment]
1. 解锁帧率请使用其他软件，我这边不会添加

2. 无边框窗口启动后面会加

**Comment by katsusan** [comment]
原神默认客户端不已经可以无边框窗口了吗，偶尔出现边框alt+enter就能去掉了

**Comment by emako** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/24737061/39be93ef-b041-4606-bd46-c74db1011bf5)
推广一波https://github.com/GenshinMatrix/Fischless

**Comment by huiyadanli** [comment]
我推荐的！
