### ISSUE TITLE
[bug] 那维莱特转圈导致游戏卡死

### ISSUE THREAD

**Issue by Daydreamer114** [babalae/better-genshin-impact#500]
- 系统环境 / System Environment：
Windows11

- BetterGI版本号 / BetterGI Version：
0.31.1

- 问题描述 / Description of the issue：
我将”长按旋转视角 - 那维莱特转圈“的快捷键设置为了Numpad0，在游戏中按下Num0后原神完全卡死（包括游戏内置计时器），松开后屏幕进行旋转并渐慢，数圈后恢复正常

- 复现步骤 / Reproduction steps：
同问题描述

**Comment by Daydreamer114** [comment]
或许可以调整转圈速度？

**Comment by huiyadanli** [comment]
调整时间间隔，参考： https://github.com/babalae/better-genshin-impact/issues/489

**Comment by Daydreamer114** [comment]
> 调整时间间隔，参考： #489

感谢，实测提到1ms就能用
