### ISSUE TITLE
[suggestion] 录制回放功能没有停止按钮吗

### ISSUE THREAD

**Issue by Aqua-Dream** [babalae/better-genshin-impact#501]
- Your suggestions / 你的建议

开始录制和停止录制都有快捷键（同一个），但是回放脚本和停止回放都没有，特别是似乎**没有停止回放的功能**。因为录制的脚本不准，很可能需要多次重新录制测试（比如我的第一个脚本直接就出问题了），如果不能停止会很麻烦（特别是切出游戏都没办法停止！）

**Comment by Aqua-Dream** [comment]
补充一点，开始录制的倒计时3s过程中，如果按停止录制，也会出现一些bug，比如虽然录制停止了，但是还显示倒计时，以及打开地图界面还是显示检测相对位置之类的

![image](https://github.com/user-attachments/assets/42771c7c-296b-4930-adca-98e9d001a921)

**Comment by peach-water** [comment]
再加一条，已经开始执行的脚本也没有停止或取消按钮。
关闭BetterGI后仍然执行脚本，必须要退出才行。

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.32 
0.32.1 已经修复上述问题，并添加了停止任务的快捷键配置
