### ISSUE TITLE
[suggestion] 快捷键支持组合键

### ISSUE THREAD

**Issue by Aqua-Dream** [babalae/better-genshin-impact#502]
- Your suggestions / 你的建议
目前快捷键设置只能输入一个键，不支持ctrl,shift,alt之类的组合键。由于BetterGI功能越来越多，快捷键设置又必须跟游戏内置快捷键区分，现在可用的键越来越少了。希望**快捷键支持组合键**。

**Comment by huiyadanli** [comment]
请使用全局热键
