### ISSUE TITLE
[suggestion] 建议加一个快速队伍切换的功能

### ISSUE THREAD

**Issue by cooper1x** [babalae/better-genshin-impact#504]
- Your suggestions / 你的建议

我有好多个队伍，每次切换都要点好多次。我有的队伍是专门用来加好感度的，因此切换非常频繁。每次切换了还要启用，太繁琐了。席位能够有一件的脚本可以快速切换。

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/commit/4cb54421619440f112973062410507d2b7bd833b

#670

**Comment by cooper1x** [comment]
目前脚本可以两个队伍来回切，大部分情况下够用了。
但偶尔也会切换到第三个第四个队伍，比方说抓晶蝶，就带钟离瑶瑶这样的配队；比方说做任务纯跑路，就会带上夜兰闲云这样的。
如果可以的话，看看能不能加入更多指定队伍的切换呢，只是感觉这个快捷键会变多。
如果辅助可以加一个类似游戏里面的轮盘呼出，或者有一个全局菜单快速选中，这个交互是不是会更加方便呢。
大佬可以考虑下哈。

**Comment by huiyadanli** [comment]
这个就是指定队伍切换的功能，后续关注 #680
