### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by echo-125** [babalae/better-genshin-impact#505]
- 系统环境 / System Environment：Win11 23H2

- BetterGI版本号 / BetterGI Version：0.32.0

- 问题描述 / Description of the issue：打开后窗口左下角无法显示日志，自动拾取能用，自动烹饪自动钓鱼不生效 (报错信息如图)

- 复现步骤 / Reproduction steps：

![bug](https://github.com/user-attachments/assets/7942dfae-2fd7-42a6-9b31-2c2c322fdc47)

**Comment by huiyadanli** [comment]
重启软件呢？

**Comment by echo-125** [comment]
重启软件之后能显示日志UI，但是自动拾取和自动钓鱼等功能都失效了。
尝试过：1、重装.net8环境。2、切换截图模式。3、以管理员方式启动。4、切换AI推理设备。均无法解决问题
图一：故障截图
![bug1](https://github.com/user-attachments/assets/b316f0c9-9ca5-40d2-a7cb-b217e27d3165)
图二：测试图像捕捉黑屏，日志文件中无报错内容
![bug2](https://github.com/user-attachments/assets/892c0824-b887-45b5-83e4-3e178a76c36b)

**Comment by huiyadanli** [comment]
图像捕捉黑屏那是另外一个问题了，换WGC的方式或者#92

**Comment by echo-125** [comment]
#92 可用
