### ISSUE TITLE
[suggestion] 鼠标监听，鼠标中建触发龙王转圈

### ISSUE THREAD

**Issue by NOWorEVER** [babalae/better-genshin-impact#506]
- Your suggestions / 你的建议

鼠标监听，鼠标中建触发龙王转圈
![image](https://github.com/user-attachments/assets/74ab93e8-3d44-4e49-9efa-1cb65e494f71)

**Comment by emako** [comment]
中键不是归正视角？

**Comment by NOWorEVER** [comment]
哦，人傻了，发现鼠标上有键盘快捷键。

**Comment by huiyadanli** [comment]
难怪我特意排除了中键
