### ISSUE TITLE
[bug] 预热失败

### ISSUE THREAD

**Issue by Swevenink** [babalae/better-genshin-impact#510]
- 系统环境 / System Environment：Windows10

- BetterGI版本号 / BetterGI Version：0.31.1

- 问题描述 / Description of the issue：预热失败
<img width="346" alt="屏幕截图 2024-08-06 125644" src="https://github.com/user-attachments/assets/29fe0688-4330-4e4a-80e9-9e7bae29d1e9">

- 复现步骤 / Reproduction steps：

**Comment by huiyadanli** [comment]
https://bgi.huiyadan.com/faq.html#%E2%9D%93%E6%8F%90%E7%A4%BA-paddleocr%E9%A2%84%E7%83%AD%E5%A4%B1%E8%B4%A5-%E5%BA%94%E8%AF%A5%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3
