### ISSUE TITLE
[bug] 很小概率出现整个系统卡几秒然后崩溃

### ISSUE THREAD

**Issue by Amb114** [babalae/better-genshin-impact#513]
- 系统环境 / System Environment：
OS：Microsoft Windows [版本 10.0.22631.3672] Win11 23H2 专业工作站版
CPU：R7 7840H；GPU：RadeonT 780M；RAM：32G LPDDDR5X 6400MHz

- BetterGI版本号 / BetterGI Version：
0.32.1（一直用的便捷版，每次更新的时候把文件粘贴过去+替换）

- 问题描述 / Description of the issue：
BetterGI截图器运行时，原神切页面有可能导致鼠标突然卡成3帧，我按Alt+Tab准备切到BetterGI点停止试试，结果发现整个系统都在卡，然后BetterGI就崩溃了（无杀软）

- 复现步骤 / Reproduction steps：
启动BetterGI，原神传送、开设置、开任务、进门我都遇到过，看运气，也不知道怎么搞的，任务管理器性能页正常
BetterGI好像只有左下角显示的那些日志，没有这种诊断日志，应该试着加进去
我BetterGI截图设置的是WGC，30毫秒，关位图缓存，GPU

**Comment by huiyadanli** [comment]
可以从事件管理器查看崩溃原因，我猜测和WGC有关。

**Comment by Amb114** [comment]
我最近BetterGI在前台的时候又卡了一次，卡的时候点主窗体没反应，也不会提示未响应
我还发现测试图像捕获5-10个一起开的时候，System和DWM都各吃了我核显10%GPU，而且有相同的卡顿效果但不会崩溃，窗口动画是流畅的别的3帧

**Comment by Amb114** [comment]
我GPU不太行，WGC开位图缓存老点黑屏，关位图缓存好像比bit慢，还是改用bit了罢
而且我自动拾取没有文档那么快，跑过树莓只捡一个或者不捡，延迟1秒左右
还有的时候上面（F右边）是东西下面是对话，结果也对话了，不知道别人有没这问题（检测到东西就会连续按F？）

**Comment by huiyadanli** [comment]
直接使用BitBlt即可，拾取的速度和电脑性能和触发器间隔有关。

上面东西下面对话出现误触是正常现象。一般是获取截图延迟较长导致的
