### ISSUE TITLE
[suggestion] 浮窗视频

### ISSUE THREAD

**Issue by pansong291** [babalae/better-genshin-impact#518]
- Your suggestions / 你的建议

我知道 Chrome 有个插件可以，但是它只能 Chrome 使用，Edge 无效，电脑上已经有个 Edge 了，不想再安装一个浏览器，浏览器都是相当臃肿的。然而 Edge 的我目前是配合 AutoHotKey 去控制，但还是有些不太方便，而且有时候会有 Bug，切换暂停时会自动退出小窗，估计是 Edge 的问题。还有就是妈宝这个软件里的沉浸模式挺不错，但是它不能改变鼠标移入浮窗区时的透明度。不知道这个项目能不能整合一下这个功能，跟跑刚需，小窗整合浏览器也好，视频播放器也好。

**Comment by huiyadanli** [comment]
后面不是还要加 video 2 path么，可能不仅能看。。。还能自动跟着跑

**Comment by emako** [comment]
> 后面不是还要加 video 2 path么，可能不仅能看。。。还能自动跟着跑

这太久远了

**Comment by pansong291** [comment]
> 后面不是还要加 video 2 path么，可能不仅能看。。。还能自动跟着跑

自动跟跑感觉不可靠，比如捡一个风种子，释放风技能再飞过高墙，这应该很难跟上视频的操作，还是手动比较妥当，建议提高这个事项的优先级。

**Comment by emako** [comment]
思路：
创建窗口要求输入AV号，用外链播放视频（不过外链只支持480P好像），游戏里Alt+Space/Alt+左右转发Space/左右到阿B

**Comment by pansong291** [comment]
> 思路： 创建窗口要求输入AV号，用外链播放视频（不过外链只支持480P好像），游戏里Alt+Space/Alt+左右转发Space/左右到阿B

小窗看 360P 都足够啦，而且那只是未登录时的限制。如果是调用浏览器，可以顺便往网页里注入一些 js 代码，去除未登录时的弹窗，这个是因为未登录的时候播放几分钟就会跳出这个弹窗。如果是内置视频播放器，在线解析视频也是不错的。透明度调整、鼠标穿透等功能可以慢慢迭代。

**Comment by huiyadanli** [comment]
> 思路： 创建窗口要求输入AV号，用外链播放视频（不过外链只支持480P好像），游戏里Alt+Space/Alt+左右转发Space/左右到阿B

直接浏览器访问，自己爱咋用咋用就行了，可以登录的。加个快捷键控制就行

**Comment by bananas12138** [comment]
这样对低配电脑恐怕会不太友好，不过也是一个可以新增的功能
