### ISSUE TITLE
[suggestion] 日志区的文字看不太清楚，建议设置背景

### ISSUE THREAD

**Issue by pansong291** [babalae/better-genshin-impact#519]
- Your suggestions / 你的建议

建议给文字设置阴影；或者给整个日志区设置灰色透明背景，类似游戏里的聊天框。

**Comment by huiyadanli** [comment]
日志内容也不重要吧

**Comment by pansong291** [comment]
「东南西北」这四个字是纯白色的，建议加阴影或者描边。

**Comment by emako** [comment]
日志加个背景开关把

**Comment by pansong291** [comment]
「东南西北」这四个字是纯白色的，转动视角有时会跟天空中的白云重合导致完全看不见文字。
