### ISSUE TITLE
[bug?] 内存使用异常

### ISSUE THREAD

**Issue by goldenapple1** [babalae/better-genshin-impact#52]
1. 我使用的是最新版本软件的提竿，但我发现从我第一次下饵，鱼咬钩之后我的电脑内存使用率就开始显著增加，到了95%左右游戏已经开始掉帧。于是我打开任务管理器，发现我钓到鱼之后这个软件的识别功能好像还开着并且内存申请的速度很快，在1G/s左右，我钓上两三条鱼之后内存就能到11000MB左右的占用

![image](https://github.com/babalae/better-genshin-impact/assets/56142186/4a7f61bb-580c-4dee-af86-a1ddcb321944)
上图是钓上两条花鳉之后的内存占用，如果这个提竿的时间花费更多很容易就会到我说的11000MB内存占用

可能帮助到你的信息：目前我是两块1440p的屏幕，不知道这个会不会对图像识别有影响

2. 还有一个也不清楚是不是bug，在启动识别之后快捷键会变成下图这样：
![image](https://github.com/babalae/better-genshin-impact/assets/56142186/64704969-27b9-4ecc-bf11-1f654a9d382f)

**Comment by huiyadanli** [comment]
1 有内存泄露问题，暂时无法定位，重启多试几次试试，你的反馈很重要
2 是已知bug

**Comment by goldenapple1** [comment]
emm，我猜测1的内存泄露是不是缓存的识别的图像没删干净啊，我刚刚调低了帧率，明显能感觉到内存申请的速度变慢了，30帧相较于60帧内存增长的速度慢了一些，我现在大概是钓完4到5条鱼才会开始掉帧

**Comment by huiyadanli** [comment]
这个是最大概率，但是我排查了半天没看出问题来。。

强制GC的情况下不会持续增长。。。你内存是不是很大？

**Comment by goldenapple1** [comment]
32G内存

**Comment by goldenapple1** [comment]
更细一点我感觉可能是垃圾回收的条件判断出了问题？据我浅薄的知识判断内存泄露往往是对象/数据没有正确析构，而且内存泄露往往是不断增长的。但是，我在收竿之后程序确实回到了它应该占用的内存大小，所以我猜测可能是垃圾回收的条件有问题？

**Comment by huiyadanli** [comment]
是的，跟CLR有关，实在不行手动定时GC一次（dirty code）:joy:

**Comment by goldenapple1** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/56142186/0abf5c8b-e356-4531-bac1-9330eef75e2b)
还有一个就是，好像收竿过程结束很久了但它还在识别收竿条？

**Comment by FangDingli** [comment]
因为发现自己也有这个内存泄漏问题所以花了点时间关注了一下，希望可以提供一点帮助
仅打开了自动剧情功能
一开始没关注内存占用，过了几次对话后打开任务管理器发现内存占用在 5k+ MB
关闭软件重开，点击启动后完全不移动游戏视角，内存占用以 5-10M / S 的速度增长，到800+的时候停止。
晃动游戏视角后马上开始继续增长，持续到 1400+
继续晃动视角继续增长，但是持续时间比较短，比如从1600+到1700+
按下攻击键，角色所在位置发生变化后又开始一直增长，没发现停下来的迹象，等不下去了。在此期间我又发现如果我切换到别的窗口他会马上停止增长

下图为插件启动时间 00:54:59 到截图时间 01:09:28 为止的内存占用图

![QQ截图20231125010928](https://github.com/babalae/better-genshin-impact/assets/45346648/4f588d06-5792-4e0b-b9d7-c64f693f816b)

**Comment by huiyadanli** [comment]
> ![image](https://user-images.githubusercontent.com/56142186/285399897-0abf5c8b-e356-4531-bac1-9330eef75e2b.png) 还有一个就是，好像收竿过程结束很久了但它还在识别收竿条？

不是收杆条，是钓鱼进度条选区，故意放在那的

**Comment by FangDingli** [comment]
咦发完刚那条回复以后回头看发现内存占用又正常了。。。

**Comment by huiyadanli** [comment]
> 咦发完刚那条回复以后回头看发现内存占用又正常了。。。

因为会随着时间推移有周期性的做垃圾回收。。如果泄露的话，得用挺久直到内存回收不掉为准。。

**Comment by FangDingli** [comment]
> > 咦发完刚那条回复以后回头看发现内存占用又正常了。。。
> 
> 因为会随着时间推移有周期性的做垃圾回收。。如果泄露的话，得用挺久直到内存回收不掉为准。。

emmm  持续用了一会内存依然飙到5k+ 而且还会继续往上，期间确实发现有回收的迹象但赶不上增长的速度。切到别的窗口一会后发现恢复正常。是不是内存比较大会发生这种现象。。  我48G

**Comment by goldenapple1** [comment]
> 因为会随着时间推移有周期性的做垃圾回收。。如果泄露的话，得用挺久直到内存回收不掉为准。。

今天刚下载了项目的所有代码，因为我对C#了解不多，但是知道C++和Python，所以大致扫了一下整个项目，目前怀疑对像是TaskTriggerDispatcher.cs文件里的Tick函数

一开始我的怀疑点就集中在GC相关的代码上，于是我在VSCode里用GC作为关键词搜索，查看了很多结果，看起来和GC机制相关的就是WinRT.cs的ResurrectObjectReference函数下105行的GC.ReRegisterForFinalize(objRef);和TaskTriggerDispatcher.cs文件里的Tick函数的225行注释掉的GC.Collect();

而WinRT.cs这个文件位于Fischless.GameCapture下，就命名猜测可能是游戏截图抓取相关的，截图方面的上层包装，加上这个函数似乎并没有被引用，所以我把目光投向了另一个结果。

大致看了一下前面的几个if检查和注释，感觉这段可能不是问题来源，但是让我提高怀疑的是这个注释：“帧序号自增 1分钟后归零(MaxFrameIndexSecond)”这个看起来很符合目前程序的行为，在停止钓鱼但是仍然在钓鱼界面之后的一分钟才主动释放内存。

而且这个也符合楼上另一位说的在自动剧情的时候遇到的问题，因为我猜测这个TaskTriggerDispatcher可能是目前所有图像识别的功能的基础，依据是在GameTaskManager.cs下的24-30行的一个字典。

```
            TriggerDictionary = new Dictionary<string, ITaskTrigger>()
            {
                { "RecognitionTest", new TestTrigger() },
                { "AutoPick", new AutoPick.AutoPickTrigger() },
                { "AutoSkip", new AutoSkip.AutoSkipTrigger() },
                { "AutoFishing", new AutoFishing.AutoFishingTrigger() }
            };
```

这个字典应该相当明显的表示出了功能之间的对应关系，这个TestTrigger应该是管识别测试的，TaskTriggerDispatcher可能是管TestTrigger的调度的，调度出了问题那么就能解释为什么自动钓鱼和自动剧情都有内存管理问题。

当然因为我不是项目的作者，我仅凭几十分钟的推理和猜测可能产生错误，所以以上推理结果主要还是起一个参考作用，而且我不会C#不能直接帮你把这个bug修了。

**Comment by goldenapple1** [comment]
不行，我今天打开游戏发现这个软件即使我没使用它的什么功能，它自己的内存和CPU占用也可能跑到很高，我觉得要不先调低这个GC的周期，或者把GC设计成达到一定内存占用就开始回收吧，这个代码我还是建议调整成手动删除内存，否则可能很难彻底摆脱这个内存管理问题

**Comment by emako** [comment]
主动GC还是有必要的，现在基本都上32G了

**Comment by goldenapple1** [comment]
可能现阶段调小周期确实是最优解了，但是我觉得还是得让这个内存稳定一点，总是假设用户内存足够也不太现实

**Comment by goldenapple1** [comment]
目前在 #131 下似乎解决了，暂时关闭问题
