### ISSUE TITLE
[bug] 柽木伐木识别失败

### ISSUE THREAD

**Issue by Alahjarko** [babalae/better-genshin-impact#521]
- 系统环境 / System Environment：

win11
- BetterGI版本号 / BetterGI Version：

0.32.1
- 问题描述 / Description of the issue：
使用自动砍伐功能去往说明文档给出的须弥区域柽木点位去砍伐柽木时会出现无法识别的情况。实际上已经砍伐成功
![image](https://github.com/user-attachments/assets/cc074388-ca95-4bef-92a2-d219f394ffca)

- 复现步骤 / Reproduction steps：

按照文档中的点位去往相应伐木点即可触发

**Comment by huiyadanli** [comment]
参考 #444
