### ISSUE TITLE
[suggestion] 能否在键鼠回放的时候，启动自动拾取。

### ISSUE THREAD

**Issue by 1357214904** [babalae/better-genshin-impact#526]
- Your suggestions / 你的建议

这样的话，我只需要录制路线，就可以采花，抓晶蝶。
最好是做一个开关，是否在录制的时候，启动自动拾取。

**Comment by huiyadanli** [comment]
这些内容未来会在JS脚本上实现，这一点是确定的，并且当前版本已经实现（未发布），比如自动晶蝶的脚本

是否在录制回放功能上提供这个功能还有待商榷。

**Comment by huiyadanli** [comment]
js 脚本已经实现

**Comment by huiyadanli** [comment]
@luguoyixiazi 很好的想法，你可以自行尝试。

另外，晶蝶点位较远的情况下传送过去基本在几个固定点位

队伍中有早柚/瑶瑶的情况下，成功率很高
