### ISSUE TITLE
[suggestion]  自动剧情选择选项增加仅单个选项自动选择

### ISSUE THREAD

**Issue by pansong291** [babalae/better-genshin-impact#527]
- Your suggestions / 你的建议

1. 目前的选项有「优先第一个」、「优先最后一个」、「随机」、「不选择」。
    希望增加「仅单个选项时」。理由是一些特殊任务场景不能随意做选择，比如「来自冬天的故事」、「说到做到」。

2. 目前我设置为「不选择」，同时开启「自动领取每日委托」，这时去凯瑟琳那不会选任何选项（有橙色选项），这个不知道是优先级问题还是 bug？

3. 自动邀约也可以增加「仅单个选项时」，目前的分支识别成功率有点感人，还是希望能自己手动选择。例如有些邀约任务需要先回答几个问题，全答对会进一个分支，答错了会进其他分支。

**Comment by huiyadanli** [comment]
仅单个选项的场景比较少吧，特殊文字不做选择可以依靠自动剧情选择的黑白名单
