### ISSUE TITLE
拾取按键更改

### ISSUE THREAD

**Issue by TheWind01** [babalae/better-genshin-impact#53]
希望可以添加一个更改默认拾取F键为其他自定义按键的功能

**Comment by huiyadanli** [comment]
目前得到的需求都是修改成E键

**Comment by lye030** [comment]
希望可以添加一个默认更改拾取F键作为其他自定义按钮的功能

**Comment by bai1996** [comment]
我这，，手柄玩家算是废了。。。

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.31.0
