### ISSUE TITLE
[feature] 一键获取抽卡分析链接地址（到剪贴板）

### ISSUE THREAD

**Issue by Pleasurecruise** [babalae/better-genshin-impact#532]
- Your feature requesting / 你的新功能请求

隔壁三月七助手里看到的有这个功能，觉得挺实用的，实现起来应该不难吧......

**Comment by emako** [comment]
复制的链接有什么用处吗？
第三方工具都是直接读完生成表格了

**Comment by huiyadanli** [comment]
不难，但是必要性有待商榷。

和 BettrGI 的功能方向不太相同

**Comment by huiyadanli** [comment]
短时间内不考虑加入，视后续开发方向而定
