### ISSUE TITLE
[bug] 独立任务自动秘境角色会自己跳崖

### ISSUE THREAD

**Issue by icecream8086** [babalae/better-genshin-impact#533]
- 系统环境 / System Environment：

  版本	Windows 10 教育版
  版本号	22H2
  安装日期	‎8/‎4/‎2021
  操作系统内部版本	19045.4780
  体验	Windows Feature Experience Pack 1000.19060.1000.0

- BetterGI版本号 / BetterGI Version：
   0.32.10

- 问题描述 / Description of the issue：
 当自动秘境打完怪物后，摄像机镜头旋转尝试寻找石化古树，找一半会向左跑，跳崖后摔回起点，然后回向右跑不停地循环摔下去的过程，尝试了绝缘本等诸多版本，无一成功寻路
。
- 复现步骤 / Reproduction steps：
 自动秘境打完后触发

**Comment by huiyadanli** [comment]
没识别到古树就会这样的。你是开了GPU推理吧

**Comment by icecream8086** [comment]
> 没识别到古树就会这样的。你是开了GPU推理吧

确实开了GPU推理，等会关了试试看

**Comment by icecream8086** [comment]
> 没识别到古树就会这样的。你是开了GPU推理吧

没效果，分别测试了绝缘本和仆人本，都会掉下去

**Comment by huiyadanli** [comment]
关闭以后需要重启软件，如果还是不行证明ONNX无法在你的电脑上正常运行

**Comment by icecream8086** [comment]
> 关闭以后需要重启软件，如果还是不行证明 ONNX 无法在你的电脑上正常运行。
> 
> 同时可以通过把自动拾取的识别引擎换成 Yap 来测试 ONNX 是否正常运行

谢谢，下午试试看

**Comment by icecream8086** [comment]
> 关闭以后需要重启软件，如果还是不行证明 ONNX 无法在你的电脑上正常运行。
> 
> 同时可以通过把自动拾取的识别引擎换成 Yap 来测试 ONNX 是否正常运行

Paddle和yap引擎都可以正确工作，摄像机可以转到正确的角度，但是角色会毫不犹豫地向左转，然和掉下去，刷回重生点后向右转，然后跳下去重复这一过程，重启过程序也分别尝试了cpu和gpu，自动拾取功能正常，进本也能正常寻路，打完了开始出问题了。

**Comment by icecream8086** [comment]
> 关闭以后需要重启软件，如果还是不行证明 ONNX 无法在你的电脑上正常运行。
> 
> 同时可以通过把自动拾取的识别引擎换成 Yap 来测试 ONNX 是否正常运行

修好了，问题来源是截图模式
WindowsGraphicCapture可正常使用，我一开始使用的是DwmGetDxSharedSurface
DwmGetDxSharedSurface好像无法自动打本，其他的正常，可能是bug
