### ISSUE TITLE
那维莱特转圈太慢了

### ISSUE THREAD

**Issue by zhubibaba** [babalae/better-genshin-impact#54]
如题，转太慢了丢伤害，怎么调能转快点

**Comment by huiyadanli** [comment]
这应该算快的吧。。。

**Comment by SoYeonQwQ** [comment]
那维莱特伤害是0.4s一判，0.4秒一圈就行了

**Comment by zhubibaba** [comment]
> 这应该算快的吧。。。

大概只有0.78s一圈，那维莱特0.4s要快一倍

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.16.0
