### ISSUE TITLE
[bug] 每次都報錯

### ISSUE THREAD

**Issue by 321999c** [babalae/better-genshin-impact#545]
- 系统环境 / System Environment：
- 
![螢幕擷取畫面 2024-08-23 055553](https://github.com/user-attachments/assets/c7e8d701-c530-42ad-99b3-68c9a6853536)
windows11 23H2 (OS組建22631.4037)

- BetterGI版本号 / BetterGI Version：
- 0.33

- 问题描述 / Description of the issue：
PaddleOcr預熱失敗: Sdcb.Paddlelnference 

- 复现步骤 / Reproduction steps：
- 按開BetterGI

**Comment by huiyadanli** [comment]
https://bgi.huiyadan.com/faq.html#%E2%9D%93%E6%8F%90%E7%A4%BA-paddleocr%E9%A2%84%E7%83%AD%E5%A4%B1%E8%B4%A5-%E5%BA%94%E8%AF%A5%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3
