### ISSUE TITLE
[bug] 在16:10的屏幕中开启“1920*1080窗口”分辨率会被识别为非1080p

### ISSUE THREAD

**Issue by ronhsia** [babalae/better-genshin-impact#548]
屏幕物理尺寸是16:10
原神设置1920*1080窗口，并使用alt+enter全屏（此时屏幕上下有黑边）
此时应用识别为非1080p
自动拾取正常运作
请兼容

**Comment by huiyadanli** [comment]
alt+enter 缩放了整个游戏画面，实际就是1080p强制拉伸到了16:10

部分功能 16:10 下依旧能用
