### ISSUE TITLE
[feature] 希望编译Sdcb.PaddleInference.runtime.win64.openblas-noavx版本

### ISSUE THREAD

**Issue by Aloereed** [babalae/better-genshin-impact#557]
- Your feature requesting / 你的新功能请求

希望编译Sdcb.PaddleInference.runtime.win64.openblas-noavx版本。使用此版本Sdcb.PaddleInference，ARM64机器可以正常使用。

**Comment by huiyadanli** [comment]
我相信你可以自己解决这个问题
