### ISSUE TITLE
[bug] 使用一键尘歌壶会卡死 卡死后BetterGI无法关闭 

### ISSUE THREAD

**Issue by PaulsonH** [babalae/better-genshin-impact#558]
- 系统环境 / System Environment：win10

- BetterGI版本号 / BetterGI Version：0.33

- 问题描述 / Description of the issue：使用一键尘歌壶会卡死 卡死后无法关闭  任务管理器里夜不行 得重启电脑

- 复现步骤 / Reproduction steps：我使用小键盘快捷键 按一两次后大概率会卡在背包里

**Comment by huiyadanli** [comment]
可能是由于以下设置造成的

![image](https://github.com/user-attachments/assets/ab5fe4d3-7328-4875-87b1-7e449acb3e01)

可以尝试关闭位图缓存

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.34
