### ISSUE TITLE
[bug] 云原神使用时判定“当前获取焦点的窗口不是原神，暂停”

### ISSUE THREAD

**Issue by Bread-NiceCat** [babalae/better-genshin-impact#566]
- 系统环境 / System Environment：
Windows10

- BetterGI版本号 / BetterGI Version：
0.33.2

- 问题描述 / Description of the issue：
焦点
- ![image](https://github.com/user-attachments/assets/9ebcb297-10f0-473b-b02e-65fbc6c05178)
https://github.com/user-attachments/assets/9ebcb297-10f0-473b-b02e-65fbc6c05178
- 复现步骤 / Reproduction steps：
使用Edge打开云原神
- ![image](https://github.com/user-attachments/assets/d426360e-ed59-4b4a-a1eb-847f57d2911b)

**Comment by huiyadanli** [comment]
网页版本云原神暂未支持。。。只支持客户端云原神

**Comment by Bread-NiceCat** [comment]
修复了吗？v0.34.1在钓鱼/自动伐木时候仍然会弹提示（而且一个是INFO提示一个是WARN提示（雾？

**Comment by Bread-NiceCat** [comment]
或许可以把开始页选择捕获目标的选择作为原神窗口？
