### ISSUE TITLE
[feature] 自动领取邮件、纪行、洞天宝钱

### ISSUE THREAD

**Issue by HZYgrandma** [babalae/better-genshin-impact#568]
- Your feature requesting / 你的新功能请求

增加自动领取邮件，纪行的js模块
增加自动领取宝钱的功能，或者加入尘歌壶地图传送识别

**Comment by huiyadanli** [comment]
https://github.com/babalae/bettergi-scripts

**Comment by HZYgrandma** [comment]
> https://github.com/babalae/bettergi-scripts

自动领邮件，历练点，纪行你打算用yolo做吗，我感觉可以让gpt直接生成回放

**Comment by huiyadanli** [comment]
就正常图像识别做。这种事轮不到YOLO
