### ISSUE TITLE
使用遇到的两个问题以及一些建议

### ISSUE THREAD

**Issue by Mr-chen-0** [babalae/better-genshin-impact#57]
1.快捷键设置不能保存，每次重新打开需要重新设置
2.设置快捷键的时候ImeProcessed，键值被输入法处理了。可以在控件上禁用输入法InputMethod.IsInputMethodEnabled="False"或者构造函数加个System.Windows.Input.InputMethod.SetIsInputMethodEnabled(this, false);
-----------------------------------------------------
1.钓鱼的ai识别效果还算是差强人意，希望以后能更好
2.拾取的话我感觉一个白名单就好了呀，把需要拾取的东西放进去就行了。一是后面需要捡的东西的数量肯定是比不需要的少得多吧，我看黑名单都3k多行了，以后每次版本更新得多麻烦啊。二是我也没懂你现在白名单的作用。

**Comment by Mr-chen-0** [comment]
新活动的主板调试就会一直识别按f。每次活动都活出各种npc还有交互的npc之类的，这样以后维护很麻烦的。感觉一个拾取目标的白名单的就好了啊。不需要的东西在白名单里删掉或者注释掉就行了

**Comment by huiyadanli** [comment]
1. 已知 BUG，近期修复 
2. 以白名单为准，意味着每次版本更新我们都要马上训练模型跟进新版本，才能拾取新物品。黑名单没有这个问题
3. 新活动就是2所说的无法识别的文字，需要重新训练模型
