### ISSUE TITLE
[suggestion] 或许可能减少封号的可能性

### ISSUE THREAD

**Issue by qaqFei** [babalae/better-genshin-impact#574]
# suggestions / 建议
- 先说在前: 我不认为BetterGI理论上会导致封号, 但是减少封号的可能性可以带来一定的保障

- 添加移动的随机缓动和抖动, 并适度偏移目标点, 而不是直接移动到目标点
- 点击增加随机的按压时间
- 键盘同理 ↑

**Comment by qaqFei** [comment]
- 或许还可以驱动级模拟键鼠, 但是要做好键鼠配置

**Comment by huiyadanli** [comment]
开源软件，厂商完全可以不讲道理的通过识别程序特征来封禁，别浪费这个时间。

这类攻防等到出现封禁的时候才会考虑
