### ISSUE TITLE
[bug] 班尼特邀约结局5和结局6有问题，识别不到关键选项，重云邀约4的名字也错了

### ISSUE THREAD

**Issue by suifracti** [babalae/better-genshin-impact#581]
![a6f4f8788b4f40829677ad1df7e82f2b](https://github.com/user-attachments/assets/3c4a545f-af3c-4035-b315-0f41ce47dc97)

**Comment by wy3057** [comment]
插个锚点

**Comment by huiyadanli** [comment]
![image](https://github.com/user-attachments/assets/62e3909a-9825-4268-a429-e1162cc31c8b)

**Comment by huiyadanli** [comment]
结局 6 存在问题，结局 5 正常。

重云结局名称确实存在错误

**Comment by wy3057** [comment]
还有说洛艾尔结局三满分答卷似乎有点问题
还有洛艾尔的56有问题
> 结局 6 存在问题，结局 5 正常。
> 
> 重云结局名称确实存在错误

**Comment by huiyadanli** [comment]
```
  "诺艾尔第二幕结局5:独1无2的诺艾尔": [
    "不要逃避,直面考试压力吧",
    "可以多想象一下考试成功的样子",
    "可以成为琴那样的[代理团长]"
  ],
  "诺艾尔第二幕结局6:女仆的本职工作": [
    "不要逃避,直面考试压力吧",
    "可以多想象一下考试成功的样子",
    "可以成为凯亚那样的[骑兵队长]"
  ],
```

诺艾尔 第二幕 全部存在问题，特殊字符会影响匹配

**Comment by wy3057** [comment]
我最近都忙飞了，QWQ

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.34
