### ISSUE TITLE
[bug] 自动剧情不跟随游戏内自动开关，开启后即会跳过剧情

### ISSUE THREAD

**Issue by NONAME-2121237** [babalae/better-genshin-impact#583]
- 系统环境 / System Environment：
版本	Windows 11 专业版
版本号	23H2
安装日期	‎2024/‎1/‎15
操作系统版本	22631.4112
体验	Windows Feature Experience Pack 1000.22700.1034.0
Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 CPUs), ~2.3GHz
Memory: 32768MB RAM
DirectX Version: DirectX 12
Card name: NVIDIA GeForce RTX 2070 Super
Dedicated Memory: 7989 MB
Current Mode: 1920 x 1080 (32 bit) (300Hz)

- BetterGI版本号 / BetterGI Version：
0.33.2

- 问题描述 / Description of the issue：
游戏内自动开关尚未开启，但自动剧情仍会跳过剧情并点击主角的气泡选项
截图为凯瑟林但我尝试过普通剧情仍会跳过

- 复现步骤 / Reproduction steps：
![image](https://github.com/user-attachments/assets/b1a89f53-3449-40ba-a417-d04798a8efc7)
![image](https://github.com/user-attachments/assets/4ba16e8b-d985-449f-930a-dc2f99ff3e40)
![image](https://github.com/user-attachments/assets/0263b9e4-c3fa-4ef8-b571-e78efa07ea55)
尚不明确

**Comment by huiyadanli** [comment]
> 游戏内自动开关尚未开启，但自动剧情仍会跳过剧情并点击主角的气泡选项

近期版本有过变更，已经不再识别这个自动图标了，现在识别的 ![image](https://github.com/user-attachments/assets/3af2e721-129a-4409-8aec-e4e51706fe60) 更加可靠。不期望自动剧情的情况下请关闭自动剧情功能。

**Comment by NONAME-2121237** [comment]
> > 游戏内自动开关尚未开启，但自动剧情仍会跳过剧情并点击主角的气泡选项
> 
> 近期版本有过变更，已经不再识别这个自动图标了，现在识别的 ![图像](https://private-user-images.githubusercontent.com/15783049/363884283-3af2e721-129a-4409-8aec-e4e51706fe60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDk0ODksIm5iZiI6MTcyNTM0OTE4OSwicGF0aCI6Ii8xNTc4MzA0OS8zNjM4ODQyODMtM2FmMmU3MjEtMTI5YS00NDA5LThhZWMtZTRlNTE3MDZmZTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA3Mzk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NDhlNTZmZjdlZmE4YjhhZWRlZTM3Zjg5YzlmMjI0OTE1ODFmYTFhMDhhM2FlMmIzZWNiYWM5ZWM0MTM1MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MPg4lTRK_YlENuvPoUG-gkvv95vKjZcFVbgdHvrYDYA) 更加可靠。不期望自动剧情的情况下请关闭自动剧情功能。

这样的话请更改ui描述，在描述中自动剧情仍然是跟游戏内自动选项
![image](https://github.com/user-attachments/assets/81fb55c5-af20-47dd-b5f2-37b08becc5ff)

**Comment by NONAME-2121237** [comment]
> > > 游戏内自动开关尚未开启，但自动剧情仍会跳过剧情并点击主角的气泡选项
> > 
> > 
> > 近期版本有过变更，已经不再识别这个自动图标了，现在识别的 ![图像](https://private-user-images.githubusercontent.com/15783049/363884283-3af2e721-129a-4409-8aec-e4e51706fe60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDk0ODksIm5iZiI6MTcyNTM0OTE4OSwicGF0aCI6Ii8xNTc4MzA0OS8zNjM4ODQyODMtM2FmMmU3MjEtMTI5YS00NDA5LThhZWMtZTRlNTE3MDZmZTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA3Mzk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NDhlNTZmZjdlZmE4YjhhZWRlZTM3Zjg5YzlmMjI0OTE1ODFmYTFhMDhhM2FlMmIzZWNiYWM5ZWM0MTM1MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MPg4lTRK_YlENuvPoUG-gkvv95vKjZcFVbgdHvrYDYA) 更加可靠。不期望自动剧情的情况下请关闭自动剧情功能。
> 
> 这样的话请更改ui描述，在描述中自动剧情仍然是跟随游戏内自动选项 ![image](https://private-user-images.githubusercontent.com/104999550/363886357-81fb55c5-af20-47dd-b5f2-37b08becc5ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDk5MDgsIm5iZiI6MTcyNTM0OTYwOCwicGF0aCI6Ii8xMDQ5OTk1NTAvMzYzODg2MzU3LTgxZmI1NWM1LWFmMjAtNDdkZC1iNWYyLTM3YjA4YmVjYzVmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QwNzQ2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODIwMzk3ZWUwMWE2NjczMjg3YjYxYThiNWU2NzhlZWMzMTRlZTdiNjg5ZGQxZTJlYjJlMzA4MDlhMmZiMDFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xKclei21djrg7KwMQOBEMr2OzsbgLNMmzcI18IBRDxI)

如果不想更改描述的话可以同时检查新的隐藏图标和旧的自动图标，当隐藏图标被检测时检查自动是否开启

**Comment by huiyadanli** [comment]
描述忘记改了。。。

**Comment by NONAME-2121237** [comment]
> 描述忘记改了。。。
> 
> 隐藏UI的图标也能够被隐藏吗？

是这样，我还是想跟随游戏内的自动来开启自动剧情，所以想在检测到隐藏ui的图标后再去检测自动图标，可以满足不会误判自动图标的同时跟随游戏自动剧情

**Comment by molehzy** [comment]
[FR] 做一个开关让用户自己选择是识别自动图标还是识别隐藏UI图标
PS:好久没用了，今天更新后还以为出问题了，个人还是习惯在游戏内实现功能切换
PPS:左手边能设为快捷键且又不会对游戏和系统造成影响的也就~，所以设置快捷键实现在游戏内切换pass

**Comment by NONAME-2121237** [comment]
> [FR] 做一个开关让用户自己选择是识别自动图标还是识别隐藏UI图标 PS:好久没用了，今天更新后还以为出问题了，个人还是习惯在游戏内实现功能切换 PPS:左手边能设为快捷键且又不会对游戏和系统造成影响的也就~，所以设置快捷键实现在游戏内切换pass

这是个已经关闭的issues，如果你想提建议请重新创建一个【suggestion】的issue
