### ISSUE TITLE
[suggestion] 自动晶蝶都有了，自动狗粮能做吗

### ISSUE THREAD

**Issue by muguodiao** [babalae/better-genshin-impact#584]
- Your suggestions / 你的建议

一键自动跑狗粮点位，捡一圈圣遗物，感觉比晶蝶有用

**Comment by NONAME-2121237** [comment]
主要是圣遗物会乱蹦，飞的老远，要不在配对带万叶聚集掉落物

**Comment by huiyadanli** [comment]
键鼠录制版本的已经有了 https://github.com/babalae/bettergi-scripts

还在测试，未发布。

后期可能会加入地图识别追踪版本的自动狗粮
