### ISSUE TITLE
[bug] 录制情况下独立任务无法进行

### ISSUE THREAD

**Issue by baixi232310** [babalae/better-genshin-impact#587]
- 系统环境 / System Environment：

- BetterGI版本号 / BetterGI Version：0.33.2/0.33.3/0,33,4

- 问题描述 / Description of the issue：

- 复现步骤 / Reproduction steps：打开键鼠录制之后如果再启动独立任务，则会进行以下图片的报错
![2fb62662a22ba806f2b518a5073cba02](https://github.com/user-attachments/assets/0a681306-3739-49d4-90c0-ebab0faf85a3)

**Comment by huiyadanli** [comment]
无法混合启用，这种混合方式以后会依靠调度器实现。
