### ISSUE TITLE
[question] 自动战斗每一个动作有长时间延迟

### ISSUE THREAD

**Issue by Violet-Epic** [babalae/better-genshin-impact#588]
- Problem Description / 问题描述 开始战斗后，每次经过大约3s后角色才使用下一个动作，导致大多数角色被动挨打中死亡
- 请尽量提供问题相关的截图/日志等内容

**Comment by huiyadanli** [comment]
1. 你开了游戏滤镜
2. 你的分辨率不是 16:9

**Comment by Violet-Epic** [comment]
非常感谢你的回复，我研究后发现我的分辨率是16：10，实际中除了自动战斗外都可以正常使用，把分辨率调整成16：9解决了问题
