### ISSUE TITLE
【0.15.0】问题汇总及建议

### ISSUE THREAD

**Issue by whomtao** [babalae/better-genshin-impact#59]
[BUG]
1.【钓鱼】英伟达显卡使用游戏滤镜时，无法识别到有鱼上钩
2.【回复】昨天反馈的有关“菲米尼”自动对话的BUG，在重启软件后恢复正常
3.【回复】昨天反馈的有关“主板调试”字样的BUG，是因为识别错误，使用时发现多次识别为“王权调”
4.【快捷键设置】在启动软件时有概率会丢失有关快捷键的配置（全部显示None）
[建议]
1.在枫丹地区，水下部分，自动禁用连续空格功能
2.类似starward,可以在工具内启动游戏(主要是starward在win11下启动很慢QWQ)
3.自动更新软件本体,将正式版上传至gitee或者使用ghproxy进行加速代理(参考starward的更新方法)
【提问】
1.游戏日志可以选择关闭的吗，或者说使用一个独立的窗口？

目前遇到的问题只有这些，如果后面遇到其他问题，会在此issue上反馈

**Comment by huiyadanli** [comment]
**4. 已经确认是bug 近期修复**

1. 连续空格没啥用吧，关闭了好了。
**2. 后期会加上，但是具体哪个版本未定**
3. 暂时不用白嫖方案。ghproxy是公益服务，当前包体实在太大了。

1. 设置内关闭

**Comment by huiyadanli** [comment]
* 快捷键问题已修复
* 空格连发功能默认改为关闭

遗留：

游戏本体启动，在后期规划内
