### ISSUE TITLE
[feature] 能够集成解锁帧率功能？

### ISSUE THREAD

**Issue by wanghao-create** [babalae/better-genshin-impact#590]
- Your feature requesting / 你的新功能请求

解锁帧率功能目前已经有相对完整的实现，同时对于提升游戏体验有较大帮助。
能否和其他开源项目作者（如[winTEuser](https://github.com/winTEuser)）合作，将此功能集成进BetterGI？

**Comment by emako** [comment]
https://www.nuget.org/packages?q=unlocker

**Comment by Amb114** [comment]
BetterGI 不会做出任何修改游戏文件、读写游戏内存等任何危害游戏本体的行为，单纯依靠视觉算法和模拟操作实现。 但是mhy是自由的，用户条款上明确说明第三方软件/模拟操作是封号理由之一。当前方案还是存在被检测的可能。只能说请低调使用，请不要跳脸官方。

**Comment by huiyadanli** [comment]
由于软件的特殊性，暂不考虑。
