### ISSUE TITLE
[bug] 自动识别的黑名单和白名单不起作用

### ISSUE THREAD

**Issue by Nathcuya** [babalae/better-genshin-impact#591]
- 系统环境 / System Environment：win11

- BetterGI版本号 / BetterGI Version：0.33.2

- 问题描述 / Description of the issue：自动拾取功能中，修改白名单和黑名单无效，已按要求进行了重启软件，但无法生效，导致有时候走的不及时会疯狂自动交互弹出窗口，影响体验

- 复现步骤 / Reproduction steps：

**Comment by huiyadanli** [comment]
请输入左下角日志中提示的内容作为黑名单

**Comment by zanjie1999** [comment]
想加个地脉花进去一直没有成功，看到了这条issues，仔细挨个对着看了日志输出的字是“接触地脈之花”

果然错字不影响阅读
