### ISSUE TITLE
[question] 关于截取本地多用户窗口的问题

### ISSUE THREAD

**Issue by HZYgrandma** [babalae/better-genshin-impact#593]
使用SimpleRemote在本地多用户状态下运行原神理论上是否能够截取画面
三种截图方式目前都不行，测试图像捕获显示如下：
BitBlt
![image](https://github.com/user-attachments/assets/7ab0a1f1-b12a-40bf-8235-70293b8b1496)
WGC
![image](https://github.com/user-attachments/assets/8475f294-c78b-4b43-a373-a4ea0f85bd17)
第三种
![image](https://github.com/user-attachments/assets/e6ef8fdd-93b6-43d0-9d5a-bf66681eff3a)

远程窗口图像如下
![image](https://github.com/user-attachments/assets/8035f555-6d31-4302-9fe4-c21d412f29fe)

**Comment by huiyadanli** [comment]
尝试使用微软的 RDP 。这个问题会少一些

**Comment by HZYgrandma** [comment]
> 尝试使用微软的 RDP 进行远程桌面连接。这个问题会少一些
![QQ20240908-171206](https://github.com/user-attachments/assets/98f2ca41-019a-4c48-a292-8a42badb355e)
试了一下用另外一个软件就可以正常截取图像
进游戏后自动拾取是正常可用的，但没有任何日志输出
不过远程连接显示帧率太低，延迟太大，基本不可用，此帖终结
