### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by Kirto0109** [babalae/better-genshin-impact#594]
![屏幕截图 2024-09-08 155719](https://github.com/user-attachments/assets/2ad38c0d-414b-4ec9-843f-a47d13340249)

- 系统环境 / System Environment：

11
- BetterGI版本号 / BetterGI Versi 
- 
- BetterGI_Setup_v0.33.2.exe
- 
- 问题描述 / Description of the issue：
边框：2560*1600无边框
为什么实际上采集到了但是没识别出来，将自动采集上限（1080P推荐）关了后就只显示次数不显示获取数量，一直运行就不停直到设置次数达成，之前好好的，一次系统升级就变成这样。这是bug吗？

- 复现步骤 / Reproduction steps：

**Comment by Kirto0109** [comment]
我发现有不少人在伐木都有这样的问题存在

**Comment by huiyadanli** [comment]
参考 https://github.com/babalae/better-genshin-impact/issues/444

下版本在首次识别失败的时候会自动关闭这个功能并提示
