### ISSUE TITLE
[bug] 自动拾取会把尘歌壶里4.8活动家具的“摆放巧像”识别为要拾取的道具

### ISSUE THREAD

**Issue by jessefjxm** [babalae/better-genshin-impact#595]
- 系统环境 / System Environment：
Windows11

- BetterGI版本号 / BetterGI Version：
0.33.2

- 问题描述 / Description of the issue：
开启自动拾取后，会把尘歌壶里4.8活动家具的“摆放巧像”识别为要拾取的道具，然后不停触发，导致退出UI后又立刻重新进入
![image](https://github.com/user-attachments/assets/aa301362-4416-4982-b897-66205b0bdef3)

- 复现步骤 / Reproduction steps：
1、摆放4.8活动送的家具
2、走到家具前面，开启自动拾取

**Comment by huiyadanli** [comment]
已加入默认自带的黑名单

https://github.com/babalae/better-genshin-impact/releases/tag/0.34
