### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by frg666** [babalae/better-genshin-impact#6]
在没有点开始图像捕获的时候，不进行自动强化圣遗物和转圈圈的相应，方便使用的时候有其他操作不会占用快捷键

**Comment by huiyadanli** [comment]
不响应是可以的。

但是快捷键是程序开启就全局注册了（有其他方案可以解决

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.24.0  已优化
