### ISSUE TITLE
[bug] 调度器页面配置组内没有滚动条无法操作下面的任务。

### ISSUE THREAD

**Issue by iris10086** [babalae/better-genshin-impact#601]
- 系统环境 / System Environment：
windows10

- BetterGI版本号 / BetterGI Version：
0.34.1

- 问题描述 / Description of the issue：
![image](https://github.com/user-attachments/assets/99ae8c77-c7f1-4e04-958e-033709a0adfc)

- 复现步骤 / Reproduction steps：
在配置组内添加12个以上的任务。

**Comment by huiyadanli** [comment]
![image](https://github.com/user-attachments/assets/16436660-716a-44b6-b9c4-d436b80b71c1)
鼠标在这里点一下，然后滚动

**Comment by HZYgrandma** [comment]
> ![image](https://private-user-images.githubusercontent.com/15783049/366074685-16436660-716a-44b6-b9c4-d436b80b71c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5ODQ3MTcsIm5iZiI6MTcyNTk4NDQxNywicGF0aCI6Ii8xNTc4MzA0OS8zNjYwNzQ2ODUtMTY0MzY2NjAtNzE2YS00NGI2LWI5YzQtZDQzNmI4MGI3MWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDE2MDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzNTQwZWY2OTQ5MTM1YjRiY2MwNGZlNWNhMWIwMzBhMjE2ZjdhN2YwMjM3NjAyN2ZkOWY1MDE0MmYxYTY3MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SsC00BEJMfk79ERLUVAIr9U_zC8g7IQw-K-sLkDeXhQ) 鼠标在这里点一下，然后滚动
红色区域滚轮无效，绿色区域滚轮有效
![image](https://github.com/user-attachments/assets/43226d5b-fa7b-4e78-9751-86973bc26064)
