### ISSUE TITLE
[suggestion] 可以建一个脚本库吗

### ISSUE THREAD

**Issue by wcj1029** [babalae/better-genshin-impact#602]
- Your suggestions / 你的建议
新开发的地图追踪和脚本功能非常赞！但是里面的.json好少，找不到需求的文件，可以搞一个专门放各种奇奇怪怪脚本文件的库吗

**Comment by emako** [comment]
脚本库开放到[wiki](https://github.com/babalae/better-genshin-impact/wiki)里也行，编辑不用PR

**Comment by boxsnake** [comment]
问，如何为脚本库贡献脚本？

**Comment by huiyadanli** [comment]
> 问，如何为脚本库贡献脚本？

https://github.com/babalae/bettergi-scripts-list  直接到这里pr即可
