### ISSUE TITLE
[question] 自动秘境功能再次挑战后冲刺会超过钥匙位置

### ISSUE THREAD

**Issue by E-sure** [babalae/better-genshin-impact#607]
在开启自动秘境功能完成第一次秘境之后，在第二次及之后的再次进入后，冲刺一次经常会超过钥匙所在位置导致无法继续开启战斗。出现问题所在秘境为纳塔天赋本，经常出现这个问题。
在秘境里再次挑战的第二次及以后的角色与钥匙的相对位置和第一次进入秘境的角色与钥匙的相对位置是不同的，是否可以修改冲刺为正常前进且经常点击F防止走过钥匙处?

**Comment by huiyadanli** [comment]
![image](https://github.com/user-attachments/assets/cfaf3d3b-41fd-4b2a-9722-d73aedd622e7)
