### ISSUE TITLE
[bug] [已定位具体bug位置] 自动秘境结束战斗时，若角色朝向正好处于正西方，则无法自动转向古树，脚本运行受阻

### ISSUE THREAD

**Issue by TomIsFat** [babalae/better-genshin-impact#608]
- 系统环境 / System Environment：
Windows10

- BetterGI版本号 / BetterGI Version：
0.34.1

- 问题描述 / Description of the issue：
自动秘境结束战斗时，若角色朝向正好处于正西方，则无法自动转向古树，会直接卡住不动。
这时候显示的方向参考线正好为于正西方，是一条水平线。

- 复现步骤 / Reproduction steps：
正常刷本，直到结束时角色朝向正好处于正西方（非常难复现）

- 解决方案
推测是在**转向古树**这一步卡住的，因为稍微碰一下鼠标他就继续正常运行了
所以应该是LockCameraToEastTask这个方法出了问题，没有考虑到角度正好为180度的情况
修改621行的`if (angle < 180)`为`if (angle <= 180)`应该可以解决问题

https://github.com/babalae/better-genshin-impact/blob/8d2b36d5fdcb181a624372f54bf73ef57c07ab23/BetterGenshinImpact/GameTask/AutoDomain/AutoDomainTask.cs#L604

**Comment by huiyadanli** [comment]
确实有问题，已修正
