### ISSUE TITLE
[bug] 遮罩窗口开关失效

### ISSUE THREAD

**Issue by NONAME-2121237** [babalae/better-genshin-impact#609]
- 系统环境 / System Environment：

版本 Windows 11 专业版
版本号 23H2
安装日期 ‎2024/‎1/‎15
操作系统版本 22631.4112
体验 Windows Feature Experience Pack 1000.22700.1034.0
Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 CPUs), ~2.3GHz
Memory: 32768MB RAM
DirectX Version: DirectX 12
Card name: NVIDIA GeForce RTX 2070 Super
Dedicated Memory: 7989 MB
Current Mode: 1920 x 1080 (32 bit) (300Hz)

- BetterGI版本号 / BetterGI Version：

0.34.1

- 问题描述 / Description of the issue：
开关失效，关闭后叠加层仍然存在
![image](https://github.com/user-attachments/assets/2148fefc-d9e2-4a04-b8ab-a39b80b35d19)

- 复现步骤 / Reproduction steps：
默认开启叠加层在不关闭游戏的情况下关闭开关

**Comment by huxinchi** [comment]
版本	Windows 11 家庭中文版 Insider Preview
版本号	Dev
安装日期	‎2024/‎12/‎15
评估到期日期	‎2025/‎9/‎16 5:16
操作系统版本	27764.1000
序列号	MP2EDDZS
功能包	Windows 功能体验包 1000.26100.39.0
我也有这种情况

**Comment by huiyadanli** [comment]
直接修改文案解决
