### ISSUE TITLE
[feature] 自动秘境加入调度器实现自动每日任务

### ISSUE THREAD

**Issue by onglu1** [babalae/better-genshin-impact#610]
- Your feature requesting / 你的新功能请求
在调度器里面加入自动秘境的调度项。
如果有充足的长效历练点，自动秘境可以搭配上自动领取历练点和自动领取每日任务，实现全自动清每日。

同时希望自动秘境加入自动复活和传送回原来的秘境继续挑战的功能，有望实现每日全自动。

**Comment by huiyadanli** [comment]
https://bgi.huiyadan.com/autos/jsscript.html#runtask 脚本语法

脚本示例：

https://github.com/babalae/bettergi-scripts-list/tree/main/repo/js/AutoDomain
