### ISSUE TITLE
[bug] 安装好之后一打开就出错

### ISSUE THREAD

**Issue by DaydayupKatherina** [babalae/better-genshin-impact#611]
- 系统环境 / System Environment：
Windows 11

- BetterGI版本号 / BetterGI Version：
0.34

- 问题描述 / Description of the issue：
程序安装好之后一打开就弹截图的第一个错误， 点启动截图器之后出现第二个错误，主界面点任何操作在游戏都无效。.net 8.0已经安装过

- 复现步骤 / Reproduction steps：
安装bettergi 打开就出错 
![Screenshot 2024-09-10 214837](https://github.com/user-attachments/assets/a9d34936-099c-483c-a01d-84da5fc11627)
![Screenshot 2024-09-10 214913](https://github.com/user-attachments/assets/0fab9aea-7647-4b39-b488-aae31eff68fc)

**Comment by huiyadanli** [comment]
https://bgi.huiyadan.com/faq.html#%E2%9D%93%E6%8F%90%E7%A4%BA-paddleocr%E9%A2%84%E7%83%AD%E5%A4%B1%E8%B4%A5-%E5%BA%94%E8%AF%A5%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3
