### ISSUE TITLE
[suggestion] 在遇到'.NET Runtime'. You may not have write access 错误时尝试检查Windows Event Log服务的运行状态

### ISSUE THREAD

**Issue by JustInfLOL** [babalae/better-genshin-impact#612]
- Your suggestions / 你的建议

如题，部分精简版系统在其服务优化方案中对这一服务进行了处理，会导致Net运行时出错，进而导致多项功能不能正常运行。因此在出现这项错误时程序可以检查这一服务的运行状态（实测启动后功能即正常）

**Comment by huiyadanli** [comment]
确实存在这个问题，摸不着头脑。

serilog 也不强依赖这个。

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/blob/1f2d3a40d92fae1f63dca8daa2e1377ebafd5767/BetterGenshinImpact/App.xaml.cs#L41-L44

fixed by @Lightczx
