### ISSUE TITLE
[bug] 使用自动伐木之后出现“请求过于频繁”的问题

### ISSUE THREAD

**Issue by DaydayupKatherina** [babalae/better-genshin-impact#613]
![Screenshot 2024-09-12 145442](https://github.com/user-attachments/assets/574a9490-067f-4a0e-a296-1abe53a6abd9)

- 系统环境 / System Environment：
windows11

- BetterGI版本号 / BetterGI Version：
0.34

- 问题描述 / Description of the issue：
使用自动伐木一段时间之后，会出现“请求过于频繁”的提示，不能再自动进入账号。之后电脑会不能使用账密登任何账号，只能用短信才能登上

- 复现步骤 / Reproduction steps：
- 使用自动伐木一段时间之后，会出现“请求过于频繁”的提示，不能再自动进入账号。之后电脑会不能使用账密登任何账号，扫码也不可以了，只能用短信才能登上
- 
![Screenshot 2024-09-12 145442](https://github.com/user-attachments/assets/3bc1c1c1-e09c-4a27-9b6c-de522f6d8730)

**Comment by huiyadanli** [comment]
服务端限制，停止重复登录退出后会自己恢复正常。

你可以通过自动伐木设置中的延迟时间来解决这个问题。反复登录速度比较慢的情况下不会触发限制
