### ISSUE TITLE
[bug] 功能无法使用

### ISSUE THREAD

**Issue by WYShine** [babalae/better-genshin-impact#616]
- 系统环境 / System Environment：

![image](https://github.com/user-attachments/assets/1b10be79-963f-4c68-abe9-d861a180693d)

- BetterGI版本号 / BetterGI Version：
0.34.1

- 问题描述 / Description of the issue：
用BitBit 和 DwmGetxxxx 这两个截图器时，自动剧情、自动拾取等都不能用
用WindowsGraphxxxx 时，功能可以用，但是转头速度特别慢，鼠标转了一大圈角色都不怎么动。就像那维莱特被削弱那会重击时候的转向速度

- 复现步骤 / Reproduction steps：
问题描述里说过了

**Comment by huiyadanli** [comment]
方案一： 尝试让BitBit变得可用 #92
方案二： 解决WGC方式造成的卡顿问题 #286

**Comment by emako** [comment]
Dwm 的combbox加个不推荐吧

**Comment by huiyadanli** [comment]
发现 Combobox 直接绑定的枚举，放弃
