### ISSUE TITLE
[question] 内置的自动晶蝶貌似有点问题

### ISSUE THREAD

**Issue by yehuoshun** [babalae/better-genshin-impact#617]
- Problem Description / 问题描述：
 内置的自动晶蝶貌似有点问题
- 请尽量提供问题相关的截图/日志等内容：
启用脚本到结束才抓一只晶蝶。可能是因为晶蝶会乱跑？

**Comment by Amb114** [comment]
启动的时候不是说了要带早柚吗

**Comment by huiyadanli** [comment]
https://bgi.huiyadan.com/autos/jsscript.html
