### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by Kirto0109** [babalae/better-genshin-impact#620]
![屏幕截图 2024-09-15 031734](https://github.com/user-attachments/assets/aeef6bb0-6c54-42ba-ac25-2c9e5c187482)

- 系统环境 / System Environment：

windows11
- BetterGI版本号 / BetterGI Version：
0.34

- 问题描述 / Description of the issue：

这是什么问题
- 复现步骤 / Reproduction steps：

选牌时嗯七圣召唤快捷键就这样

**Comment by Kirto0109** [comment]
分辨率也调成了1920*1080

**Comment by Kirto0109** [comment]
使用牌组雷神克莱刻晴，还有刻晴雷神甘雨都是同一个问题

**Comment by huiyadanli** [comment]
重启软件即可

**Comment by Kirto0109** [comment]
哇，真谢谢了，一直都没能搞定重启真行了
