### ISSUE TITLE
[bug]自動劇情的自動領取每日委託獎勵和自動探索派遣無法使用

### ISSUE THREAD

**Issue by lulufruit-0403** [babalae/better-genshin-impact#621]
- 系统环境 / System Environment：win11

- BetterGI版本号 / BetterGI Version：0.34.1

- 问题描述 / Description of the issue：跟凱瑟琳對話後會不做動作

- 复现步骤 / Reproduction steps：

**Comment by huiyadanli** [comment]
请先完整阅读教程 https://bgi.huiyadan.com/quickstart.html
