### ISSUE TITLE
重启电脑会自动删文件

### ISSUE THREAD

**Issue by SMRQWQ** [babalae/better-genshin-impact#623]
- Problem Description / 问题描述
- 请尽量提供问题相关的截图/日志等内容
重启pc会自动删除自己，重新安装多次，无法解决

**Comment by huiyadanli** [comment]
https://bgi.huiyadan.com/faq.html#%E2%9D%93%E9%87%8D%E5%90%AF%E5%90%8E%E7%A8%8B%E5%BA%8F%E8%A2%AB%E5%88%A0%E9%99%A4%E4%BA%86%E6%98%AF%E4%BB%80%E4%B9%88%E6%83%85%E5%86%B5

直接覆盖安装即可。软件的提示你是一点都不看啊

**Comment by SMRQWQ** [comment]
> https://bgi.huiyadan.com/faq.html#%E2%9D%93%E9%87%8D%E5%90%AF%E5%90%8E%E7%A8%8B%E5%BA%8F%E8%A2%AB%E5%88%A0%E9%99%A4%E4%BA%86%E6%98%AF%E4%BB%80%E4%B9%88%E6%83%85%E5%86%B5
> 
> 直接覆盖安装即可。软件的提示你是一点都不看啊

试过了没用才问的...装再另一个盘又没事了
