### ISSUE TITLE
[bug] 新版本探索领取失效

### ISSUE THREAD

**Issue by i-cecreamer** [babalae/better-genshin-impact#625]
- 系统环境 / System Environment：
win10,22h2
![QQ截图20240915210700](https://github.com/user-attachments/assets/dd9a50f7-bbe6-4351-8903-2517d0fc8e79)
![QQ截图20240915221843](https://github.com/user-attachments/assets/ee231e70-c73b-41be-bb7c-7c03e9f5eee9)

- BetterGI版本号 / BetterGI Version：
0.34

- 问题描述 / Description of the issue：
0.32开始的版本自动领取探索失效

- 复现步骤 / Reproduction steps：

回退0.31目前正常使用

**Comment by huiyadanli** [comment]
请使用 0.34 版本

**Comment by i-cecreamer** [comment]
> 请使用 0.34 版本

我就是0.34版本探索领取失效的反馈啊，现在0.31是可以正常使用这个功能的

**Comment by huiyadanli** [comment]
无法复现，你的截图方式配置是否和0.31版本一致

**Comment by i-cecreamer** [comment]
> 无法复现，你的截图方式配置是否和0.31版本一致

是的，我都是用exe安装包覆盖安装的，我等下试试卸载后重新安装看看

**Comment by huiyadanli** [comment]
删掉User目录后重新安装。

早期版本关掉自动领取探索奖励的功能关闭后有不生效的问题，但在0.34版本修复了。你是否关掉了这个功能
