### ISSUE TITLE
[feature] 地图追踪/脚本添加重新加载按钮

### ISSUE THREAD

**Issue by boxsnake** [babalae/better-genshin-impact#627]
- Your feature requesting / 你的新功能请求

由于在创建脚本/追踪JSON时，会通过直接修改文件进行编辑，但 BetterGI 无法监听到文件变更或目录变更。因此建议在这两个标签页中加入对应的重新加载按钮，以方便开发调试。

**Comment by huiyadanli** [comment]
切换标签页后,会刷新

**Comment by boxsnake** [comment]
由于界面上并没有提示说明切换标签页会刷新数据，所以用户一般不会认为切换标签页会刷新数据。

并且，刷新标签页刷新数据可能是导致调度器中当前选中配置组的选中状态消失的原因。

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.35
