### ISSUE TITLE
[feature] 添加地图追踪脚本 action 方式

### ISSUE THREAD

**Issue by boxsnake** [babalae/better-genshin-impact#628]
- Your feature requesting / 你的新功能请求

添加 action：
- 普通攻击（可能和下落攻击按键一致？）
- 短按/长按E、Q，开启技能
- 切换角色1-4

对于长按E的例子：
- 钟离开盾防止采集流程被怪物干扰
- 卡齐娜、绮良良长按E进行爬墙
- 万叶按E起飞

**Comment by boxsnake** [comment]
建议添加飞行中非下落下降（按X自由落体一定时间），但需要 action_param 支持

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.36 
0.36 添加了自动队伍切换以及角色开E等选项，应该以及满足需求了
