### ISSUE TITLE
mac os可否使用

### ISSUE THREAD

**Issue by macchen123** [babalae/better-genshin-impact#63]
求助，我是mac m1max用户，在crossover23.6上玩原神，我直接把BetterGI0.15的文件夹放在crossover中然后点击exe一直处于加载状态无法打开，.net7在crossover中已安装。

**Comment by huiyadanli** [comment]
不太行吧，里面的ONNX大概率跑不动

**Comment by emako** [comment]
鸭蛋 ava 开发起来
