### ISSUE TITLE
[bug] 路径记录器添加关闭日志

### ISSUE THREAD

**Issue by boxsnake** [babalae/better-genshin-impact#631]
- 系统环境 / System Environment：

Windows 10 22H2 (19045.4894)

- BetterGI版本号 / BetterGI Version：

0.34.1

- 问题描述 / Description of the issue：

路径记录器关闭时无日志，建议添加路径记录器的关闭日志。在无关闭日志的情况下，用户（目前来说是开发者使用的功能）很难判断他现在是否处于路径记录器开启状态。

- 复现步骤 / Reproduction steps：

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.35
