### ISSUE TITLE
[feature] 新增其他的日志阅读方案

### ISSUE THREAD

**Issue by boxsnake** [babalae/better-genshin-impact#632]
- Your feature requesting / 你的新功能请求

从目前版本（0.34.1）看来，日志仅显示在叠层，但叠层的日志高度不是太够，对于大量的日志来说，无法上下滚动进行翻阅和回溯。

因此建议添加一个别的日志浏览方案，以下是一些实现方法：
- 在面板中，新增一个名为【日志】的标签页，可以滚动查看、复制浏览日志。
- 将日志存到本地 `*.log` 日志文件，使用户可以自行浏览日志。
- 将叠层中的日志绘制，独立出来，做成可拖动、缩放和滚动的独立弹窗。

**Comment by huiyadanli** [comment]
日志已经存储在本地，在 `log`目录下，可以通过其他第三方软件来实时查看，类似于 linux 的 tail 命令。

https://stackoverflow.com/questions/187587/a-windows-equivalent-of-the-unix-tail-command

**Comment by boxsnake** [comment]
> 日志已经存储在本地，在 `log`目录下，可以通过其他第三方软件来实时查看，类似于 linux 的 tail 命令。
> 
> https://stackoverflow.com/questions/187587/a-windows-equivalent-of-the-unix-tail-command

@huiyadanli 

建议在日志窗口设置中添加【打开日志目录】按钮，用来快捷打开目录。

**Comment by huiyadanli** [comment]
![image](https://github.com/user-attachments/assets/446489c9-7cbd-4fb3-9708-cdf56425b256)
