### ISSUE TITLE
[bug] 地图追踪弹窗报错

### ISSUE THREAD

**Issue by boxsnake** [babalae/better-genshin-impact#633]
- 系统环境 / System Environment：

Windows 10 22H2 (19045.4894)

- BetterGI版本号 / BetterGI Version：

0.34.1

- 问题描述 / Description of the issue：

地图追踪弹窗报错

![image](https://github.com/user-attachments/assets/5b2adc71-862a-4900-9fce-b0f510f729df)

- 复现步骤 / Reproduction steps：

在【地图追踪】中，点击【打开实时追踪地图】，然后关闭弹窗，再次点击【打开实时追踪地图】即可出现此问题。

**Comment by huiyadanli** [comment]
此问题已经修复，在下版本更新提供
