### ISSUE TITLE
[question] 关于实时追踪地图的显示

### ISSUE THREAD

**Issue by boxsnake** [babalae/better-genshin-impact#634]
- Problem Description / 问题描述

为什么每次打开实时追踪地图都显示的是同一个区域的地图？是未实现功能还是有 Bug？

![image](https://github.com/user-attachments/assets/de3d8670-a3cf-4d01-a0fd-1830e4323084)

并且，最大化窗体，图片区域不会拉伸

![image](https://github.com/user-attachments/assets/8e27caae-0c32-4fe4-bcf9-5a87e5060440)

**Comment by HZYgrandma** [comment]
实时追踪地图打开时左上角为默认0,0点；开始寻路后会显示寻路路线

**Comment by huiyadanli** [comment]
给了一个默认区域，为了性能考虑不会提供拉伸能力
