### ISSUE TITLE
[suggestion] 自动剧情识别图标的选择功能

### ISSUE THREAD

**Issue by qhmw** [babalae/better-genshin-impact#635]
以前是用“自动剧情” 现在是“隐藏界面”
想要两个都能判定 可以在实时触发-自动剧情一栏下选择
![`KK )QA~JML4)%J)FCN2BC4](https://github.com/user-attachments/assets/a8dfc380-ca17-4583-8a2e-09b4d36edb0a)

**Comment by huiyadanli** [comment]
自动的识别是不够准确的，所以不再推荐使用
