### ISSUE TITLE
[feature] 提供两种默认路径点

### ISSUE THREAD

**Issue by HZYgrandma** [babalae/better-genshin-impact#637]
- Your feature requesting / 你的新功能请求
两种途径点，一种为“途径点”一种为“兴趣点”
途径点快速通过，兴趣点根据不同脚本类型执行不同的行为，如采集类兴趣点原地停留3秒，挖矿类兴趣点环视一周寻找矿物等
同时，途径点和兴趣点在地图编辑器中以不同颜色显示，方便辨认来修改脚本
同时现在快捷键较多，如果可以的话建议给快捷键页加上树状列表，或者按功能分类进行缩进显示

**Comment by huiyadanli** [comment]
这个已经有了，就是 `target` 目标点。`action` 待完善中

https://bgi.huiyadan.com/autos/pathing.html 文档已提前更新

**Comment by huiyadanli** [comment]
2. 地图编辑器不同颜色渲染线条对我来说有点困难，倒是右侧表格可以换颜色

3. https://github.com/babalae/better-genshin-impact/issues/639
