### ISSUE TITLE
[suggestion] 重写快捷键页

### ISSUE THREAD

**Issue by HZYgrandma** [babalae/better-genshin-impact#639]
- Your suggestions / 你的建议
按照功能分类
现在这个快捷键页我每次打开前都要吃两粒晕车药
![Image_1726595301120](https://github.com/user-attachments/assets/89374f35-e75d-472e-bce0-7ddc7599fb61)

**Comment by emako** [comment]
suggestion: 搜索框

**Comment by huiyadanli** [comment]
> suggestion: 搜索框

臣妾做不到啊呜呜呜

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.35
