### ISSUE TITLE
[suggestion] 新一点的gif

### ISSUE THREAD

**Issue by HZYgrandma** [babalae/better-genshin-impact#643]
- Your suggestions / 你的建议
![0 34 1](https://github.com/user-attachments/assets/cd8dc3ce-624b-41f8-9a20-57a19c3cad61)

**Comment by huiyadanli** [comment]
感谢录制，已经更新。

https://github.com/babalae/better-genshin-impact/commit/1a4682bf29593ab4b98da5b11582bd664220a25e
