### ISSUE TITLE
[bug] 自动对话识别问题

### ISSUE THREAD

**Issue by Vinkle-hzt** [babalae/better-genshin-impact#646]
- 系统环境 / System Environment：
windows11
WindowsGraphicsCapture
推理设备 CPU
分辨率 3840x2560 素材缩放 1.0 DPI缩放1.5

- BetterGI版本号 / BetterGI Version：
0.34.1

- 问题描述 / Description of the issue：
![QQ20240918-223557](https://github.com/user-attachments/assets/d6763974-a5a2-4742-a0c1-7f0d7a955e6e)
自动对话会识别到隐藏界面的图标

- 复现步骤 / Reproduction steps：
无

**Comment by huiyadanli** [comment]
![image](https://github.com/user-attachments/assets/4a2d9cc3-0f73-4991-b77c-98b841bbf5f0)
