### ISSUE TITLE
[question] 路线追踪任务疑似在粗略接近途径点时捡到特产，会导致精确接近时捡不到并超时

### ISSUE THREAD

**Issue by Amb114** [babalae/better-genshin-impact#648]
- Problem Description / 问题描述
- 请尽量提供问题相关的截图/日志等内容
路线追踪任务疑似在粗略接近途径点时捡到特产，会导致精确接近时捡不到并超时
可能与我GPU性能低有关
也有可能如果路上路过后面的特产，执行到那个特产的时候也会捡不到超时
复现主要看运气 跑几遍就出来了
可以加一个机制，如临时把这个特产加入拾取黑名单

**Comment by huiyadanli** [comment]
两者没有关联，精确接近超时是接近尝试次数过多以后产生的日志。很容易出出现，如果不影响拾取请无视
