### ISSUE TITLE
几个需求

### ISSUE THREAD

**Issue by ZedeX** [babalae/better-genshin-impact#65]
1. 遇到有下图文字的地方：自动点击![image](https://github.com/babalae/better-genshin-impact/assets/394198/3daf5bcf-f185-4e1f-85eb-b9c6b5f0bad7)
2. 纪行自动获取已完成任务的奖励：监控纪行图标如果有感叹号则点击并依次点击有感叹号的按钮并点击领取按钮
3. 自动升级武器
4. 自动根据设定好的脚本打Boss / 怪：可以参考自动打牌的策略来设计，在L队伍界面中获取人物姓名，如果名字或顺序不对则自动调整队伍。然后手动到达怪处，系统判定窗口顶部区域有怪物名或血条则自动根据脚本QEA，由于可能存在被打断的情况，所以脚本的触发机制是判断右下角QE区域是否“暗下去”为是否执行下一指令的前提条件（当然这个策略并不完美，毕竟有的怪有脚/会飞，抛砖引玉）

**Comment by Normal-pcer** [comment]
升级武器会在下个版本优化

**Comment by huiyadanli** [comment]
1. 即黑屏点击功能，已经修复
2. #222
3. 原神4.3的优化已经足够了
4. 0.21版本后支持自定义脚本进行自动秘境，无怪物追踪能力
