### ISSUE TITLE
[feature] 紧凑的UI

### ISSUE THREAD

**Issue by Amb114** [babalae/better-genshin-impact#650]
- Your feature requesting / 你的新功能请求
UI行距太大，屏幕上显示的内容太少了，建议加一个紧凑UI功能放设置里

**Comment by huiyadanli** [comment]
没看懂你的需求

**Comment by Amb114** [comment]
> 没看懂你的需求
就是减少软件UI的行距，这样可以清楚的显示更多内容（经常展开个什么东西就排到N个屏幕外了）

**Comment by huiyadanli** [comment]
不考虑，当前 UI 遵循 fluent design 的规范。
