### ISSUE TITLE
[feature] 调度器增加重命名和重复执行功能

### ISSUE THREAD

**Issue by Amb114** [babalae/better-genshin-impact#651]
- Your feature requesting / 你的新功能请求
重命名：虽然改一下文件名就行，但是软件里操作更方便
重复执行：重复执行（）次特定的*几行*功能

**Comment by boxsnake** [comment]
个人感觉，重复执行某特定的几行功能，在创建寻路进行分段调试的时候比较有用，不需要从一开始的传送点再跑一路。
当然注释掉部分代码运行也是可以的，但感觉不够方便。

**Comment by huiyadanli** [comment]
重命名已添加
