### ISSUE TITLE
[bug] 略高缩放比例的设备下少部分弹窗弹到右下角

### ISSUE THREAD

**Issue by Amb114** [babalae/better-genshin-impact#653]
- 系统环境 / System Environment：
Microsoft Windows [版本 10.0.22631.3672] Windows 11 23H2 amd64

- BetterGI版本号 / BetterGI Version：
0.34.4-release

- 问题描述 / Description of the issue：
略高缩放比例的设备（笔记本）下少部分弹窗弹到右下角

- 复现步骤 / Reproduction steps：
桌面右键，显示设置，把缩放调到最高
然后找到调度器选一个配置组
然后右键一个步骤，修改通用配置，会弹出窗口到右下角
之前“发现新版本”的弹窗也会弹到右下角

**Comment by Amb114** [comment]
高缩放只是弹右下角 最高缩放直接不见了导致bgi窗口点不动

**Comment by huiyadanli** [comment]
wpfui的bug，等待ui框架更新
