### ISSUE TITLE
在自动秘境战斗完成后增加自定义任务

### ISSUE THREAD

**Issue by ZhaYi-Miao** [babalae/better-genshin-impact#659]
- Your feature requesting / 你的新功能请求

在自动秘境战斗完成后增加自定义任务，例如可将结束后的等待五秒自定义为某角色做某事（同自动战斗）
例如为角色回复血量（芙宁娜重击 e/芭芭拉e）

**Comment by huiyadanli** [comment]
暂不考虑，关于恢复血量参考  #649
