### ISSUE TITLE
关于自动寻路的action

### ISSUE THREAD

**Issue by iris10086** [babalae/better-genshin-impact#664]
关于action，我大概想到几点。

1. 增加parm字段
给action传递一个参数。
如果后期要实现切人的功能的话，由用户传参数给action处理应该会比较方便。
或者直接将当前正在执行的对象传递到action，那这个写起来可能更灵活了。

2. 增加action数量。
在单点中添加action数组。将复杂任务分割成小任务。
例如：["fight","切人(万叶)","长E"]
但是这样的话又不好传递参数了。

**Comment by huiyadanli** [comment]
此类action，需要在整个路径追踪任务开始前先识别整个队伍，action执行角色+操作。

或者直接复用战斗策略，执行自动战斗的独立任务直接实现。开发量极低。

但是又想到后续会提供 action 调用 JS脚本的能力（JS脚本能够调用所有其他的脚本与策略），感觉这一步都可以省略了。

不过你提到的要添加一个 `action_param` 的字段，我是赞同的，早晚会加上

**Comment by huiyadanli** [comment]
https://bgi.huiyadan.com/feats/autos/pathing.html

![Image](https://github.com/user-attachments/assets/117ea074-c58c-47e1-99a5-4c4ea7111605)
