### ISSUE TITLE
[question] 请问BetterGL的启动参数是什么意思，应该如何填写，有哪些功能

### ISSUE THREAD

**Issue by WQ568** [babalae/better-genshin-impact#665]
- Problem Description / 问题描述
- 请尽量提供问题相关的截图/日志等内容
![image](https://github.com/user-attachments/assets/5be178d4-6a33-437b-95fd-4aaeb74388e6)
如图所示，启动参数可以配置哪些功能、填写格式是什么？在BetterGL的使用文档中并未找到关于该参数的描述，不知道“启动参数”有什么作用，烦请百忙之中拨冗解答一下，谢谢

**Comment by huiyadanli** [comment]
其本质是 Unity 独立平台播放器命令行参数 ，测试下来有用的参数大概如下： 

 - `-window-mode exclusive` 参数
    - **独占全屏**，即选择游戏进程以独占全屏模式运行
      - **该功能与游戏内浏览器功能不兼容，你应仅在能独立描述独占全屏的技术原理和效果的情况下开启本项**
  - `-screen-fullscreen` 参数
    - **全屏**，即选择启动游戏后的游戏界面是否设置为全屏
  - `-popupwindow` 参数
    - **无边框**，即选择启动游戏后的游戏界面是否设置为无边框窗口
  - `-platform_type CLOUD_THIRD_PARTY_MOBILE` 参数
    - **触摸屏模式**，即启用原神内置的触摸屏操作模式（键鼠输入将被忽略）
  - 分辨率
    - 该功能可以快速设置下方的覆盖屏幕宽度和高度选项，有一些常见的预设项可供选择
  - `-screen-width` 参数
    - **宽度**，即选择启动游戏后的游戏界面的宽度，例如 `1920`
  - `-screen-height` 参数
    - **高度**，即选择启动游戏后的游戏界面的高度，例如 `1080`
  - `-monitor` 参数
    - **显示器**，允许多显示器用户选择指定的显示器来运行游戏

**Comment by WQ568** [comment]
> 其本质是 Unity 独立平台播放器命令行参数 ，测试下来有用的参数大概如下：
> 
> * `-window-mode exclusive` 参数
>   
>   * **独占全屏**，即选择游戏进程以独占全屏模式运行
>     
>     * **该功能与游戏内浏览器功能不兼容，你应仅在能独立描述独占全屏的技术原理和效果的情况下开启本项**
> * `-screen-fullscreen`参数
>   
>   * **全屏**，即选择启动游戏后的游戏界面是否设置为全屏
> * `-popupwindow`参数
>   
>   * **无边框**，即选择启动游戏后的游戏界面是否设置为无边框窗口
> * `-platform_type CLOUD_THIRD_PARTY_MOBILE`参数
>   
>   * **触摸屏模式**，即启用原神内置的触摸屏操作模式（键鼠输入将被忽略）
> * 分辨率
>   
>   * 该功能可以快速设置下方的覆盖屏幕宽度和高度选项，有一些常见的预设项可供选择
> * `-screen-width`参数
>   
>   * **宽度**，即选择启动游戏后的游戏界面的宽度，例如 `1920`
> * `-screen-height`参数
>   
>   * **高度**，即选择启动游戏后的游戏界面的高度，例如 `1080`
> * `-monitor`参数
>   
>   * **显示器**，允许多显示器用户选择指定的显示器来运行游戏

谢谢大佬，已按照您提供的说明配置了对应的启动参数。经测试，不同参数之间使用空格来隔开。

**Comment by WQ568** [comment]
补充一下：5.3版本更新后（2025年1月1日后），“-window-mode exclusive”启动参数（独占全屏）很容易失效，经测试，10次中只有1到2次可以成功启动“独占全屏”功能。
建议有独占全屏需求的小伙伴，将BetterGI启动参数中的“-window-mode exclusive”替换成“ -popupwindow”。

**Comment by cannorY** [comment]
启动参数无法生效，启动后依然是显示器原始分辨率

![Image](https://github.com/user-attachments/assets/f46f3715-6099-43ac-adf0-ba7a70309469)
