### ISSUE TITLE
[question] 有关自动剧情识别及任务快速对话取消的问题

### ISSUE THREAD

**Issue by SMFDrummer** [babalae/better-genshin-impact#666]
### 有关自动剧情识别
我记得之前BetterGI的识别是去识别游戏内自动剧情的按钮，但是不知道怎么新版本去吸附识别UI隐藏按钮了，这是后更新的吗，还是我这边截图器出了问题，实测三种截图方式均会吸附UI隐藏按钮
![image](https://github.com/user-attachments/assets/ee82a54a-7042-4ad8-96b0-9092ca663047)

### 有关快速对话
实测该设置项开启时为快速跳过对话没有问题，但关闭后不会像之前一样主动在人物说完之后进行自动点击，早些版本的BetterGI可以做到，这是bug吗？
![image](https://github.com/user-attachments/assets/d86e03db-2f60-40de-942f-7cb927d6ace7)

**Comment by huiyadanli** [comment]
不是bug，你自己打开游戏自动就行了

#635
