### ISSUE TITLE
[bug] 路径跟踪的卡死脱离行为没用

### ISSUE THREAD

**Issue by HZYgrandma** [babalae/better-genshin-impact#668]
ai写的太唐了，麻烦转人工

**Comment by huiyadanli** [comment]
发个卡死的路线我测试下

**Comment by HZYgrandma** [comment]
[耐卡王.json](https://github.com/user-attachments/files/17178859/default.json)
r'g如果不出意外会卡在这里
![QQ20240929-181608](https://github.com/user-attachments/assets/2fd11abf-d8af-492b-922e-0dd77db63af9)
当前的卡死脱离目测就是短按一下s，a，d

**Comment by huiyadanli** [comment]
帮忙测试下，我改了，但是可能这个场景还脱离不了

**Comment by HZYgrandma** [comment]
成了
