### ISSUE TITLE
[bug] 2k分辨率开1920X1080窗口化下自动剧情实现不了，也不能自动采集

### ISSUE THREAD

**Issue by Encountertay** [babalae/better-genshin-impact#670]
- 系统环境 / System Environment：win11

- BetterGI版本号 / BetterGI Version：0.341

- 问题描述 / Description of the issue：2k分辨率开1920X1080下自动剧情实现不了

- 复现步骤 / Reproduction steps：

**Comment by huiyadanli** [comment]
请先阅读文档 https://bgi.huiyadan.com/quickstart.html
