### ISSUE TITLE
[suggestion] 0.35图标（周年庆）

### ISSUE THREAD

**Issue by HZYgrandma** [babalae/better-genshin-impact#671]
不出意外0.35是bgi一周年版本
仿照原神做了相应的周年庆图标
可在0.35版本使用
[asset1st.zip](https://github.com/user-attachments/files/17168546/asset1st.zip)

**Comment by emako** [comment]
хорошо

**Comment by emako** [comment]
@HZYgrandma 能否多整几个2周年 3周年 的图标...

**Comment by huiyadanli** [comment]
banner不需要，banner我有新图，圆形图标倒是可以

**Comment by HZYgrandma** [comment]
[asset_anniversary.zip](https://github.com/user-attachments/files/17178921/asset_anniversary.zip)
1-5周年的图片（虽然我觉得绮良良这个logo可能撑不到五周年就会换掉）
反正如果到时候换了logo换张底图导出就行了，也不是什么麻烦事
