### ISSUE TITLE
[suggestion] 自动剧情希望加一条好友壶加速功能

### ISSUE THREAD

**Issue by i-cecreamer** [babalae/better-genshin-impact#677]
- Your suggestions / 你的建议

开启自动剧情的情况下，进好友壶加速会自动点离开，每次都得关闭自动剧情，希望加一条代码判定
![QQ截图20241001102311](https://github.com/user-attachments/assets/90f93f49-0e8f-4014-82a5-522609a2c896)

**Comment by i-cecreamer** [comment]
对了，还有七圣周常打牌对话，能否也加一个，最好是识别后无缝衔接快捷键开启自动打牌功能
![QQ截图20241006231218](https://github.com/user-attachments/assets/fbe12c12-e66c-4e42-a4cd-9f4e990874c3)

**Comment by i-cecreamer** [comment]
![QQ截图20241006231218](https://github.com/user-attachments/assets/651303c6-e399-4ce8-892c-37c631976d1b)

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.35  已加入黑名单

**Comment by huiyadanli** [comment]
> 对了，还有七圣周常打牌对话，能否也加一个，最好是识别后无缝衔接快捷键开启自动打牌功能 ![QQ截图20241006231218](https://private-user-images.githubusercontent.com/128817713/373957793-fbe12c12-e66c-4e42-a4cd-9f4e990874c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NDEwODksIm5iZiI6MTcyODg0MDc4OSwicGF0aCI6Ii8xMjg4MTc3MTMvMzczOTU3NzkzLWZiZTEyYzEyLWU2NmMtNGU0Mi1hNGNkLTlmNGU5OTA4NzRjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxNzMzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDNmMTI2ZTczNTZlZTdjMGJhYjY0YzQ0N2Y3MzVlYjRiOTA1YmY0ODc1NzUyM2FhNzc2YTY1MTQ4NDc3YzQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8__ePU56JYkD6uwClVF9zRyooR8BNTDI_WpAD8YLfCM)

这个已经有类似issue了
