### ISSUE TITLE
[feature] 关于切换队伍

### ISSUE THREAD

**Issue by iris10086** [babalae/better-genshin-impact#680]
- Your feature requesting / 你的新功能请求

 有些用户有好感队和打架队。我认为可以实现一个切换队伍的功能。
通过对左下角队伍名称配置的OCR识别可以设置不同的队伍。
![image](https://github.com/user-attachments/assets/f7e6685e-d75f-4803-94bb-b4bac42e820b)
使用这个队伍名为依据来切换到对应的队伍。

若选择的队伍不是当前的出战队伍，上面的方块会有一个金边的方块。可以判断是否切换一圈队伍。
![image](https://github.com/user-attachments/assets/2a5f58e3-ff84-48f5-b9e7-765bb21aca7d)

**Comment by huiyadanli** [comment]
队伍名称的命名麻烦，而且可能会遇到换人的情况。OCR的识别率也是堪忧的

我初步的想法是点击 
![image](https://github.com/user-attachments/assets/3713be77-531c-48e2-a5c7-769ef8b686ec)
后，在左侧列表的侧面头像处，通过bgi已有的角色分类器来识别队伍。

![image](https://github.com/user-attachments/assets/8d8dfd29-0143-4ed8-8d6d-d81705ccce3d)

直接OCR这块文字也是可以的，但是实际不太靠谱。头像分类器可以做到接近100%的识别率。。

**Comment by iris10086** [comment]
识别队伍名的话好感队就不用重新配置，直接切到好感队就行了。

**Comment by iris10086** [comment]
突然感觉像我这样的需求直接切第一队为好感队也不用识别之类的了。

**Comment by tignioj** [comment]
队伍侧边栏因为是固定颜色背景，并且与文字有较高的对比度，OCR识别队伍名称似乎还行

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/commit/4cb54421619440f112973062410507d2b7bd833b

已实现

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.36
