### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by STC214** [babalae/better-genshin-impact#682]
- 系统环境 / System Environment：win 11 24H2 

- BetterGI版本号 / BetterGI Version：0.34.1

- 问题描述 / Description of the issue：自动剧情失效，鼠标不会自己动，剧情也不会自动点了

- 复现步骤 / Reproduction steps：F11之后直接打开自动剧情快捷键，屏幕有提示自动剧情开启。但是实际上无效。

**Comment by huiyadanli** [comment]
https://bgi.huiyadan.com/quickstart.html

https://github.com/babalae/better-genshin-impact/issues/92
