### ISSUE TITLE
[suggestion] 自动秘境后因为加载慢 导致地图没打开就开始执行传送

### ISSUE THREAD

**Issue by Levantine-i** [babalae/better-genshin-impact#686]
调度器自动秘境后因为加载慢 导致地图没打开就开始执行传送导致传送失败 或许可以在调度器里加一个等待？

**Comment by huiyadanli** [comment]
已经加入重试机制

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.35
