### ISSUE TITLE
[feature] 关于路径追踪建议增加的功能

### ISSUE THREAD

**Issue by yulalaa** [babalae/better-genshin-impact#687]
- Your feature requesting / 你的新功能请求

路径追踪的跑步/走路状态自定义
路径追踪增加爬坡

路径追踪增加到达点位后的自定义等待时间，默认空为1秒
路径追踪增加到达点位后普通攻击，默认空为不打，数字1为打1秒，2为2秒，以此类推
路径追踪增加到达点位后使用E技能，不转圈的，默认空为不放，true后，E技能时间默认空为1秒，2为2秒，以此类推

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.36

跑步、走路、攀爬已经全部添加

普通攻击与E技能当前换做为元素力采集，以兼容不同用户使用不同角色的场景。

等待时间暂未实现，计划把战斗脚本作为参数丢进去
