### ISSUE TITLE
搭配Genshin Impact FPS Unlocker使用失焦问题

### ISSUE THREAD

**Issue by x724307156** [babalae/better-genshin-impact#69]
开启Genshin Impact FPS Unlocker内的power saving功能，游戏会在失焦后自动限制帧数至10fps
如果搭配BetterGI.v0.15.0使用，开启功能后游戏内会持续失焦导致掉帧
改用本站内GIS_0.0.49+Genshin Impact FPS Unlocker不会有该问题

**Comment by huiyadanli** [comment]
是不是 BetterGI 的资源占用太高导致的掉帧

**Comment by x724307156** [comment]
> 是不是 BetterGI 的资源占用太高导致的掉帧

否定。关闭power saving功能后使用能稳定120fps的
附个硬件配置：5600x+6800xt

**Comment by huiyadanli** [comment]
尝试更换截图方式。理论上除了对整机的性能消耗，不会对原神产生任何影响。

**Comment by x724307156** [comment]
三种截图方式均已尝试，未能结局问题。只能暂时二选一使用了
感谢开发
