### ISSUE TITLE
[suggestion] 物品自动拾取达到上限后可以暂时暂停自动拾取

### ISSUE THREAD

**Issue by wen20919** [babalae/better-genshin-impact#694]
- Your suggestions / 你的建议

![屏幕截图 2024-10-13 230328](https://github.com/user-attachments/assets/3fc3bda2-94cc-4190-994f-7460eca9cd63)
物品自动拾取达到上限后可以暂时暂停自动拾取，否则角色不迅速移开会反复弹出提示被硬控

**Comment by wen20919** [comment]
> * Your suggestions / 你的建议
> 
> ![屏幕截图 2024-10-13 230328](https://private-user-images.githubusercontent.com/154748075/376045676-3fc3bda2-94cc-4190-994f-7460eca9cd63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MzI0NDYsIm5iZiI6MTcyODgzMjE0NiwicGF0aCI6Ii8xNTQ3NDgwNzUvMzc2MDQ1Njc2LTNmYzNiZGEyLTk0Y2MtNDE5MC05OTRmLTc0NjBlY2E5Y2Q2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxNTA5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2VlNGU0YTc2NzEzZDZkZWM1MjUyZWM4YTkyNTAzMmFjMjljZTJmODAwMmZiNzY5NWQ0MDYyMzUxNmFjYmIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hTgNM6FJcw4c847YqHLUMUoc0V1PNg_WjK9WFMaX-o8) 物品自动拾取达到上限后可以暂时暂停自动拾取，否则角色不迅速移开会反复弹出提示，使得被硬控难以移动

**Comment by huiyadanli** [comment]
加入拾取黑名单即可
