### ISSUE TITLE
[suggestion] 能不能有一个每日一条龙的功能

### ISSUE THREAD

**Issue by yinyur2** [babalae/better-genshin-impact#698]
- Your suggestions / 你的建议

最近绝区零那边用了个脚本有类似的功能，自己预先设置完干什么之后。点击开始，自动打开游戏登录、领月卡、派遣、喝咖啡、清体力、领取每日奖励、领大月卡奖励。这么一整套流程都自己顺下来。

**Comment by 3364729893** [comment]
> * Your suggestions / 你的建议
> 
> 最近绝区零那边用了个脚本有类似的功能，自己预先设置完干什么之后。点击开始，自动打开游戏登录、领月卡、派遣、喝咖啡、清体力、领取每日奖励、领大月卡奖励。这么一整套流程都自己顺下来。

你可以先试试从合成树脂，领取奖励，委派，的脚本试试，你就会发现成功率不高，因为出现了走路的原因，会有误差

**Comment by huiyadanli** [comment]
#846
