### ISSUE TITLE
[bug] 地图缩放过小时传送异常

### ISSUE THREAD

**Issue by onglu1** [babalae/better-genshin-impact#699]
- 系统环境 / System Environment：
   windows11
- BetterGI版本号 / BetterGI Version：
  0.35.0

- 问题描述 / Description of the issue：
如果地图的缩放过小，传送锚点会被隐藏。  
使用genshin.tp(x, y)语句进行传送的时候，他会点击对应地方。但如果缩放过小，无法点击到传送锚点，从而无法实现传送。

- 复现步骤 / Reproduction steps：
在地图上将地图缩放到最小，再运行tp的脚本。

**Comment by HZYgrandma** [comment]
那为什么要把地图缩得那么小

**Comment by onglu1** [comment]
> 那为什么要把地图缩得那么小

我觉得可以把重心放在怎么解决这个问题上，而不是反问我

**Comment by huiyadanli** [comment]
传送需要添加改变默认地图缩放的能力

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.38
