### ISSUE TITLE
优化一下圣遗物强化功能

### ISSUE THREAD

**Issue by d2913406181** [babalae/better-genshin-impact#7]
在使用圣遗物强化功能时，长按功能键会导致操作过快，再次按相应功能键无法停止，希望可以优化一下或者改成点按开关形式的逻辑

**Comment by huiyadanli** [comment]
发现长按这个优化代价比较大。该功能应该也会在4.3下线。决定不优化了。

文档已补充不能长按选项。

**Comment by 2315506431** [comment]
> 发现长按这个优化代价比较大。该功能应该也会在4.3下线。决定不优化了。
> 
> 文档已补充不能长按选项。

我有一个想法，虽然不知道好不好实现，就是让长按只会识别成单机一次，再按多久也不会重复触发，在本次未完成时也不进行下一次触发
