### ISSUE TITLE
[feature] js脚本中对于自动对话的支持

### ISSUE THREAD

**Issue by onglu1** [babalae/better-genshin-impact#700]
- Your feature requesting / 你的新功能请求
在运行js脚本时，默认关闭自动对话，这对于包含对话的任务不太方便完成。
例如我想实现一个自动每日，在领奖时编写领取每日奖励和探索任务的脚本比较麻烦，并且不能自动找到对话位置。
如果可以将自动对话加入到js脚本中，并支持随时开启和关闭，可以帮助完成包含对话类型的脚本。

**Comment by huiyadanli** [comment]
https://bgi.huiyadan.com/dev/js/dispatcher.html#addtimer-realtimetimer-timer

已经外露方法
