### ISSUE TITLE
[bug] Auto pathing for materials does not revive party when all is dead

### ISSUE THREAD

**Issue by ParasiteEve** [babalae/better-genshin-impact#701]
- 系统环境 / System Environment：Windows10

- BetterGI版本号 / BetterGI Version：0.35

- 问题描述 / Description of the issue：Auto pathing for materials; if I run a script made of several pathing scripts for materials, at some point I will die due to nearby enemies while pathing and BetterGI does not click the revive button to continue the script.

- 复现步骤 / Reproduction steps：Run a scripts of all materials at once and at some point the party will die, making the rest of the script unable to collect

**Comment by huiyadanli** [comment]
现在会自动复活

https://github.com/babalae/better-genshin-impact/releases/tag/0.36
