### ISSUE TITLE
[question] 0.35版本路径追踪问题

### ISSUE THREAD

**Issue by Yang-z** [babalae/better-genshin-impact#703]
1. 一个文件中有多个"type": "teleport"，时，第二个传送不触发，直接跳过了后面全部的点。（0.35）
2. 自动冲刺不能删除啊，写点位的时候只要在离目标点稍微近一点的地方再加一个点，就能保证最后一段路时走过去的。现在没了自动冲刺，就很浪费时间呀。希望恢复，或者加一个"move_mode": "run",的标识，让用户自己指定。（0.35）
3. 还可以添加一个自动冲刺游泳的move_mode。原先的自动冲刺对游泳好像不会自动持续加速。
4. 有时候是要爬墙的，可以让用户指定一个原地爬墙的超时时间，不然有些高墙爬到一半就被误判为卡死，自动下落了。

**Comment by Yang-z** [comment]
发现"move_mode": "run"是有的，只是文档里没有。那第2点没事了。

**Comment by huiyadanli** [comment]
1. 待测试
2. 0.35已经删除，也添加了run
3. 也可以使用run
4. 使用climb

**Comment by Yang-z** [comment]
感谢这么迅速的答复。
期待第1点的修复。

**Comment by Yang-z** [comment]
> 1. 待测试

是"action": "pick_around"导致的，改为"action": "" 就可以。原来是pick_around删除了呀。

**Comment by huiyadanli** [comment]
0.35.1 添加了一个 "pick_around" ，待测试

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.36
