### ISSUE TITLE
[bug] 用调度器不能连贯运行

### ISSUE THREAD

**Issue by baixi232310** [babalae/better-genshin-impact#704]
用调度器进行一连串任务，就比如最近的一条龙，除了传送自动秘境和传送到凯瑟琳，自动晶蝶，其他的比如领取历练点、委托、纪行等都不能运行，但类似的问题在上上个版本及上上上个版本基本不会出现

- 系统环境 / System Environment：Win11  2k分辨率下的1080p

- BetterGI版本号 / BetterGI Version：0.35

- 问题描述 / Description of the issue：

- 复现步骤 / Reproduction steps：

**Comment by baixi232310** [comment]
但其他人好像可以正常运行

**Comment by huiyadanli** [comment]
这些功能都是用户录制或者编写的，我无法知道你遇到的问题是什么，建议提供录屏

**Comment by baixi232310** [comment]
BV1tfmNYREjw,录屏不知为何没有bgi页面,执行的任务如图
![Uploading 3e60539a7818c0853c3576d5cc40ee7c.png…]()

**Comment by baixi232310** [comment]
![Uploading 3e60539a7818c0853c3576d5cc40ee7c.png…]()

**Comment by baixi232310** [comment]
BV1tfmNYREjw   游戏录屏

**Comment by huiyadanli** [comment]
看了，上下衔接延时不够出现的问题。我看有脚本作者加了延时脚本来着。

我这边也跳转默认延时长度吧

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.38
