### ISSUE TITLE
[bug] 升级到0.35版本后，执行自动狗粮，出现syntaxerror:unexpected string

### ISSUE THREAD

**Issue by THAS99** [babalae/better-genshin-impact#705]
- 系统环境 / System Environment：
win 11

- BetterGI版本号 / BetterGI Version：
0.35.0

- 问题描述 / Description of the issue：

升级到0.35版本后，执行自动狗粮，出现syntaxerror:unexpected string
- 复现步骤 / Reproduction steps：

升级到0.35版本后，执行自动狗粮，出现syntaxerror:unexpected string

------------------------------------------------------------------
已解决，解决方式：在脚本仓库订阅自动狗粮脚本

**Comment by huiyadanli** [comment]
1.6狗粮脚本有问题，更新1.7即可
