### ISSUE TITLE
[question] 快速商店购买和传送时特殊屏幕有鼠标偏移

### ISSUE THREAD

**Issue by mengshengzhijie** [babalae/better-genshin-impact#706]
- Problem Description / 问题描述
- 请尽量提供问题相关的截图/日志等内容
我的屏幕长宽比有点特殊，在使用工具的时候鼠标点击不到按钮，总是差一点，想请问一下快速购买商店物品的主要文件是在什么位置。我想自己改一改

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/blob/main/BetterGenshinImpact/GameTask/QucikBuy/QuickBuyTask.cs
