### ISSUE TITLE
[suggestion] 建议提供JS脚本规范

### ISSUE THREAD

**Issue by Aqua-Dream** [babalae/better-genshin-impact#708]
- Your suggestions / 你的建议

目前的JS脚本对移速的限制比较严重，但不同脚本之间没有统一的规范，比如脚本1需要琳妮特前台，脚本2需要成男/成女，会导致冲突的脚本无法进入同一个调度器组。
（话说捡狗粮为啥不能用minimap的地图追踪逻辑来着？minimap好像对角色的移速没有限制）

然后规范里面希望JS脚本不要利用角色本身的技能，只限制体型和队伍双风。比如琳妮特捡东西的路上会遇到怪物，世界9的怪物还是挺疼的，我的琳妮特小脆皮，等级没拉起来容易死在路上。

**Comment by huiyadanli** [comment]
因为脚本可以调用键鼠脚本，也可以调用路径追踪任务。狗粮和晶蝶都是存在键鼠相关操作，会受角色等多种因素影响。

你可以使用 122 点位的路径追踪狗粮，这个不受角色影响
