### ISSUE TITLE
七圣召唤骰子识别问题

### ISSUE THREAD

**Issue by yukiryo** [babalae/better-genshin-impact#71]
![image](https://github.com/babalae/better-genshin-impact/assets/58250223/d8b164f5-d91a-4083-a4d3-19c8eef52d66)
骰子识别位置错误
而且保留全 雷 冰只保留全和雷，冰骰子会被点掉

**Comment by huiyadanli** [comment]
0.16.1版本有针对优化这个问题，现在还有问题吗

**Comment by yukiryo** [comment]
> 0.16.1版本有针对优化这个问题，现在还有问题吗

新版本没问题了
