### ISSUE TITLE
[feature] 以前出过更好的鸣潮己长草未更新 现要求出 更好的归龙潮 可改过来一点

### ISSUE THREAD

**Issue by qincenhua** [babalae/better-genshin-impact#713]
- Your feature requesting / 你的新功能请求
1.更好的归龙潮
2.更新更好的鸣潮 已经长草了没有事情可以干了
3.自动上锁归龙潮角色对应词条
4.更好的原神 通过图像识别自动上锁圣义物双瀑词条
5. 更好的原神 添加js脚本自动分解四星以下圣义物
6. 更好的原神 添加js脚本刷本识别角色自动战斗
7. 更好的原神 js脚本采集路线能一键运行包括体力委托历练点领取
![Screenshot_20241017_223116](https://github.com/user-attachments/assets/ee988649-653c-4ee2-86df-5da3f4af12e6)
![Screenshot_20241017_222128](https://github.com/user-attachments/assets/a2767e07-6362-498c-89d8-4b51f3a840ed)

![Screenshot_20241017_220633](https://github.com/user-attachments/assets/887bb7ea-c309-43a5-9330-6168269ead25)

**Comment by huiyadanli** [comment]
1. 不玩
2. 已弃坑
3. 不玩
4. 以后再说
5. 近期会做
6. 没看懂你表达的什么，现在就会识别角色
7. 一条龙正在开发
