### ISSUE TITLE
[question] 七圣召唤 真人匹配打不过 别人都装上装备和圣义物我方一点没动只限制群友分享的那几个配置

### ISSUE THREAD

**Issue by qincenhua** [babalae/better-genshin-impact#714]
- Problem Description / 问题描述
- 请尽量提供问题相关的截图/日志等内容
1.七圣召唤优化通过图像识别队伍装上圣遗物核武器
2. bug 经常烧牌失败卡在界面无法退出 并且退出重进在启动脚本不动
3. 七圣召唤 里面有几个无相BOOS打不过容易暴毙 识别配对自动过
4. 自动秘境 限制角色要有护盾角色不方便 在秘境里面识别当前角色给出方案自动过在外面打材料比如BOOS突破材料也希望能自动运行
5.七圣召唤 js脚本能自动匹配把本期币打满 确保能过
6.js脚本自动锄大地材料运行打完勾选自动关机可选地区比如名刀之类材料
7.完善自动狗粮 有部分人没有林尼特或者草神无法运行js脚本 希望运行都尽量适配各位旅行者 有双风只有早抽用了狗粮没剪完就走了增加识别
8.云原神 使用脚本没反应有窗口问题不知道出在哪js脚本运行也显示异常
![IMG_20241011_135726](https://github.com/user-attachments/assets/7cbe10b0-0c31-4e42-9c5c-c4b49343de2a)

**Comment by huiyadanli** [comment]
七圣召唤功能不可用于PVP
