### ISSUE TITLE
[bug] 调度器添加路径追踪任务时找不到刚录制的脚本

### ISSUE THREAD

**Issue by DaydayupKatherina** [babalae/better-genshin-impact#715]
- 系统环境 / System Environment：
win11

- BetterGI版本号 / BetterGI Version：
0.35

- 问题描述 / Description of the issue：
先在全自动-地图追踪里面用录制编辑器录制一个脚本并保存成 未命名路径.json， 可以成功的看到录制的脚本。但回到调试器却找不到怎么添加刚录制的脚本
- 复现步骤 / Reproduction steps：
![Screenshot 2024-10-17 121754](https://github.com/user-attachments/assets/60a343b1-064a-45c7-8896-e680cebb06a6)
![Screenshot 2024-10-17 121820](https://github.com/user-attachments/assets/79337894-2d49-4012-a245-c390224c5ba4)

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.36
