### ISSUE TITLE
[suggestion] 关于自动狗粮JS脚本的优化建议

### ISSUE THREAD

**Issue by Because66666** [babalae/better-genshin-impact#718]
- 现状
很多时候没法正确找到调查点 & 调查交互后没捡起圣遗物，就直接离开了。&控制台输出部分键鼠操作延迟14ms左右。
- 分析
小地图或者键鼠录制过于死板，容易出现误差。尽管在程序运行中我并没有人工干预，但仍然无法正确获取狗粮。
- 建议
增加新的识别/判别功能：当靠近调查点时候，调整为游戏界面识别而不是小地图识别，根据调查点的闪光动画进行特征识别。识别后走到附近，交互调查后**拾取圣遗物**。_（完善拾取圣遗物这个过程）_
- 思考
能否使用简单深度学习进行判别与简短寻路？（判别指的是从游戏主界面识别调查闪光点，简短寻路指的是从识别闪光点到移动到可以交互的地方）（简单深度学习指的是层数少，推理和运算要求低，速度快，灵感来源于：[B站链接](https://www.bilibili.com/video/BV1qE421c7mU)）

**Comment by huiyadanli** [comment]
这个建议比较难，只能靠近无法判断举例，而且闪光点会被角色遮挡。

我们会通过其他方式来优化地图追踪的拾取。自动狗粮脚本中键鼠录制的部分优化就比较困难了。

3D空间寻路的相关技术应该是SLAM，而不是视频中的RL（这个代价也太高了）

**Comment by Because66666** [comment]
我的想法是利用现有的技术，只是在靠近调查点的时候额外增加一个脚本来判断。
以月莲采集为例，使用了特征识别技术，我认为可以适当移植到圣遗物调查点中。

**Comment by Because66666** [comment]
后面的想法更现实一些

**Comment by huiyadanli** [comment]
> 我的想法是利用现有的技术，只是在靠近调查点的时候额外增加一个脚本来判断。 以月莲采集为例，使用了特征识别技术，我认为可以适当移植到圣遗物调查点中。

这不是已经有了吗？

**Comment by huiyadanli** [comment]
基于地图路径追踪的 `AutoArtifacts_A_B_Extra - 狗粮ABE路线，自动拾取分解` 脚本已经非常完善
