### ISSUE TITLE
[suggestion] 建议可以和“空莹酒馆”合作共享一下地图数据

### ISSUE THREAD

**Issue by zhengzetao1** [babalae/better-genshin-impact#719]
- Your suggestions / 你的建议

“空莹酒馆”这个软件的作者有很完整的地图数据，包括但不限于材料，任务，宝箱等等，有这些数据在自动采集，寻路会有很大帮助

**Comment by qincenhua** [comment]
都有米游社了/并且还可以自行录制路线传到群文件采集更快

**Comment by huiyadanli** [comment]
空莹酒馆 的数据是人工标注，存在误差。

而且你说的数据我们有其他渠道能够获得完全精准数据。这个对路径追踪任务的制作帮助有限。
