### ISSUE TITLE
[bug] 更新新版本过后，启动时会一直提示找不到原神窗口

### ISSUE THREAD

**Issue by Johnxjj** [babalae/better-genshin-impact#727]
- 系统环境 / System Environment：
win11

- BetterGI版本号 / BetterGI Version：

0.35.0
- 问题描述 / Description of the issue：
更新新版本过后，启动时会一直提示找不到原神窗口,需要手动选择窗口

- 复现步骤 / Reproduction steps：
![image](https://github.com/user-attachments/assets/31ad7b9c-3894-4998-9464-2d355fdf09dd)

**Comment by Johnxjj** [comment]
![image](https://github.com/user-attachments/assets/62435cc0-454b-4927-98d8-5e5af88e21e1)

**Comment by Skinyi** [comment]
我们可能是一样的问题：#728，只不过我的并没有弹出这个错误提示窗口。

**Comment by huiyadanli** [comment]
和你系统有关，使用手动选择游戏窗口的功能
