### ISSUE TITLE
[bug] 打开自动TP功能后，在尘歌壶中，如果尘歌壶壶灵的有些选项的黄色没有被点掉，那么它会自动点击该黄色选项。

### ISSUE THREAD

**Issue by Tudorose** [babalae/better-genshin-impact#730]
- 系统环境 / System Environment： Windows 11

- BetterGI版本号 / BetterGI Version： 0.35.0

- 问题描述 / Description of the issue：打开自动TP功能后，在尘歌壶中，如果尘歌壶壶灵的有些选项的黄色没有被点掉，那么它会自动点击该黄色选项从而阻碍玩家正常点击洞天宝钱。 

- 复现步骤 / Reproduction steps：使用洞天百宝、制作摆设、切换形态等等选项还仍然保持黄色的账号即可复现。

**Comment by huiyadanli** [comment]
这个是自动剧情的功能，会优先点击橙色选项

你进去后把相关功能点一下就不会是黄色选项了
