### ISSUE TITLE
我想问一下遮罩窗口是怎么实现的

### ISSUE THREAD

**Issue by Smart-huhu** [babalae/better-genshin-impact#731]
是这样的，我是一个个人开发者，和你一样也是做这种游戏脚本辅助的，经常使用的技术是yolo，在24年年初我就看到有关BetterGI的介绍，当时也是用了一两个月，记得当时实现的功能只有钓鱼拾取等简单识别操作功能，当时我就很好奇了，不管是Java21还是Python3我都不能复刻出同款遮罩窗口，最多也是利用Python和C/C++在屏幕上渲染文字和图像，并不能做到字体和图形实时更新

示例代码
[示例代码.zip](https://github.com/user-attachments/files/17448669/default.zip)

我尝试过很多遮罩窗口的实现，但是经常是以黑屏/单个截屏/窗口不覆盖/不刷新等告终，BetterGI的开发语言是C#，我真的很希望在Python上复刻出来

**Comment by huiyadanli** [comment]
本质是Win32透明窗口，任何语言都可以做到。至于实时展示我也是依靠WPF本身的控件展示的，简单的方法就是直接依靠一些UI框架去做。

甚至可以直接用C#实现这个窗口，然后通过管道（其他通讯方式也可以）去推送日志展示。

**Comment by Smart-huhu** [comment]
import win32api
import win32con
import pyautogui

**Comment by Smart-huhu** [comment]
import win32api
import win32con
import pyautogui
我也是用的win32，可以看一下你的关于遮罩窗口代码片段吗，觉得应用程序在屏幕上输出日志真的很科幻！谢谢大佬
（C#和py的win32用法应该差不远）

**Comment by huiyadanli** [comment]
透明窗口

https://github.com/babalae/better-genshin-impact/blob/d23ba65d51b9f385bbf13d1eb16fb6188eb6f330/BetterGenshinImpact/View/MaskWindow.xaml#L11

WPF已经封装了，没法当作参考的

https://github.com/babalae/better-genshin-impact/blob/d23ba65d51b9f385bbf13d1eb16fb6188eb6f330/BetterGenshinImpact/View/MaskWindow.xaml#L67-L76

日志框

**Comment by Smart-huhu** [comment]
好吧，谢谢

**Comment by wnark** [comment]
用python尝试了下，用win32的方式工程量太大了，快速实现可以用tkinter，为了性能可以用pyqt5
