### ISSUE TITLE
[feature] 自动秘境 那维莱特相关

### ISSUE THREAD

**Issue by qhmw** [babalae/better-genshin-impact#732]
- Your feature requesting / 你的新功能请求
就像介绍那样 charge：长按左键。其中那维莱特重击会自动旋转。
那么这个“自动旋转”的默认速度能否增加 比如鼠标移动距离1000间隔10这样？

**Comment by huiyadanli** [comment]
会把屏幕缩放dpi和移动距离做乘算，影响元素：

* 屏幕缩放dpi（本次优化）
* 游戏帧率
* 游戏内鼠标敏感度设置（默认3）
