### ISSUE TITLE
[suggestion] 群文件希望能导入脚本仓库进行订阅直接丢进去不识别如图所示

### ISSUE THREAD

**Issue by qincenhua** [babalae/better-genshin-impact#734]
- Your suggestions / 你的建议

一条龙日常脚本群文件下载解压之后丢进去软件文件不重启再打开不识别希望能加入脚本仓库订阅
![Image](https://github.com/user-attachments/assets/f164d5ca-3b26-46ab-9264-87ca27d4bd7a)

**Comment by huiyadanli** [comment]
#735
