### ISSUE TITLE
[suggestion] 加入脚本仓库进行订阅如图所示

### ISSUE THREAD

**Issue by qincenhua** [babalae/better-genshin-impact#735]
- Your suggestions / 你的建议

![Image](https://github.com/user-attachments/assets/f01a9446-53b6-40e9-af93-d913dd060b2a)
希望能加入脚本仓库进行订阅自行解压的软件文件夹里面重启再打开不识别

**Comment by huiyadanli** [comment]
0.38 将会有官方一条龙
