### ISSUE TITLE
[bug] 使用js脚本执行自动战斗时会卡死并结束运行

### ISSUE THREAD

**Issue by 3295375783** [babalae/better-genshin-impact#736]
- 系统环境 / System Environment：
Windows 11

- BetterGI版本号 / BetterGI Version：
0.35.0

- 问题描述 / Description of the issue：
使用js脚本执行自动战斗时会卡死并提示“当前线程无法访问此对象，因为另一个线程拥有该对象”之后BetterGI会结束运行

- 复现步骤 / Reproduction steps： 
在js脚本中添加并执行这条代码
await dispatcher.runTask(new SoloTask("AutoFight"));

**Comment by huiyadanli** [comment]
确实会有这个问题，这块还没外露，因为自动战斗的结束判定还有问题

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.38
