### ISSUE TITLE
JS脚本鼠标悬浮展示描述信息

### ISSUE THREAD

**Issue by huiyadanli** [babalae/better-genshin-impact#738]
不然老是有人不知道怎么用

**Comment by HZYgrandma** [comment]
路径追踪能不能也有单独的显示实时状态的框，包含当前坐标，目标坐标，行走状态，进行的action这种

**Comment by huiyadanli** [comment]
> 路径追踪能不能也有单独的显示实时状态的框，包含当前坐标，目标坐标，行走状态，进行的action这种

在你那个P图UI展示运行任务的issue里面补充下
