### ISSUE TITLE
自动化任务时候的一些角色选择和技巧

### ISSUE THREAD

**Issue by huiyadanli** [babalae/better-genshin-impact#740]
## 自动狗粮JS脚本

需要 琳妮特
* 带冒险家圣遗物（开启各类宝箱后的5秒内，持续恢复30%生命值。是否对调查点有效？）
* 旅行剑（获得元素晶球或元素微粒时，恢复1%/1.25%/1.5%/1.75%/2%生命值。调查点会又元素微粒）

这个技巧也可以用在路径追踪中的狗粮路线

## 路径追踪

* E盾：莱依拉、绮良良、钟离（可能会爬柱子）
* 前台持续回血：芭芭拉（满命复活）、七七
* 后台回血：生命值低于40%时，**迪希雅**将基于生命值上限的20%恢复生命值，并在接下来的10秒内，每2秒基于生命值上限的6%为迪希雅恢复生命值。该效果每20秒至多触发一次。
* 采集回血：**白术**处于队伍中时，与部分采集物交互能够为队伍中自己的当前场上角色恢复生命值，回复量基于白术生命值上限的2.5%。

**Comment by emako** [comment]
最简单不是带一个芭芭拉冲鸭

**Comment by huiyadanli** [comment]
> 最简单不是带一个芭芭拉冲鸭

其实还是比较推荐盾，被怪击飞还是挺影响跑路的。

**Comment by ZedeX** [comment]
通过：https://github.com/babalae/better-genshin-impact/issues/756
+
https://github.com/babalae/bettergi-scripts-list/pull/46

可否解决这类问题？
