### ISSUE TITLE
[bug] 使用安装包版本，启动出错提示，怀疑是打包错误

### ISSUE THREAD

**Issue by UVJkiNTQ** [babalae/better-genshin-impact#745]
- 系统环境 / System Environment：
Windows 11 24H2

- BetterGI版本号 / BetterGI Version：

0.35
- 问题描述 / Description of the issue：

![Image](https://github.com/user-attachments/assets/65fd2edd-ae4c-4923-9bd2-6adee5f0455d)

- 复现步骤 / Reproduction steps：

安装包安装后，启动即可。

从报错信息来看，应该是调用的ocr组件引用了开发者的本地路径，未配置变量。

**Comment by huiyadanli** [comment]
https://bgi.huiyadan.com/faq.html#%E2%9D%93%E6%8F%90%E7%A4%BA-paddleocr%E9%A2%84%E7%83%AD%E5%A4%B1%E8%B4%A5-%E5%BA%94%E8%AF%A5%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3

**Comment by UVJkiNTQ** [comment]
Solved.
