### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by Zegic** [babalae/better-genshin-impact#746]
- 系统环境 / System Environment：

win11 24h2 amd+nvidia
- BetterGI版本号 / BetterGI Version：
0.35.0

- 问题描述 / Description of the issue：

无法正常进行操作

启动游戏后，来源于bettergi的所有操作都是无效的。包括屏幕识别、按键按下等。。就好像bettergi从未启动
![Image](https://github.com/user-attachments/assets/1926a726-242a-470e-99cb-7d76697eec8f)

- 复现步骤 / Reproduction steps：
启动游戏即可复现

**Comment by Zegic** [comment]
其他补充：屏幕分辨率2560x1600，以1920x1080的窗口化游玩。bettergi是管理员权限启动的。

**Comment by HZYgrandma** [comment]
> 其他补充：屏幕分辨率2560x1600，以1920x1080的窗口化游玩。bettergi是管理员权限启动的。

更换截图方式

**Comment by huiyadanli** [comment]
https://bgi.huiyadan.com/quickstart.html
