### ISSUE TITLE
[feature] 美化任务添加菜单

### ISSUE THREAD

**Issue by HZYgrandma** [babalae/better-genshin-impact#750]
![Image](https://github.com/user-attachments/assets/77c09e0f-c1b6-46d5-b9ab-4c413e463379)
痛点是添加treeview
如果能加上icon会更美观
搜索框不太确定后续会不会成为刚需（好像也比较难做）

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.38
