### ISSUE TITLE
[feature] 在线仓库分类调整

### ISSUE THREAD

**Issue by HZYgrandma** [babalae/better-genshin-impact#753]
![Image](https://github.com/user-attachments/assets/f88bad0c-781e-4276-b539-1dc60de707ae)
使用米游社的分类标准对任务进行分类
![Image](https://github.com/user-attachments/assets/540e5963-b1c5-40f5-8fda-9d4fc817543c)
并用卡片式菜单展示任务
![Image](https://github.com/user-attachments/assets/e9059598-770a-430a-95cc-d4edf660dda7)
并使用更直观的订阅图标
如
![Image](https://github.com/user-attachments/assets/e11d7e65-c382-4ae8-a7a7-8c50a30d5103)

**Comment by huiyadanli** [comment]
只接受改图标，树状图不是人改的

**Comment by HZYgrandma** [comment]
菜就多练

**Comment by huiyadanli** [comment]
done

![Image](https://github.com/user-attachments/assets/b5d23362-0226-4957-9eff-79fd807ecdf4)
