### ISSUE TITLE
[feature] 希望地图追踪脚本可以支持调用js脚本

### ISSUE THREAD

**Issue by ZedeX** [babalae/better-genshin-impact#756]
现状：地图追踪只有固定几种动作

遇到的问题：目前在执行采集过程中，因为会路过怪物被打或被冰冻导致执行不达预期，所以想通过切换角色调用钟离长E来霸体抗伤害，但是地图追踪的action做切换感觉会比较复杂

解决方案：感觉是不是直接使用pathing新开一个“调用js脚本”的action，会比较容易实现一些，这样通过path+js组合可以实现更多的功能，仅供参考~

**Comment by huiyadanli** [comment]
这个已经实现了，但不是通过js，新版本未发布。

action不适合做此类操作

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.36
