### ISSUE TITLE
[suggestion] 关于地图追踪功能的纳西妲的长E材料收集的建议

### ISSUE THREAD

**Issue by pkjsjq** [babalae/better-genshin-impact#757]
我发现纳西妲的长E材料收集方式是按住E后“螺旋上升”，这对四周的覆盖率不太高。在我使用“**劫波莲（纳西妲采集）@lifrom**”的地图追踪脚本时，这可能会导致在一些特殊角度（例如脚边）和高处（这是进行收集的时间太短导致的）的材料无法拾取。
如果可行的话，我建议将收集方式改为“阶梯上升”：也就是转完一圈后抬升视角一定角度，最后持续转到最高角度限制为止。

**Comment by huiyadanli** [comment]
已加快转圈速度
