### ISSUE TITLE
[suggestion] 在脚本仓库标签中补充地图追踪脚本所必须的角色或者一些必须的备注

### ISSUE THREAD

**Issue by zxygzxy** [babalae/better-genshin-impact#758]
- Your suggestions / 你的建议
在使用地图追踪进行采集的时候，脚本仓库里提供了许多已经录制好的脚本，但是有些脚本需要某些特定的角色，例如嘟嘟莲脚本需要纳西妲，这样对不知道的用户在使用的时候可能会产生错误，目前在脚本仓库里有的标注了用纳西妲进行采集，但是大部分是没有标注的，能否进行一个标注或者在详情里进行描述，谢谢！

**Comment by huiyadanli** [comment]
已添加，且下版本会加入队伍识别以及切人的功能

![Image](https://github.com/user-attachments/assets/8bcf4201-c66f-4661-97b3-24e167e88732)

https://github.com/babalae/bettergi-scripts-list/commit/67bb400422c9d9088542a8973b2a3c340bc344cd

**Comment by zxygzxy** [comment]
哥你后面全打成纳西妲了……我的意思是，第一个嘟嘟莲需要纳西妲，后面石珀需要钟离，这样刚需或者作者在录制的时候用的特殊人物标注一下就行

**Comment by huiyadanli** [comment]
石珀 是特殊情况，后面要改的
