### ISSUE TITLE
是只支持 windows 原神 PC 客户端吗？云原神PC 客户端支持吗？

### ISSUE THREAD

**Issue by taotieren** [babalae/better-genshin-impact#76]
是只支持 windows 原神 PC 客户端吗？云原神PC 客户端支持吗？
如果支持 云原神 PC 客户端的话，我有打包一个 Linux 的云原神的包？
这份代码我在 Linux 下编译一份是否也能在 Linux 下给云原神使用呢？

AUR 云原神：https://aur.archlinux.org/packages/genshin-nativefier

**Comment by emako** [comment]
没法支持，GUI等的运行环境仅支持windows系统

**Comment by huiyadanli** [comment]
很多环境都不太能跨平台，你可以尝试下。大概率不行

**Comment by taotieren** [comment]
那 windows 版本的云原神支持吗？

**Comment by huiyadanli** [comment]
支持 #17
