### ISSUE TITLE
[bug] 执行自动狗粮脚本时发生异常: "Error: The path is empty. (Parameter 'path')"

### ISSUE THREAD

**Issue by RooseveltELK** [babalae/better-genshin-impact#769]
- 系统环境 / System Environment：Windows 11 Enterprise, 26100.2161

- BetterGI版本号 / BetterGI Version：0.36.0

- 问题描述 / Description of the issue：执行自动狗粮脚本（1.9版本）后在望舒客栈报错，自动退出脚本。log如下：
- [better-genshin-impact20241106.log](https://github.com/user-attachments/files/17649323/better-genshin-impact20241106.log)

- 复现步骤 / Reproduction steps：在全自动---》JS脚本--》执行自动狗粮脚本后传送到望舒客栈捡完狗粮即出现错误。

**Comment by huiyadanli** [comment]
重新在 Release 中下载 0.36.1 版本，0.36.0版本存在bug

**Comment by RooseveltELK** [comment]
谢谢，0.36.1版本已解决！
