### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by oraclexuan** [babalae/better-genshin-impact#770]
- 系统环境 / System Environment：
win11 24H2

- BetterGI版本号 / BetterGI Version：
0.36.1

- 问题描述 / Description of the issue：
每次重新启动电脑主程序就不见了，查看了windows definder，没有被删除。必须得卸载重新安装才能正常运行。

- 复现步骤 / Reproduction steps：

As the descriptionof th issue. 额外使用了原神的帧率解锁

**Comment by huiyadanli** [comment]
https://bgi.huiyadan.com/faq.html#%E2%9D%93%E9%87%8D%E5%90%AF%E5%90%8E%E7%A8%8B%E5%BA%8F%E8%A2%AB%E5%88%A0%E9%99%A4%E4%BA%86%E6%98%AF%E4%BB%80%E4%B9%88%E6%83%85%E5%86%B5
