### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by Kev1n-mbj** [babalae/better-genshin-impact#773]
- 系统环境 / System Environment：
很普通的win11

- BetterGI版本号 / BetterGI Version：
0.36.1 2024年11月8日刚更新

- 问题描述 / Description of the issue：
**地图追踪石珀只能用纳西妲采集啊？？？？**
**钟离只能开盾 不能采集**

- 复现步骤 / Reproduction steps：
调度器调用采集石珀的地图追踪

### ad：地图追踪把e和纳西妲e区分开来

**Comment by huiyadanli** [comment]
已经临时下线此路线，后续会提供专门的action用于此类场景
