### ISSUE TITLE
[question] 2k画质2560X1440下不能使用BitBlt功能，只能使用WindowsGraphicsCapture功能，而WindowsGraphicsCapture有问题

### ISSUE THREAD

**Issue by Encountertay** [babalae/better-genshin-impact#775]
- 2k画质2560X1440下不能使用BitBlt，只能使用WindowsGraphicsCapture，而WindowsGraphicsCapture在自动剧情中老自动断开，经常会点击隐藏对话框
- 请问只是什么原因呢，

![Image](https://github.com/user-attachments/assets/122ab547-ab47-4ff9-9f5f-420b29a2d505)

**Comment by huiyadanli** [comment]
https://bgi.huiyadan.com/quickstart.html
