### ISSUE TITLE
[bug] 调度器页面，任务的通用配置与JS自定义配置窗口无法正常显示

### ISSUE THREAD

**Issue by moulai** [babalae/better-genshin-impact#776]
- 系统环境 / System Environment：
Windows 11 专业版 23H2

- BetterGI版本号 / BetterGI Version：
0.36.1/0.35.0 均有此Bug

- 问题描述 / Description of the issue：
在调度器→配置组页面，右键单击某任务，“修改通用配置”与“修改JS脚本自定义配置”窗口均无法正常弹出。
能看出窗口是有反应的，颜色稍微变化，页面上其它元素无法点击，但配置窗口并没有正常显示。此时只能按ESC键退回。

- 复现步骤 / Reproduction steps：
![Image](https://github.com/user-attachments/assets/16b3b5c9-ec40-40a9-acf2-e614afdeff6d)

**Comment by moulai** [comment]
另外，发现升级到0.36.1以后，脚本仓库→订阅→确认弹窗也无法正常显示了（但是用左右方向键挪一下点回车是有反应的，说明只是显示出了问题），这个问题在0.35.0是没有的。

已尝试卸载重装Windows Web Experience Pack和WebView2 Runtime，无法解决问题。

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/issues/653

**Comment by moulai** [comment]
谢谢，确实是这样，我因为缩放比太大，这个弹窗根本找不到，怎么也想不到是这个原因啊……折腾了一晚上WebView Orz
