### ISSUE TITLE
[bug] 自動秘境 偵測房主錯誤

### ISSUE THREAD

**Issue by PICDarcy** [babalae/better-genshin-impact#777]
- 系统环境 / System Environment：
win11
解析度為1600x900
- BetterGI版本号 / BetterGI Version：
0.36.1

- 问题描述 / Description of the issue：
- 自動秘境時 多人連機 偵測房主錯誤 此情況在 2 3 4 人世界都會發生 但是在自己世界是房主時 會偵測在別人世界 
- 复现步骤 / Reproduction steps：

到加入世界 開始自動秘境就會錯誤
如圖片所示 我是2P  
建議可抓取左上 1P 2P 3P 圖片來辨識

**Comment by PICDarcy** [comment]
![Image](https://github.com/user-attachments/assets/59e36d6e-589c-4b61-9354-c58a105e9f91)
![Image](https://github.com/user-attachments/assets/ccbb9dd5-664b-4ba5-bf25-b985c6817874)

**Comment by huiyadanli** [comment]
![Image](https://github.com/user-attachments/assets/f3840242-a999-46c6-8e72-f1894621391e)

**Comment by huiyadanli** [comment]
看上去是判断写反了

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.37
