### ISSUE TITLE
[feature] 希望增加走到冒险家协会和合成台的功能

### ISSUE THREAD

**Issue by e0r** [babalae/better-genshin-impact#785]
- Your feature requesting / 你的新功能请求

用地图追踪不够精确，之前用键鼠录制可以做到，不够后来有个人老是走来走去干扰，也不精确了

**Comment by huiyadanli** [comment]
地图追踪配合图像识别足以。


相关功能已实现未发布
https://github.com/babalae/better-genshin-impact/commit/3c2739c5c54e482fb392209cf24ab5817b8b791b

**Comment by mortal1976** [comment]
> 地图追踪配合图像识别足以。
> 
> 相关功能已实现未发布 [3c2739c](https://github.com/babalae/better-genshin-impact/commit/3c2739c5c54e482fb392209cf24ab5817b8b791b)

感谢，期待早日发布。
另外希望增加任务完成让电脑关机或睡眠的选项。

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.38
