### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by chentaoinbox** [babalae/better-genshin-impact#786]
- 系统环境 / System Environment：
联想小新笔记本 AMD Ryzen 7 5700U with Radeon Graphics  1.80 GHz  
RAM  16GB
云原神平台，采用云原神专用捕获

- BetterGI版本号 / BetterGI Version：
0.36.1

- 问题描述 / Description of the issue：
地图追踪在启用后，等带文件加载闪退
将其放于调度其中也有此问题

- 复现步骤 / Reproduction steps：
运行地图追踪/加入调度器后运行追踪（树王圣体菇）
游戏位置与天水丛林锚点，队伍钟离，心海等，无双凤

**Comment by huiyadanli** [comment]
闪退后，在 windows 事件查看器中找到具体报错，发上来看看

**Comment by chentaoinbox** [comment]
From: 辉鸭蛋
Date: 2024-11-14 11:17
To: babalae/better-genshin-impact
CC: chentaoinbox; Author
Subject: Re: [babalae/better-genshin-impact] [bug] (Issue #786)
闪退后，在 windows 事件查看器中找到具体报错，发上来看看

**Comment by huiyadanli** [comment]
无回应，关闭
