### ISSUE TITLE
[feature] 能不能以js脚本的方式实现一键全自动过剧情

### ISSUE THREAD

**Issue by CGangel** [babalae/better-genshin-impact#787]
如题，目前的自动剧情是自动跳过+自动选择对话框，除此以外都要自己做（比如传送、移动、打怪）之类的
每次传说任务和活动任务的剧情又臭又长，即便开了自动剧情，也是不可避免地心神疲惫。

所以，忽然有了一个奇思妙想，能不能以js脚本的方式来实现全自动过剧情？
目前js脚本已经支持大世界传送+跑图+打怪了，再配合目前的自动剧情，理论上讲，实现一键全自动剧情，似乎并没有太大的技术难度？

**Comment by huiyadanli** [comment]
差个寻路，而且你低估了完全实现这个愿想的工作量。

而且路径追踪在部分地区难以运作。

短时间内不会考虑做这个
