### ISSUE TITLE
[feature] 关于地图追踪功能的问题

### ISSUE THREAD

**Issue by zpf279898050** [babalae/better-genshin-impact#790]
最近尝试用地图追踪制作捡狗粮脚本遇到一些比较难受的问题，一个是定位不够精确，同样的路线可能每次跑都会有偏差，还有在某些特定位置必然会触发镜头乱晃的情况，这种位置在路途中的话其实还好，如果是在目标点附近，那经常会浪费非常多的时间。
其次是pick_around功能非常鸡肋，只会乱跑乱跳，还不如在点位附近多添加几个目标点来得稳定，实在做不好就删了吧，每个点位的情况都不一样，乱跑乱跳反而可能会出现爬墙、掉下去、捡到非狗粮调查点等问题，有些狗粮和非狗粮点是紧挨着的，这个时候我只想捡狗粮。
建议增加基础动作技能和切人等动作功能，然后用户还可以把基础动作技能和切人做成自定义的组合动作，这样的话就可以用脚本实现很多功能。比如E技能跑图和爬山，钟离挖矿等之前无法实现的操作。

**Comment by huiyadanli** [comment]
pick_around 已经重置
自定义策略也已经添加，详情见文档
https://github.com/babalae/better-genshin-impact/releases/tag/0.38
