### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by gyyc96** [babalae/better-genshin-impact#791]
- 系统环境 / System Environment：
win11

- BetterGI版本号 / BetterGI Version：
0.361

- 问题描述 / Description of the issue：
启动BetterGI后会导致鼠标时不时出现卡顿无法移动，停止软件后又恢复正常

- 复现步骤 / Reproduction steps：
启动后都会出现

**Comment by huiyadanli** [comment]
参考这个 https://github.com/babalae/better-genshin-impact/issues/286

本质是软件消耗了太多CPU导致的，建议使用BitBlt的截图方式。Win11下 BitBlt截图方式不可用的解决方法 #92

**Comment by gyyc96** [comment]
按照操作设置问题依旧，更新了0.37版本也一样
