### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by suimeng-zero** [babalae/better-genshin-impact#792]
- 系统环境 / System Environment：
win11  23h2

- BetterGI版本号 / BetterGI Version：
0.36 最新版

- 问题描述 / Description of the issue：
独立任务 自动七圣召唤 无法识别界面元素

选择初始卡牌确认后就会报错：

> [15:57:41ERR]在图像1920x1080中查找模板，名称：InCharacterPick，R0I位
 置960x600,区域960x600,边界溢出！
 [15:57:41ERR]0<= roi.x && 0 <=roi.width && roi.x + roi.width
<= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height
<= m.rows

- 复现步骤 / Reproduction steps：
设置延时5000毫秒没用
试过每周挑战，角色邀约，都不行
多次尝试，我这里100%报错

**Comment by huiyadanli** [comment]
自动拾取是否能够正常使用

**Comment by suimeng-zero** [comment]
可以

辉鸭蛋 ***@***.***> 于 2024年11月16日周六 23:26写道：

**Comment by huiyadanli** [comment]
重启软件就能解决这个问题
