### ISSUE TITLE
[feature] 建议开发和开放更多api以实现对任务的完全控制

### ISSUE THREAD

**Issue by mfkvfhpdx** [babalae/better-genshin-impact#794]
例如，我想实现，调度器挂机到4点，停止当前调度器任务A，执行狗粮任务，狗粮任务执行完,接着执行完一条龙，在执行前面调度器未完成的任务A
所以建议开发和开放以下相关api和功能
1、调度器任务关闭方法，返回当前任务节点。
2、调度器任务开始方法，支持传入任务节点参数，能从指定节点开始任务
3、在js脚本中能调用其他的js任务，包括和1、2一样的相关开始结束方法
4、建议增加lib文件夹，能自行引入公用方法，供js脚本复用
5、队伍切换api

**Comment by luguoyixiazi** [comment]
附议，如果暴露更多API能基于js自己编写脚本适应设备，比如onnx出识别结果的，可以让脚本有更多控制权

**Comment by huiyadanli** [comment]
1、2、3 不考虑，有违背基础设计，且有其他解决方案。

4. 已经补充文档  https://bgi.huiyadan.com/dev/js/create.html#manifest-json。 `"library": ['src']` 可以导入指定文件夹内的js方法，使用难度较高，需要对 js 以及 [ClearScript](https://github.com/microsoft/ClearScript/tree/master) 有较深的理解才能使用。
6. 队伍切换 https://bgi.huiyadan.com/dev/js/genshin.html#switchparty-string-partyname
7. OCR以及图像识别后续会编写文档，当前实际已经暴露（未测试）
