### ISSUE TITLE
获取不到云原神画面

### ISSUE THREAD

**Issue by Gaoxiang2002** [babalae/better-genshin-impact#795]
# 获取不到云原神画面
## 以下三个云原神的窗口前两个是全黑的，第三个是全灰的，总之就是没有有效画面
![Image](https://github.com/user-attachments/assets/2c65df8d-59cc-4460-8589-e2cf3bb1c28f)
## 使用的以下设置
截图器设置，也尝试过其他截图模式，也没有截到画面
![Image](https://github.com/user-attachments/assets/7f9c8e16-7657-4170-8449-315009bf221c)
软件设置
![Image](https://github.com/user-attachments/assets/a1cbe23e-fa3f-44b1-bc47-64e354adfe38)
win11显示卡设置
![Image](https://github.com/user-attachments/assets/ab6a22f3-14e9-4d32-93cc-08f12f628a54)

**Comment by huiyadanli** [comment]
WGC模式，三个窗口都试试
