### ISSUE TITLE
[bug] 脚本仓库一点订阅就卡死

### ISSUE THREAD

**Issue by DaydayupKatherina** [babalae/better-genshin-impact#796]
- 系统环境 / System Environment：
WIndows11

- BetterGI版本号 / BetterGI Version：
0.36.1

- 问题描述 / Description of the issue：
自从更新0.36.1之后， 在脚本仓库点任何一个订阅都会让整个程序卡住，只能通过任务管理器强制关闭bettergi。 上一版本还没有这问题

- 复现步骤 / Reproduction steps：
在bettergi选脚本仓库，然后在脚本仓库点任何一个订阅都会让整个程序卡住，只能通过任务管理器关闭。

**Comment by huiyadanli** [comment]
没见过的场景，尝试更新下系统中的 webview2
