### ISSUE TITLE
[feature] 增加清除执行日志的功能,同时增加快捷键的清屏功能,

### ISSUE THREAD

**Issue by static7** [babalae/better-genshin-impact#797]
- Your feature requesting / 你的新功能请求

![Image](https://github.com/user-attachments/assets/a11357dd-5999-480d-90ea-1ff0ffb2210b)
增加一键清屏的功能, 就是清理日志的功能

**Comment by huiyadanli** [comment]
![Image](https://github.com/user-attachments/assets/0491898a-b24a-4d96-94f1-482b8a7b437e)

可以使用这个功能
