### ISSUE TITLE
[question] 一直启动失败。显示无法传送

### ISSUE THREAD

**Issue by hzxszjl** [babalae/better-genshin-impact#798]
- Problem Description / 问题描述
- 请尽量提供问题相关的截图/日志等内容
- 点击启动运行调度器。。
- 然后一直是显示传送失败[better-genshin-impact20241120.log](https://github.com/user-attachments/files/17827371/better-genshin-impact20241120.log)
[better-genshin-impact20241120.log](https://github.com/user-attachments/files/17827379/better-genshin-impact20241120.log)

复现过程：1.打开[better-genshin-impact]
2.点击启动-better gi 截图器-启动
3.点击-全自动-调度器-选择配置组-运行。

**Comment by hzxszjl** [comment]
系统版本-windows 10
better gi版本0.36.1

**Comment by hzxszjl** [comment]
![Image](https://github.com/user-attachments/assets/29b859d7-2123-4e5b-b7fb-7b2a8c3ec797)
然后这个是游戏界面截图。启动后一直不动。

**Comment by huiyadanli** [comment]
System.Exception: Some simulated input commands were not sent successfully. The most common reason for this happening are the security features of Windows including User Interface Privacy Isolation (UIPI). Your application can only send commands to applications of the same or lower elevation. Similarly certain commands are restricted to Accessibility/UIAutomation applications. Refer to the project home page and the code samples for more information.

人话：被杀毒软件拦截了
