### ISSUE TITLE
钓鱼框识别有问题

### ISSUE THREAD

**Issue by Nats-ji** [babalae/better-genshin-impact#8]
导致钓不上来鱼。
![image](https://github.com/babalae/better-genshin-impact/assets/13299626/fe9141e5-02e8-4573-90e6-6191b0986850)
![image](https://github.com/babalae/better-genshin-impact/assets/13299626/f2beb444-03a2-458e-8f1b-8cc6ddb78a7d)

**Comment by huiyadanli** [comment]
重启软件重新进入钓鱼试试
