### ISSUE TITLE
[bug] 自动拾取会对“查看本期签文”起作用

### ISSUE THREAD

**Issue by jiemoL** [babalae/better-genshin-impact#800]
- 系统环境 / System Environment：
Windows 11 23H2

- BetterGI版本号 / BetterGI Version：
0.36.1

- 问题描述 / Description of the issue：
在幻想真剧诗的剧演准备间中，自助运势占卜机在抽签后会出现选项“查看本期签文”。
自动拾取功能会不断点击此选项。
希望把“查看本期签文”加入默认的黑名单。

- 复现步骤 / Reproduction steps：
1.开启”自动拾取“功能
2.前往”剧演准备间“ 并移动至地图左下角的”自助运势占卜机“。
3.抽签
4.回到主界面

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.38
