### ISSUE TITLE
自动寻路时开风之翼会卡死+闪退

### ISSUE THREAD

**Issue by wuyan1337** [babalae/better-genshin-impact#805]
- 系统环境 / System Environment：
Intel(R) Core(TM) i9-14900K   3.20 GHz
RTX4080 super
win11 23H2 22631.4460

- BetterGI版本号 / BetterGI Version：
0.36.1

- 问题描述 / Description of the issue：
自动寻路时开风之翼会卡死+闪退

- 复现步骤 / Reproduction steps：
https://x.ws28.cn/f/fmy4rc4quox 复制链接到浏览器打开

**Comment by HZYgrandma** [comment]
这种情况是可以稳定复现的吗

**Comment by Linkows** [comment]
貌似第一次卡退后再进游戏去同一个点位那个点位就没问题了，但其他点位还是会卡退（重启原神之后对应点位不再复发）

重启betterGI和原神后所有点位都会卡退

**Comment by HZYgrandma** [comment]
之前有用户反应他使用BGI时莫名其妙闪退，后来发现把微星主板的游戏模式关掉就不会出问题了，考虑到最近14代酷睿的缩肛问题，感觉是硬件问题的可能性大一点

**Comment by Linkows** [comment]
确实卡退的时候cpu温度会飙高

**Comment by huiyadanli** [comment]
较少个例，我也不知道为什么
