### ISSUE TITLE
[feature]新角色入队路径追踪失效

### ISSUE THREAD

**Issue by ligodamn** [babalae/better-genshin-impact#806]
建议添加角色识别的开关设置，以防新角色入队导致路径脚本无法运行。或者有其它解决方案。

![Image](https://github.com/user-attachments/assets/21078dd2-ee7c-47af-a60b-ed91bcf3eea5)

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.37
