### ISSUE TITLE
[bug] 5.2 自动秘境领取奖励时点击跳过会点到锁定辅助按钮

### ISSUE THREAD

**Issue by ZoftTy** [babalae/better-genshin-impact#807]
- 系统环境 / System Environment：

Windows 11 24H2 26100.2454

原神分辨率: 1920x1080，使用 [fps_unlocker v3.3.0](https://github.com/34736384/genshin-fps-unlock) 解锁 FPS

- BetterGI版本号 / BetterGI Version：

0.36.1

- 问题描述 / Description of the issue：

5.2 版本领取圣遗物秘境奖励页面在右上角添加了一个锁定辅助按钮

![Image](https://github.com/user-attachments/assets/007a3137-7f5e-4e5b-a8ca-b7c4d2740631)

自动秘境领取奖励时点到了锁定辅助按钮

- 复现步骤 / Reproduction steps：

在 5.2 版本中，运行自动秘境

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.37
