### ISSUE TITLE
[bug] 自动秘境续战功能部分副本可能出现错误判断

### ISSUE THREAD

**Issue by ufoccjipo7** [babalae/better-genshin-impact#809]
自动秘境连战时，使用的是奔跑到钥匙处互动开启战斗，但新版本续战出生点位于钥匙附近，导致部分副本（如纳塔天赋本：蕴火的幽墟）识别到钥匙互动按钮时，由于奔跑距离较大，可能错过互动按键出现时机，从而不触发开始战斗。

建议：续战使用步行，不奔跑，避免速度过快奔跑距离过远导致错过互动时机。

**Comment by huiyadanli** [comment]
![Image](https://github.com/user-attachments/assets/23fd9fab-ec3c-4915-8007-8be2f1453c57)
