### ISSUE TITLE
[bug] 地陵龛无法自动拾取.

### ISSUE THREAD

**Issue by static7** [babalae/better-genshin-impact#810]
- 系统环境 / System Environment：
windows11

- BetterGI版本号 / BetterGI Version：
0.37.0

- 问题描述 / Description of the issue：
地陵龛无法自动拾取材料, 还有混合材料(圣遗物, 材料等混合)宝箱, 无法自动拾取, 也就是说当宝箱内的东西大于6个 出现滚动条的时候 无法自动拾取

- 复现步骤 / Reproduction steps：
![Image](https://github.com/user-attachments/assets/3dba0130-eb07-404e-a1a5-d0bee3da3d21)

**Comment by huiyadanli** [comment]
无滚动条的情况下无法自动拾取，暂时没有想要解决的打算
