### ISSUE TITLE
[feature] 自動秘境希望增加多人連機時按鍵點擊

### ISSUE THREAD

**Issue by PICDarcy** [babalae/better-genshin-impact#812]
- Your feature requesting / 你的新功能请求

如題 目前的自動秘境動作是單人秘境的動作
像是必須開鑰匙才會到戰鬥步驟 如果非房主 可以不用開
以及到達之後 房主等待10秒 現在直接跑也可以一樣會繼續
但非房主的話 在房主按下繼續後 不會自動接受 希望可以判斷等待房主繼續 或是退出

**Comment by 3364729893** [comment]
联机开自动，没必要吧？单机自动刷就是了，联机是不是还要考虑房主开的时间及断开链接的问题？

**Comment by huiyadanli** [comment]
只考虑多人情况下的识别是否存在问题，不考虑支持多人功能。
