### ISSUE TITLE
[suggestion] 地图追踪飞行模式下镜头抖动问题修改思路

### ISSUE THREAD

**Issue by phligl** [babalae/better-genshin-impact#814]
- Your suggestions / 你的建议

1. 视角抖动大多是由于经过复杂地图视角方向识别失效，我的建议是在飞行模式下仅仅在路径开始阶段做视角调整操作，因为设计飞行的路径受干扰的可能性小，保持直线飞行即可。缺点是这种方案在遇到初始点的镜头识别错误时会直接往错误的方向飞。
2. 第二种思路是给视角方向识别添加一个置信度参数，置信度过低时使用历史数据作为当前方向。缺点是如果路径上大量的点都置信度低的话就完全没办法走了。
3. 第三种思路是直接获取鼠标移动距离和转动角度的关系，与视角识别互相佐证，可以借助思路二中的置信度。
4. 第四种最简单直接的就是修正视角识别的算法，我对图像识别不太懂，目前使用cv2的库，可否通过大量打标的数据集训练神经网络去处理。缺点是工作量非常大，运行过程中可能比cv2更耗费资源？
PS：问题不仅出现在飞行模式，部分行走也会遇到类似问题。仅纸上谈兵，如有不切实际之处勿怪。

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/pull/835
