### ISSUE TITLE
[feature] Win11启动软件后自动关闭游戏窗口化优化，能否在关闭软件时自动打开？

### ISSUE THREAD

**Issue by hyqinglan** [babalae/better-genshin-impact#817]
- Your feature requesting / 你的新功能请求

如题，现在我为了防止用完后忘记打开，都不敢开启这个新功能

**Comment by huiyadanli** [comment]
这个打开能优化你的游戏体验吗。感觉是意义不大的功能

**Comment by hyqinglan** [comment]
> 这个打开能优化你的游戏体验吗。感觉是意义不大的功能

我每次用BetterGI的时候都是先手动关闭游戏窗口化优化，然后用完再手动开启游戏窗口化优化。现在BetterGI内置了自动关闭游戏窗口化优化，但没有内置自动开启游戏窗口化优化

**Comment by hyqinglan** [comment]
> 我的意思你一直关闭没影响就一直关闭。这个功能打开并不能在肉眼程度上提升你的游戏体验。
> 
> 针对你这个需求我还要再加一个配置项来自动开启。对于整个软件来说是无用的。
> 
> 如果不新增选项，直接判断之前的状态并在软件关闭后还原，那针对小白用户就没法起到打开软件就能用BitBlt的目标了

一直关闭肯定是有影响的。那我只能继续手动了。
