### ISSUE TITLE
[suggestion] 自动拾取建议屏蔽世界任务里的特殊对话

### ISSUE THREAD

**Issue by Mqpzi** [babalae/better-genshin-impact#822]
如图这种任务流程需要跟小龙对话的，文字前面会有爪子图标，或许可以靠这个来识别？不然太快了还没看清文字就自动被点掉了![Image](https://github.com/user-attachments/assets/a034fd6a-1a26-43c7-aab2-71f654be9a0f)

**Comment by huiyadanli** [comment]
看下左下角的识别文字，加入到自动拾取黑名单即可

**Comment by Mqpzi** [comment]
意思是手动把文字加入黑名单吗，可是这种任务里的选项每句话都不一样，也不可能提前知道内容

**Comment by huiyadanli** [comment]
我也不能提前知道阿

有一个加一个
