### ISSUE TITLE
[bug] 最新5.2适配版本 自动剧情并没有使用F 还是在用Space 导致无法自动选择选项

### ISSUE THREAD

**Issue by duyh90** [babalae/better-genshin-impact#824]
- 系统环境 / System Environment：Win 11

- BetterGI版本号 / BetterGI Version：0.37.1

- 问题描述 / Description of the issue：最新5.2适配版本 自动剧情并没有使用F 还是在用Space 导致无法自动选择选项 剧情结束后可以看到人物一直在跳

- 复现步骤 / Reproduction steps：

**Comment by duyh90** [comment]
hmm重新启动原神fix the issue

**Comment by duyh90** [comment]
我是在原神开着的时候下载了BetterGI然后启动 感觉这种情况下会使用Space 重启原神就用F了 剧情结束人物也不跳了 maybe some weird bug

**Comment by huiyadanli** [comment]
会判断是否前后台的，前台还是使用的Space
