### ISSUE TITLE
[feature] 希望增加网页大地图位置追踪功能

### ISSUE THREAD

**Issue by segeix** [babalae/better-genshin-impact#827]
- Your feature requesting / 你的新功能请求

目前已经拥有基于地图追踪的许多脚本功能，希望能增加一个观测枢-提瓦特大地图的地图定位功能，能在网页大地图上显示目前的坐标，方便使用。
目前已有的具有类似功能的项目有：
https://github.com/YuehaiTeam/zhiqiong       (志琼，已经停更)
https://yuanshen.site/docs/    (空荧酒馆，非官方地图，且需要客户端)

**Comment by huiyadanli** [comment]
暂无此类打算
