### ISSUE TITLE
[bug] 启动自动伐木功能提示 "请先装备小道具王树瑞佑"

### ISSUE THREAD

**Issue by whyhhh** [babalae/better-genshin-impact#833]
- 系统环境 / System Environment：
处理器	AMD Ryzen 5 7500F 6-Core Processor                3.70 GHz
机带 RAM	32.0 GB (31.7 GB 可用)
版本	Windows 11 专业版
版本号	23H2

- BetterGI版本号 / BetterGI Version：
0.37.1

- 问题描述 / Description of the issue：
![Image](https://github.com/user-attachments/assets/e52c385e-fa25-4484-a597-2d25648b5b7f)
![Image](https://github.com/user-attachments/assets/9d7ac71f-f67d-40c5-b986-8f427b55acb5)

- 复现步骤 / Reproduction steps：
启动原神
启动betterGI
通过快捷键或者按钮启动自动伐木功能

**Comment by emako** [comment]
游戏分辨率？

**Comment by huiyadanli** [comment]
请完整阅读文档 https://bgi.huiyadan.com/quickstart.html
