### ISSUE TITLE
进入脚本仓库点击订阅后无响应

### ISSUE THREAD

**Issue by xinyang233** [babalae/better-genshin-impact#839]
- 系统环境 / System Environment：Windows 10 专业版22H2

- BetterGI版本号 / BetterGI Version：BetterGI_v0.37.1

- 问题描述 / Description of the issue：已更新最新版游戏和BetterGI，并安装在英文路径下，以管理员身份运行，其他功能正常。当打开脚本仓库后，加载出脚本页面可正常查阅，但是只要点击订阅，BetterGI和脚本仓库2个页面都会无响应，长时间等待无效，重启和重新安装软件都无效。在[0.35]版本时可正常订阅使用，烦请帮忙定位故障原因并给出解决方案，感谢！

- 复现步骤 / Reproduction steps：打开软件，进入脚本仓库，点击订阅即卡死。详情请参见附件：https://github.com/user-attachments/assets/8462fe59-eb6a-49df-9884-5220aef0f9e9

**Comment by huiyadanli** [comment]
尝试使用在线版， https://bgi.sh/

**Comment by xinyang233** [comment]
使用在线版，点击订阅后会复制订阅链接，粘贴到浏览器后提示：有个网站想打开BetterGI，点击打开后，BetterGI同样无响应，强行关闭后弹出程序异常，详见附图。![Image](https://github.com/user-attachments/assets/63ad6eb4-e3ff-43ed-bbec-a508668660b7)
![Image](https://github.com/user-attachments/assets/c8217e88-1999-40e3-a0d8-368d0eb19d80)
![Image](https://github.com/user-attachments/assets/c324fa54-fda3-4069-89d5-976025ff0733)
![Image](https://github.com/user-attachments/assets/24d5aea8-8c4f-4d43-95a8-a672416c81e2)
![Image](https://github.com/user-attachments/assets/fd305bdc-2f28-49df-b31b-3da131841464)
![Image](https://github.com/user-attachments/assets/15e013e2-3706-4558-a00b-8f47b29b75db)

**Comment by xinyang233** [comment]
已手动安装.NET 9.0 运行时且无安全软件和防火墙，无效。
已暂时解决：通过[bettergi-scripts-list](https://github.com/babalae/bettergi-scripts-list)手动下载需要的文件，移动到对应文件夹，达到订阅效果。
感谢BetterGI带来的体验！

**Comment by emako** [comment]
这个是BGI的单例冲突了？

**Comment by Senstino** [comment]
遇到同样的问题，未解决
