### ISSUE TITLE
[bug]调度器中存在多个配置组连续执行时，f11快捷键无法关闭全部任务

### ISSUE THREAD

**Issue by ironcz** [babalae/better-genshin-impact#842]
- 系统环境 / System Environment：
Windows11系统

- BetterGI版本号 / BetterGI Version：
0.37.1

- 问题描述 / Description of the issue：
1、调度器中添加了很多个配置组，我是将每个采集物单独设置了一个配置组。
2、选择连续执行，全选配置组，随后开始执行。
3、当我希望停止采集任务时，按f11快捷键关闭了程序（遮罩窗口已消失），但马上又会自动开启程序，运行下一个配置组。
4、继续按f11快捷键，程序会停止当前的配置组，去运行下一个配置组。假如我有100个配置组，我需要按100次f11才能完全退出。

- 复现步骤 / Reproduction steps：
如上

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.38
