### ISSUE TITLE
[bug] alk+鼠标移动的回放失败

### ISSUE THREAD

**Issue by heyuanYao-pku** [babalae/better-genshin-impact#843]
- 系统环境 / System Environment：
Win11

- BetterGI版本号 / BetterGI Version：
0.37

- 问题描述 / Description of the issue：
在录制时使用alt+鼠标移动。看json文件确实录制了alt键的按下和释放。但是回放时没有出现相同效果，鼠标移动变成了转镜头。

- 复现步骤 / Reproduction steps：

**Comment by heyuanYao-pku** [comment]
群消息里说修复了，感谢！

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/commit/294d0962299d7114c7a7ca4c150f4062cd997ce5
