### ISSUE TITLE
[suggestion] 原神程序启动相关 关于使用质量上的一个小建议

### ISSUE THREAD

**Issue by Ropgrc** [babalae/better-genshin-impact#845]
每次打开游戏后都要手动启动 BGI ，即使设置了全局按键也觉得手动还是有些不方便。
如果使用 BGI 启动游戏的话，就没办法启动 GIMI（3dmigoto） 和 unlock fps ，所以我都是用 XXMI 来启动原神，原神打开后手动启动 BGI。
能不能实现一个功能， BGI 监听 yuanshen.exe 程序是否存在，如果存在先让程序 sleep 50 秒来等待玩家进入游戏中，然后自动开启 BGI 。

这是关于使用质量上的一个小建议。

**Comment by huiyadanli** [comment]
可以参考 #359 
建立一个bgi的快捷方式，并添加start参数，那程序启动后会自动启动截图器

**Comment by Ropgrc** [comment]
> 可以参考 [#359](https://github.com/babalae/better-genshin-impact/issues/359) 建立一个bgi的快捷方式，并添加start参数，那程序启动后会自动启动截图器

成功了！问题解决。
