### ISSUE TITLE
许愿个自动捡狗粮

### ISSUE THREAD

**Issue by G-T-L** [babalae/better-genshin-impact#85]
虽然感觉难度有点大，好像也用不上啥图像识别技术只能以传送点为点位直接录制移动脚本？那样就纯靠工作量去堆了但好像也不见得能稳定。。。  但要是真有的话那可太舒服了qaq

**Comment by huiyadanli** [comment]
只要纵深不大能做的

**Comment by G-T-L** [comment]
> 只要环境纵深不大，还是能做的。
> 
> 但是效果的话，只能说抓抓传送点附近的晶蝶应该没问题。。

还别说  每天顺路自动毛点晶蝶还真不赖  不需要多   几只就行  然后再把这些东西整个可自定义的每日自动大任务   比如把自动打矿 派遣 领委托奖励 捡狗粮或者其他材料  或者直接把打本也加进去得了  每天上线做个活动再把历练点领了  然后再点个自动直接完事

**Comment by goldenapple1** [comment]
有点tb工作室的味儿了😂

**Comment by Yukari42015050831** [comment]
如果可以的话我更想要个自动寻怪的，刷材料最烦跑路了

**Comment by Normal-pcer** [comment]
我去，我的电脑在自动玩原神😨

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.34

自带了一个脚本
