### ISSUE TITLE
[bug]自动拾取狗粮中途出现报错：“识别大地图位置失败”

### ISSUE THREAD

**Issue by jdy18** [babalae/better-genshin-impact#859]
- 系统环境 / System Environment：
Windows11

- BetterGI版本号 / BetterGI Version：
0.34.1

- 问题描述 / Description of the issue：
自动拾取狗粮中途出现报错：“识别大地图位置失败”
![Image](https://github.com/user-attachments/assets/3a114cb5-b7ce-4976-a5f9-fae40e57497f)
分别率改成16:9后仍有该问题

- 复现步骤 / Reproduction steps：
- 自动拾取狗粮功能，前面正常，到前往荻花洲的时候出错

**Comment by huiyadanli** [comment]
请更新最新版
