### ISSUE TITLE
打开软件就卡

### ISSUE THREAD

**Issue by 2315506431** [babalae/better-genshin-impact#86]
只要打开软件，无论是否开启任何功能，哪怕是主开关，都会引起原神很多非正常卡顿，是否能修复这个问题。

**Comment by 2315506431** [comment]
打开地图尤为明显，也可能是我渣机有一部分原因，但平时是流畅的，打开软件即使不开任何功能，就会卡顿

**Comment by huiyadanli** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/15783049/47abedea-92bf-4e15-8046-d5e4b5af1158)

**Comment by 2315506431** [comment]
鉴定完了，是因为关了窗口化游戏优化导致的，重新开了就不卡了

**Comment by emako** [comment]
> 鉴定完了，是因为关了窗口化游戏优化导致的，重新开了就不卡了

想问问配置，关了窗口化优化会卡

**Comment by emako** [comment]
> 鉴定完了，是因为关了窗口化游戏优化导致的，重新开了就不卡了

想问问配置，关了窗口化优化会卡

**Comment by 2315506431** [comment]
> > 鉴定完了，是因为关了窗口化游戏优化导致的，重新开了就不卡了
> 
> 想问问配置，关了窗口化优化会卡

i5-7500
GTX 1050 Ti
16GB
