### ISSUE TITLE
[suggestion] 全自动时多人队伍变更建议

### ISSUE THREAD

**Issue by zhangyina1** [babalae/better-genshin-impact#860]
1号位恰斯卡，2号位纳西妲，进入材料号采集鸟蛋，进来了个广子，变成了地主2个角色，我单个1号位纳西妲，3p广子占个位，广退出后我变成了1号位纳西妲2号位恰斯卡，全自动依然认为2号位才是纳西妲，每次要e转圈时都切到2号位恰斯卡
一个简单的解决办法是1进世界前就把1号位设为纳西妲
另一个解决方法是每次使用技能前（或其他时机？）重新检测一下队伍列表

**Comment by huiyadanli** [comment]
不考虑
