### ISSUE TITLE
[bug]请补充标题内容

### ISSUE THREAD

**Issue by Lawson075720** [babalae/better-genshin-impact#864]
- 系统环境 / System Environment：

PC win 11 b服
- BetterGI版本号 / BetterGI Version：

0.37.1
- 问题描述 / Description of the issue：
自动伐木失败，没有自动平a

- 复现步骤 / Reproduction steps：

视频

**Comment by Lawson075720** [comment]
视频传不上来，我发个网盘链接吧（第一次用GitHub

**Comment by Lawson075720** [comment]
通过网盘分享的文件：Yuan Shen 原神 2024.12.17 - 23.52.00.01.zip
链接: https://pan.baidu.com/s/1pTAGXsEtb9a4ae_GKftEhQ?pwd=bqbt 提取码: bqbt 
--来自百度网盘超级会员v4的分享

**Comment by MisakaAldrich** [comment]
请问是否装备须弥3级声望奖励道具"王树瑞佑"

**Comment by huiyadanli** [comment]
看了下自动伐木的独立任务，这个就是上下线伐木的，使用前先看文档
