### ISSUE TITLE
[bug]联机时复苏功能异常

### ISSUE THREAD

**Issue by johsang** [babalae/better-genshin-impact#865]
- 系统环境 / System Environment：
win10LTSC21H2 1080p其他全开最低

- BetterGI版本号 / BetterGI Version：
0.37.2

- 问题描述 / Description of the issue：
联机时死亡，log尝试复苏，但实际上并没有成功，之后一直log传送失败

**Comment by huiyadanli** [comment]
提供下相关截图，如果有录屏就更好了。

全队死亡复苏的问题好像单机也有，不过单机是切换队伍场景出现的。这个问题会在下个版本修复

**Comment by johsang** [comment]
尝试了复苏但是没成功，可惜这次log跳动太快没截图到，可能就是这个问题，等新版发版我再观察一下。
