### ISSUE TITLE
[feature] 希望支持单角色全自动

### ISSUE THREAD

**Issue by johsang** [babalae/better-genshin-impact#866]
- 系统环境 / System Environment：
win10LTSC21H2 1080p其他全开最低

- BetterGI版本号 / BetterGI Version：
0.37.2

- 问题描述 / Description of the issue：
除了联机卡复活，还存在钟离套盾之后切不回草神，导致后续全是钟离长E，还有草神摔死检测不到红血换别的角色长E，经常会出现无效采集。
最简单的解决办法就是支持仅草神单角色，死了就复活重跑，简单又稳定，可以给草神出全肉装防暴毙。
目前版本单角色会报错，要实现需要先四角色过验证之后迅速切单角色（有趣的是联机单草神会被识别成可莉+草神，从而正常运行）。

**Comment by huiyadanli** [comment]
设置里面把自动开E的角色配置去掉就行。

必须四角色，不考虑其他场景
