### ISSUE TITLE
进入秘境后冲刺了一下不走了

### ISSUE THREAD

**Issue by Alphan-K** [babalae/better-genshin-impact#867]
- 系统环境 / System Environment：
版本	Windows 11 专业工作站版
版本号	24H2
操作系统版本	26100.2605
体验	Windows 功能体验包 1000.26100.36.0

- BetterGI版本号 / BetterGI Version：
0.37

- 问题描述 / Description of the issue：
进入秘境后冲刺了一下不走了，根据快速上手文档操作重启软件无效，仍然复现。

- 复现步骤 / Reproduction steps：
开启自动秘境功能-等待进入-进入之后就会看见只有冲一下

**Comment by huiyadanli** [comment]
重启计算机后重试，多账号切换后可能会遇到这个问题
