### ISSUE TITLE
长按空格的问题

### ISSUE THREAD

**Issue by clcm8629** [babalae/better-genshin-impact#87]
有时摁空格不会连发，有时又会而且连发的频率很低
还不如自己手动连按，希望做个被控制住自动挣脱的识别
或者给这个功能加个开关（长按会影响水下的上升跟开船时离开飞出的动作）

**Comment by huiyadanli** [comment]
这个功能开关一直有，在操控辅助页进行关闭。

0.16已经默认关闭这个功能。没啥大用。

连发频率其实很高，但是空格长按的时候不是立马连发的，导致体感使用体验不佳。

后续这个功能可能会完全废弃改用其他战斗辅助方案。
