### ISSUE TITLE
[bug]调度器无法添加二级目录及以下的路径任务

### ISSUE THREAD

**Issue by MisakaAldrich** [babalae/better-genshin-impact#873]
- 系统环境 / System Environment：

- BetterGI版本号 / BetterGI Version：
0.37.7

- 问题描述 / Description of the issue：

- 复现步骤 / Reproduction steps：

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/commit/84c7fcec21450eb4368e4ea62876a3d0366af8a7
