### ISSUE TITLE
[bug/enhancement] 0.16.1关于自动重新派遣和长按空格功能

### ISSUE THREAD

**Issue by goldenapple1** [babalae/better-genshin-impact#88]
1.首先是bug，不知道为什么我每次在原神打开派遣面板的时候它总是指向璃月区域，目前配置的自动重新派遣队伍是“班尼特,菲谢尔,刻晴,重云,九条裟罗”，这时候触发了自动重新派遣条件之后，程序正确的重新派遣了刻晴、重云和九条裟罗但是之后把派遣区域移动到了枫丹并且显示了自动重新派遣已完成，此时班尼特和菲谢尔还没有重新派遣。猜测程序逻辑是不是写成了移到后出的区域就默认前面已经完成？考虑改成根据角色选区域？

2.希望把自动重新派遣和自动领取每日委托奖励剥离出自动剧情，我不想自动剧情但是想用这两个功能😂

3.在水下长按空格上升的时候发现连按空格触发了，要不加个按键布局判断现在是陆地还是水下？

**Comment by huiyadanli** [comment]
1. 不是，当前页派遣完毕以后会重新从蒙德开始一个个标签页点过去。可能是哪边识别出问题了。你可以再下次使用的时候再反馈下。
2. 使用快捷键开关自动剧情即可。不能剥离，前置判断方式是完全一致的。
3. 该功能由于用处不大，已经于 0.16 版本默认关闭，你可以手动关闭这个功能。

**Comment by goldenapple1** [comment]
我当时看到的运行过程是，先是打开派遣面板就在璃月，然后璃月的派遣完了就跳到了稻妻，九条派遣出去之后跳到枫丹界面，然后左下就显示派遣完毕了

**Comment by goldenapple1** [comment]
1.触发器间隔修改数字后按enter还是会保持编辑中的状态，而不是已经修改完毕
2.能不能给自动选项加一个可以编辑的延迟秒数，有时候还没看清文本是什么就被按键跳过了
3.能不能实现在鼠标焦点不在屏幕时UID遮罩仍然存在？
4.这个每日委托的自动点击概率不触发
5.今天又去自动派遣发现自动派遣只收不派

具体过程传到b站了[https://www.bilibili.com/video/BV19N4y117QU](BV19N4y117QU)

**Comment by huiyadanli** [comment]
1. 这个不影响实际操作。UI框架问题，也不太好改。
2. TODO
3. 这样体验会很差，UID遮罩其实也就图一乐的功能。。。
4. 看了视频， 左上角未出现红框的情况下，不会去识别点击。这个是正常现象，文档中也有说明。本质是识别成功率的问题
5. 看了视频，是延迟太高的原因，导致后续步骤未触发 #107
