### ISSUE TITLE
[feature] 追踪系统需要折叠和分类

### ISSUE THREAD

**Issue by johsang** [babalae/better-genshin-impact#883]
- Your feature requesting / 你的新功能请求

如题，折叠方便寻找，现在脚本多了之后很乱

![Image](https://github.com/user-attachments/assets/835ac172-fc4d-4b22-b12a-2b49994dd3e0)

分类可以是按国家按种类，或者直接首字母拼音排序，搜索功能容易错别字先不推荐

![Image](https://github.com/user-attachments/assets/362d8bc8-0570-45eb-aef2-717cb1c4613d)

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.38
