### ISSUE TITLE
自动秘境新功能：指定秘境

### ISSUE THREAD

**Issue by MuxZzz** [babalae/better-genshin-impact#895]
- Problem Description / 问题描述
- 请尽量提供问题相关的截图/日志等内容
没有纳塔圣遗物本：虹灵的净土；在选择指定秘境界面选择一个副本后，不能取消选择，导致现在想自动秘境纳塔圣遗物也不行

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/pull/894
