### ISSUE TITLE
（疑似）高延迟环境下快速强化圣遗物功能无法正常运作

### ISSUE THREAD

**Issue by TheTychoStar** [babalae/better-genshin-impact#9]
感谢大佬的工具，发现宝藏了！
我是国服和美服双修，在两个服都用了一下，发现了这个问题。网络环境美服延迟30-40ms，国服220-240ms。
美服的可以正常使用，国服则不能正常使用。表现症状为按下F4后，迅速进行了菜单点击切换，但之后仍然跳出了强化成功的窗口。因为平时也经常手动这样操作，只有在强化成功窗口弹出前一小段时间内切换才能卡掉这个窗口，如果过早切换菜单则卡不掉。所以我认为应该是切换菜单的操作过快，而延迟较高窗口弹出的时间较晚，导致该功能无法成功。不知道是否可以增加一个慢速模式，或者更好的是在按下强化按钮和开始切换菜单之间，添加一个自定义等待时间，让使用者可以自行调整来适应高ping环境？
转圈、钓鱼、自动剧情和拾取目前测试下来都没有问题，拾取因为延迟高所以没有办法捡很快，但这个也没办法只能如此。

另外大佬不知道有没有计划做手柄的适配？平时用手柄玩比较多，希望也可以增加手柄操作界面的适配。

**Comment by huiyadanli** [comment]
1. 会添加自定义延时配置功能
2. 手柄不会适配。鼠标功能和手柄无法共存

**Comment by huiyadanli** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/15783049/9c74dd8c-3388-44b1-bd7e-db381a460528)

延长这个配置即可

**Comment by TheTychoStar** [comment]
感谢，我的游戏内显示延迟大概在220-240ms之间，经测试设置等待时间在150-250ms都能正常运行，低于100ms时都失败，100-150ms之间则有时成功有时失败。至于为什么设置等待时间超过延迟还能正常运行，可能是游戏显示的ping值并不完全准确吧。总之结论是大约设置成比游戏内显示的延迟低30-70ms我感觉是比较稳定的。
