### ISSUE TITLE
自动伐木截图失败

### ISSUE THREAD

**Issue by 2315506431** [babalae/better-genshin-impact#90]
自动伐木截图失败会直接停住，不会自动重试，退出来会看到后台一个窗口
![屏幕截图 2023-11-27 111031](https://github.com/babalae/better-genshin-impact/assets/116888261/e8a9f632-6f6c-4f32-88dc-cc4e190d3be4)

**Comment by huiyadanli** [comment]
更换为bitblt的截图方式吧

**Comment by 2315506431** [comment]
> 更换为bitblt的截图方式吧

用bitblt要关窗口化游戏优化，但如我前面的问题，我关闭了窗口化游戏优化会卡顿

**Comment by huiyadanli** [comment]
已经加入自动重试功能，下版本发布

伐木游戏卡顿不影响。。反正都是挂机了。

**Comment by huiyadanli** [comment]
[0.17.0](https://github.com/babalae/better-genshin-impact/releases/tag/0.17.0) 已经加入自动重试
