### ISSUE TITLE
[bug] 无法安装新版本0.38.1

### ISSUE THREAD

**Issue by yogurt-lid** [babalae/better-genshin-impact#901]
在两个系统上做了测试，均无法正常启动Setup.exe（0.37.1可以正常启动）

- 系统环境 / System Environment：
  【1】Win11 Pro English
  【2】Win10 Pro 简体中文 inside HyperV VM with GPU passthrough
Windows Defender均关闭

- BetterGI版本号 / BetterGI Version：0.38.1

- 问题描述 / Description of the issue：

Event Viewer 显示 ID 1026：Application: BetterGI_Setup_v0.38.1.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.IO.FileNotFoundException at MicaSetup.Program.Main() 

- 复现步骤 / Reproduction steps：

双击Setup.exe（下载于Github Release / 飞书）。

**Comment by huiyadanli** [comment]
已修复
