### ISSUE TITLE
自动伐木未检测弹出菜单

### ISSUE THREAD

**Issue by qingyun296** [babalae/better-genshin-impact#91]
![a11729ccbfa399b6fe4dc6950c9b4de9](https://github.com/babalae/better-genshin-impact/assets/105291860/3c40660f-8f79-47e5-bcad-9b790f128a3f)

**Comment by qingyun296** [comment]
> 程序按ESC未起效？
> 
> 没有测试过其他功能是否有效，因此“自动拾取”能够正常F拾取物品

其他功能正常

**Comment by huiyadanli** [comment]
从近期反馈来看，其他人几乎没有遇到过这个问题。

你是可以稳定复现吗。

**Comment by qingyun296** [comment]
是的，可以

**Comment by qingyun296** [comment]
是的，可以

**Comment by huiyadanli** [comment]
报错的时候游戏画面能截图一张看下吗

**Comment by qingyun296** [comment]
> 报错的时候游戏截图能看下吗？
> 
> 你手动按ESC能弹出菜单吗
![image](https://github.com/babalae/better-genshin-impact/assets/105291860/6b863af9-e76f-41b0-8e07-a349a12fad6f)

**Comment by huiyadanli** [comment]
你平时弹出菜单的快捷键是什么，是否把ESC修改成了其他按键

**Comment by qingyun296** [comment]
> 你平时弹出菜单的快捷键是什么，是否把ESC修改成了其他按键

没有改

**Comment by qingyun296** [comment]
> > 你平时弹出菜单的快捷键是什么，是否把ESC修改成了其他按键
> 
> 没有改

偶尔能弹出一次，但还是报错

**Comment by huiyadanli** [comment]
尝试下最新版本

**Comment by huiyadanli** [comment]
长时间无回复，关闭issues。
