### ISSUE TITLE
Win11下 BitBlt截图方式不可用的解决方法

### ISSUE THREAD

**Issue by huiyadanli** [babalae/better-genshin-impact#92]
通过软件内直接跳转设置
![image](https://github.com/huiyadanli/bettergi-docs/assets/15783049/4f161ebc-207d-4a8f-90dc-9b70760cad6a)

查找Yuanshen（国际服Genshin），点击选项，并勾选不使用窗口化游戏优化

![image](https://github.com/huiyadanli/bettergi-docs/assets/15783049/3430b888-1ce6-4279-887b-0503abd15c0d)

然后重启游戏和软件，重新试试BitBlt截图方式

**Comment by huiyadanli** [comment]
@nagisawarm 
家庭版可能要用特殊方式实现了。。（但是我不知道如何操作
先用其他截图方式

**Comment by nagisawarm** [comment]
> @nagisawarm 家庭版可能要用特殊方式实现了。。（但是我不知道如何操作 先用其他截图方式

啊没事没事 实际上我是可以用bitblt的，目前使用体验是，存在长按失败的情况，以及如果识别到两条鱼，会在两个目标之间来回纠缠的情况。感谢作者的贡献，respect

**Comment by huiyadanli** [comment]
0.36 版本将会在系统版本为Win11的情况下自动关闭窗口优化。
**注意：变更后需重启游戏生效（也就是说这个自动关闭窗口优化功能后，如果你是先启动的游戏，需要重启下游戏）**

![Image](https://github.com/user-attachments/assets/7bef2bde-2ae4-436d-99ac-d2c9452e1c2d)

使用 Process Monitor 可以发现该操作实际变更的注册表为
```
HKEY_CURRENT_USER\Software\Microsoft\DirectX\UserGpuPreferences
DirectXUserGlobalSettings = SwapEffectUpgradeEnable=0;
```

**Comment by huiyadanli** [comment]
补充：

Win11 更新可能会导致  窗口化游戏优化 功能自动开启。导致部分用户出现突然间什么功能都用不了的情况。

由于如上面提到的，新版 BetterGI 启动后会自动修改 窗口化游戏优化 为关闭状态，但是在原神启动状态下的修改是不会实时生效的，也就是说：**你只需要重启原神后重试即可！**
