### ISSUE TITLE
“赤糜饵 经常无法选中（我把识别阈值调高了，不然老是会把果酿饵识别成赤糜饵）”

### ISSUE THREAD

**Issue by nagisawarm** [babalae/better-genshin-impact#96]
我的使用体验是，阈值可能仍然不够大，此问题仍然出现。

**Comment by nagisawarm** [comment]
也碰到果尔酿识别不出的情况，
![image](https://github.com/babalae/better-genshin-impact/assets/65408583/f6022072-493b-42ad-9214-75c79ebb55ab)

**Comment by nagisawarm** [comment]
> 最近改了识别方式，但还是会出现，考虑进行多模板匹配

补上一个可能的饵料识别问题，因为在打开饵料界面的时候，鼠标初始为中心，如果当前钓鱼区域仅有一种饵料，那么鼠标会影响饵料的识别。具体问题位置在风龙废墟钓鱼点，会造成仅有的果尔酿无法被识别，所以建议在打开饵料界面后，额外增加鼠标的一点位移量，避免对饵料识别造成问题。

对于果尔和赤尔的混淆，个人觉得应该不会特别困难，有点反直觉，更可能是样本量不够。这两个饵料只有在rgb上有所差异，形状上是一模一样的，yolov8也算是近一两年很先进的yolo检测算法了，不应该在这种简单问题上出错。

不过样本这一块儿，单靠作者自己扩充确实也挺难的。

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.25.0 已修复
