### ISSUE TITLE
关于自动伐木的道具按键的自定义配置

### ISSUE THREAD

**Issue by Pengppi** [babalae/better-genshin-impact#98]
目前**自动伐木**只能在王树瑞佑道具设置为“**Z**”键使用，但我在游戏中的道具快捷键不是“**Z**”’，所以每次使用**自动伐木**都要调整道具快捷键。
希望**自动伐木**功能能够支持**自定义**的**道具快捷键**配置

**Comment by emako** [comment]
考虑后续增加自动检测游戏内热键配置

**Comment by emako** [comment]
> 考虑后续增加自动检测游戏内热键配置

Usage code

```c#
SettingsContainer sc = new();

if (sc.OverrideController?.KeyboardMap?.ActionElementMap.Where(item => item.ActionId == ActionId.Gadget).FirstOrDefault()?.KeyboardKeyCode is Keys key)
{
}
```

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases

已经支持自定义按键，会自动读取原神注册表配置的按键
